### ISSUE TITLE
Fail to start a container from 1.5.0 in master

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#11432]
If I create simple a container in Docker 1.5.0

    docker run -it --name foo ubuntu

Then I pull master (b6ac111abfb) and run the build.  Doing

    docker start -a foo

Fails with the following

```
DEBU[0002] attach: stdin: begin                         
DEBU[0002] attach: stdout: begin                        
DEBU[0002] attach: stderr: begin                        
DEBU[0002] Calling POST /containers/{name:.*}/start     
INFO[0002] POST /v1.17/containers/foo/start             
INFO[0002] +job start(foo)                              
INFO[0002] +job allocate_interface(eb2ec4523928bcb7b152c658e355e2e9175e93c42a68753ba0c30f9d2a2af4cb) 
INFO[0002] -job allocate_interface(eb2ec4523928bcb7b152c658e355e2e9175e93c42a68753ba0c30f9d2a2af4cb) = OK (0) 
INFO[0002] +job log(start, eb2ec4523928bcb7b152c658e355e2e9175e93c42a68753ba0c30f9d2a2af4cb, ubuntu:14.04) 
INFO[0002] -job log(start, eb2ec4523928bcb7b152c658e355e2e9175e93c42a68753ba0c30f9d2a2af4cb, ubuntu:14.04) = OK (0) 
INFO[0002] +job release_interface(eb2ec4523928bcb7b152c658e355e2e9175e93c42a68753ba0c30f9d2a2af4cb) 
INFO[0002] -job release_interface(eb2ec4523928bcb7b152c658e355e2e9175e93c42a68753ba0c30f9d2a2af4cb) = OK (0) 
DEBU[0002] attach: stdout: end                          
DEBU[0002] attach: stderr: end                          
DEBU[0002] attach: stdin: end                           
INFO[0002] -job attach(foo) = OK (0)                    
DEBU[0002] Closing buffered stdin pipe                  
INFO[0002] +job release_interface(eb2ec4523928bcb7b152c658e355e2e9175e93c42a68753ba0c30f9d2a2af4cb) 
INFO[0002] -job release_interface(eb2ec4523928bcb7b152c658e355e2e9175e93c42a68753ba0c30f9d2a2af4cb) = OK (0) 
DEBU[0002] Put on a non-mounted device eb2ec4523928bcb7b152c658e355e2e9175e93c42a68753ba0c30f9d2a2af4cb 
INFO[0002] +job log(die, eb2ec4523928bcb7b152c658e355e2e9175e93c42a68753ba0c30f9d2a2af4cb, ubuntu:14.04) 
INFO[0002] -job log(die, eb2ec4523928bcb7b152c658e355e2e9175e93c42a68753ba0c30f9d2a2af4cb, ubuntu:14.04) = OK (0) 
Cannot start container foo: [0] Id already in use: Container with id exists: eb2ec4523928bcb7b152c658e355e2e9175e93c42a68753ba0c30f9d2a2af4cb
INFO[0002] -job start(foo) = ERR (1)                    
ERRO[0002] Handler for POST /containers/{name:.*}/start returned error: Cannot start container foo: [0] Id already in use: Container with id exists: eb2ec4523928bcb7b152c658e355e2e9175e93c42a68753ba0c30f9d2a2af4cb 
ERRO[0002] HTTP Error: statusCode=500 Cannot start container foo: [0] Id already in use: Container with id exists: eb2ec4523928bcb7b152c658e355e2e9175e93c42a68753ba0c30f9d2a2af4cb 
```

**Comment by ibuildthecloud** [comment]
Sorry if this is a dup of another issue, but here's what I've found.  If `/var/lib/docker/execdriver/native/ID` exists when a container goes to start it will fail at https://github.com/docker/docker/blob/b6ac111abfbed628a80b67f0b092a248083b354c/vendor/src/github.com/docker/libcontainer/factory_linux.go#L134

It seems that in the new native driver/libcontainer the `/var/lib/docker/execdriver/native/ID` directory is deleted on container stop.  During the "migration" from the old container.json style to this new code base the directories are not deleted, just the files in them.  If you delete `/var/lib/docker/execdriver/native/ID` manually the issue is fixed.

**This raises another problem though.  If you kill the Docker daemon while containers are running, the `/var/lib/docker/execdriver/native/ID/state.json` still exists, and thus containers will fail to start because the directory exists.**

ping @crosbymichael @LK4D4

**Comment by LK4D4** [comment]
@ibuildthecloud Yup, something wrong with destroy in second case and we should delete all dirs of course in first.
I'll take a look tomorrow.

**Comment by ibuildthecloud** [comment]
@LK4D4 thanks

**Comment by tianon** [comment]
Just restarted my daemon and I'm seeing the same behavior -- containers fail to start back up with the same cryptic error.

Can confirm that simple `rmdir` on the `/var/lib/docker/execdriver/native/ID` directory in question lets me `docker start` the relevant containers again.

**Comment by tianon** [comment]
I've got other containers where `/var/lib/docker/execdriver/native/ID` isn't empty though, so the simple `rmdir` doesn't fix the issue.
