### ISSUE TITLE
Docker 1.6 push with multiple tags duplicates push

### ISSUE THREAD

**Issue by pbecotte** [docker/docker#12489]
Related to #12257 

Am evaluating docker 1.6.  Was very interested in testing the performance of docker push / docker pull (docker push is by far the slowest step in our entire CI pipeline).  Was encouraged at first- pushing the same image repeatedly (so it shouldn't have done anything) was getting 20-30% improvement from the new version.

However, after reading bug #12257 I thought to add a second tag to the image and push it.  In this case, the v 1.6 docker pushes the same set of images twice.  After it outputs the digest from the first push, it repeats the process again up to giving a new digest for the second tag pushed.  The time consumed is doubled.  Doing the same process on a 1.5 daemon showed basically no time penalty for pushing two tags at once.  My results...
1.6 one tag ~ 30s
1.5 one tag ~ 45s
1.5 two tags ~ 45s
1.6 two tags ~ 60s

(I was doing the testing using jpetazzo/dind:latest docker in docker image)

> docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
INFO[3127] GET /v1.18/version                           
INFO[3127] +job version()                               
INFO[3127] -job version() = OK (0)                      
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64

> uname -a
Linux cc6d716dcd51 3.13.0-46-generic #77-Ubuntu SMP Mon Mar 2 18:23:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

> docker -D info
INFO[3350] GET /v1.18/info                              
INFO[3350] +job info()                                  
INFO[3350] +job subscribers_count()                     
INFO[3350] -job subscribers_count() = OK (0)            
INFO[3350] +job registry_config()                       
INFO[3350] -job registry_config() = OK (0)              
INFO[3350] -job info() = OK (0)                         
Containers: 0
Images: 20
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 20
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-46-generic
Operating System: Ubuntu 14.04.2 LTS (containerized)
CPUs: 1
Total Memory: 1.955 GiB
Name: cc6d716dcd51
ID: OW43:W6ZA:GPX3:GRZC:CDV5:57JO:JH4Z:JY4H:7WD5:TZS6:MRT3:IVJE
Debug mode (server): false
Debug mode (client): true
Fds: 10
Goroutines: 16
System Time: Fri Apr 17 16:04:43 UTC 2015
EventsListeners: 0
Init SHA1: 9145575052383dbf64cede3bac278606472e027c
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
Username: pbecotte
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support

**Comment by thaJeztah** [comment]
Thanks for reporting, @pbecotte!

**Comment by thaJeztah** [comment]
I think I've seen something similar when doing `docker pull`. During pull, the progress sometimes outputted `already being pulled..skipping`, which could indicate that more processes are started than are required (just thinking out loud here)

**Comment by PikachuEXE** [comment]
I have seen the same thing too for every pushing
New layers seem to be pushed twice

**Comment by LK4D4** [comment]
ping @dmcgowan

**Comment by dmcgowan** [comment]
@pbecotte were both tags the same image ID only differing by tags or different images/builds?

**Comment by pbecotte** [comment]
I ran the following comands in a fresh install...
docker pull myimage
docker push myimage
docker tag myimage:HEAD
docker push myimage

**Comment by andrask** [comment]
:+1:

Have there been any changes with this issue? I've been trying to optimize image pushes in our CI but this issue is causing serious overheads.

**Comment by erikswanson** [comment]
I'm seeing a variant of this where there is one layer in the middle of our stack that always gets re-uploaded every single time, whether pushing the same image:tag or a different image:tag, even though the layers above and below it are fine.

    The push refers to a repository [**/xxxx] (len: 1)
    45e91323aec3: Image already exists
    45e91323aec3: Image already exists
    793c2236aad1: Image already exists
    6e1e70df2e82: Image already exists
    091929ba9621: Image already exists
    72263cb0334d: Buffering to Disk
    72263cb0334d: Image successfully pushed
    a72f8e7eabbf: Image already exists
    9454fe2424a1: Image already exists
    ded7cd95e059: Image already exists
    48ecf305d2cf: Image already exists
    Digest: sha256:b8939886844b7d2497164f451f8f0368a1fc2649cdad5634bfd56fae8e54ec43

    The push refers to a repository [**/yyyyy] (len: 1)
    2b2fca621bba: Image already exists
    2b2fca621bba: Image already exists
    32c268a85f51: Image already exists
    c2c069a63e14: Image already exists
    5103dbddb88e: Image already exists
    a8a12a81cb69: Image already exists
    72263cb0334d: Buffering to Disk
    72263cb0334d: Image successfully pushed
    a72f8e7eabbf: Image already exists
    9454fe2424a1: Image already exists
    ded7cd95e059: Image already exists
    48ecf305d2cf: Image already exists
    Digest: sha256:259fe06650aaad9a3e05eeb0441d34ab0519b18718cc8c504878ca816891d7a4

This is extremely aggravating because it means our push-to-prod CI job takes tens of minutes instead of a few seconds.

**Comment by devshorts** [comment]
Also seeing this behavior :+1:

**Comment by thaJeztah** [comment]
I may be completely off here, but wondering if @vbatts tar-split PR https://github.com/docker/docker/pull/14067 helps resolving this?

**Comment by vbatts** [comment]
@thaJeztah #14067 is transparent to this and would not resolve it.

**Comment by andresriancho** [comment]
Anyone working on this issue? It seems to be a big waste of time and resources for all "docker push" users

**Comment by coopernurse** [comment]
We're seeing the same issue as @erikswanson - intermediate layers are always re-pushed.

We also see duplicate work happening on push.  Here's an example from one push, with the checksum counts:

```
docker push registry.redacted.net:5000/redacted-image | cut -d: -f 1 | grep -v Digest | grep -v 'push refers' | sort | uniq -c
1 006e54467cc3
      2 00eee1ccd3b7
      1 0290d4126960
     14 07f7421689bf
      2 0911365cf4c4
      3 0c312fa04680
      3 0da1149fe55c
      3 0f56ddf4853c
     40 1255fa1c4db2
      1 12acff17ecb5
      2 191fe48ddd04
      3 1c87146fd492
      2 1d3131b7dda7
      3 1d869bb280cc
      2 1df2d5a51b0f
     10 1eab5510e6da
     40 21d25cdacc2e
     10 22a9ce2de6b1
      3 26827eea0555
      3 28146e8e0e07
      2 28ce6a716d4c
      1 2928369b9441
      1 2e543f30afe6
     14 30f6a46c9811
      1 32cafbb1b4bc
      2 3310e4e9206b
      2 334f67aa7553
      2 3488e515b292
      1 3629fad03d3e
     14 43fbf8f5d432
      1 45d41f43ee51
      1 461339ba27f1
      3 466bb9b4c31c
      2 4676ae426b13
     10 46b1cdc2b648
      1 46be55097f91
     10 4a67c9d8fa2b
      2 4a80b1c7ec0e
      2 4bf395041881
     10 5036aeb81d8a
      1 50b36633a176
     40 523013b1a2ea
      3 5734382778e3
     40 5760bc9831a4
      3 5973e5c3f9e4
     10 59877e49d74f
      3 5be3dd554436
      4 5bf70b5e79cd
     14 5cd1d58d5e51
      1 5ec33384d016
      3 611f3f00ac0d
      2 61860286fb1e
     40 673a5463d35e
      1 683f7287d126
      3 69ca7c6a5dcb
      3 6a0048693495
      2 6d1b60bc8f1b
     10 6da49ea59739
      6 6e11953c3729
      1 704749c17806
      2 713a8e48a565
     14 72785ba38b6c
     40 7322fbe74aa5
      1 75a49b7a29f8
     10 75d4282607e3
      1 76438409bf82
     40 76797907cb08
     14 7b0d78574f62
      2 81e4ef02925e
      1 824146d03336
      3 836cc6c4ba8a
      2 846c756a735c
      3 85032aa8b968
      3 85249c75b602
      3 85a0b3322ded
      2 86a54853abf3
      1 8bb2c6566b57
      4 8c811622d81e
      1 8e516e36431e
     14 8f8d1fdd9b8b
      1 8fce7bae6362
      3 8fd18db91ca3
     10 9143298a53d1
      1 918f556024cb
     40 91fd3869af47
      3 94bf832e0252
     40 950dad0d114d
      3 974282e28ebd
      6 9832a91d8ec6
      3 99b640f2540b
      1 9b307610a0ea
      1 9c20c38fd5b6
      2 a08fef3cb647
      3 a45d5f8699a6
      1 a75bbfe7a1d6
      1 a91e712ab3b2
      1 a933b206617d
      3 aa3d568061f2
      3 ab266c7521d9
      1 abaee76f9542
      2 ac1048aedaaf
     14 ad4f6b48fe28
     10 ae4357131fc4
      2 aeaf24df8e53
      2 af008722a450
     10 b17183592e15
      2 b3c4fcf22abd
      2 b43006c303ed
      2 b48b53131b4c
      1 b503533d43ac
     14 b7a1b79a5125
     20 bcdc889e9565
      3 bdaffaf14e4f
     14 c03b5c8869f1
      3 c18d0cfb8c5a
     28 c1a3d1d86178
      1 c6a5bfea39b5
      1 c7184fb10d2b
     40 c852f6d61e65
      3 c8e9cac7bd1f
      1 cab00b20dda6
     10 cb0991978ff6
     40 ccbad523da9f
      2 ce1e7e642e96
      3 d024dd4b2a22
     14 d1d934332ddd
      3 d2bb99518257
      1 d2f65f3e2911
     40 d4831e6205be
      1 d5532136e028
     14 d565cca1eee5
      1 d625d631485f
      3 d74d71ff5037
      3 d86691b1c92c
      3 da2e90e45d26
     40 dbf6f8a96f9f
     10 dd5460f3fa04
      2 ddde631005e4
      1 df09c6e6ef6d
      6 e2109ecfd434
      1 e8484c1f08e3
      1 e88952e1486a
      2 e95987ce0637
      1 ed6860316783
      3 ee462b1d1727
     40 f1b10cd84249
      2 f2041a6e6b2e
      3 f47c1c2da4c8
      1 f4bd743a713f
      3 f72c229e6603
      3 f8d4e5b6a831
      3 fae19cc90bf1
     14 fc32253e2738
     40 fccbe5d8469f
      3 fd5ee1abe8ac
```

This results in push times > 2 minutes even when no layers have been modified (private docker registry), or > 30 minute push times to docker hub.

**Comment by aaronlehmann** [comment]
Looking into this.

**Comment by aaronlehmann** [comment]
One thing I see in many of these comments is that there's redundant effort spent checking whether images already exist with HEAD requests - for example:

    45e91323aec3: Image already exists
    45e91323aec3: Image already exists

I can reproduce this by creating multiple tags. This could be slowing down pushes in cases that involve a lot of tags. It should be relatively easy to fix these duplicate checks.

However, several comments say that actual pushes are being repeated. This is something I haven't been able to reproduce with Docker 1.7.0. When I pull, add a tag, and push, no actual images get repushed. Can anyone share a particular image or set of steps that reproduces this problem?

**Comment by erikswanson** [comment]
Big difference from my circumstances: doing a pull. This is happening with images that were built on the machine that's doing the pushing.

The layers in question, the ones being re-uploaded every single time, are also rather large (180Mb approximately), hence the half-hour times I'm seeing for a couple dozen pushes.

**Comment by mitchcapper** [comment]
it does seem to not be random as to which image but rather certain images with when pushing dozens of images/layers the same one image layer may be pushed multiple times from dockerfile to dockerfile.

**Comment by coopernurse** [comment]
The layers that always re-push for us also happen to be of medium size (one is ~190MB, the other is ~60MB).  There are two layers that are consistently re-pushed.

We're using docker 1.7 on CentOS 7.  `docker info` output from our build host:

```
Containers: 0
Images: 681
Storage Driver: devicemapper
 Pool Name: docker-253:1-201656689-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 18.47 GB
 Data Space Total: 107.4 GB
 Data Space Available: 24.97 GB
 Metadata Space Used: 33.54 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.114 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.63-11.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 7.815 GiB
Name: redacted
ID: redacted
Username: redacted
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

`docker version`:

```
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

**Comment by mitchcapper** [comment]
I am also not sure if it is somehow related to tagging that causes the issue but the base layer we have gets tagged a few ways.

**Comment by vbatts** [comment]
After mulling on this for a minute, what this needs is the 'cross-mount' feature that @ncdc and @mattmoor have discussed.
Basically the duplicate push is a side effect of the docker client needing to prove to the registry that the content is the same (checksum validation).

So in answer to tar-split inquiry, it will indirectly help by having consistent tar archives, but this fix needs an additional feature.

**Comment by Freyskeyd** [comment]
Any idea of a solution for this bug?

I get the same problem with my CI, i'm pushing every layer of my image every time..

**Comment by aaronlehmann** [comment]
If the same repository name has already been pushed before, I think this is most likely related to inconsistent tar digests. The upcoming Docker 1.8 release should solve this.

**Comment by dmp42** [comment]
@pbecotte @Freyskeyd can you give a try to 1.8 release candidate and let us know if the changes there are fixing your issue (see @aaronlehmann comment)?

**Comment by mitchcapper** [comment]
@dmp42 I gave this a shot running head and its still double pushing the same base image.  Running the latest version of distribution.  What is interesting is it says:
d07b7229f8b7: Image successfully pushed
now instead of already pushed.   But if I push another dockerfile with the same base image I get:
d07b7229f8b7: Image successfully pushed
again.

Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   c69a2a6-dirty
 Built:        Thu Aug 13 00:01:33 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   d50881e
 Built:        Thu Aug 13 00:10:13 UTC 2015
 OS/Arch:      linux/amd64

**Comment by dmp42** [comment]
@mitchcapper the optimization introduced a regression, and we rolled it out for now.

**Comment by andrask** [comment]
The issue still persists with Docker 1.9.0 with registry:2.2.0 and distribution/registry:2.2.0 (I guess the same as registry:2.2.0).

Push performance with v2 registries improved due to the removal of the "Buffering to disk" phase but pushes to v2 registries with different tags will still repeat the full push.

I even tried with dockerhub that does not repeat the push just similarly to the v1 registry.

**Comment by hai-ld** [comment]
I can confirm that this problem still persists in docker version 1.10.3, although seems to be in another form: if same layers are used in different repositories, they get pushed twice. It works normally for different tags in same repo though. e.g if layer_x (already pushed) is used by repo_a and repo_b, then the following happens:
- push `repo_a:latest`, layer_x is re-pushed
- push `repo_a:<a_git_hash>`, layer_x is not pushed
- push `repo_b:latest`, layer_x is re-pushed
- push `repo_b:<same_git_hash>`, layer_x is not pushed

Extremely annoying and counter-productive as our CI pipeline now takes almost half an hour to finish. I'd like this to be fixed as soon as possible, so please tell me how I can help fix it (I can't code though, as Go and system programming is not my specialty :( )

```
$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```

**Comment by erikswanson** [comment]
@hai-ld What you're describing sounds like #20387. (I experienced the exact same thing.)

If you're using a registry with token authentication, make sure it supports creating tokens with multiple scopes.

**Comment by aaronlehmann** [comment]
@hai-ld: Are you using Docker Registry, and if so, what version? The combination of Docker Engine 1.10.x and Docker Registry 2.3.x should make it possible to skip re-uploading layers when pushing to a different repository. See https://github.com/docker/distribution/issues/634 and https://github.com/docker/distribution/issues/908 for context on why this requires special support.

**Comment by hai-ld** [comment]
@aaronlehmann I was foolish enough for pulling the short tag registry:2, now I don't know exactly the version of our running registry. Trying to pull and upgrade to 2.3, hopefully nothing would break. I will re-run our CI pipeline to see whether this problem occurs and report it here.

@erikswanson I did not get 'unauthorized: authentication required' as reported in the issue, so I guess I'm experiencing a separate problem. Thanks for replying!

**Comment by hai-ld** [comment]
@aaronlehmann I upgraded to Docker Registry v2.3 and layers are no longer getting re-pushed. Thanks for your help!

**Comment by aaronlehmann** [comment]
Great!

I am closing this issue because I believe the situation in the original report was resolved with Docker 1.10. Please reopen if you continue to experience it.
