### ISSUE TITLE
Networking issue on 1.6

### ISSUE THREAD

**Issue by richardjortega** [docker/docker#12613]
#### Description of problem: 
I recently updated from Docker 1.5 to Docker 1.6 and ran into an issue regarding fetching gems from Rubygems on a `docker build` or `docker-compose up` command. I found that building a Docker container that requires an external networking request does not work correctly in Docker version 1.6. Experienced this while using a `ruby:2.1-onbuild` image (https://registry.hub.docker.com/_/ruby/) and the trigger on build executes `bundle install` which reaches out to https://rubygems.org and returned HTTP fetch errors. 

I was able to reproduce the error using `ping` in Docker 1.5 with no errors, but found the error to occur in 1.6. It is reproducible through any container however using `ping`. 

`docker version`:
```text
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64
```

`docker info`:
```text
Containers: 0
Images: 9
Storage Driver: devicemapper
 Pool Name: docker-253:1-26931123-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 776.3 MB
 Data Space Total: 107.4 GB
 Data Space Available: 3.626 GB
 Metadata Space Used: 1.208 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.4.4.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 1.798 GiB
Name: localhost.localdomain
ID: ZKP2:2OZK:ZJJR:B3FE:GQQF:NDNR:QY3S:SIAO:OVGL:RIWI:QGEA:H77N
```
`uname -a`:
```text
Linux localhost.localdomain 3.10.0-123.4.4.el7.x86_64 #1 SMP Fri Jul 25 05:07:12 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

#### Environment details (AWS, VirtualBox, physical, etc.):
CentOS 7.1.1503 (Core) 64-bit, VirtualBox 4.3.26, Mac OSX 10.10.2, Vagrant 1.7.2
#### Steps to Reproduce:
From Docker host machine:
`$ docker run -it --rm ubuntu /bin/bash`

From inside running container:
`$ ping google.com`

#### Actual Results:
```bash
[root@localhost example]# docker run -it --rm ubuntu /bin/bash
Unable to find image 'ubuntu:latest' locally
latest: Pulling from ubuntu
706766fe1019: Pull complete 
a62a42e77c9c: Pull complete 
2c014f14d3d9: Pull complete 
b7cf8f0d9e82: Already exists 
ubuntu:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:80d996c3693d792505039a3612cf9221ae9704317ea11fda75c86ede672ee1b3
Status: Downloaded newer image for ubuntu:latest

root@025bc4c6b926:/# ping google.com
ping: unknown host google.com
root@025bc4c6b926:/# 

```

#### Expected Results:
*Same server configuration system as above, except Docker 1.5 (installed from `yum`)*:
`docker version`:
```text
Client version: 1.5.0-dev
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): fc0329b/1.5.0
OS/Arch (client): linux/amd64
Server version: 1.5.0-dev
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): fc0329b/1.5.0
OS/Arch (server): linux/amd64
```
```bash

[root@localhost example]# docker run -it --rm ubuntu /bin/bash
Unable to find image 'ubuntu:latest' locally
Trying to pull repository docker.io/ubuntu ...
d0955f21bf24: Download complete 
511136ea3c5a: Download complete 
f3c84ac3a053: Download complete 
a1a958a24818: Download complete 
9fec74352904: Download complete 
Status: Downloaded newer image for docker.io/ubuntu:latest

root@c4daa2819f42:/# ping google.com
PING google.com (216.58.216.110) 56(84) bytes of data.
64 bytes from ord30s22-in-f14.1e100.net (216.58.216.110): icmp_seq=1 ttl=61 time=46.9 ms
64 bytes from ord30s22-in-f14.1e100.net (216.58.216.110): icmp_seq=2 ttl=61 time=46.9 ms
64 bytes from ord30s22-in-f14.1e100.net (216.58.216.110): icmp_seq=3 ttl=61 time=46.9 ms
--- google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 46.905/46.908/46.912/0.176 ms

 ```

**Comment by LK4D4** [comment]
looks like dns issue, could you try ping 8.8.8.8?

**Comment by richardjortega** [comment]
@LK4D4 Ok thank you for this, this did work fine using `$ ping 8.8.8.8` (provided below). Is there a DNS settings change from 1.5 to 1.6 that I should modify?

However would that affect why `bundle install` is failing when using the `ruby:2.1-onbuild` image?

Ran this on my home Mac laptop (using same config via Vagrant/VirutalBox/CentOS as referenced in issue)

##### Output from Docker 1.6
```text
root@9cf79df6d1e1:/# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=61 time=17.6 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=61 time=12.5 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=61 time=24.0 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=61 time=16.6 ms
^C
--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 12.525/17.714/24.047/4.132 ms
```

##### Output from Docker 1.5.0-dev: 
```text
root@abe0534b2c41:/# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=61 time=171 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=61 time=13.8 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=61 time=11.5 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=61 time=12.3 ms
^C
--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3008ms
rtt min/avg/max/mdev = 11.504/52.276/171.461/68.816 ms
```

**Comment by timbordemann** [comment]
It's a SELinux related problem. After updating docker to 1.6, none of my containers are able to read the files resolv.conf, /etc/hosts and /etc/hostname anymore. This prevents the containers to lookup hosts:

```
docker run --rm -ti centos:centos7 /bin/bash

[root@7103fa6cb47c /]# ls -l /etc/
ls: cannot access /etc/resolv.conf: Permission denied
ls: cannot access /etc/hosts: Permission denied
ls: cannot access /etc/hostname: Permission denied
total 888
[...]
drwxr-xr-x.  3 root root     19 Apr 15 14:28 gss
-rw-r--r--.  1 root root      9 Jun  7  2013 host.conf
???????????  ? ?    ?         ?            ? hostname
???????????  ? ?    ?         ?            ? hosts
-rw-r--r--.  1 root root    370 Jun  7  2013 hosts.allow
-rw-r--r--.  1 root root    460 Jun  7  2013 hosts.deny
[...]
lrwxrwxrwx.  1 root root     10 Apr 15 14:28 rc5.d -> rc.d/rc5.d
lrwxrwxrwx.  1 root root     10 Apr 15 14:28 rc6.d -> rc.d/rc6.d
lrwxrwxrwx.  1 root root     14 Apr 15 14:28 redhat-release -> centos-release
???????????  ? ?    ?         ?            ? resolv.conf
-rw-r--r--.  1 root root   1634 Dec 25  2012 rpc
drwxr-xr-x.  2 root root     24 Apr 15 14:29 rpm
drwxr-xr-x.  2 root root     24 Apr 15 14:29 rsyslog.d
```

When I start a container with the --privileged flag or disable selinux temporarily (setenforce 0), everything works as expected. 

Unfortunately I didn't figure out how to fix this yet.

**Comment by richardjortega** [comment]
@timbordemann What was the Docker host OS?

**Comment by jfrazelle** [comment]
that would probably be centos or RHEL

**Comment by jfrazelle** [comment]
or any machine w SELinux enabled then

ping @rhatdan

**Comment by rhatdan** [comment]
There is a fix for labeling /etc/resolv.conf correctly.  At least in our patches. Although I am pretty sure it has been upstreamed.  Try running the docker that comes with the distribution.

**Comment by richardjortega** [comment]
@rhatdan Yes, the Docker that comes with CentOS7 distribution (version `1.5.0-dev`) works fine and that's what I am using now. I just wanted to point this out for anyone who upgrades to the latest outside of upstream.

A detail I left out, is I upgraded to 1.6.0 via the following upgrade install recommended on the Docker website:

```bash
# Stop docker service
$ systemctl stop docker

# Downloaded latest binary
$ wget https://get.docker.com/builds/Linux/x86_64/docker-latest -O /usr/bin/docker
$ chmod +x /usr/bin/docker

# Restart docker service
$ systemctl start docker
```

**Comment by rhatdan** [comment]
Looks like upstream does not have the fix.  In our 1.6 patch set I see.

+               }
+       }
+
        if container.ResolvConfPath != "" {
-               mounts = append(mounts, execdriver.Mount{Source: container.ResolvConfPath, Destination: "/etc/resolv.conf", Writable: true, Private: true})
+               mounts = append(mounts, execdriver.Mount{Source: container.ResolvConfPath, Destination: "/etc/resolv.conf", Writable: true, Relabel: "Z", Private: true})
        }

**Comment by jfrazelle** [comment]
@rhatdan its not really acceptable that this is breaking vanilla docker, is there a way to modilfy the selinux profile so it wont apply to those files

**Comment by icecrime** [comment]
@rhatdan That's a patch upstream definitely doesn't have as it's a patch over the "SELinux labels" patch that upstream doesn't have...

**Comment by jfrazelle** [comment]
I also think, if you had previous installed the RH version, then it came with this SELinux policy, so if you were to uninstall that version and then use our binary it would work, I think the problem is _just_ swapping out the binaries is causing their SELinux profile to linger

**Comment by jfrazelle** [comment]
we will have our own rpm soon so you can just use ours and wont even have to worry about this :D

**Comment by rhatdan** [comment]
I can send you a patch to fix the problem.

**Comment by rhatdan** [comment]
https://github.com/docker/docker/commit/433e0a2b0d5acc2df96efc0872923b223f1ee000

Will fix this, but I can't seem to generate a pull request versus v1.6.0

**Comment by jfrazelle** [comment]
thanks @rhatdan! can you make the PR to master then we can cherrypick to release if need be :)

**Comment by rhatdan** [comment]
It already is in master

61b2766e758f21b8b6bd32dc82ba624c2f0c5fd6

**Comment by jfrazelle** [comment]
oh sorry missed that, it is also in 1.6.0

**Comment by jfrazelle** [comment]
so idk if that is our fix

**Comment by cpuguy83** [comment]
So that is actually not in 1.6 afiact

**Comment by jfrazelle** [comment]
it is in the tag

**Comment by visualphoenix** [comment]
Is this an issue with the static 1.6? I'm not having problems on RHEL/Centos 6.6 using this rpm:

https://kojipkgs.fedoraproject.org/packages/docker-io/1.6.0/1.el6/x86_64/docker-io-1.6.0-1.el6.x86_64.rpm

**Comment by jfrazelle** [comment]
because the version of udev has to be the same it has been explained in
several issues

**Comment by jfrazelle** [comment]
that is not the same issue as this though

**Comment by visualphoenix** [comment]
@jfrazelle ah - failed to notice this was running on a centos7 host. not having this problem with 1.6 on a 6.6 host.

**Comment by ksylvan** [comment]
I'm running into access issues with the distribution docker-io 1.6 on Fedora 21 and SELinux.

    $ docker --version 
    Docker version 1.6.0, build 3eac457/1.6.0
    $ docker run --rm -it -v $HOME/src:/src busybox /bin/sh
    / # ls /src
    ls: can't open '/src': Permission denied
    / # 

After running "setenfoce 0", the same commands yield this:

    $ docker run --rm -it -v $HOME/src:/src busybox /bin/sh
    / # ls /src
    [... list of files ...]

I used to be able to do this:

    chcon -Rt svirt_sandbox_file_t /path/on/host

and then "docker run -v /path/on/host:/path/in/container" would work. As of 1.6, it no longer works. Anyone got any workarounds/fixes? @rhatdan ?

**Comment by rhatdan** [comment]
THis should still work.  Would need AVC's to tell you what is happening, and would be best handled in Bugzilla.

**Comment by diresi** [comment]
I also swapped docker binaries on centos7 with the one from https://get.docker.com and ran into this issue. I fixed access to resolv.conf, hostname and hosts with the following rules:

    allow svirt_lxc_net_t docker_var_lib_t:file open;
    allow svirt_lxc_net_t docker_var_lib_t:file read;
    allow svirt_lxc_net_t docker_var_lib_t:file getattr;

I updated to vanilla docker-1.6 because of similar issues connecting to docker.sock from within containers.

**Comment by rhatdan** [comment]
The problem is the patch that adds proper labels to /etc/hosts, /etc/.resolv.conf and /etc/hostname keeps getting removed from upstream.  No idea why.  We have it in our patches and I will resubmit when I get back from Vacation.

**Comment by thaJeztah** [comment]
@rhatdan what's the status on this? Did you manage to get the patch in (again)?

**Comment by rhatdan** [comment]
@thaJeztah docker-1.7 has the SELinux patches merged.

**Comment by thaJeztah** [comment]
ping @jfrazelle is this safe to close? Or not fixed yet? (see https://github.com/docker/docker/issues/12613#issuecomment-107428789)
