### ISSUE TITLE
In windows can't use arrow navigation exec bash into container

### ISSUE THREAD

**Issue by phazei** [docker/docker#13817]
BUG REPORT INFORMATION

**docker version:**
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): windows/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

**docker info:**
Containers: 15
Images: 309
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 339
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.0.3-boot2docker
Operating System: Boot2Docker 1.6.2 (TCL 5.4); master : 4534e65 - Wed May 13 21:24:28 UTC 2015
CPUs: 4
Total Memory: 1.957 GiB
Name: boot2docker
ID: FKPI:HE56:LNVN:B25Q:RDMA:YB5E:AENE:Y2HR:72C4:CNUS:LNMP:3G7M
Debug mode (server): true
Debug mode (client): false
Fds: 32
Goroutines: 49
System Time: Tue Jun  9 06:00:31 UTC 2015
EventsListeners: 0
Init SHA1: 7f9c6798b022e64f04d2aff8c75cbf38a2779493
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: rasterdocker
Registry: [https://index.docker.io/v1/]

**uname -a:**
MINGW64 _NT-6.1 raster-dev-PC 2.1.2(0.288/5/3) 2015-05-25 15:48 x86_64 Msys

Provide additional environment details (AWS, VirtualBox, physical, etc.):
Windows 7 using native windows client in either cmd or msys2.

List the steps to reproduce the issue:
1)  docker run --rm -it --entrypoint=//bin/bash ubuntu:14.04
2) type anything, press enter, type some more
3) Hit left, right, up, down, home, end.

Describe the results you received:
Nothing happens: cursor does not move.

Describe the results you expected:
cursor moves left, right, up one in history, down one in history, beginning of line, end of line

Provide additional info you think is important:
Tried it on 2 windows 7 machines, same results.
It does work if I do boot2docker ssh first and follow same steps.

**Comment by phazei** [comment]
Updated!

**Comment by phemmer** [comment]
This is likely a result of an unusual terminal emulator.
Try running

    docker run -e TERM --rm -it --entrypoint=//bin/bash ubuntu:14.04

**Comment by phazei** [comment]
TERM doesn't seem to make a difference.  Same results with cygwin, linux, xterm-color

**Comment by tmds** [comment]
I have the same issue when using ConEmu, but not when using the default windows terminal.

**Comment by phazei** [comment]
I'm also in ComEmu actually, hmm.
I tried detaching the cmd tab and running docker exec, it was weird as well, all sorts of funky characters, think that was because of something when it's disconnected it doesn't even have the normal windows console since it's resizable.
I ran cmd as admin since it doesn't attach auto attach, and ran docker exec, and the arrow keys seemed to work fine.

**Comment by Maximus5** [comment]
When you are in ConEmu and arrow navigation doesn't work, reveal [RealConsole](http://conemu.github.io/en/RealConsole.html) by Ctrl+Win+Alt+Space, set focus into it and try keys. Result?

**Comment by tmds** [comment]
RealConsole has the same behavior, i.e.: arrow keys don't work

**Comment by Maximus5** [comment]
If so, I believe the problem is not in ConEmu or docker itself. But in the configuration of your shell. It starts with different ways I believe.

**Comment by tmds** [comment]
Summary of findings:
When running a command like docker run -ti --rm debian:jessie /bin/bash
* arrow keys are working when started in 'cmd' or 'powershell'
* arrow keys are _not_ working when started in 'ConEmu' via 'cmd' or 'powershell'
* arrow keys are working when started in 'ConEmu' using 'boot2docker ssh' via 'cmd' or 'powershell'

From this I guess that there is some incompatibility in how 'docker run' and 'ConEmu' work with the arrow keys.

**Comment by phazei** [comment]
Not sure if this might shed some light on it, but if I choose "detach" on the current bash window, then go into a docker container, it gives me strange characters, maybe their particular encoding might explain something?

```bash
adam@dev-PC MINGW64 ~
$ docker.exe run --rm -it ubuntu:14.04 //bin/bash -l -i
root@edfa63f0e3e4:/# ls
bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
root@edfa63f0e3e4:/# exit
logout

# detach from ConEmu here and do exact same thing again:

adam@dev-PC MINGW64 ~
$ docker.exe run --rm -it ubuntu:14.04 //bin/bash -l -i
←]0;root@ad7bbdddd009: /root@ad7bbdddd009:/# ls
←[0m←[01;34mbin←[0m  ←[01;34mboot←[0m  ←[01;34mdev←[0m  ←[01;34metc←[0m  ←[01;34mhome←[0m  ←[01;34mlib←[0m  ←[01;34mlib64←[0m  ←[01;34mmedia←[0m  ←[01;34mmnt←[0m  ←[01;34mopt←[0m  ←[01;34
mproc←[0m  ←[01;34mroot←[0m  ←[01;34mrun←[0m  ←[01;34msbin←[0m  ←[01;34msrv←[0m  ←[01;34msys←[0m  ←[30;42mtmp←[0m  ←[01;34musr←[0m  ←[01;34mvar←[0m
←]0;root@ad7bbdddd009: /root@ad7bbdddd009:/# exit
logout

adam@dev-PC MINGW64 ~
$
```

**Comment by crmckenzie** [comment]
We are so close to awesomesauce on this. Would love to see it addressed. If I knew anything about terminal emulation I'd jump in and help.

**Comment by aarontgrogg** [comment]
Ditto, no arrow-history is a pretty big hole in this awesomeness...

**Comment by Maximus5** [comment]
OK. If I have a clean PC with only ConEmu installed, what shall I do to reproduce the issue?

**Comment by aarontgrogg** [comment]
From what I read from others:
- type a command
- Enter
- press up arrow
Expected behavior:
- console should display previous commands entered as you press the up arrow
Actual behavior:
- nothing

For me, however:
- set-up a tab to automatically run a shell script when it opens
- open that tab
- after command finishes, press up arrow
Expected behavior:
- console should display previous commands entered as you press the up arrow
Actual behavior:
- nothing

**Comment by Maximus5** [comment]
I mean I have no docker installed or configured any of containers. Newby step-by-step guide...

**Comment by aarontgrogg** [comment]
same situation for me, actually:
- straight ConEmu
- using Startup > Task file has several lines, one calls .bat files that
does:
  mvn lesscss:compile -Dlesscss.watch=true
- sometimes fails if /target directory isn't created yet by other tab
- pressing ^ arrow key does nothing

again, this is my situation, i think the others above are slightly
different.

**Comment by Maximus5** [comment]
Running something (mvn) from batch will *not* place this command in the history buffer. The reason is that the command was obtained not from user's interaction. Therefore Up arrow will do nothing.

Workarounds

1. Just restart the console, default shortcut is `Win~`
2. Or more tricky way, use GuiMacro print to send the command into the command input (and the history buffer)

**Comment by aarontgrogg** [comment]
gotcha, thanks!

**Comment by crmckenzie** [comment]
Re: Step-by-Step guide

There are step-by-step instructions (here)[http://docs.docker.com/windows/step_one/]

Once you have `docker run hello-world` working you can get to a docker container's command line by running `docker run -it ubuntu bash`

**Comment by phazei** [comment]
@Maximus5 

Steps from clean pc with ComEmu. 
1) Set "Force ConEmu as default terminal for console applications" with all checks right below it.

2) Install https://github.com/boot2docker/windows-installer/releases/tag/v1.7.1
     This will add the boot2docker command and docker command
     a) run **boot2docker init** to set up the initial virtual box it uses to run docker.
     b) run **boot2docker shellinit**  that will give you the environmental variables to be able to run "docker" from either cmd or bash.
     
3) Install https://github.com/git-for-windows/git/releases/tag/v2.4.6.windows.1
      This will add the bash, make sure to include the command line items to be added to path.

4)  Now everything should be in a position where this issue can be reproduced.
      a) Start either cmd or bash.  It should open in ConEmu
      b) run **docker run --rm -it --entrypoint=//bin/bash ubuntu:14.04**
          (the first time this will need to download a large image every other time it will be fast)
      c) Type anything, tap left to move cursor back, shouldn't work.  Same for home/end.
      d) run **exit**
      e) run **boot2docker ssh**
      f) now run **docker run --rm -it --entrypoint=//bin/bash ubuntu:14.04** again
      g) Type anything, try arrows/home/end, they work.  They also work if ConEmu isn't used.

**Comment by tmds** [comment]
@Maximus5, have you been able to reproduce the issue with the instructions of @phazei?

**Comment by Maximus5** [comment]
Lack of time, haven't tried yet. Docker can't be installed in Virtual box, and I haven't got to any test PC yet. But I keep in mind this.

**Comment by gitfool** [comment]
Same problem here; running `docker run -it ubuntu bash` in powershell directly works as expected, but if running it via ConEmu then arrows don't work and I get other output (like @phazei):

```
←]0;root@3423f69d3960: /root@3423f69d3960:/# ls
←[0m←[01;34mbin←[0m  ←[01;34mboot←[0m  ←[01;34mdev←[0m  ←[01;34metc←[0m  ←[01;34mhome←[0m  ←[01;34mlib←[0m  ←[01;34mlib64←[0m  ←[01;34mmedia←[0m  ←[01;34mmnt←[0m  ←[01;34mopt←[0m  ←[01;34mproc←[0m  ←[01;34mroot←[0m  ←[01;34mrun←[0m  ←[01;34msbin←[0m  ←[01;34msrv←[0m  ←[01;34msys←[0m  ←[30;42mtmp←[0m
  ←[01;34musr←[0m  ←[01;34mvar←[0m
```

**Comment by lucasvc** [comment]
It also fails using `docker exec -ti {container} bash`.

**Comment by Maximus5** [comment]
OK, I've checked it. When you run from ConEmu

```
docker run --rm -it --entrypoint=//bin/bash ubuntu:14.04
```

The docker calls [SetConsoleMode](https://msdn.microsoft.com/en-us/library/ms686033.aspx) to reset flags `ENABLE_PROCESSED_INPUT|ENABLE_LINE_INPUT|ENABLE_ECHO_INPUT` which are critical to enable history in [ReadConsole](https://msdn.microsoft.com/en-us/library/ms684958.aspx). Of course, history (`up` key) is not working anymore because application says "Hey, I'll process all keypressed internally, buzz off". I have no idea why it is working in cmd.exe started outside of ConEmu, it must not in theory. To process history in this mode, docker must not reset these flags. ConEmu can't do it instead of it because, when I tried it, output lines are duplicated...

```
root@e7570f5ed288:/#                                                                                   
root@e7570f5ed288:/# ls                                                                                
ls                                                                                                     
bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var 
root@e7570f5ed288:/#                                                                                   
root@e7570f5ed288:/#                                                                                   
```

When you run `boot2docker ssh`, neither ConEmu nor started ssh client do not do history processing at all, instead all keypressed (`up` key too) are transferred to the ssh server, and history is processed on the server side.

**Comment by Maximus5** [comment]
@gitfool You've disabled [ConEmuHk](http://conemu.github.io/en/ConEmuHk.html) so you have unprocessed ANSI sequences in console.

**Comment by tmds** [comment]
@Maximus5 thanks for investigating!

**Comment by gitfool** [comment]
@Maximus5 Thanks. I enabled the 'Inject ConEmuHk' option and the ANSI sequences are being processed now.

Then I tried again with both Command and PowerShell consoles launched outside of ConEmu and the `up` key definitely provides history functionality in these cases.

**Comment by tmds** [comment]
If I understand @Maximus5's analysis, the docker executable is saying to Windows: I'll handle these special keys. I think this is okay because we expect them to be passed down to the container so that bash (or what ever is reading the terminal) can read them. So these keys arrive in the docker executable but they get lost before they reach the linux terminal.

**Comment by tmds** [comment]
The last line isn't necessarily true. ConEmu might eat them or transform them some way.
I think the settings done by docker make sense and I see how they allow the history to work in cmd (bash is handling it).

**Comment by Maximus5** [comment]
As I said, docker.exe calls ReadConsole function. It read **lines**, so key presses like arrow keys do not reach Linux host at all.
On the contrary, ssh.exe call ReadConsoleInput to read real key presses and they reach Linux host.

**Comment by tmds** [comment]
Ow I see, I misunderstood what you meant by "reset" the flags.
Grepping through the docker code shows leads us to term_windows.go. In that file docker only disables ENABLE_ECHO_INPUT. There doesn't seem to be any code which would turn this on (except for restoring the previous state). ENABLE_PROCESSED_INPUT and ENABLE_LINE_INPUT do get turned on [here](https://github.com/docker/docker/blob/634a848b8e3bdd8aed834559f3b2e0dfc7f5ae3a/pkg/term/term_windows.go#L139).

**Comment by Maximus5** [comment]
Can't check it now, as I remember, docker calls GetConsoleMode several times and SetConsoleMode once during initialization. After that we do not have 0x7 flags set... they are cleared.

**Comment by lucasvc** [comment]
Today I've realized,... that can't either left or right arrow to move in the same command line.
Docker:

    Client:
     Version:      1.8.1
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   d12ea79
     Built:        Thu Aug 13 02:49:29 UTC 2015
     OS/Arch:      windows/amd64

ConEmu: `150913 alpha`

**Comment by koppor** [comment]
Same issue here with ConEmu 150813 and docker 1.8.3.

**Comment by tmds** [comment]
@calavera can you assign this issue to someone with the right experience? @Maximus5 is the maintainer of ConEmu and he has already investigated the issue. Now we are in need of Windows docker expert.

**Comment by thaJeztah** [comment]
@tmds thanks, I'll check with the maintainers

**Comment by thaJeztah** [comment]
@tmds @Maximus5 could you provide some additional information in what area you are seeking assistance? I briefly chatted with someone from the Microsoft team, and he wasn't sure if he could give any useful information, but they're interested in getting this issue fixed.

**Comment by Maximus5** [comment]
Docker is written in Go, isn't it?
The problem is that docker.exe calls ReadConsole. This is  bad approach, because even if tab-completion is working, it would be processed in the Windows side, instead of box side.
It would be better to read console input, key-by-key, and transmit them to box.
In WinApi there is a function ReadConsoleInput, but I'm not aware of Go.

**Comment by Maximus5** [comment]
I described the problem in this comment: https://github.com/docker/docker/issues/13817#issuecomment-140941879

**Comment by jhowardmsft** [comment]
I just spent a few minutes looking at this after talking to @thaJeztah on IRC. Using a very recent (non-public, pre-TP4) build of Windows, I added some debugging and installed the latest conEMU from http://www.fosshub.com/ConEmu.html (alpha 151025 x64).

Docker client turns off it's native ANSI emulation in the case of running under conEMU: https://github.com/docker/docker/blob/master/pkg/term/term_windows.go#L32

I put debugging https://github.com/docker/docker/blob/master/pkg/term/term_windows.go#L175 to see what the mode was. This is called at the point the client puts the terminal into raw mode. The value is 0x1E7, or binary 1 1110 0111. This equates to processed; line input; echo input on (lowest 3 bits).

Next debugging was at https://github.com/docker/docker/blob/master/pkg/term/term_windows.go#L189, and the value is 0x1E0, or binary 1 1110 0000. In other words, those three bits have been turned off (no surprise looking at the lines between). 

I also added a debug statement at the entrypoint into SetConsoleMode to see if anything else was calling it, but it didn't fire apart from the client call to make the terminal raw.

I was doing this pointing docker at a Windows container (rather than Ubuntu) to see if up/down arrow did anything. What I noticed was that they didn't. I then changed docker to stop disabling ECHO_INPUT and LINE_INPUT (ie commenting out these two lines: https://github.com/docker/docker/blob/master/pkg/term/term_windows.go#L178-L179). This did have the effect of up arrow followed by return inside a (Windows) container recalling the previous command and executing it respectively. It wasn't perfect, as typing "exit" for example echo'd this out to the console. 

What are the right flags that conEMU expects for the SetConsoleMode call when docker makes the console into "raw" mode? There shouldn't be an issue changing MakeRaw to set this appropriately in the conEMU case if that sounds like the issue.

**Comment by Maximus5** [comment]
May be the following would be better? Can't compile and check it now...

~~~diff
diff --git a/pkg/term/term_windows.go b/pkg/term/term_windows.go
index da9295e..4b529c0 100644
--- a/pkg/term/term_windows.go
+++ b/pkg/term/term_windows.go
@@ -30,8 +30,13 @@ type Winsize struct {
 func StdStreams() (stdIn io.ReadCloser, stdOut, stdErr io.Writer) {
 	switch {
 	case os.Getenv("ConEmuANSI") == "ON":
-		// The ConEmu shell emulates ANSI well by default.
-		return os.Stdin, os.Stdout, os.Stderr
+		// The ConEmu shell emulates ANSI on output streams well by default.
+		if IsConsole(os.Stdin.Fd()) {
+			stdIn = newAnsiReader(syscall.STD_INPUT_HANDLE)
+		} else {
+			stdIn = os.Stdin
+		}
+		return stdIn, os.Stdout, os.Stderr
 	case os.Getenv("MSYSTEM") != "":
 		// MSYS (mingw) does not emulate ANSI well.
 		return windows.ConsoleStreams()
~~~

**Comment by jhowardmsft** [comment]
I tried that but it just ended up hitting an invalid memory address or nil pointer dereference in the log routine.

``Administrator@WIN-9QQMSEQFG8N E:\go\src\github.com\docker\docker\docker         
$ docker run -it --rm windowsservercore cmd                                     
panic: runtime error: invalid memory address or nil pointer dereference         
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x48b016]                              
                                                                                
goroutine 18 [running]:                                                         
github.com/Sirupsen/logrus.(*Logger).Debugf(0x0, 0x1202bd0, 0x4e, 0xc0824d3b20, 
0x3, 0x3)                                                                       
        e:/go/src/github.com/docker/docker/vendor/src/github.com/Sirupsen/logrus
/logger.go:68 +0x26                                                             
github.com/docker/docker/pkg/term/windows.readInputEvents(0x8, 0x8000, 0x0, 0x0,
 0x0, 0x0, 0x0)                                                                 
        e:/go/src/github.com/docker/docker/pkg/term/windows/ansi_reader.go:114 +
0x22f                                                                           
github.com/docker/docker/pkg/term/windows.(*ansiReader).Read(0xc08200c720, 0xc08
24de000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)                                      
        e:/go/src/github.com/docker/docker/pkg/term/windows/ansi_reader.go:73 +0
x437                                                                            
io.Copy(0x4537e98, 0xc0824c3a70, 0x4537e20, 0xc08200c720, 0x0, 0x0, 0x0)        
        C:/Go/src/io/io.go:362 +0x1fd                                           
net.genericReadFrom(0x4537a38, 0xc08204c5b0, 0x4537e20, 0xc08200c720, 0x0, 0x0, 
0x0)                                                                            
        C:/Go/src/net/net.go:404 +0xbc                                          
net.(*TCPConn).ReadFrom(0xc08204c5b0, 0x4537e20, 0xc08200c720, 0x4537e70, 0x0, 0
x0)                                                                             
        C:/Go/src/net/tcpsock_posix.go:72 +0xe7                                 
io.Copy(0x4537a38, 0xc08204c5b0, 0x4537e20, 0xc08200c720, 0x0, 0x0, 0x0)        
        C:/Go/src/io/io.go:358 +0x144                                           
github.com/docker/docker/api/client.func┬╖013()                                 
        e:/go/src/github.com/docker/docker/api/client/hijack.go:228 +0xda       
created by github.com/docker/docker/api/client.(*DockerCli).hijackWithContentTyp
e                                                                               
        e:/go/src/github.com/docker/docker/api/client/hijack.go:240 +0xe00      
                                                                                ``

**Comment by jhowardmsft** [comment]
https://github.com/docker/docker/compare/master...Microsoft:jjh/conemu?expand=1

**Comment by Maximus5** [comment]
Finally, I'd successfully built `docker.exe` from sources (using `go build` in docker folder).
But now I face the API version mismatch error.
~~~
client is newer than server (client API version: 1.22, server API version: 1.20)
~~~
Any hints how to update the server?

**Comment by jhowardmsft** [comment]
Is this a Linux server or Windows?

**Comment by jhowardmsft** [comment]
You should be able to pull the right binary from https://master.dockerproject.org/

**Comment by Maximus5** [comment]
Linux server. Installed by DockerToolbox-1.8.3.exe.

**Comment by Maximus5** [comment]
Hmm... A how may I update the daemon on boot2docker linux server?
[linux server screenshot](http://i.imgur.com/EcUxTHI.png)

**Comment by jhowardmsft** [comment]
@Maximus5 I've never used boot2docker, but if it's similar to Ubuntu Linux, I do `which docker` to find the path of the current binary; `service docker stop`; `cp [newbinary] /path/to/docker`; `service docker start`. HTH :)

**Comment by tmds** [comment]
@Maximus5 alternatively you can build the docker client which supports API version 1.20. Building the 1.8.3 tag should give you a compatible client.

**Comment by Maximus5** [comment]
Here is a [patch](https://github.com/Maximus5/docker/commit/fee2b85928e3a04f9b419077f6ff99e055a3dec4) and [test  binary](https://github.com/Maximus5/docker/releases/tag/v1.8.3-conemu-test1) for a problem.

**Comment by tmds** [comment]
Hooray! Thanks for fixing this @Maximus5
Can you send a pull request to the docker guys?

**Comment by Maximus5** [comment]
They demand real signer name. Aliases are not acceptable. The contribution rules say.

**Comment by jhowardmsft** [comment]
@Maximus5 Do you want me to submit your patch (and sign it), and reference you on the PR?

**Comment by Maximus5** [comment]
@jhowardmsft Yes, it's OK for me.

**Comment by jhowardmsft** [comment]
Unfortunately this patch is against 1.8.x. With current master, I'm not sure how to implement ConEmuStreams() - the code is quite different.

**Comment by tmds** [comment]
@jhowardmsft That's indeed unfortunate.
Looks like things changed mostly in the commit you made here: https://github.com/docker/docker/commit/c923774c41678e4044081a87ec5841173d9577e7
Can you figure out how make it work in the new code? Perhaps you can re-use some of the code which got removed and plug in what @Maximus5 wrote.

**Comment by Maximus5** [comment]
The patch for current master branch is [here](https://github.com/Maximus5/docker/commit/635583f629e46eaa413baac87f85986112557fe0).

`docker.exe` compiled successfully, but I can't check it, because have no idea how to build new boot2docker virtual machine.

**Comment by lucasvc** [comment]
@Maximus5, I tested a litte bit the [`v1.8.3-conemu-test1`](https://github.com/Maximus5/docker/releases/tag/v1.8.3-conemu-test1) binary and seems to work fine :) Thanks!

If you can generate the binary for master, I can test it against a docker 1.9.0 server.

**Comment by Maximus5** [comment]
Here it is [v1.9.0-conemu-test1](https://github.com/Maximus5/docker/releases/tag/v1.9.0-conemu-test1).

**Comment by thaJeztah** [comment]
For those wanting to test it, release candidates for docker toolbox 1.9 can be found here; https://github.com/docker/toolbox/releases

**Comment by Maximus5** [comment]
@thaJeztah How? Latest available 1.9.0-rc3 still has API version 1.21. But master branch is now 1.22.

**Comment by thaJeztah** [comment]
@Maximus5 o, you're right the API-version in the repository was bumped when the RC was created. There's actually an issue open to allow overriding the version, see https://github.com/docker/docker/issues/11486 and https://github.com/docker/docker/pull/15964, but that doesn't solve it for now :/

**Comment by lucasvc** [comment]
I found it too ^^', but [binaries from here](https://master.dockerproject.org/) are API 1.22.
But,.... not working :(
This is the trace, doing `docker exec -ti <container> bash`:
````
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x4a01b3]

goroutine 14 [running]:
github.com/Sirupsen/logrus.(*Logger).Debugf(0x0, 0xaeb080, 0x4e, 0xc082191998, 0x3, 0x3)
	T:/gopath/src/github.com/docker/docker/vendor/src/github.com/Sirupsen/logrus/logger.go:68 +0x23
github.com/docker/docker/pkg/term/windows.readInputEvents(0x3, 0x8000, 0x0, 0x0, 0x0, 0x0, 0x0)
	T:/gopath/src/github.com/docker/docker/pkg/term/windows/ansi_reader.go:114 +0x262
github.com/docker/docker/pkg/term/windows.(*ansiReader).Read(0xc08200d1a0, 0xc082192000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	T:/gopath/src/github.com/docker/docker/pkg/term/windows/ansi_reader.go:73 +0x47b
io.copyBuffer(0x12762f8, 0xc082157be0, 0x1276280, 0xc08200d1a0, 0xc082192000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	T:/Go/src/io/io.go:381 +0x24e
io.Copy(0x12762f8, 0xc082157be0, 0x1276280, 0xc08200d1a0, 0xc082157be0, 0x0, 0x0)
	T:/Go/src/io/io.go:351 +0x6b
net.genericReadFrom(0x1276128, 0xc0820241b0, 0x1276280, 0xc08200d1a0, 0x0, 0x0, 0x0)
	T:/Go/src/net/net.go:559 +0xb8
net.(*TCPConn).ReadFrom(0xc0820241b0, 0x1276280, 0xc08200d1a0, 0xc082191e28, 0x0, 0x0)
	T:/Go/src/net/tcpsock_posix.go:63 +0x2f8
io.copyBuffer(0x1276128, 0xc0820241b0, 0x1276280, 0xc08200d1a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	T:/Go/src/io/io.go:375 +0x187
io.Copy(0x1276128, 0xc0820241b0, 0x1276280, 0xc08200d1a0, 0xc08200d1a0, 0x0, 0x0)
	T:/Go/src/io/io.go:351 +0x6b
github.com/docker/docker/api/client.(*DockerCli).hijackWithContentType.func3(0x1274c00, 0xc08200d1a0, 0x1275048, 0xc0820241b0, 0xc08200db60)
	T:/gopath/src/github.com/docker/docker/api/client/hijack.go:228 +0xe2
created by github.com/docker/docker/api/client.(*DockerCli).hijackWithContentType
	T:/gopath/src/github.com/docker/docker/api/client/hijack.go:240 +0xd95

goroutine 1 [runnable]:
github.com/docker/docker/api/client.(*DockerCli).CmdExec(0xc082072300, 0xc08200e250, 0x3, 0x3, 0x0, 0x0)
	T:/gopath/src/github.com/docker/docker/api/client/exec.go:99 +0xf62
reflect.callMethod(0xc082160300, 0xc082101c78)
	T:/Go/src/reflect/value.go:628 +0x203
reflect.methodValueCall(0xc08200e250, 0x3, 0x3, 0x1, 0xc082160300, 0x0, 0x0, 0xc082160300, 0x0, 0x466a1b, ...)
	T:/Go/src/reflect/asm_amd64.s:29 +0x3d
github.com/docker/docker/cli.(*Cli).Run(0xc082105f20, 0xc08200e240, 0x4, 0x4, 0x0, 0x0)
	T:/gopath/src/github.com/docker/docker/cli/cli.go:89 +0x38a
main.main()
	T:/gopath/src/github.com/docker/docker/docker/docker.go:65 +0x31e

goroutine 5 [syscall]:
os/signal.loop()
	T:/Go/src/os/signal/signal_unix.go:22 +0x1f
created by os/signal.init.1
	T:/Go/src/os/signal/signal_unix.go:28 +0x3e

goroutine 11 [select]:
github.com/docker/docker/api/client.(*DockerCli).hijackWithContentType(0xc082072300, 0xa22618, 0x4, 0xc08200f9a0, 0x4c, 0xa7ef50, 0x10, 0xc08200f901, 0x1274c00, 0xc08200d1a0, ...)
	T:/gopath/src/github.com/docker/docker/api/client/hijack.go:242 +0x1147
github.com/docker/docker/api/client.(*DockerCli).CmdExec.func2(0x0, 0x0)
	T:/gopath/src/github.com/docker/docker/api/client/exec.go:95 +0x1ff
github.com/docker/docker/pkg/promise.Go.func1(0xc08200d980, 0xc08200d920)
	T:/gopath/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x24
created by github.com/docker/docker/pkg/promise.Go
	T:/gopath/src/github.com/docker/docker/pkg/promise/promise.go:9 +0x64

goroutine 9 [IO wait]:
net.runtime_pollWait(0x1276018, 0x72, 0xc082157920)
	T:/Go/src/runtime/netpoll.go:157 +0x67
net.(*pollDesc).Wait(0xc08201b4f0, 0x72, 0x0, 0x0)
	T:/Go/src/net/fd_poll_runtime.go:73 +0x41
net.(*ioSrv).ExecIO(0xc082024188, 0xc08201b3e0, 0xa23138, 0x7, 0xb26870, 0x360000, 0x0, 0x0)
	T:/Go/src/net/fd_windows.go:182 +0x177
net.(*netFD).Read(0xc08201b380, 0xc08215f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	T:/Go/src/net/fd_windows.go:463 +0x17e
net.(*conn).Read(0xc082024198, 0xc08215f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	T:/Go/src/net/net.go:172 +0xeb
net/http.noteEOFReader.Read(0x12760d8, 0xc082024198, 0xc082098478, 0xc08215f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	T:/Go/src/net/http/transport.go:1370 +0x6e
net/http.(*noteEOFReader).Read(0xc082164420, 0xc08215f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd7
bufio.(*Reader).fill(0xc08200d740)
	T:/Go/src/bufio/bufio.go:97 +0x1f0
bufio.(*Reader).Peek(0xc08200d740, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	T:/Go/src/bufio/bufio.go:132 +0xd3
net/http.(*persistConn).readLoop(0xc082098420)
	T:/Go/src/net/http/transport.go:876 +0xfe
created by net/http.(*Transport).dialConn
	T:/Go/src/net/http/transport.go:685 +0xc7f

goroutine 10 [select]:
net/http.(*persistConn).writeLoop(0xc082098420)
	T:/Go/src/net/http/transport.go:1009 +0x413
created by net/http.(*Transport).dialConn
	T:/Go/src/net/http/transport.go:686 +0xca4

goroutine 12 [runnable]:
github.com/docker/docker/pkg/term.restoreAtInterrupt.func1(0xc08200daa0, 0x3, 0xc082157b80)
	T:/gopath/src/github.com/docker/docker/pkg/term/term_windows.go:200
created by github.com/docker/docker/pkg/term.restoreAtInterrupt
	T:/gopath/src/github.com/docker/docker/pkg/term/term_windows.go:204 +0xee

goroutine 13 [runnable]:
github.com/docker/docker/api/client.(*DockerCli).hijackWithContentType.func2(0x1274c00, 0xc08200d1a0, 0xc082024101, 0xc082072300, 0xc082157b80, 0x12742c0, 0xc082024010, 0xc0821579a0, 0xc08200da40, 0x12742c0, ...)
	T:/gopath/src/github.com/docker/docker/api/client/hijack.go:204
created by github.com/docker/docker/api/client.(*DockerCli).hijackWithContentType
	T:/gopath/src/github.com/docker/docker/api/client/hijack.go:222 +0x11e4
````

**Comment by Maximus5** [comment]
How to get proper boot2docker?

**Comment by vladgabriel** [comment]
Can't you just update the docker binary inside the boot2docker image?

**Comment by lucasvc** [comment]
If you can access VirtualBox filesystem, you can change the `/usr/bin/docker` binary with [this one](https://master.dockerproject.org/linux/amd64/docker).
I can't tell you how to access the virtual machine, as I don't use boot2docker :(

**Comment by jhowardmsft** [comment]
@Maximus5 Yeah, tried the patch from Commit https://github.com/Maximus5/docker/commit/635583f629e46eaa413baac87f85986112557fe0 against docker master, and hits that panic both myself and @lucasvc mentioned.

**Comment by tmds** [comment]
Looking at @Maximus5's patch, it looks very similar to the other code. I'd expect it to work or not work, but I don't expect it to crash.
Looking a bit closer at the stacktrace, could it be that this is caused by the [logger being null](https://github.com/docker/docker/blob/master/pkg/term/windows/ansi_reader.go#L114)?
@jhowardmsft what do you think?

**Comment by tmds** [comment]
@jhowardmsft can you investigate why the patch is causing a panic?

**Comment by lucasvc** [comment]
@jhowardmsft @Maximus5 any update on this?

**Comment by krishna81m** [comment]
Is this related to my windows ubuntu container docker 1.9 issue where **I cannot use arrows in vim** and live with alphabets to go around? 

```
root@924f6bbd5f18:/# echo $TERM
xterm

$ docker info
Containers: 7
Images: 257
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 271
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.12-boot2docker
Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: NRKH:UFIV:Y42U:7XGL:NQ3H:QEK5:5JT3:M7AJ:7O2X:EPWJ:MSPR:DXCH
Debug mode (server): true
 File Descriptors: 20
 Goroutines: 39
 System Time: 2016-01-27T02:43:41.379470091Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

**Comment by tmds** [comment]
@krishna81m are you using ConEmu?
@phazei or @calavera, can we update the title of this issue? and replace 'windows' by 'ConEmu'

@calavera @jhowardmsft can we find someone to work on this issue? With the info we have gathered so far and the help of @Maximus5 we should be able to get this fixed quite fast. We need someone with some Docker (go) development experience and some background in terminals. @jhowardmsft I think you have the right background, do you have some time? Or do you know another contributor who'd fit these criteria?

**Comment by krishna81m** [comment]
@tmds No I am not, I am using Windows.

**Comment by tmds** [comment]
@krishna81m I think it is best to scope this issue to "ConEmu - Docker interoperability" (and update the title). So in that view, it is be better if you create a separate issue.

**Comment by xinity** [comment]
@tmds FWIW i've switched to using [consoleZ](https://github.com/cbucher/console)
which seems to fix all issues (tty, arrows ...)

i can share a setup if needed :)

**Comment by Maximus5** [comment]
Of course, ConsoleZ works, Docker does not care or know anything about it at all!

If Docker does not care if it is started in ConEmu,
arrows would work like a charm too!

Let's take a look at the problem history:

* Prior to commit b38ff8c Docker did not know anything about ConEmu,
  and arrows were working properly, exactly as in startard Windows console.
* Commit b38ff8c (by @ahmetalpbalkan) stopped Docker's internal ANSI
  processor, and started passing RAW output to ConEmu. Nice, but this breaks
  arrows processing completely.
* OK, after users requests I started hacking on Docker, and fixed the problem
  for Docker version 1.8.3 by commit Maximus5/docker@fee2b85.
* Docker version 1.9.0 was released and things went worse. ‘Patched’ version
  crashed on start.

Unaffiliated authors have to make fixes in Docker, to let it work properly.
Seems like nobody in Docker's team works in Windows, and Windows' users
are supported on leftovers.

OK, I understand, Docker is an ‘open source software’, but it's a disappointment,
to see users complaining ‘ConEmu is not working...’

### Finally

After commits below, arrows are working in version 1.9.0.

* Maximus5/docker@18d803a
* Maximus5/docker@1aa2a6d

However, after `exit` Docker shows some warning, but who cares?

~~~
/ # exit
json: cannot unmarshal object into Go value of type []string
~~~

**Comment by friism** [comment]
@Maximus5 is there are a way that the integration tests can exercise the `winconsole` tests to ensure that we don't get regressions?

I'm sorry about the breakage, I'd love for us to find a way to ensure that we get a good experience across the various Windows terminal emulators.

**Comment by Maximus5** [comment]
@friism Are you talking about some new test, which may be inserted in Docker's tests queue? If you may point me to some docs or examples, it would be nice.

As for the arrows issue in Docker+ConEmu, the test may contains following steps

* Run docker shell in ConEmu on Windows
* Post into console input buffer series of keypresses (this may be done via [GuiMacro](https://conemu.github.io/en/GuiMacro.html)), sort of

~~~
docker run --rm -it busybox <ENTER>
ls <ENTER>
<UP> <ENTER>
~~~

But I'm not aware if this test can be verified. Well, instead of `ls` any other command may be executed, for example `echo abc >> docker.log` and the test can check that `abc` was added to the file twice. What integration tests are you using now?

**Comment by tmds** [comment]
@Maximus5 Thanks for caring about your users.

The update to @Maxmus5 patch shows that the logger is only created when instantiating a newAnsiWriter. Since that isn't needed for ConEmu, the logger remains null and causes the panic.

It would be nice of someone from the docker team could work on this issue more actively.
All ingredients for a solution have been available for about 3 months now.

**Comment by jhowardmsft** [comment]
I just built a docker Windows binary based on master with cherry-picks of https://github.com/Maximus5/docker/commit/18d803a and https://github.com/Maximus5/docker/commit/1aa2a6d

It's pointing at an Ubuntu Linux VM running a relatively recent build of docker based on master (see docker version in screenshot below). Yay, no more panic.

In busybox, yes, the repro steps above: docker run --rm -it busybox <ENTER> ls <ENTER> <UP> <ENTER> works.

However, I tried the same against an Ubuntu image running sh. As you can see, here, the <UP> is being interpreted in some way as an ANSI sequence.

Interestingly, I do not see the `json unmarshal` error, so I guess something else has been fixed in Docker, or the bug was a byproduct of an older version of go(?).

![conenu](https://cloud.githubusercontent.com/assets/10522484/12667036/735c8e1c-c5fb-11e5-84bc-c993da795494.JPG)


By comparison, the below is docker/docker master as of a few minutes ago, no cherry picks. Arguably this is worse as the <UP> does nothing at all. Note also I don't see json unmarshal error here either.


![conemu2](https://cloud.githubusercontent.com/assets/10522484/12667275/166b7102-c5fe-11e5-901f-46be8a6d250c.JPG)

I have squashed the commits and submitted this to docker (on behalf of @Maximus5 based on previous conversations) as PR #19823.

**Comment by Maximus5** [comment]
The problem with ubuntu is only docker's problem. Same error when running original docker, outside of ConEmu, using shortcut created by Docker Toolbox.
Interestingly, that when you run `docker run -it --rm ubuntu`, arrows and BS are working properly.

![2016-01-29_10-36-11](https://cloud.githubusercontent.com/assets/1222388/12669771/211bc450-c674-11e5-9bb0-7aaba05b4f6c.png)

Perhaps, there is something related to profile load and `TERM` variable on client and server.

![2016-01-29_10-39-59](https://cloud.githubusercontent.com/assets/1222388/12669838/a70efeb0-c674-11e5-917a-19d66b091381.png)

Anyway, this is absolutely different issue, not related to ConEmu at all.

**Comment by MatthewMiele** [comment]
Before I go and open a ticket I just want to check here...

For me I'm getting this exact same issue, using the latest docker for windows 1.12. After finding this ticket and seeing the fix was merged in a while ago I'm thinking it shouldn't be happening anymore?

Or is this fix for Docker for before it went native on windows? 

Windows 10 with anniversary update
Docker 1.12 (tested with beta as well)
ConEmu Build 160724

**Comment by mdunc** [comment]
Yep, I'm running in to this as well with Docker for Windows and Cmder (which uses ConEmu).

**Comment by vladgabriel** [comment]
For those who want a reliable solution you can user cmder: https://github.com/cmderdev/cmder/releases , download and extract the latest release. Then under cmder/bin folder place docker-machine.exe, docker.exe and docker-compose.exe from the official github pages. 
![docker1](https://cloud.githubusercontent.com/assets/10796639/17472920/497ad354-5d56-11e6-8c79-2568722f65e1.jpg)

After you first open cmder a user-profile.bat will be created under cmder/config folder. Edit the file to look like this:

```
:: Isolate windows PATH
@set PATH=C:\Windows
PATH=%PATH%;C:\Windows\system32
PATH=%PATH%;C:\Program Files\Oracle\VirtualBox
PATH=%PATH%;%CMDER_ROOT%
PATH=%PATH%;%CMDER_ROOT%\bin
PATH=%PATH%;%CMDER_ROOT%\vendor\conemu-maximus5
PATH=%PATH%;%CMDER_ROOT%\vendor\conemu-maximus5\ConEmu
PATH=%PATH%;%CMDER_ROOT%\vendor\git-for-windows\bin
PATH=%PATH%;%CMDER_ROOT%\vendor\git-for-windows\cmd
PATH=%PATH%;%CMDER_ROOT%\vendor\git-for-windows\mingw32\bin
PATH=%PATH%;%CMDER_ROOT%\vendor\git-for-windows\usr\bin

:: Set VM storage
@set MACHINE_STORAGE_PATH=D:\.docker

:: Set docker active machine
@SET DOCKER_TLS_VERIFY=1
@SET DOCKER_HOST=tcp://192.168.99.100:2376
@SET DOCKER_CERT_PATH=D:\.docker\machines\docker
@SET DOCKER_MACHINE_NAME=docker
```

Save and reopen cmder.

For me this is the only solution in which everything works accordingly. Also after entering a docker container this may help: `export TERM=linux`

**Comment by Cano8** [comment]
@vladgabriel Your solution doesn't apply for those of us running Docker for Windows.

@MatthewMiele @mdunc Have you found any solutions?

I'm running 
```Docker version 1.12.0, build 8eab29e```

While running the folowing command:
```docker exec -it ubuntu bash```
I can't use arrow keys, Home, End, PgUp, PgDown, Delete and probably other keys.
Not that I CAN use these keys when I open Real Console or use standard cmd.exe.

Even weirder things happen when I run docker with cygwin bash.
If I run a task like this:
```bash.exe```
It's exactly the same - I can only use arrow keys etc. in Real Console.

If I run a task like this:
```bash -cur_console:p1```
Repeatedly pressing Del produces:
```333~~~33~~~333~33~~~~~33~~33~~~3~33~~3~~3~333~```
PgDown:
```6~66666~6666666~666~~6~~~666~66?~6```
Arrow keys just make the window flash and work and actually work once in a blue moon.

Seems like an issue exclusive to ConEmu considering it doesn't occur in standard cmd.exe or in Real Console.
Does anyone have the same issue?

**Comment by Maximus5** [comment]
Does docker utilize bash from LinuxSubsystemForWindows?
I haven't checked yet, what was broken in Docker sources. I consider it was broken, because it was working before, isn't it?
But, you may try to check any of previous ConEmu builds.

**Comment by vladgabriel** [comment]
@Cano8 

Offtopic:
Docker for windows is bull****. Once you enable Hyper-V you won't be able to use any other virtualization method(ex, virtualbox).
Docker for windows does the same exact same thing like docker toolbox, it uses virtualization to create a small linux machine in order to run the docker engine. I don't see any value in using it just because windows came by and 'helped' the docker team.

Ontopic:
The cmder solution should be working even with docker for windows, try and set the correct path to the docker binary. The example written above takes it from cmder/bin, remove that and set it to the folder where docker for windows is installed. You will probably need some other binaries but that needs to be checked.

Happy coding:D

**Comment by cpuguy83** [comment]
@vladgabriel Sure it's using a hypervisor (as it does on Mac as well). But it does the integration for you and much more cleanly than can be done with virtualbox, and it sets up file sharing, and all kinds of other stuff. Hardly BS.

**Comment by Cano8** [comment]
@Maximus5 It used to work because previously docker itself was running within a VM.
In docker for Windows it defacto sill does, but you use docker.exe client running on Windows to communicate with it instead of SSHing to VM and running docker there.

I don't have LinuxSubsystemForWindows so I guess Docker for Windows doesn't use it.

**Comment by jajansen** [comment]
It is a regression on docker 1.12.x 
It worked on 1.10.x, 1.11.x, but is broken again in 1.12.x

**Comment by Cano8** [comment]
@jajansen Thanks man, I think we can expect this to be fixed soon.
https://github.com/docker/docker/pull/25578

**Comment by otravers** [comment]
For the record I can still replicate that behavior with Docker for Windows 1.12.1-stable (b7135) and ConEmu v160914[64]. Which I guess makes sense since the issue referenced by @Cano8 is still under code review.

**Comment by skione** [comment]
@cpuguy83 sure hyper-v has its benefits but honestly it is SUCH an abortion. The fact that you can't run any other virtualization platform is enough to say it is not worth any of the supposed benefits. VirtualBox allows for file sharing in a way that is pretty similar to hyper-v and the worst part is if you remove the role of hyper-v and then try and add it back in Docker breaks. It took a long time and lost of uninstalls and reinstalls to get it to work again. Hyper-v sucks!

**Comment by amclelland** [comment]
Any luck on this? I am also unable to use arrow keys, home, etc. when I `docker exec -it web bash` from cmder. But if I use vanilla cmd it works fine - I think it was the recent docker update?

**Comment by jcwilson** [comment]
> @tmds FWIW i've switched to using consoleZ
> which seems to fix all issues (tty, arrows ...)
> 
> i can share a setup if needed :)

Can you share this, @xinity? I am using ConsoleZ but have been running into this issue recently. Oddly enough, this only started after installing the latest Docker for Windows, though I'm using the virtualbox driver (not hyper-v). When using DockerToobox 1.12.0 I did not have any issues.

> 
> Client:
>  Version:      1.12.1
>  API version:  1.24
>  Go version:   go1.6.3
>  Git commit:   23cf638
>  Built:        Thu Aug 18 17:52:38 2016
>  OS/Arch:      windows/amd64
> 
> Server:
>  Version:      1.12.1
>  API version:  1.24
>  Go version:   go1.6.3
>  Git commit:   23cf638
>  Built:        Thu Aug 18 17:52:38 2016
>  OS/Arch:      linux/amd64

**Comment by thaJeztah** [comment]
@jcwilson we released a release-candidate for 1.12.2 for testing; see https://github.com/docker/docker/releases/tag/v1.12.2-rc1. I _think_ this is a client-side only fix, so you only need the `docker` (client) binary to test if it's resolved.

**Comment by amclelland** [comment]
That worked, @thaJeztah! Thanks very much :D

**Comment by jcwilson** [comment]
@thaJeztah That works! I did have to `export ConEmuANSI=ON` even though I'm using ConsoleZ. I can add that it appears ConsoleZ injects the following environment variables into its shell sessions:
```
ConsoleZVersion=1.16.1.16068
ConsoleZBaseDir=C:\Users\Josh.Wilson\<path-to>\ConsoleZ.x64.1.16.1.16068
```
Perhaps it would make sense to add a check similar to the ConEmuANSI one. It does seem a bit weird for docker to be adding terminal/shell checks into its code. Maybe docker should look for a more generic `ANSI_STDIN` (or whatever) and let ConEmu and ConsoleZ users set that for themselves in their environment. In any case, thanks for the rc!

**Comment by thaJeztah** [comment]
Thanks @amclelland @jcwilson for testing! W.r.t. the environment variables; if you think it's an important improvement, please open a new issue (feature request) for discussion

**Comment by helgeho** [comment]
@thaJeztah @Maximus5 I had the same issue and the new docker.exe from the 1.12.2 RC1 indeed fixes it partially. Arrow keys work on Bash now, so moving up and down in the history does work, however, it turns out that they still don't work everywhere. For instance, inside 'less' you still cannot navigate in an opened file with the arrow keys, when running it inside a container on ConEmu. This can easily be reconstructed by, for example, running a docker container on an ubuntu image in ConEmu (`docker run --rm -ti ubuntu bash`), install 'less' using apt-get (`apt-get update && apt-get install less`) and open some file, e.g. `less var/log/bootstrap.log`. Now try to press up/down.

I would be very happy to see this fixed completely soon as ConEmu seems to be widely used as an alternative console emulator and together docker it is a great way to work with all the linux tools on windows.

**Comment by helgeho** [comment]
Okay, I just figured that this is just because of the terminal mode set in the ubuntu image.
Changing the terminal mode of ConEmu to XTerm or calling docker with `docker run -e TERM ...` fixes it.

**Comment by elijahgagne** [comment]
@helgeho Thanks for posting. I am using the latest versions of Docker for Windows beta and ConEmu and trying what you suggest, but not having luck yet. I am probably misunderstanding. 

I have tried setting an environment variable:

```
docker run -e TERM --rm -ti ubuntu bash

apt-get update && apt-get install less
less var/log/bootstrap.log
```

But that's not working. Do I need to specify TERM=something? I am not sure how to change the terminal mode of ConEmu. In the settings I have:

![image](https://cloud.githubusercontent.com/assets/2213005/19419640/f9307374-93a9-11e6-9f56-bd7f82fc1f0a.png)

![image](https://cloud.githubusercontent.com/assets/2213005/19419642/04299418-93aa-11e6-8d4b-04ad5079f972.png)

But that doesn't make a difference. Is there another setting I am missing for setting the terminal mode?

**Comment by helgeho** [comment]
@elijahgagne I am not sure, but don't think the docker.exe from RC1 is included in the latest beta yet. I am using the one from https://github.com/docker/docker/releases/tag/v1.12.2-rc1 . Without the right .exe file the arrow keys won't even work for navigating the history.

To make it work in less or vi etc. just setting `-e TERM` (without a parameter) has been enough for me, this unsets the `TERM` variable (the default value on ubuntu is xterm). Alternatively, you can change the terminal mode in ConEmu by right clicking on the status bar at the bottom and check *terminal modes*. Then left click on the terminal modes menu in the status bar and switch to XTerm.

Hope this helps!

**Comment by elijahgagne** [comment]
Interesting. Thanks for making it clear about nulling out the TERM env var and changing terminal modes in ConEmu.

I am running 1.12.2 (not a release candidate).
```
PS C:\Users\egagn> docker --version
Docker version 1.12.2, build bb80604, experimental
```
It looks like 1.12.2 was released 6 days ago, whereas 1.12.2-rc1 was released 19 days ago. https://github.com/docker/docker/releases/

I will comment that up/down works fine in bash and kinda works in vi (although it seems a little buggy). It's not working at all for me in less.

**Comment by Maximus5** [comment]
In ConEmu ine may change "AppKeys" same way as "XTerm" mode in the [StatusBar](https://conemu.github.io/en/StatusBar.html).
This may be a workaround for less until Docker fix the problem in its codebase.
Note that in Unix arrow keys may be encoded in two ways at least ;)

**Comment by matthid** [comment]
Just wanted to add that additionally https://github.com/docker/docker/releases/tag/v1.12.2-rc1 seems to fix another issue where pasted text (right click in ConEmu) sometimes contained `?` and missing characters in the "dockerized" shell.

Thanks everyone and especially @Maximus5! So frustrating when the terminal is not working :)

**Comment by helgeho** [comment]
Even if it is indeed working by changing the terminal mode in ConEmu, it is still not working well. At the first glance, everything looks fine, but if you try to navigate in larger files in VIM, really strange things happen. Sometimes lines disappear or the cursor jumps arround and one can scroll in VIM indefinitely. Similarly, when typing in bash and pressing `tab` to autocomplete a path, the curser sometimes jumps to the next line and completes it there or you end it having a part of the path somewhere at the end of the line in the terminal.

Is this just me or do others have these or similar problems as well?
I've been using the terminal and VIM inside Docker in ConEmu a lot, because I am working on windows and do all my unix/linux tasks in Docker containers. But these issues make it almost impossible to use, e.g., edditing files in VIM is really a pain.

Are there any ideas or workaround for this?
And whoms task is it to fix this? ConEmu? Docker?
Thanks in advance!

**Comment by thaJeztah** [comment]
I wonder if changes such as https://github.com/docker/docker/pull/28304 will help here. ping @ijc25 ?

**Comment by erikverheij** [comment]
I had the same problem and I can confirm it's fixed after I updated Docker for windows :).

**Comment by helgeho** [comment]
@erikverheij are you running a beta? I am on 1.12.3, that's the latest stable Docker for windows

**Comment by erikverheij** [comment]
Docker v1.12.3 stable channel build 8488
ConEmu 161022 {Stable} with startup task "Shells::PowerShell"

**Comment by helgeho** [comment]
@erikverheij Thanks, but that's exactly what I am using, anyone else with the same issues?

**Comment by erikverheij** [comment]
You could try it with my config file; https://gist.github.com/erikverheij/e207071d37fc064e57bff6a6406dcf84

**Comment by elijahgagne** [comment]
@helgeho Yes, I am on ConEmu 161022x64, PowerShell. With Docker 1.12.3-beta30.1 (8711). I agree with your statement that at first glance, things seem ok, but strangeness occurs as you try to use it a lot.

**Comment by ijc25** [comment]
@thaJeztah I'm afraid that #28304 will only make a difference to the rendering of the progress bars on a `docker pull` or similar, it won't make any difference to an interactive shell session's handling of arrows etc. Sorry!

**Comment by thaJeztah** [comment]
@ijc25 alright, thanks! Was just letting my mind go :)

**Comment by ijc25** [comment]
@thaJeztah it is possible that terminfo improvements elsewhere might help, e.g. a terminfo entry in the container corresponding to the `$TERM` set by whichever shell is in use.

**Comment by arthi-ramachandran** [comment]
@jhowardmsft , I have been trying to get to git bash after installing that insider a windows server 2016 container. docker run -it git-windows powershell. the image git-windows installs git for windows just fine in c:\git. However, once inside the powershell ( container ), unable to get to git bash. Have been struggling for a while. Can you pls give some light ?

**Comment by jhowardmsft** [comment]
It appears none of the msys posix utilities work interactively. I believe they take a reliance on console hooks which aren't present in a Windows container, but haven't looked at the source code for them.

**Comment by arthi-ramachandran** [comment]
@jhowardmsft thanks for the response.
am not even concerned abt the interactive ones. Atlease basic ones like vi, who, which, grep, find is what we need. I've attached the install of git inside a windows container. Much appreciated any suggestion to get past this ?
 


Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\> cd git
PS C:\git> ls


    Directory: C:\git


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       11/18/2016  10:16 AM                bin
d-----       11/18/2016  10:16 AM                cmd
d-----       11/18/2016  10:17 AM                dev
d-----       11/18/2016  10:17 AM                etc
d-----       11/18/2016  10:16 AM                mingw64
d-----       11/18/2016  10:17 AM                tmp
d-----       11/18/2016  10:17 AM                usr
-a----        10/4/2016   6:19 PM         151272 git-bash.exe
-a----        10/4/2016   6:19 PM         150760 git-cmd.exe
-a----         8/9/2016   6:54 PM          18765 LICENSE.txt
-a----        10/4/2016   6:36 PM          80827 ReleaseNotes.html
-a----       11/18/2016  10:17 AM         825060 unins000.dat
-a----       11/18/2016  10:16 AM        1293032 unins000.exe
-a----       11/18/2016  10:17 AM          22811 unins000.msg


PS C:\git>

**Comment by jhowardmsft** [comment]
vi is only going to work interactively. But as I said I've never got any of the posix utilities to work interactively. See the note in dockerfile.windows for example.

**Comment by arthi-ramachandran** [comment]
@jhowardmsft Hi John, thanks.
https://github.com/docker/docker/blob/master/Dockerfile.windows#L165
Assume, 
The posix utilities from git aren't usable interactively as at October 2016. This
# is because they require a console window which isn't present in a container in Windows.
# See the example at the top of this file. Do NOT use -it in that docker run. It will not work.

I have all windows  prereqs listed in Dockerfile.windows.

However, your run cmd,
docker run --name binaries nativebuildimage sh -c 'cd /c/go/src/github.com/docker/docker; hack/make.sh binary'

cmd like sh is from git install I assume. Is there any reco for me on using cmds like sh, bash, find, grep, egrep inside windows container ? Appreciate much.

**Comment by jhowardmsft** [comment]
As I said, not interactively. So don't use -it.

**Comment by arthi-ramachandran** [comment]
@jhowardmsft , Thanks!
This run cmd seems to access bash.exe in cygwin
PS C:\cygwin\bin> docker run cygwin-win c:\cygwin\bin\bash -c 'cd /cygdrive/c/cygwin; /cygdrive/c/cygwin/bin/ls -al'
total 12
d---rwxr-x+ 1 Administrators         ContainerAdministrator      0 Nov 17 17:57 .
drwxrwxr-x+ 1 Administrators         SYSTEM                      0 Nov 19 13:20 ..
-r--rw-r--+ 1 Administrators         Administrators          53342 Nov 17 17:57 Cygwin-Terminal.ico
-r-xrwxr-x+ 1 Administrators         Administrators             57 Nov 17 17:57 Cygwin.bat
----rw-r--+ 1 Administrators         ContainerAdministrator 157097 Nov 17 17:57 Cygwin.ico
drwxr-xr-x+ 1 ContainerAdministrator ContainerAdministrator      0 Nov 19 13:20 bin
d---rwxr-x+ 1 Administrators         ContainerAdministrator      0 Nov 17 17:57 dev
drwxr-xr-x+ 1 ContainerAdministrator ContainerAdministrator      0 Nov 19 13:20 etc
d---rwxrwt+ 1 Administrators         ContainerAdministrator      0 Nov 17 17:56 home
d---rwxr-x+ 1 Administrators         ContainerAdministrator      0 Nov 17 17:56 lib
d---rwxr-x+ 1 Administrators         ContainerAdministrator      0 Nov 17 17:56 sbin
drwxrwxrwt+ 1 ContainerAdministrator ContainerAdministrator      0 Nov 17 17:57 tmp
d---rwxr-x+ 1 Administrators         ContainerAdministrator      0 Nov 17 17:56 usr
d---rwxr-x+ 1 Administrators         ContainerAdministrator      0 Nov 17 17:56 var
