### ISSUE TITLE
docker pull: always show me "Layer already being pulled by another client. Waiting."

### ISSUE THREAD

**Issue by EasonYi** [docker/docker#15603]
## Question
Yesterday I tried the docker 1.8 on my Mac pro, and created two docker machines (default and dev) first and then removed the dev machine. 
Today when I tried to pull the redis image but always got the "Layer already being pulled by another client. Waiting." error message even I reboot my mac. What should I do to solve it?

## Environment
➜  ~  docker version
Client:
 Version:      1.8.0
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0d03096
 Built:        Tue Aug 11 17:17:40 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.0
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0d03096
 Built:        Tue Aug 11 17:17:40 UTC 2015
 OS/Arch:      linux/amd64

➜  ~  docker info
Containers: 2
Images: 41
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 45
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.0 (TCL 6.3); master : 7f12e95 - Tue Aug 11 17:55:16 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: FAS3:MCST:CB2E:IFIE:KTB6:EIDL:YGST:6I65:N64P:AQ6O:5J7N:OHJN
Debug mode (server): true
File Descriptors: 15
Goroutines: 25
System Time: 2015-08-15T02:03:44.917069573Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: easonyi
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox

➜  ~  uname -a
Darwin Eason 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64

### Step 1:
Last login: Fri Aug 14 23:35:21 on ttys006
------Welcome back!------ [2015-08-15 06:35:26]
➜  ~  docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL   SWARM
default            virtualbox   Stopped
➜  ~  docker-machine start default
Starting VM...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
➜  ~  docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM
default   *        virtualbox   Running   tcp://192.168.99.100:2376
➜  ~  eval $(docker-machine env default)
➜  ~  docker pull redis
Using default tag: latest
latest: Pulling from library/redis

a81e536d75d2: Pull complete
b5385b7b49ae: Pull complete
5eced7370894: Pull complete
9b5f6b31f2b8: Pull complete
68145731e6c3: Pull complete
e07b98fdf391: Pull complete
e53cade0786f: Pull complete
d41c1101f46b: Pulling fs layer
76ef21f24f06: Download complete
4736cd3389a7: Download complete
d794940dc881: Download complete
bfb2f87f9ad0: Download complete
1c03c2a5aa29: Pulling fs layer
2ff62b1c4295: Download complete
0ff407d5a7d9: Download complete
0ff407d5a7d9: Layer already being pulled by another client. Waiting.
60c52dbe9d91: Already exists
Pulling repository docker.io/library/redis

^C%                                                                                                                                                          
➜  ~  docker pull redis
Using default tag: latest
latest: Pulling from library/redis
d41c1101f46b: Pulling fs layer
76ef21f24f06: Pulling fs layer
d41c1101f46b: Verifying Checksum
d794940dc881: Layer already being pulled by another client. Waiting.
bfb2f87f9ad0: Layer already being pulled by another client. Waiting.
1c03c2a5aa29: Layer already being pulled by another client. Waiting.
2ff62b1c4295: Layer already being pulled by another client. Waiting.
0ff407d5a7d9: Layer already being pulled by another client. Waiting.
0ff407d5a7d9: Layer already being pulled by another client. Waiting.
60c52dbe9d91: Already exists
a81e536d75d2: Already exists
b5385b7b49ae: Already exists
5eced7370894: Already exists
9b5f6b31f2b8: Already exists
68145731e6c3: Already exists
e07b98fdf391: Already exists
e53cade0786f: Already exists
Pulling repository docker.io/library/redis

➜  ~  docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
mysql               latest              c45e4ba02f47        2 days ago          283.8 MB
nginx               latest              6886fb5a9b8d        3 weeks ago         132.9 MB
<none>              <none>              e53cade0786f        3 weeks ago         100.1 MB

### Step 2:
**After I rebooted my mac pro, I've tried again and got the same error:**

Last login: Sat Aug 15 07:58:54 on ttys000
------Welcome back!------ [2015-08-15 07:59:29]
➜  ~  docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL   SWARM
default            virtualbox   Stopped
➜  ~  docker-machine start default
Starting VM...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
➜  ~  eval $(docker-machine env default)
➜  ~  docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM
default   *        virtualbox   Running   tcp://192.168.99.100:2376
➜  ~  docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
mysql               latest              c45e4ba02f47        2 days ago          283.8 MB
nginx               latest              6886fb5a9b8d        3 weeks ago         132.9 MB
<none>              <none>              e53cade0786f        3 weeks ago         100.1 MB
➜  ~  docker pull redis
Using default tag: latest
latest: Pulling from library/redis

d41c1101f46b: Pull complete
76ef21f24f06: Pull complete
4736cd3389a7: Pull complete
d794940dc881: Pull complete
bfb2f87f9ad0: Pull complete
1c03c2a5aa29: Pulling fs layer
2ff62b1c4295: Download complete
0ff407d5a7d9: Download complete
4c8cbfd2973e: Already exists
60c52dbe9d91: Already exists
a81e536d75d2: Already exists
b5385b7b49ae: Already exists
5eced7370894: Already exists
9b5f6b31f2b8: Already exists
68145731e6c3: Already exists
e07b98fdf391: Already exists
e53cade0786f: Already exists
Pulling repository docker.io/library/redis
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/redis/images. You may want to check your internet connection or if you are behind a proxy.
➜  ~  docker pull redis
Using default tag: latest
latest: Pulling from library/redis
1c03c2a5aa29: Pull complete
2ff62b1c4295: Layer already being pulled by another client. Waiting.
0ff407d5a7d9: Layer already being pulled by another client. Waiting.
4c8cbfd2973e: Already exists
60c52dbe9d91: Already exists
a81e536d75d2: Already exists
b5385b7b49ae: Already exists
5eced7370894: Already exists
9b5f6b31f2b8: Already exists
68145731e6c3: Already exists
e07b98fdf391: Already exists
e53cade0786f: Already exists
d41c1101f46b: Already exists
76ef21f24f06: Already exists
4736cd3389a7: Already exists
d794940dc881: Already exists
bfb2f87f9ad0: Already exists

^C%                                                                                                                                                          
➜  ~

**Comment by tonistiigi** [comment]
This looks very similar to what #15646 tries to solve. Only thing I don't understand is that how this could appear on the first request after restart as we don't store the pulling pool on the disk. That VM was rebooted after Mac restart? Not restored from snapshot/state?

**Comment by powdahound** [comment]
I ran into this problem as well and resolved it by stopping the VM, removing all my unused images, and then restarting the VM. Not sure if removing the images was necessary, but I'd wanted to clean them up anyway.

    $ docker-machine stop default
    $ docker images -q | xargs docker rmi
    $ docker-machine start default

**Comment by EasonYi** [comment]
Hi tonistiigi,
Sorry for the late reply to your question **That VM was rebooted after Mac restart?**
The answer is "Yes", which you can see in my post as following:
```➜ ~ docker-machine ls
NAME ACTIVE DRIVER STATE URL SWARM
default virtualbox Stopped
➜ ~ docker-machine start default
Starting VM...
Started machines may have new IP addresses. You may need to re-run the docker-machine env command.```

**But this morning after my Mac upgrade and restarted I pull the *redis* image successfully.**
```
Last login: Sun Aug 23 07:13:31 on console
------Welcome back!------ [2015-08-23 07:15:13]
➜  ~  docker-machine start default
Starting VM...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
➜  ~  docker version
Client:
 Version:      1.8.0
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0d03096
 Built:        Tue Aug 11 17:17:40 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.0
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0d03096
 Built:        Tue Aug 11 17:17:40 UTC 2015
 OS/Arch:      linux/amd64
➜  ~  docker info
Containers: 2
Images: 47
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 51
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.0 (TCL 6.3); master : 7f12e95 - Tue Aug 11 17:55:16 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: 2J2O:SBU2:HKMV:6FQP:UHJS:7CEV:UKR5:IWR5:TO3J:5VS2:TABG:IJ7W
Debug mode (server): true
File Descriptors: 11
Goroutines: 16
System Time: 2015-08-22T23:56:05.020724404Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: easonyi
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
➜  ~  docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
kalilinux/kali-linux-docker   latest              11cd69e79221        9 days ago          325.1 MB
mysql                         latest              c45e4ba02f47        10 days ago         283.8 MB
nginx                         latest              6886fb5a9b8d        5 weeks ago         132.9 MB
<none>                        <none>              1c03c2a5aa29        5 weeks ago         109.5 MB
➜  ~  docker pull redis
Using default tag: latest
latest: Pulling from library/redis
2ff62b1c4295: Pull complete
0ff407d5a7d9: Already exists
4c8cbfd2973e: Already exists
60c52dbe9d91: Already exists
a81e536d75d2: Already exists
b5385b7b49ae: Already exists
5eced7370894: Already exists
9b5f6b31f2b8: Already exists
68145731e6c3: Already exists
e07b98fdf391: Already exists
e53cade0786f: Already exists
d41c1101f46b: Already exists
76ef21f24f06: Already exists
4736cd3389a7: Already exists
d794940dc881: Already exists
bfb2f87f9ad0: Already exists
1c03c2a5aa29: Already exists
library/redis:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:7fd29d65ad8fe915de46ed3660b037bb7325a360fdd76bfdef3011094ebeb139
Status: Downloaded newer image for redis:latest
➜  ~  docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
kalilinux/kali-linux-docker   latest              11cd69e79221        9 days ago          325.1 MB
mysql                         latest              c45e4ba02f47        10 days ago         283.8 MB
nginx                         latest              6886fb5a9b8d        5 weeks ago         132.9 MB
redis                         latest              0ff407d5a7d9        5 weeks ago         109.5 MB
```

**Comment by SaiOngole** [comment]
+1

**Comment by voidengineer** [comment]
I have the same problem, but the deadlock is only happening, when using a http-proxy (by setting ```export HTTPS_PROXY=...``` in ```/etc/default/docker``` on Ubuntu). Without http-proxy the same message is shown for a short moment, but then everything continues to work. When the error occurs, the /var/log/upstart/docker.log shows the message ```error copying from layer download progress reader: download canceled```.

~docker Version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

~docker info
Containers: 4
Images: 124
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-22-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 7.797 GiB
Name: dockerbuild
ID: HKWL:XODL:PGFT:YV3U:BAJF:HAA6:5OFF:J3OE:CPFQ:GG2L:MXYG:NY6U

**Comment by jmagnusson** [comment]
+1

**Comment by arun-gupta** [comment]
Have only one Docker Machine and freshly booted. Tried to run the containers using the https://github.com/javaee-samples/docker-java/blob/master/attendees/cicd/docker-compose.yml and stuck at the message "Layer already being pulled by another client. Waiting.".

Restarted the Docker Machine. `docker-compose up -d` moved past that error and stuck at a different image now.

Restarted Docker Machine again, and finally got it working.

Here are version details:

```
Containers: 10
Images: 127
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 147
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: docker-java
ID: EPX6:EEVU:T4KV:35OM:PZEK:SARX:UUNF:BNCN:IDLI:NI34:SGQE:UQPA
Debug mode (server): true
File Descriptors: 31
Goroutines: 48
System Time: 2015-09-16T14:58:20.615785119Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: arungupta
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Comment by arun-gupta** [comment]
Building an image that inherits from `jenkinsci/jenkins` always causes the following issue:

```
Sending build context to Docker daemon 17.92 kB
Step 0 : FROM jenkinsci/jenkins
latest: Pulling from jenkinsci/jenkins
902b87aaaec9: Verifying Checksum 
9a61b6b1315e: Download complete 
1ff9f26f09fb: Downloading [>                                                  ] 199.6 kB/18.54 MB
607e965985c1: Pulling fs layer 
682b997ad926: Downloading [======================>                            ] 136.1 kB/303.1 kB
a594f78c2a03: Pulling fs layer 
8859a87b6160: Pulling fs layer 
9dd7ba0ee3fe: Pulling fs layer 
93934c1ae19e: Pulling fs layer 
2262501f7b5a: Pulling fs layer 
bfb63b0f4db1: Pulling fs layer 
49ebfec495e1: Pulling fs layer 
dffc38e078ec: Downloading [=============>                                     ] 135.8 kB/521.5 kB
85c4a7072f1d: Download complete 
8a65ac3e251d: Pulling fs layer 
35ca7575d3f1: Pulling fs layer 
3f88b332fe98: Pulling fs layer 
ccffd44f3697: Pulling fs layer 
ea6b780d316b: Pulling fs layer 
245f6094be5b: Pulling fs layer 
1ca6d57a59d5: Pulling fs layer 
1497cb6a4049: Pulling fs layer 
abc98d24647e: Pulling fs layer 
9560ae5b3e2d: Pulling fs layer 
e7f6b23ecf92: Pulling fs layer 
1f301f9e9e47: Download complete 
c7f666cbee49: Pulling fs layer 
ffab25bb53d2: Download complete 
514af8fa48be: Pulling fs layer 
34d222c4e2da: Pulling fs layer 
15719a5d4ea4: Pulling fs layer 
8f9e416ec514: Pulling fs layer 
24f3f3d22062: Pulling fs layer 
24f3f3d22062: Layer already being pulled by another client. Waiting. 
```

Dockerfile is at: https://github.com/javaee-samples/docker-java/blob/master/attendees/cicd/jenkins/Dockerfile. Just change `FROM jenkinsci/jenkins`.

**Comment by zhangchl007** [comment]
get the issue also , I try to restart docker and delete images ,the issue still exits 

Layer already being pulled by another client. Waiting

**Comment by bahrmichael** [comment]
Received the same issue pulling mysql.

root@drop:~# docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Killed the docker process, removed all the images with ` docker images -q | xargs docker rmi` and then restarted the pull. Working now.

**Comment by zhangchl007** [comment]
so do I!

**Comment by cybertk** [comment]
Same issue here for `1.8.2`

**Comment by george-videoamp** [comment]
Seeing this issue as well attempting to pull postgres:latest in a docker within a docker image

**Comment by njgraham** [comment]
I've been evaluating Docker for our shop the past couple of days.  I must say it's disheartening when the _very first thing_ I try to do requires 13 restarts of the Docker daemon to complete successfully.

Windows + boot2docker VM and also LinuxMint (17.2):

    docker@default:~$ docker version
    Client:
     Version:      1.8.2
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   0a8c2e3
     Built:        Thu Sep 10 19:10:10 UTC 2015
     OS/Arch:      linux/amd64

    Server:
     Version:      1.8.2
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   0a8c2e3
     Built:        Thu Sep 10 19:10:10 UTC 2015
     OS/Arch:      linux/amd64

**Comment by cpuguy83** [comment]
It's unfortunate the patch which probably fixes this didn't make it into 1.8.2
But I believe these issues are resolved on master. It is hard to tell though until there is wide-spread usage.

**Comment by pinnokio** [comment]
This issue became a head pain for me. I located in Ukraine. And two days ago I had this issue only on few images. Now I can't retrieve any images at all. I think it's connected with Amazon Cloudfront somehow. I have Digital Ocean droplet in the US. So I installed tinyproxy there and started docker daemon manually with HTTP_PROXY env variable. And bang, image pulled successfully.
So I think this issue is on the Amazon side.

**Comment by a7rk6s** [comment]
On my slow/unreliable home connection I've had problems downloading images since the pre-1.0 days and still to this day. Large/complex images are hit or miss, and then I often run into this issue.

What I do is pull the image on a remote server, `docker save` to a file, then rsync it over. This always works fine. It's also easy to cancel and restart. You would think that since docker has knowledge of the layer structure, it should be faster and more reliable than rsync, but it usually isn't.

Is there a way to serialize the download of layers? So it would start at the first layer I don't have and then continue from there, one at a time? That would probably help.

**Comment by Radau** [comment]
Happened very frequently for me on both OS X (with Docker Toolbox 1.8.1). It was definitely more apparent on a slower connection (needed to reboot the VM roughly 5 times for a relatively small image), but it still happened pretty frequently on a 100mbit connection.

Since upgrading to 1.8.2 it seems to be less frequent (also dumped all of my images and containers). I was able to download ubuntu:14.04 and tutum/wordpress without rebooting the VM once. For reference yesterday I had to restart the VM about 20 times just to get the Wordpress image. 

It still happens occasionally on 1.8.2 on my Macbook (OS X 10.9.5), but it usually only happens on very large images now on a slower connection.

In terms of upgrading from OS X I believe you have to download the whole Toolbox again and just rerun the installer, then when it's done (I believe) you have to create a new image to update the Server version, so maybe give that a try. I believe you will lose your images in the transition using this method. You could also try `docker-machine upgrade MACHINENAME`, I just removed my machine and made a new one to get a fresh start.

#### Version Info
```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64
```

```
➜  ~  VBoxManage --version
5.0.2r102096
```

**Comment by voidengineer** [comment]
I started the docker daemon with debug-logging enabled so I could see what happend directly before the message "Layer already being pulled by another client. Waiting." appears.

It seems docker tries to restart the download off all layers (even those that are already pulled) on __any__ error without cleaning up the previous download.

For me this happend on two occassions:
1. My private repository-mirror timed out (because scanning for malware took to Long). In this case docker retries the download from the official repository (which is a bug on ist own).
2. I had no space left on the device where /var/lib/docker resides.

In both cases the message appears, and docker deadlocks itself.

**Comment by ghost098** [comment]
I am expiriencing same issue on linux with version 1.8.2:

```
$ uname -a                                                                                                                                  [11:01:29]
Linux ighost 4.1.6-1-ARCH #1 SMP PREEMPT Mon Aug 17 08:52:28 CEST 2015 x86_64 GNU/Linux
```

```
$ docker version                                                                                                                            [11:01:39]
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   0a8c2e3-dirty
 Built:        Mon Sep 14 12:09:36 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   0a8c2e3-dirty
 Built:        Mon Sep 14 12:09:36 UTC 2015
 OS/Arch:      linux/amd64
```

this is a sample of what happens:
```
$ docker pull centos                                                                                                                        [11:02:35]
Using default tag: latest
latest: Pulling from library/centos
47d44cb6f252: Pulling fs layer 
f6f39725d938: Layer already being pulled by another client. Waiting. 
f9a8cbc8dd13: Layer already being pulled by another client. Waiting. 
f37e6a610a37: Layer already being pulled by another client. Waiting. 
0f73ae75014f: Layer already being pulled by another client. Waiting. 
0f73ae75014f: Layer already being pulled by another client. Waiting. 
^C% 
```

What's the solution?!

**Comment by elyulka** [comment]
I'm also having frequent troubles with pulling images today. 
As i can see there are almost no free inodes left on hard drive.
After
```
$ docker rmi $(docker images --no-trunc -q)
$ docker-machine restart default
```
Everything works like a charm.
It is consistent problem in my expirience. Images eat too much inodes.

See issue:
* #9755 - inodes not freed after repeated builds - aufs

```
$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64
```
docker.log:
```
time="2015-09-26T19:48:01.944960324Z" level=error msg="error copying from layer download progress reader: write tcp 192.168.99.1:61335: broken pipe"
time="2015-09-26T19:48:05.940615137Z" level=debug msg="Calling POST /images/create"
time="2015-09-26T19:48:05.940649988Z" level=info msg="POST /v1.20/images/create?fromImage=php%3A5.4-cli"
time="2015-09-26T19:48:05.940713049Z" level=debug msg="Trying to pull php from https://registry-1.docker.io v2"
time="2015-09-26T19:48:05.989304109Z" level=debug msg="Fetched 1 base graphs at 2015-09-26 19:48:05.989288547 +0000 UTC"
time="2015-09-26T19:48:05.992594816Z" level=debug msg="Reloaded graph with 3 grants expiring at 2017-03-22 19:04:46.713978458 +0000 UTC"
time="2015-09-26T19:48:26.349295241Z" level=debug msg="Downloaded b4fb234b95b140b70f5a77d8d56739d85b34ad968013488ccb874a9990857625 to tempfile /mnt/sda1/var/lib/docker/tmp/GetImageBlob406045864"
time="2015-09-26T19:48:29.912252763Z" level=debug msg="Error trying v2 registry: ApplyLayer exit status 1 stdout:  stderr: open /usr/src/php/ext/spl/tests/recursiveIteratorIterator_endchildren_error.phpt: no space left on device"
```

```
docker@default:~$ sudo df -i
Filesystem              Inodes      Used Available Use% Mounted on
tmpfs                   127518      4466    123052   4% /
tmpfs                   127518         1    127517   0% /dev/shm
/dev/sda1              1218224   1203906     14318  99% /mnt/sda1
cgroup                  127518        11    127507   0% /sys/fs/cgroup
none                      1000         0      1000   0% /Users
overlay                1218224   1203906     14318  99% /mnt/sda1/var/lib/docker/overlay/d093cc262d0065032b7cff8b1f08adcff5ec5e2ab3a096e08c776153b9585b75/merged
overlay                1218224   1203906     14318  99% /mnt/sda1/var/lib/docker/overlay/ca72d1fea07d75501979c084dc324c9fd84a2c1a9536041a6ad38532d5ecc8f3/merged
```

**Comment by cpuguy83** [comment]
@elyulka excessive inode usage is a known issue with overlay fs.

**Comment by satakare** [comment]
I am also facing the same issue while downloading any docker images its taking long hours and image is not getting downloaded...

**Comment by tinco** [comment]
I get this issue, even after `rm -r /var/lib/docker` when I do: `docker pull phusion/passenger-ruby22:0.9.16`. It almost immediately says another client is already downloading the image, but there's nothing in `ps aux | grep docker`. Is there another place where there's information stored about what docker is downloading?

**Comment by tonistiigi** [comment]
@tinco The reason why you get that message right away is that this image contains a duplicate layer. This should be unrelated to this issue and not cause blocking on pulls. The issue that caused creating such layers on pushes should be fixed with #14421, that is included in `v1.8`.

---

For the issue that causes blocking, its caused by `1.8.2` not recovering form pull errors and should be fixed in master. Please let us know if you can still reproduce it on master or `v1.9` RC-s once they come out.

**Comment by satakare** [comment]
I am getting this issue while pulling jenkins, java, sonarqube docker images. I am running docker 1.8.2 using ubuntu 14 in Virtual box hosted on Windows 7. Tried restarting docker service, ubuntu and even host os, nothing helped, please suggest or shall I need to wait for v1.9

**Comment by dragon9783** [comment]
same issue to me with docker v1.8.2

**Comment by ghost098** [comment]
Guys I solved my problem by installing cow proxy and passing docker daemon through http_proxy. Try it. It may solve your problem two.

**Comment by h0tbird** [comment]
+1

**Comment by michaeljs1990** [comment]
Never had this issue before but today on pretty much any container i pull... redis, mysql, ubuntu they are all getting the issue above. Have tried deleting the docker-machine vm via docker-machine rm multiple times and it just gets stuck at random places every time. These issues are moral killers when trying to onboard teams to docker.

```
Containers: 0
Images: 3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 3
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: default
ID: E46T:223X:37CP:FORH:4QNP:Y6JC:NUN2:52E2:SOBA:ZFRX:AR3E:JFN6
Debug mode (server): true
File Descriptors: 27
Goroutines: 49
System Time: 2015-10-02T05:36:32.018688627Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: michaeljs1990
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Comment by dpmex4527** [comment]
@michaeljs1990 +1, same here. Had a rancher server set up with docker and as of 8PM central I started experiencing these issues with redis, mysql, and now rancher/server as well.....

**Comment by Anupchat** [comment]
+1  
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64

**Comment by matm** [comment]
Same issue here while pulling `gitlab/gitlab-ce`. Stalled download, abort it then try pulling again: 
```
Repository docker.io/gitlab/gitlab-ce already being pulled by another client. Waiting.
```

```
$ uname -a
Linux arrakis 4.2.2-1-ARCH #1 SMP PREEMPT Tue Sep 29 22:21:33 CEST 2015 x86_64 GNU/Linux
```
```
$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   0a8c2e3-dirty
 Built:        Mon Sep 14 12:09:36 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   0a8c2e3-dirty
 Built:        Mon Sep 14 12:09:36 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by rodolfo42** [comment]
Same issue here. However, removing all images alone solved the issue for me:
```
docker images -q | xargs docker rmi
```

```
$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by phlegx** [comment]
+1 Happens to me frequently the last 2 weeks 

```
$ sudo docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by mallegrini** [comment]
+1 
Same version as phlegx above on Mac OS X

**Comment by dalbrekt** [comment]
+1
```
$ sudo docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by gerritwessels** [comment]
+1

Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64

**Comment by rodolfo42** [comment]
I've just switched to the latest `boot2docker` version (was using `docker-machine`) and it hasn't happened since. Not sure if related.

**Comment by d3vil-st** [comment]
+1
```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by tallsam** [comment]
+1
````
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64
````

**Comment by joegoggins** [comment]
+1

```
$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by michaeljs1990** [comment]
for all the people +q with client and server version can you follow up and say what resolved your issue or if it was just waiting X amount of time and trying again? Did you have to force remove containers or reboot your VM. Information like that is much more helpful as we can see that the issue is indeed occurring on the current client. If you want to subscribe use the button on the right.

**Comment by antonienko** [comment]
I haven't solved the issue, but what I do is to restart docker service and
try again. Eventually it gets done.

On Wed, Oct 7, 2015 at 11:17 PM, Michael Schuett <notifications@github.com>
wrote:

> for all the people +q with client and server version can you follow up and
> say what resolved your issue or if it was just waiting X amount of time and
> trying again? Did you have to force remove containers or reboot your VM.
> Information like that is much more helpful as we can see that the issue is
> indeed occurring on the current client. If you want to subscribe use the
> button on the right.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/15603#issuecomment-146331898>.
>



-- 
--
Antonio Hernández

**Comment by dalbrekt** [comment]
A workaround that works for me is to restart the docker daemon.

**Comment by mallegrini** [comment]
I haven't solved the issue either and even when I restart docker service and/or delete the VM, I have to  try more than once in a seemingly random pattern until it eventually works.

**Comment by phlegx** [comment]
Can confirm this @mallegrini , sometimes it is solved by restarting the docker daemon and/or the VM. But it does not seem to be reproducible at all times

**Comment by mallegrini** [comment]
Let me restate it: what I mean is that I need to try more than once in order to pull the image successfully. Sometimes (very very rarely) it works on first try. Most of the times I have to restart docker, pull again (and fail), restart, pull, etc until it finally succeeds. 

I'm trying right now, but this is weird: on my Mac I have also a Linux VM with docker 1.6.2 that used to pull images flawlessy 3 days ago while 1.8.2 couldn't. Today I'm getting timeout error even pulling images with docker 1.6.2
----- here is what I get with docker 1.6.2. Command was: docker pull wordpress
Get https://index.docker.io/v1/repositories/library/wordpress/images: dial tcp 54.210.246.75:443: connection timed out
--------------
I ruled out server/network problems because docker 1.6.2 used to work but now I'm clueless...
On status.docker.com everything seems ok and my network works like a charm too

**Comment by TheSerapher** [comment]
You may laugh, but I have been looking at this myself and at a whim started docker using strace: `strace -s 1024 -f docker daemon -D`

Then I ran the client trying to pull an image that I knew was consistently failing unless the docker daemon was restarted multiple times (up to 20 times until it worked). To my surprise, albeit slow, the download finished successfully.

So maybe this slowdown by strace is helping the daemon to not run into a weird race condition between download/verification processes which cause the verification of an image to fail for no apparent reason.

I know this is a wild guess but figured I'd add it to this discussion.

**Comment by rodolfo42** [comment]
For me, this issue only happens when I'm impatient and `Ctrl+C` before `docker pull` finishes. Afterwards, every pull for the same image results in "already being pulled by another client". Restarting `boot2docker` once solves it 100% of the time.

**Comment by tallsam** [comment]
I get this issue with `dockie/dockie` but not with the official ubuntu image.

**Comment by TheSerapher** [comment]
@rodolfo42 I should have clarified, this is even before the issue with aborting a download. Checksum validation simply fails, maybe I should have opened or checked for another ticket?

**Comment by icecrime** [comment]
Hello all! I believe this should by fixed on master by #15489 (and will soon ship in a few weeks as part of Docker 1.9.0).

Can you please try with the current master, or with the nightly builds available on [this page](http://master.dockerproject.com/)?

I'm tentatively closing this, but keeping the tab open in case it breaks ;-)

**Comment by dmitrym0** [comment]
@icecrime Is there an associated version of `boot2docker.iso`? After getting `docker` from your link, I'm getting:

```
~ ❯❯❯ docker version                                                                                                                                                                                    ⏎
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   6e12d9f
 Built:        Sun Oct 11 19:48:14 UTC 2015
 OS/Arch:      darwin/amd64

Error response from daemon: client is newer than server (client API version: 1.21, server API version: 1.20)
```

**Comment by dmitrym0** [comment]
FWIW, I installed docker 1.9 and pulled `boot2docker.iso` from [here](http://sirile.github.io/2015/07/02/using-docker-18-experimental-with-docker-machine-and-virtualbox-driver-boot2docker.html) and my issue went away.

**Comment by thaJeztah** [comment]
Thanks for testing @dmitrym0 !

**Comment by michaeljs1990** [comment]
Upgrading and having it work doesn't prove a whole lot unfortunately. I got it to work by walking away from my computer for 30 minutes and trying again. Prior to that I had tried deleting all the images / containers and pulling down again up to 10 times. @thaJeztah you will likely want to lock this thread out and leave a message that if you run into this issue and you are using 1.9.0 to open a new issue or I have a feeling messages will just keep coming into here.

**Comment by tallsam** [comment]
Works for me too.

**Comment by icecrime** [comment]
:+1:

**Comment by xiaods** [comment]
thanks, can't wait to use it

**Comment by Terry-Weymouth** [comment]
Just a note, which may help others. In my case, the error with the message 'Layer already being pulled by another client. Waiting.' appears to have been caused by using the 'boot2docker' command instead of docker-machine (or perhaps intermixing the two). I removed /usr/local/bin/boot2docker, deleted ~/.docker, deleted all docker-related VMs, reinstalled from the "Docker Toolkit", built the 'default' docker-machine, and have not had this problem since. Docker Version (client/server) 1.8.3 (build from commit f4bf5c7); docker-machine version 0.4.1 (e2c88d6) .

**Comment by michaeljs1990** [comment]
@Terry-Weymouth likely a coincidence. I have only ever had docker-machine installed on my computer and I have run into this issue 4 or 5 times.

**Comment by elbow-jason** [comment]
I have been having this issue with docker-machine. A simple stop and start seems to resolve the issue for now.

**Comment by phpguru** [comment]
@powdahound I got an error trying to xargs docker rmi after the machine was stopped. This worked though, thanks for the tip!

$ docker-machine stop default
$ docker-machine start default
$ docker images -q | xargs docker rmi

**Comment by asheshambasta** [comment]
Happens quite often on `1.8.2` when someone hits `Ctrl+C` on a docker pull cmd, and since this is our dev environment with other devs using other services running on docker, restarting the docker daemon is absolutely not an option.
