### ISSUE TITLE
Devicemapper remounts /var/lib/docker/devicemapper to itself on startup

### ISSUE THREAD

**Issue by perj** [docker/docker#16884]
Hi,

I'm running docker with device mapper in direct lvm mode on CentOS 7.

When docker engine starts up, it seems to mount the root file system to /var/lib/docker/devicemapper for no reason:

```
/dev/mapper/centos-root on /var/lib/docker/devicemapper type xfs (rw,relatime,seclabel,attr2,inode64,logbsize=256k,sunit=512,swidth=1024,noquota)
```

This is the root device as also seen in mount:

```
/dev/mapper/centos-root on / type xfs (rw,relatime,seclabel,attr2,inode64,logbsize=256k,sunit=512,swidth=1024,noquota)
```

It also leave the directory mounted even if I stop docker.
It's the sub directory mounted to itself, after manually unmounting it, docker still works fine.

It's not a huge deal, but it does affect `lsof` which complains:

```
lsof: WARNING: can't stat() xfs file system /var/lib/docker/devicemapper
      Output information may be incomplete.
```

Environment:
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.1.1503 (Core)
Release:	7.1.1503
Codename:	Core
Docker version 1.8.2, build 0a8c2e3

Steps to reproduce (not actually tried, sorry)
```
yum install http://yum.dockerproject.org/repo/main/centos/7/Packages/docker-engine-1.8.2-1.el7.centos.x86_64.rpm
cat > /etc/systemd/system/docker.service <<EOT
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// \
	--storage-opt dm.datadev=/dev/centos/docker-data-direct-lvm --storage-opt dm.metadatadev=/dev/centos/docker-metadata-direct-lvm --storage-opt dm.fs=xfs --storage-opt dm.blocksize=512K
EOT
(setup lvm as per above line)
systemctl daemon-reload
systemctl start docker.socket
systemctl start docker
```

**Comment by perj** [comment]
`docker version`: 
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:08:45 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:08:45 UTC 2015
 OS/Arch:      linux/amd64

`docker info`:
Containers: 8
Images: 227
Storage Driver: devicemapper
 Pool Name: docker-253:1-150996065-pool
 Pool Blocksize: 524.3 kB
 Backing Filesystem: xfs
 Data file: /dev/centos/docker-data-direct-lvm
 Metadata file: /dev/centos/docker-metadata-direct-lvm
 Data Space Used: 24.47 GB
 Data Space Total: 268.4 GB
 Data Space Available: 244 GB
 Metadata Space Used: 9.331 MB
 Metadata Space Total: 17.05 GB
 Metadata Space Available: 17.04 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.14.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 12
Total Memory: 94.13 GiB
Name:
ID: R2YU:UDXA:YS6R:ILD4:3O47:SQJ3:HLGW:VSVK:LCL2:ACEJ:SZN4:LEZU
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

`uname -a`:
Linux 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by LK4D4** [comment]
@rhvgoyal Do you know if this is still issue?

**Comment by rhvgoyal** [comment]
This should not be an issue. /var/lib/docker/devicemapper is a bind mount onto itself. We marked it private due to various propagation issues.

Also at somepoint of time there was issue that when docker daemon stopped, it did not unmount this mount point. But it is now fixed since. So this can be closed.

**Comment by LK4D4** [comment]
@rhvgoyal Thanks!

**Comment by unicolet** [comment]
Issue still happens on fully patched Centos7 with:
```
docker-engine-selinux-17.05.0.ce-1.el7.centos.noarch
docker-engine-17.05.0.ce-1.el7.centos.x86_64
```

As a result, snapshotting the VM fails due to the double mount (qemu guest agent isn't smart enough apparently).
