### ISSUE TITLE
wildcard COPY breaks if the Dockerfile or .dockerignore files are ignored

### ISSUE THREAD

**Issue by miquella** [docker/docker#17911]
`docker build .` produces a stat error when using `COPY` with a `*` wildcard, if the `Dockerfile` or `.dockerignore` files are ignored.

# Environment
`docker version`:
```
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   76d6bc9
 Built:        Tue Nov  3 21:17:46 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
Containers: 13
Images: 410
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 436
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.12-boot2docker
Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
CPUs: 4
Total Memory: 3.858 GiB
Name: dinghy
ID: QJZJ:UGUZ:I6EO:NMD3:7IHO:6DU5:PQ2U:5YO5:DG2V:GH7M:7EKI:TQL5
Debug mode (server): true
 File Descriptors: 40
 Goroutines: 73
 System Time: 2015-11-11T19:28:57.927694016Z
 EventsListeners: 1
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=vmwarefusion
```

`uname -a`:
```
Darwin markse-l 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64
```

Using boot2docker through `docker-machine` and `dinghy` hosted in a VMWare Fusion VM.

# Steps to Reproduce

1. Using the `Dockerfile`:
  ```Dockerfile
FROM alpine
COPY *.txt /
  ```

2. Add `Dockerfile` to `.dockerignore`

3. `docker build .` will produce an error of: `stat Dockerfile: no such file or directory`

4. Add `.dockerignore` to `.dockerignore`

5. `docker build .` will produce an error of: `stat .dockerignore: no such file or directory`

# Actual Results
`stat Dockerfile: no such file or directory`
or
`stat .dockerignore: no such file or directory`

# Expected Results
As described in [builder.md](https://github.com/docker/docker/blob/v1.9.0/docs/reference/builder.md#dockerignore-file):
> You can even use the .dockerignore file to exclude the Dockerfile and .dockerignore files. These files are still sent to the daemon because it needs them to do its job. But the ADD and COPY commands do not copy them to the the image.

Building a docker image with `Dockerfile` or `.dockerignore` ignored should complete successfully.

**Comment by thaJeztah** [comment]
confirmed; this is a regression since 1.8.3

```bash
mkdir test
cd test/
echo "foo" > test.txt
echo Dockerfile > .dockerignore


cat <<EOF >> Dockerfile
FROM scratch
COPY *.txt /
EOF

docker build .
Sending build context to Docker daemon 4.096 kB
Step 1 : FROM scratch
 --->
Step 2 : COPY *.txt /
stat Dockerfile: no such file or directory
```

**Comment by thaJeztah** [comment]
however, it looks like this is fixed in master https://master.dockerproject.org

**Comment by thaJeztah** [comment]
Also just tested this on the 1.9.1 bump branch and it looks to be fixed https://github.com/docker/docker/pull/17852

**Comment by thaJeztah** [comment]
Briefly discussed this with @tonistiigi and this looks like a dup(-ish) of https://github.com/docker/docker/issues/17756 (even though there's no symlink involved here), which is resolved in https://github.com/docker/docker/pull/17710

I'm going to close this issue, but please comment if you're able to reproduce on 1.9.1 once that has been released

Thanks for reporting!!

**Comment by duglin** [comment]
phew, I was just testing this (before I saw it was closed)  and I couldn't reproduce it :-)

**Comment by thaJeztah** [comment]
@duglin thanks! I also tested on four versions (1.8.3, 1.9.0, master and the 1.9.1 bump).

**Comment by BowlingX** [comment]
This is still broken for me when using `.*` in a `.dockerignore`

**Comment by thaJeztah** [comment]
@BowlingX do you have the steps to reproduce?

**Comment by BowlingX** [comment]
I have a `.dockerignore` with `.*` and following command: `ADD target/J3k_Tools-*jar-with-dependencies.jar $VOLUME_NAME/toolkit.jar`.

**Comment by thaJeztah** [comment]
@BowlingX and `$VOLUME_NAME` is a volume? Because using volumes during build is not really working. Does this repro-case work for you? https://github.com/docker/docker/issues/17911#issuecomment-155932521

**Comment by duglin** [comment]
It would be great if you could reduce this down to the minimal testcase/Dockerfile - w/o any stuff from your specific project.

**Comment by BowlingX** [comment]
@thaJeztah $VOLUME_NAME is a Volume yes, but it will be linked later to another container and it always worked before (and now after removing .*). The case in the comment works for me. I will try to create a small testcase
