### ISSUE TITLE
docker fails on all commands with "404 page not found" error

### ISSUE THREAD

**Issue by unoexperto** [docker/docker#17960]
I don't know what happened but my work is completely paralyzed. I can't do anything with existing containers. I get

> Error response from daemon: 404 page not found

error on pretty much all commands.

I googled a lot and some people recommended adding

> export NO_PROXY="/var/run/docker.sock

line to `/etc/default/docker`. It fixed "docker info" command but not the rest such as `rm`, `start` or `restart`.

I have:

* Linux expert-linux 4.2.0-18-generic #22-Ubuntu SMP Fri Nov 6 18:25:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

* docker version output

> Client:
> Version:      1.9.0
> API version:  1.21
> Go version:   go1.4.2
> Git commit:   76d6bc9
> Built:        Tue Nov  3 17:54:53 UTC 2015
> OS/Arch:      linux/amd64
> Server:
> Version:      1.9.0
> API version:  1.21
> Go version:   go1.4.2
> Git commit:   76d6bc9
> Built:        Tue Nov  3 17:54:53 UTC 2015
> OS/Arch:      linux/amd64` 

* docker info output

> Containers: 2
> Images: 58
> Server Version: 1.9.0
> Storage Driver: aufs
> Root Dir: /var/lib/docker/aufs
> Backing Filesystem: extfs
> Dirs: 62
> Dirperm1 Supported: true
> Execution Driver: native-0.2
> Logging Driver: json-file
> Kernel Version: 4.2.0-18-generic
> Operating System: Ubuntu 15.10
> CPUs: 8
> Total Memory: 15.61 GiB
> Name: expert-linux
> ID: 3RY6:E2ID:APBE:GB3U:N6CM:ZSUY:Q3KN:7E7L:LLN3:Q5CY:6XAS:NGAN
> Username: expert
> Registry: https://index.docker.io/v1/
> WARNING: No swap limit support`

I tried reinstalling docker which also didn't fix it. 

It seems like it's an issue with proxy setting and is some obvious bug. If I call `unset http_proxy` before running docker command it helps. With that I can remove container and recreate it again thus launching it. But doing so on every reboot is horrible.

Please help!!!

**Comment by cppexpert** [comment]
I cannot provide reproducible case because it broke up overnight. I cannot fix issue by reinstalling docker as I mentioned in my report. But if we google we'll see dozens of other people reporting this issue. If you can guide me how to collect extended log for you I'll be happy to do it.

**Comment by crosbymichael** [comment]
@docker/network-maintainers could this be caused by networking issues because the linked dup #17962 has some errors in the output about sandbox and keys.

**Comment by HackToday** [comment]
@cppexpert  did you mean that command fails only when you set http proxy ? If not have proxy setting, everything will work ?

**Comment by cppexpert** [comment]
@HackToday *Some* commands work if you unset env variables.

**Comment by HackToday** [comment]
@cppexpert  it is interesting. I mean  could you specify what env varilable and what commans work ? Thanks

**Comment by cppexpert** [comment]
@HackToday It's specified in my original post in last paragraph.

**Comment by mavenugo** [comment]
The only known panic that got resolved in 1.9.1 is https://github.com/docker/docker/pull/17639. I think it is worth to try the 1.9.1-rc1 and confirm.

**Comment by cppexpert** [comment]
Has anyone looked at this ? Shall I upgrade to latest docker engine ?

**Comment by pandeiro** [comment]
This `"404 page not found"` error happens to me once, the first time (per X session) that I try to `docker-compose up --force-recreate` on my current project. All subsequent invocations work as expected.

Just adding that as a data point.

**Comment by sidharta-s** [comment]
I ran into this as well. Though in my case it does seem related to #17639 .  An 'unclean' daemon shutdown seems to have left some containers in an invalid state - the docker daemon was restarted (after a long time) and it got into a state where it responds to commands with a 404. The corresponding systemd logs are pasted below. I wiped /var/lib/docker and started over to get out of this state. 

```
Nov 06 20:43:33 q docker[7925]: time="2015-11-06T20:43:29.023645184-05:00" level=info msg="Container 07e3341102228e5afb5c524e0662136bf4feb6106df570694113e698befc3714 failed to exit within 10 seconds of SIGTERM - using the force"
Nov 06 20:43:33 q docker[7925]: time="2015-11-06T20:43:29.023673430-05:00" level=info msg="Container d51708bfb3dbbb7389b6b00904145f4a1ef8be8a0d068e53e84b198322e8ad79 failed to exit within 10 seconds of SIGTERM - using the force"
Nov 06 20:43:33 q docker[7925]: time="2015-11-06T20:43:29.023708893-05:00" level=info msg="Container 4714496abb3c877c89f2c52f0777bf4d160116168430af520d34780d6a0e4707 failed to exit within 10 seconds of SIGTERM - using the force"
Nov 06 20:43:34 q docker[7925]: time="2015-11-06T20:43:33.959678182-05:00" level=error msg="Force shutdown daemon"
Nov 06 20:44:48 q systemd[1]: docker.service stopping timed out. Killing.
Nov 06 20:46:18 q systemd[1]: docker.service still around after SIGKILL. Ignoring.
Nov 06 20:46:18 q systemd[1]: Stopped Docker Application Container Engine.
Nov 06 20:46:18 q systemd[1]: Unit docker.service entered failed state.
Nov 18 16:26:35 q systemd[1]: Starting Docker Application Container Engine...
Nov 18 16:26:35 q docker[20077]: time="2015-11-18T16:26:35.416431223-05:00" level=info msg="API listen on /var/run/docker.sock"
Nov 18 16:26:35 q docker[20077]: time="2015-11-18T16:26:35.599523507-05:00" level=warning msg="Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section."
Nov 18 16:26:35 q docker[20077]: time="2015-11-18T16:26:35.683620070-05:00" level=info msg="[graphdriver] using prior storage driver \"devicemapper\""
Nov 18 16:26:35 q docker[20077]: time="2015-11-18T16:26:35.687930888-05:00" level=info msg="Firewalld running: true"
Nov 18 16:28:05 q systemd[1]: docker.service operation timed out. Terminating.
Nov 18 16:28:05 q systemd[1]: Failed to start Docker Application Container Engine.
Nov 18 16:28:05 q systemd[1]: Unit docker.service entered failed state.
Nov 18 16:28:09 q systemd[1]: Starting Docker Application Container Engine...
Nov 18 16:28:09 q docker[20583]: time="2015-11-18T16:28:09.708417880-05:00" level=info msg="API listen on /var/run/docker.sock"
Nov 18 16:28:09 q docker[20583]: time="2015-11-18T16:28:09.852075180-05:00" level=warning msg="Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section."
Nov 18 16:28:09 q docker[20583]: time="2015-11-18T16:28:09.936751011-05:00" level=info msg="[graphdriver] using prior storage driver \"devicemapper\""
Nov 18 16:28:09 q docker[20583]: time="2015-11-18T16:28:09.941163311-05:00" level=info msg="Firewalld running: true"
Nov 18 16:28:18 q docker[20583]: time="2015-11-18T16:28:18.827750090-05:00" level=error msg="getNetworkFromStore for nid 01201658859c21cf7013357fb4ce5b5ff6b8b2c44b8c5e7268e22d02ec9a8e44 failed while trying to build sandbox for cleanup: network 01201658859c21cf7013357fb4ce5b5ff6b8b2c44b8c5e7268e22d02ec9a8e44 not found"
Nov 18 16:28:18 q docker[20583]: time="2015-11-18T16:28:18.827798760-05:00" level=warning msg="Failed detaching sandbox 7e32c3c9108708bcdca2270f3c4de66b290d05d8eea41cf474f572464df371d2 from endpoint 1dbb819c9769722bc344e2ca4a8b30c66afecdea3ac88b09cc11095b128f0fc3: failed to get network from store during leave: network 01201658859c21cf7013357fb4ce5b5ff6b8b2c44b8c5e7268e22d02ec9a8e44 not found\n"
Nov 18 16:28:18 q docker[20583]: time="2015-11-18T16:28:18.827822029-05:00" level=warning msg="Failed deleting endpoint 1dbb819c9769722bc344e2ca4a8b30c66afecdea3ac88b09cc11095b128f0fc3: failed to get network during Delete: network 01201658859c21cf7013357fb4ce5b5ff6b8b2c44b8c5e7268e22d02ec9a8e44 not found\n"
Nov 18 16:28:18 q docker[20583]: time="2015-11-18T16:28:18.827833903-05:00" level=error msg="failed to delete sandbox 7e32c3c9108708bcdca2270f3c4de66b290d05d8eea41cf474f572464df371d2 while trying to cleanup: could not cleanup all the endpoints in container 2c9233e5886ae07b018106391d466676bf7d530cecc6fd4cfc4afcc9509ce77e / sandbox 7e32c3c9108708bcdca2270f3c4de66b290d05d8eea41cf474f572464df371d2"
Nov 18 16:29:06 q docker[20583]: time="2015-11-18T16:29:06.851783994-05:00" level=error msg="getNetworkFromStore for nid 3f329c947911dabebef85519bc7b0b96a4fb75d9e04e90de0ecbf403bc77b28e failed while trying to build sandbox for cleanup: network 3f329c947911dabebef85519bc7b0b96a4fb75d9e04e90de0ecbf403bc77b28e not found"
Nov 18 16:29:06 q docker[20583]: time="2015-11-18T16:29:06.851831298-05:00" level=warning msg="Failed detaching sandbox 699c1774a78212af001ad846840786c03b83c14c9e64bb02100336dba3f777a2 from endpoint ddbb15163b14b3e1028bf703c2c09c004fec4e9c9b8b8f4a5ee7cf236f7735e0: failed to get network from store during leave: network 3f329c947911dabebef85519bc7b0b96a4fb75d9e04e90de0ecbf403bc77b28e not found\n"
Nov 18 16:29:06 q docker[20583]: time="2015-11-18T16:29:06.851851749-05:00" level=warning msg="Failed deleting endpoint ddbb15163b14b3e1028bf703c2c09c004fec4e9c9b8b8f4a5ee7cf236f7735e0: failed to get network during Delete: network 3f329c947911dabebef85519bc7b0b96a4fb75d9e04e90de0ecbf403bc77b28e not found\n"
Nov 18 16:29:06 q docker[20583]: time="2015-11-18T16:29:06.851865960-05:00" level=error msg="failed to delete sandbox 699c1774a78212af001ad846840786c03b83c14c9e64bb02100336dba3f777a2 while trying to cleanup: could not cleanup all the endpoints in container c34d9c5e1d8e1108ad1aca5bc3d636366fcbc9878363844a5b9d7c2093b34936 / sandbox 699c1774a78212af001ad846840786c03b83c14c9e64bb02100336dba3f777a2"
Nov 18 16:29:15 q docker[20583]: time="2015-11-18T16:29:15.789783788-05:00" level=error msg="getNetworkFromStore for nid 3f329c947911dabebef85519bc7b0b96a4fb75d9e04e90de0ecbf403bc77b28e failed while trying to build sandbox for cleanup: network 3f329c947911dabebef85519bc7b0b96a4fb75d9e04e90de0ecbf403bc77b28e not found"
Nov 18 16:29:15 q docker[20583]: time="2015-11-18T16:29:15.789834577-05:00" level=warning msg="Failed detaching sandbox 18807bfb28f2a95c60f96c6f290c6349b8de3e561b23672a7aa41633689a2abc from endpoint 4e9f9a4a23e3686b31d92cd19275b7e1dadd7bc0b385771f2e45cd9e1412f551: failed to get network from store during leave: network 3f329c947911dabebef85519bc7b0b96a4fb75d9e04e90de0ecbf403bc77b28e not found\n"
Nov 18 16:29:15 q docker[20583]: time="2015-11-18T16:29:15.789855989-05:00" level=warning msg="Failed deleting endpoint 4e9f9a4a23e3686b31d92cd19275b7e1dadd7bc0b385771f2e45cd9e1412f551: failed to get network during Delete: network 3f329c947911dabebef85519bc7b0b96a4fb75d9e04e90de0ecbf403bc77b28e not found\n"
Nov 18 16:29:15 q docker[20583]: time="2015-11-18T16:29:15.789873301-05:00" level=error msg="failed to delete sandbox 18807bfb28f2a95c60f96c6f290c6349b8de3e561b23672a7aa41633689a2abc while trying to cleanup: could not cleanup all the endpoints in container 32165a7e29284b4a53bc0103e7e230497391fef3f54c5621b681459a5c5c6129 / sandbox 18807bfb28f2a95c60f96c6f290c6349b8de3e561b23672a7aa41633689a2abc"
Nov 18 16:29:19 q docker[20583]: time="2015-11-18T16:29:19.407759965-05:00" level=error msg="getNetworkFromStore for nid 01201658859c21cf7013357fb4ce5b5ff6b8b2c44b8c5e7268e22d02ec9a8e44 failed while trying to build sandbox for cleanup: network 01201658859c21cf7013357fb4ce5b5ff6b8b2c44b8c5e7268e22d02ec9a8e44 not found"
Nov 18 16:29:19 q docker[20583]: time="2015-11-18T16:29:19.407812079-05:00" level=warning msg="Failed detaching sandbox 6897fb0d7e4f89dc28feccd4f3dfe96c95db3f3dd478917bb52692e4bc51cd94 from endpoint d14881dfa3d79925190eb5848bd1314255bc7d636744d6c4f356354cf3225bd5: failed to get network from store during leave: network 01201658859c21cf7013357fb4ce5b5ff6b8b2c44b8c5e7268e22d02ec9a8e44 not found\n"
Nov 18 16:29:19 q docker[20583]: time="2015-11-18T16:29:19.407842976-05:00" level=warning msg="Failed deleting endpoint d14881dfa3d79925190eb5848bd1314255bc7d636744d6c4f356354cf3225bd5: failed to get network during Delete: network 01201658859c21cf7013357fb4ce5b5ff6b8b2c44b8c5e7268e22d02ec9a8e44 not found\n"
Nov 18 16:29:19 q docker[20583]: time="2015-11-18T16:29:19.407855451-05:00" level=error msg="failed to delete sandbox 6897fb0d7e4f89dc28feccd4f3dfe96c95db3f3dd478917bb52692e4bc51cd94 while trying to cleanup: could not cleanup all the endpoints in container 9c93a4e6ec8526077fc6043cc8d07f081fdf48df360bb406f87ff40960c24453 / sandbox 6897fb0d7e4f89dc28feccd4f3dfe96c95db3f3dd478917bb52692e4bc51cd94"
Nov 18 16:29:32 q docker[20583]: time="2015-11-18T16:29:32.289769695-05:00" level=error msg="getNetworkFromStore for nid 01201658859c21cf7013357fb4ce5b5ff6b8b2c44b8c5e7268e22d02ec9a8e44 failed while trying to build sandbox for cleanup: network 01201658859c21cf7013357fb4ce5b5ff6b8b2c44b8c5e7268e22d02ec9a8e44 not found"
Nov 18 16:29:32 q docker[20583]: time="2015-11-18T16:29:32.289822921-05:00" level=warning msg="Failed detaching sandbox 8e65341cbbc30b16e9c4917ac578b998f8ab53d900e81650cbe3851f69bf37d2 from endpoint 6e97f3a47707b3595b921a1306833b27e9a9df5e58d2027f810a0e0ac6976f61: failed to get network from store during leave: network 01201658859c21cf7013357fb4ce5b5ff6b8b2c44b8c5e7268e22d02ec9a8e44 not found\n"
Nov 18 16:29:32 q docker[20583]: time="2015-11-18T16:29:32.289844080-05:00" level=warning msg="Failed deleting endpoint 6e97f3a47707b3595b921a1306833b27e9a9df5e58d2027f810a0e0ac6976f61: failed to get network during Delete: network 01201658859c21cf7013357fb4ce5b5ff6b8b2c44b8c5e7268e22d02ec9a8e44 not found\n"
Nov 18 16:29:32 q docker[20583]: time="2015-11-18T16:29:32.289854917-05:00" level=error msg="failed to delete sandbox 8e65341cbbc30b16e9c4917ac578b998f8ab53d900e81650cbe3851f69bf37d2 while trying to cleanup: could not cleanup all the endpoints in container ddec3f0419154321483c3a39159c557e70f438c8448f264cdc63730d4baaa326 / sandbox 8e65341cbbc30b16e9c4917ac578b998f8ab53d900e81650cbe3851f69bf37d2"
Nov 18 16:29:32 q docker[20583]: time="2015-11-18T16:29:32.848755075-05:00" level=error msg="getNetworkFromStore for nid 07cfc345a11f2df80c3e2b5669599a11060c77fdfa3d8313f30b8f0441636b9c failed while trying to build sandbox for cleanup: network 07cfc345a11f2df80c3e2b5669599a11060c77fdfa3d8313f30b8f0441636b9c not found"
Nov 18 16:29:32 q docker[20583]: time="2015-11-18T16:29:32.848802831-05:00" level=warning msg="Failed detaching sandbox d7a3ca9a6147b84706cfd993f522fad69627f817f308647530d4ec3f9cc800ae from endpoint 3ff17b181a0f63f26c6b538b9e7fcece55b8c0a66163fcbf44abd94fb8a06d68: failed to get network from store during leave: network 07cfc345a11f2df80c3e2b5669599a11060c77fdfa3d8313f30b8f0441636b9c not found\n"
Nov 18 16:29:32 q docker[20583]: time="2015-11-18T16:29:32.848827682-05:00" level=warning msg="Failed deleting endpoint 3ff17b181a0f63f26c6b538b9e7fcece55b8c0a66163fcbf44abd94fb8a06d68: failed to get network during Delete: network 07cfc345a11f2df80c3e2b5669599a11060c77fdfa3d8313f30b8f0441636b9c not found\n"
Nov 18 16:29:32 q docker[20583]: time="2015-11-18T16:29:32.848839859-05:00" level=error msg="failed to delete sandbox d7a3ca9a6147b84706cfd993f522fad69627f817f308647530d4ec3f9cc800ae while trying to cleanup: could not cleanup all the endpoints in container abee8b65c515715a31d29324ada3be7752bbe7a4a2bf5709541f70064b9e8103 / sandbox d7a3ca9a6147b84706cfd993f522fad69627f817f308647530d4ec3f9cc800ae"
Nov 18 16:29:37 q docker[20583]: time="2015-11-18T16:29:37.632756153-05:00" level=error msg="getNetworkFromStore for nid 3f329c947911dabebef85519bc7b0b96a4fb75d9e04e90de0ecbf403bc77b28e failed while trying to build sandbox for cleanup: network 3f329c947911dabebef85519bc7b0b96a4fb75d9e04e90de0ecbf403bc77b28e not found"
Nov 18 16:29:37 q docker[20583]: time="2015-11-18T16:29:37.632807953-05:00" level=warning msg="Failed detaching sandbox 2904a3778b96c733eb2c144beb4f19d32334cdd269aa701271bd8b6e83f8c48c from endpoint b00d9b14efe9b6aec016ee119ad1f3da180b7f22471e6b498fe05d6a6dc77b34: failed to get network from store during leave: network 3f329c947911dabebef85519bc7b0b96a4fb75d9e04e90de0ecbf403bc77b28e not found\n"
Nov 18 16:29:37 q docker[20583]: time="2015-11-18T16:29:37.632830996-05:00" level=warning msg="Failed deleting endpoint b00d9b14efe9b6aec016ee119ad1f3da180b7f22471e6b498fe05d6a6dc77b34: failed to get network during Delete: network 3f329c947911dabebef85519bc7b0b96a4fb75d9e04e90de0ecbf403bc77b28e not found\n"
Nov 18 16:29:37 q docker[20583]: time="2015-11-18T16:29:37.632842106-05:00" level=error msg="failed to delete sandbox 2904a3778b96c733eb2c144beb4f19d32334cdd269aa701271bd8b6e83f8c48c while trying to cleanup: could not cleanup all the endpoints in container 56821a6d6873826e385295d5682f7a727e3e38dab0fb0653aa4344b07f41b252 / sandbox 2904a3778b96c733eb2c144beb4f19d32334cdd269aa701271bd8b6e83f8c48c"
Nov 18 16:29:39 q systemd[1]: docker.service operation timed out. Terminating.
Nov 18 16:29:39 q systemd[1]: Failed to start Docker Application Container Engine.
Nov 18 16:29:39 q systemd[1]: Unit docker.service entered failed state.
Nov 18 16:38:27 q systemd[1]: Stopped Docker Application Container Engine.
```

**Comment by DavidBruant** [comment]
Had the same problem (Ubuntu wily, docker 1.9.1 that can be found from docker package sources (not Ubuntu's)). Reverting to Docker 1.8.3 fixed the issue on my side.

**Comment by elpirata15** [comment]
Had the same problem.

docker version output
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:02:53 UTC 2015
 OS/Arch:      linux/amd64

docker info
Error response from daemon: 404 page not found

uname -a
Linux debian01 4.2.0-1-amd64 #1 SMP Debian 4.2.5-1 (2015-10-27) x86_64 GNU/Linux

I didn't remember how to reproduce it. I just was trying start my docker containers after the weekend and get this error.

**Comment by gumieri** [comment]
Same problem here.

Docker version:
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:34:39 UTC 2015
 OS/Arch:      linux/amd64
Error response from daemon: 404 page not found
```

docker info:
```
Error response from daemon: 404 page not found
```

all uname: (fedora 22)
```
Linux gumieri 4.2.6-200.fc22.x86_64 #1 SMP Tue Nov 10 16:45:19 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

After using 'sudo dnf downgrade' to 1.9.0 was not enough (the same problem persists).
Just after a second downgrade (to 1.8.3) it back to work.

**Comment by asziranyi** [comment]
I had the same issue:

docker version
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:34:39 UTC 2015
 OS/Arch:      linux/amd64
Error response from daemon: 404 page not found
```

uname -a
```
Linux ********* 3.19.0-37-generic #42-Ubuntu SMP Fri Nov 20 18:22:05 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

systemctl status docker.service
```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since k 2015-12-01 10:31:51 CET; 1min 3s ago
     Docs: https://docs.docker.com
 Main PID: 6765 (code=exited, status=1/FAILURE)

dec 01 10:31:51 ********* systemd[1]: Starting Docker Application Container Engine...
dec 01 10:31:51 ********* docker[6765]: time="2015-12-01T10:31:51.082073428+01:00" level=info msg="API listen on /var/run/docker.sock"
dec 01 10:31:51 ********* docker[6765]: time="2015-12-01T10:31:51.082211982+01:00" level=info msg="API listen on [::]:2375"
dec 01 10:31:51 ********* docker[6765]: time="2015-12-01T10:31:51.084289048+01:00" level=info msg="[graphdriver] using prior storage driver \"aufs\""
dec 01 10:31:51 ********* docker[6765]: time="2015-12-01T10:31:51.135320794+01:00" level=info msg="Firewalld running: false"
dec 01 10:31:51 ********* docker[6765]: time="2015-12-01T10:31:51.172263879+01:00" level=fatal msg="Error starting daemon: Error initializing network controller: could not delete the default bridge network: network bridge has active endpoints"
dec 01 10:31:51 ********* systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
dec 01 10:31:51 ********* systemd[1]: Failed to start Docker Application Container Engine.
dec 01 10:31:51 ********* systemd[1]: Unit docker.service entered failed state.
dec 01 10:31:51 ********* systemd[1]: docker.service failed.

```

Running
```
sudo mv /var/lib/docker/network/files/ /path/to/backup/docker-network-files
```

solved the problem.

(If everything goes well, /path/to/backup/docker-network-files can be deleted)

**Comment by gumieri** [comment]
Solved here removing the network files.
Thank you @asziranyi.

**Comment by aeperea** [comment]
I had the same problem but when I tried @asziranyi suggestion (moving the network files) everything went green. Thank you @asziranyi and everyone here :)

**Comment by thaJeztah** [comment]
@aboch is this also related to the `local-kv.db` you were investigating in https://github.com/docker/docker/issues/18113 ?

**Comment by aboch** [comment]
@thaJeztah Nope, that case is specific to an inconsistent ipam vs network state in the local store.

**Comment by pandeiro** [comment]
I've tried the proposed solution with `sudo mv /var/lib/docker/network/files/ /path/to/backup/docker-network-files` and it did not solve the problem. Would so love a fix for this annoying issue...

docker version:

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5-dirty
 Built:        Sun Nov 22 00:15:15 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5-dirty
 Built:        Sun Nov 22 00:15:15 UTC 2015
 OS/Arch:      linux/amd64
```

uname -a

```
Linux power 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux
```

docker info

```
Containers: 31
Images: 342
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-8:3-13770757-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 10.5 GB
 Data Space Total: 107.4 GB
 Data Space Available: 67.59 GB
 Metadata Space Used: 20.3 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.127 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /home/mu/var/docker/devicemapper/devicemapper/data
 Metadata loop file: /home/mu/var/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.112 (2015-11-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.5-1-ARCH
Operating System: Arch Linux (containerized)
CPUs: 4
Total Memory: 7.716 GiB
Name: power
ID: CWFN:OTRR:L5GE:VFDJ:DJ26:XQSD:KQSP:ZC6V:LHJU:CDFS:B2ZL:YZU6
```

**Comment by asziranyi** [comment]
@pandeiro a 
```
systemctl status docker.service
```
or logs might help to find the real cause.

**Comment by whymarrh** [comment]
I think I can reproduce this issue in the following Vagrant environment:

```ruby
$script = <<SCRIPT
sudo apt-get update
sudo apt-get -y dist-upgrade

sudo apt-get -y install linux-image-extra-$(uname -r)
sudo modprobe aufs

wget -qO- https://get.docker.com/ | sh
sudo usermod --groups docker $(whoami)
SCRIPT

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/vivid64"
    config.vm.provision "shell", privileged: false, inline: $script
end
```

When I initially start up the VM, Docker commands work fine. Output from a few notable commands:

- `uname -a`

        Linux vagrant-ubuntu-vivid-64 3.19.0-37-generic #42-Ubuntu SMP Fri Nov 20 18:22:05 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

- `lsb_release -a`

        No LSB modules are available.
        Distributor ID:	Ubuntu
        Description:	Ubuntu 15.04
        Release:	15.04
        Codename:	vivid

- `docker version`

        Client:
         Version:      1.9.1
         API version:  1.21
         Go version:   go1.4.2
         Git commit:   a34a1d5
         Built:        Fri Nov 20 13:16:54 UTC 2015
         OS/Arch:      linux/amd64
    
        Server:
         Version:      1.9.1
         API version:  1.21
         Go version:   go1.4.2
         Git commit:   a34a1d5
         Built:        Fri Nov 20 13:16:54 UTC 2015
         OS/Arch:      linux/amd64

- `docker info`

        Containers: 0
        Images: 0
        Server Version: 1.9.1
        Storage Driver: aufs
         Root Dir: /var/lib/docker/aufs
         Backing Filesystem: extfs
         Dirs: 0
         Dirperm1 Supported: true
        Execution Driver: native-0.2
        Logging Driver: json-file
        Kernel Version: 3.19.0-37-generic
        Operating System: Ubuntu 15.04
        CPUs: 1
        Total Memory: 489.1 MiB
        Name: vagrant-ubuntu-vivid-64
        ID: TOXL:DK4E:6EZN:PISH:73OI:GQGO:FUOK:2A5I:AEYH:5BVI:4AN3:GJHJ
        WARNING: No swap limit support

After reloading the VM (`vagrant reload`), Docker commands respond with a 404:

- `docker version`

        Client:
         Version:      1.9.1
         API version:  1.21
         Go version:   go1.4.2
         Git commit:   a34a1d5
         Built:        Fri Nov 20 13:16:54 UTC 2015
         OS/Arch:      linux/amd64
        Error response from daemon: 404 page not found

- `docker info`

        Error response from daemon: 404 page not found

- `systemctl status docker.service`

        ● docker.service - Docker Application Container Engine
           Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
           Active: failed (Result: exit-code) since Sat 2015-12-05 00:43:02 UTC; 17s ago
             Docs: https://docs.docker.com
          Process: 1272 ExecStart=/usr/bin/docker daemon -H fd:// (code=exited, status=1/FAILURE)
         Main PID: 1272 (code=exited, status=1/FAILURE)

A complete transcript of the process can be found in [this Gist](https://gist.github.com/whymarrh/c5c75cf6b0795328df93).

Interestingly, though, if I don't run `apt-get update` and `apt-get dist-upgrade` during provisioning, I can reload the VM without issues.

**Comment by thaJeztah** [comment]
@whymarrh does the daemon log show anything useful? Reason for the service not starting successfully? For debugging, it may be worth adding `-D` to the daemon options, or starting it manually, `docker daemon -D ...`

**Comment by whymarrh** [comment]
Running `sudo journalctl -fu docker.service` gives me:

    -- Logs begin at Sat 2015-12-05 22:37:14 UTC. --
    Dec 05 22:37:43 vagrant-ubuntu-vivid-64 systemd[1]: Unit docker.service entered failed state.
    Dec 05 22:37:43 vagrant-ubuntu-vivid-64 systemd[1]: docker.service failed.
    Dec 05 22:37:43 vagrant-ubuntu-vivid-64 systemd[1]: Starting Docker Application Container Engine...
    Dec 05 22:37:43 vagrant-ubuntu-vivid-64 docker[1267]: time="2015-12-05T22:37:43.619197421Z" level=info msg="API listen on /var/run/docker.sock"
    Dec 05 22:37:43 vagrant-ubuntu-vivid-64 docker[1267]: time="2015-12-05T22:37:43.622730280Z" level=error msg="[graphdriver] prior storage driver \"aufs\" failed: driver not supported"
    Dec 05 22:37:43 vagrant-ubuntu-vivid-64 docker[1267]: time="2015-12-05T22:37:43.623145271Z" level=fatal msg="Error starting daemon: error initializing graphdriver: driver not supported"
    Dec 05 22:37:43 vagrant-ubuntu-vivid-64 systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
    Dec 05 22:37:43 vagrant-ubuntu-vivid-64 systemd[1]: Failed to start Docker Application Container Engine.
    Dec 05 22:37:43 vagrant-ubuntu-vivid-64 systemd[1]: Unit docker.service entered failed state.
    Dec 05 22:37:43 vagrant-ubuntu-vivid-64 systemd[1]: docker.service failed.

Starting the daemon manually `docker daemon -D`:

    DEBU[0000] docker group found. gid: 999                 
    DEBU[0000] Server created for HTTP on unix (/var/run/docker.sock)
    ERRO[0000] [graphdriver] prior storage driver "aufs" failed: driver not supported
    FATA[0000] Error starting daemon: error initializing graphdriver: driver not supported

And I can fix (?) the issue by reinstalling `linux-image-extra-$(uname -r)` and readding the aufs module.

Judging by the issue tag, maybe this isn't related?

**Comment by thaJeztah** [comment]
@whymarrh that's weird; did the kernel got updated in the VM? No idea how the linux-image-extra package got uninstalled

**Comment by whymarrh** [comment]
@thaJeztah yep, looks like it, running `apt-get dist-upgrade` during provisioning installed 3.19.0-39 from 3.19.0-37 and the reboot saw it take effect.

**Comment by pandeiro** [comment]
@asziranyi On system startup, that command shows this:

```
â— docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: https://docs.docker.com
```

After trying to run a system through docker-compose and getting the 404 message, it shows this:

```
â— docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: active (running) since Thu 2015-12-17 18:57:14 BRST; 4s ago
     Docs: https://docs.docker.com
 Main PID: 1109 (docker)
   CGroup: /system.slice/docker.service
           â””â”€1109 /usr/bin/docker daemon -H fd:// --exec-opt native.cgroupdriver=cgroupfs

Dec 17 18:57:13 power docker[1109]: time="2015-12-17T18:57:13.347883120-02:00" level=warning msg="Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section."
Dec 17 18:57:13 power docker[1109]: time="2015-12-17T18:57:13.445634908-02:00" level=info msg="[graphdriver] using prior storage driver \"devicemapper\""
Dec 17 18:57:13 power docker[1109]: time="2015-12-17T18:57:13.662546634-02:00" level=info msg="Firewalld running: false"
Dec 17 18:57:13 power docker[1109]: time="2015-12-17T18:57:13.722747415-02:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Dec 17 18:57:13 power docker[1109]: time="2015-12-17T18:57:13.869178135-02:00" level=info msg="Loading containers: start."
Dec 17 18:57:14 power docker[1109]: ..................................................................
Dec 17 18:57:14 power docker[1109]: time="2015-12-17T18:57:14.206477977-02:00" level=info msg="Loading containers: done."
Dec 17 18:57:14 power docker[1109]: time="2015-12-17T18:57:14.206507589-02:00" level=info msg="Daemon has completed initialization"
Dec 17 18:57:14 power docker[1109]: time="2015-12-17T18:57:14.206542668-02:00" level=info msg="Docker daemon" commit=a34a1d5-dirty execdriver=native-0.2 graphdriver=devicemapper version=1.9.1
Dec 17 18:57:14 power systemd[1]: Started Docker Application Container Engine.
```

And a few seconds later, when I try to run compose again, it works.

**Comment by asziranyi** [comment]
@pandeiro I found your previous comment, too https://github.com/docker/docker/issues/17960#issuecomment-157813024. Strange. Is it possible to a firewall or selinux issue?

**Comment by feus4177** [comment]
Removing the network files worked for me as well. Thanks @asziranyi.

**Comment by pandeiro** [comment]
@asziranyi with regard to firewall and selinux, I have not setup anything beyond what Arch Linux provides out of the box. I find it strange that the 404 error occurs on the first run of docker, but after 1-2 seconds, all subsequent calls work. It's as if the first call is starting the daemon or something, and indeed you can see the different values for "Active: ..." in the output I pasted above.

**Comment by pandeiro** [comment]
Great news: seems I was able to get past this issue with the following commands.

```
$ sudo systemctl stop docker.socket
$ sudo systemctl disable docker.socket
$ sudo reboot
...
$ sudo systemctl start docker.service
$ sudo systemctl start docker.service
```

I have no idea why `docker.socket` was setup in systemd, instead of/in addition to `docker.service`. But removing it in this way seems to have solved the issue. I'm not getting the 404 message on my initial docker commands anymore.

**Comment by thaJeztah** [comment]
@pandeiro looks like it's setup with systemd socket activation; see for example https://github.com/docker/docker/issues/18212, https://github.com/docker/docker/pull/8451, https://github.com/docker/docker/pull/10891

**Comment by cppexpert** [comment]
Gentlemen, is it still broken ? Shall I upgrade from 1.8.3 to 1.9.1 ?

**Comment by bduffany** [comment]
@pandeiro did you actually have to run `$ sudo systemctl start docker.service` twice or is that a typo?

**Comment by pandeiro** [comment]
@bduffany Honestly I can't seen this since upgrading to 1.10.x and I don't recall if that's intentional or not, but from my understanding of systemd, it looks unnecessary, so I think it's a typo.

**Comment by Vanuan** [comment]
This happens when using docker-compose 1.7 with docker 1.8

**Comment by lnalex** [comment]
Upgrading to Docker 1.11 fixes the problem.

**Comment by richburdon** [comment]
docker-compose recently stopped working for me; I updated everything and still have the issue:

```
docker --version
Docker version 1.12.1, build 23cf638

docker-compose --version
docker-compose version 1.8.0, build unknown

docker-compose up
ERROR: 404 page not found
```

**Comment by richburdon** [comment]
Seems that "ERROR:page not found" is the error message display for any problems within the yml file. (eventually discovered after --verbose).

I guess no one has errors in their yml files?

**Comment by tebeka** [comment]
This seems to be a problem with curl, when I run the following Python script I get 200 and see JSON output:

```python
#!/usr/bin/env python3

from socket import socket, AF_UNIX

request = '''\
GET /containers/json HTTP/1.1
Host: localhost
Connection: close

'''

sock = socket(AF_UNIX)
sock.connect('/var/run/docker.sock')
sock.sendall(request.encode())
buf = []
while True:
    data = sock.recv(1024)
    if not data:
        break
    buf.append(data.decode())
print(''.join(buf))
```

**Comment by thaJeztah** [comment]
I this still an issue for anyone?

**Comment by feus4177** [comment]
I've upgraded to Docker for Mac.

**Comment by asziranyi** [comment]
@thaJeztah I haven't experienced it for a while.

**Comment by thaJeztah** [comment]
I'm gonna go ahead and close this, but feel free to comment if you think this is still an issue, thanks!

**Comment by tebeka** [comment]
I still see the problem:

    $ curl --version
    curl 7.50.2 (x86_64-pc-linux-gnu) libcurl/7.50.2 OpenSSL/1.0.2h zlib/1.2.8 libidn/1.33 libssh2/1.7.0
    Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
    Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets    

    $ docker version
    Client:
     Version:      1.12.1
     API version:  1.24
     Go version:   go1.7
     Git commit:   23cf638
     Built:        Fri Aug 19 02:03:02 2016
     OS/Arch:      linux/amd64

    Server:
     Version:      1.12.1
     API version:  1.24
     Go version:   go1.7
     Git commit:   23cf638
     Built:        Fri Aug 19 02:03:02 2016
     OS/Arch:      linux/amd64
    ╭─miki@archer  ~ 
    ╰─$ curl -i --unix-socket /var/run/docker.sock http:/containers/json
    HTTP/1.1 404 Not Found
    Content-Type: application/json
    Date: Fri, 16 Sep 2016 05:32:46 GMT
    Content-Length: 29

    {"message":"page not found"}

**Comment by thaJeztah** [comment]
@tebeka that's an issue with cURL, it looks like cURL treats `containers` as the hostname, and tries to call `/json` as endpoint. You can see this happening if you use the `-v` (verbose) option;


```bash
# curl -v --unix-socket /var/run/docker.sock "http:/containers/json"

* Unwillingly accepted illegal URL using 1 slash!
*   Trying /var/run/docker.sock...
* Connected to containers (/var/run/docker.sock) port 80 (#0)
> GET /json HTTP/1.1
> Host: containers
> User-Agent: curl/7.50.2
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Type: application/json
< Date: Fri, 16 Sep 2016 10:02:41 GMT
< Content-Length: 29
<
{"message":"page not found"}
* Curl_http_done: called premature == 0
* Connection #0 to host containers left intact
```

(See `Host: containers`)

Adding a "bogus" hostname works around this issue;

```bash
# curl -v --unix-socket /var/run/docker.sock "http:/bla/containers/json"

* Unwillingly accepted illegal URL using 1 slash!
*   Trying /var/run/docker.sock...
* Connected to bla (/var/run/docker.sock) port 80 (#0)
> GET /containers/json HTTP/1.1
> Host: bla
> User-Agent: curl/7.50.2
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Server: Docker/1.13.0-dev (linux)
< Date: Fri, 16 Sep 2016 10:03:32 GMT
< Content-Length: 889
<
[{"Id":"baa9cea03fe3390ff5f9900cba82303f9042017e17b445078176647fd3cd9d69","Names":["/hopeful_morse"],"Image":"alpine","ImageID":"sha256:4e38e38c8ce0b8d9041a9c4fefe786631d1416225e13b0bfe8cfa2321aec4bba","Command":"sh","Created":1474019132,"Ports":[],"Labels":{},"State":"running","Status":"Up 17 minutes","HostConfig":{"NetworkMode":"default"},"NetworkSettings":{"Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"6e1b8e7330078255b697d875ebe4c3c53ccbed5d3ea8baaea2709dffa51f3be3","EndpointID":"a045494453a2a20154c6264ac016dc4d493dafc561e3f194bbc56faf5db5f647","Gateway":"172.18.0.1","IPAddress":"172.18.0.2","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:12:00:02"}}},"Mounts":[{"Type":"bind","Source":"/var/run/docker.sock","Destination":"/var/run/docker.sock","Mode":"","RW":true,"Propagation":""}]}]
* Curl_http_done: called premature == 0
* Connection #0 to host bla left intact
```

I looked around if there's some way to make cURL "do the right thing", but couldn't find it directly, perhaps someone else knows. In any case that's not a bug in Docker

**Comment by thaJeztah** [comment]
Actually, may be a bug in either curl 7.50 or one of the libraries it uses. Running the same on a different version of curl (in a ubuntu 16.04 container);

```
curl --version
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
```

Works without issues:

```
root@442c6432204a:/# curl -v --unix-socket /var/run/docker.sock "http:/containers/json"
*   Trying /var/run/docker.sock...
* Connected to http (/var/run/docker.sock) port 80 (#0)
> GET /containers/json HTTP/1.1
> Host: http
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Server: Docker/1.13.0-dev (linux)
< Date: Fri, 16 Sep 2016 10:11:52 GMT
< Content-Length: 906
<
[{"Id":"442c6432204a7c35c34801051257aa23280f91fc9651817304b5c2561438c43d","Names":["/fervent_yalow"],"Image":"ubuntu:16.04","ImageID":"sha256:bd3d4369aebc4945be269859df0e15b1d32fefa2645f5699037d7d8c6b415a10","Command":"/bin/bash","Created":1474020647,"Ports":[],"Labels":{},"State":"running","Status":"Up About a minute","HostConfig":{"NetworkMode":"default"},"NetworkSettings":{"Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"6e1b8e7330078255b697d875ebe4c3c53ccbed5d3ea8baaea2709dffa51f3be3","EndpointID":"f71e6b7c65421d39612b18b525c391590fd53e1648b5f5ffe46238497d821e0e","Gateway":"172.18.0.1","IPAddress":"172.18.0.2","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:12:00:02"}}},"Mounts":[{"Type":"bind","Source":"/var/run/docker.sock","Destination":"/var/run/docker.sock","Mode":"","RW":true,"Propagation":""}]}]
* Connection #0 to host http left intact
````

**Comment by thaJeztah** [comment]
Right, so they changed the behavior in cURL 7.5 and this is "by design":
https://github.com/curl/curl/issues/936

> I don't see how "/foo" could ever have been expected from such a malformed url. I agree that the behavior is changed but is now more aligned with how browsers parse it.

**Comment by asziranyi** [comment]
@thaJeztah Look at your example: you mistyped the url: `curl -v --unix-socket /var/run/docker.sock "http:/containers/json"` There is no double slash after the colon. 

with 

`curl -v --unix-socket /var/run/docker.sock "http://containers/json"` the curl 7.47 produces the same error.

```
$ curl -v --unix-socket /var/run/docker.sock "http://containers/json"
*   Trying /var/run/docker.sock...
* Connected to containers (/var/run/docker.sock) port 80 (#0)
> GET /json HTTP/1.1
> Host: containers
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Type: application/json
< Date: Fri, 16 Sep 2016 10:41:10 GMT
< Content-Length: 29
< 
{"message":"page not found"}
* Connection #0 to host containers left intact
```

```
$ curl --version
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 
```

**Comment by thaJeztah** [comment]
@asziranyi: originally a single slash was expected for a socket connection, and I decided to use the exact URL that @tebeka used. Both _with_ and _without_ the double slash leads to the same result.

**Comment by thaJeztah** [comment]
@asziranyi so TL;DR

Curl 7.4x:

- do **not** add a hostname
- use `http:`, followed by the *literal* endpoint path (so `/containers/json`). *Don't* use a double slash, as it's used as path for the endpoint (`//containers/json`), so produces a 404

Curl 7.5x expects a valid url:

- prepend a "dummy" hostname for the endpoint-path
- use `http://` (_with_ double slash)

**Comment by justincormack** [comment]
I think it is possibly related to the fact that http 1.1 requires the hostname, so it is impossible to make a valid http 1.1 request without specifying it. But it should have been better documented.

**Comment by tebeka** [comment]
Thanks @thaJeztah, the following works for me:
```
$ curl -i --unix-socket /var/run/docker.sock http://localhost/containers/json 
HTTP/1.1 200 OK
Content-Type: application/json
Server: Docker/1.12.1 (linux)
Date: Fri, 16 Sep 2016 12:36:53 GMT
Content-Length: 3

[]
```

**Comment by asziranyi** [comment]
@thaJeztah Thank you for the clarification of socket connection. Now everything is clear!

**Comment by eliasb** [comment]
All my Docker containers stopped working. I am getting the same error message "404 page not found".

After updating Docker, everything went awry! 

In an attempt to fix the problem I verified that I had "docker-engine" version 17.03.0-ce, build 60ccb22.

I uninstalled the old docker and installed the new "docker-ce" version 17.03.1-ce, build c6d412e. 

I also updated docker-composer to version 1.13.0, build 1719ceb.

The problem remains!

I am running Docker inside a CentOS 7.3.1611 VirtualBox.

I am under a lot of pressure to make this thing work again! Any help would be greatly appreciated.

**Comment by thaJeztah** [comment]
@eliasb Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

For direct interaction with other users, using the Community Slack may be your best option

**Comment by eliasb** [comment]
Thanks for the prompt response! 

I will do that.
