### ISSUE TITLE
2 veth are created when **deleting** a container with  overlay network

### ISSUE THREAD

**Issue by ezrasilvera** [docker/docker#19884]
It seems that the host interfaces are not cleaned correctly when deleting a container with overlay interface.

How to reproduce:
Setup: docker engine with etcd as the KV store for overlay network
1. Create an overlay network  "docker network create --driver=overlay nw1"
2. create and start a container "docker run -d --name=cont1 --net=nw1 busybox httpd -f -p 3000)
--->  a new veth is created on the host (connected to  docker_gwbridge)
3. Delete the container "docker rm -f test_cont1"

--->  The veth that created at (2) is removed
--->  Two new veth interfaces are CREATED on the host as a result of the container removal.

**Comment by thaJeztah** [comment]
@ezrasilvera which version of docker are you running? Could you provide the information that was requested by @GordonTheTurtle?

Also, could you test if this is reproducible on the 1.10 release candidate? because many improvements are made in this area, so this may already been resolved; note that the release-candidates should not yet be used on a production system; https://github.com/docker/docker/releases

**Comment by ezrasilvera** [comment]
docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64
==================================================
docker info

Containers: 0
Images: 2
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 2
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-23-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 15.67 GiB
Name: swarm-mesos-exp-2
ID: FGLD:SLZU:3THO:DAIZ:X5XA:2AKT:ARQA:QNHB:XOCE:DKW6:MNSN:I5JO
Cluster store: etcd://10.143.197.99:2379/swarm
Cluster advertise: 10.143.129.230:2375
===========================================

**Comment by thaJeztah** [comment]
Looks like you're not running an up-to-date version of docker 1.9 (1.9.1 has been released), also notice that you look to be running a non-standard kernel (ubuntu 14.04.3 does not ship with kernel 4.2), but not sure that's the issue here

**Comment by thaJeztah** [comment]
ping @mavenugo any ideas?

**Comment by mountkin** [comment]
I think the problem is already fixed by https://github.com/docker/docker/pull/19198 and https://github.com/docker/docker/pull/19857

**Comment by thaJeztah** [comment]
Thanks @mountkin, I suspected there were improvements made already for 1.10

@ezrasilvera can you try if the 1.10 release candidate resolves this for you?

**Comment by mavenugo** [comment]
@ezrasilvera @thaJeztah this issue is still open in RC2 and is resolved by https://github.com/docker/docker/pull/19857. If we have an RC3, then please cherry-pick https://github.com/docker/docker/pull/19857 patch as well.

**Comment by ezrasilvera** [comment]
Tested with 1.10-rc2. The bug is still there 
When I "docker rm -f" the container 2 new veth interfaces are created !
I can see according to the MAC that one of them is related to the eth0 inside the container (that is not there anymore) 
As each container delete leaves you with 2 additional interfaces you can reach thousands of ghost interfaces very quickly 
Only reboot of the machine cleans those ghost veth.

**Comment by ezrasilvera** [comment]
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.10.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 2
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null overlay
Kernel Version: 4.2.0-23-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.67 GiB
Name: swarm-mesos-exp-2
ID: FGLD:SLZU:3THO:DAIZ:X5XA:2AKT:ARQA:QNHB:XOCE:DKW6:MNSN:I5JO
Cluster store: etcd://10.143.197.99:2379/swarm
Cluster advertise: 10.143.129.230:2375
