### ISSUE TITLE
Cannot start containers: port is already allocated

### ISSUE THREAD

**Issue by matevarga** [docker/docker#20486]
Description of problem:

I want to start a specific container with port 80 exposed and also with port 80 bound to the hosts port 80. The container is part of an overlay network. This operation fails:
```
root@uatweb2:~# docker start phr-nginx
Error response from daemon: container cc39fe5306c1ba7633fa14b9bcddb66536153619bf57b84b30673e2328e9295a: endpoint create on GW Network failed: failed to create endpoint gateway_cc39fe5306c1 on network docker_gwbridge: Bind for 0.0.0.0:80 failed: port is already allocated
Error: failed to start containers: phr-nginx
```
I can confirm that nothing is listening on port 80 on the host (and if I simply start another container bound to port 80, then it works).

`docker version`:
```
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64
```

`docker info`:
```
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64
mvarga@uatweb2:~$ docker info
Containers: 13
 Running: 4
 Paused: 0
 Stopped: 9
Images: 211
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 252
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge overlay null host
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.792 GiB
Name: uatweb2
ID: 3D3C:HPUL:BPHZ:HKF4:BB5G:4WDU:TU5S:4RIU:CJG4:4MWB:B54Y:DUAL
Cluster store: consul://104.239.161.67:8500
Cluster advertise: 23.253.235.69:2376
```

`uname -a`:
`Linux uatweb2 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

Environment details (AWS, VirtualBox, physical, etc.):
Rackspace VM.

How reproducible:
Can't reproduce.

Actual Results:
The container fails to start.

Expected Results:
Container starts.

Additional info:

Tail of /var/log/upstart/docker.log (after restarting Docker):
```
ESC[34mINFOESC[0m[0007] API listen on /var/run/docker.sock           
ESC[34mINFOESC[0m[0007] API listen on 23.253.235.69:2376             
ESC[33mWARNESC[0m[0026] Failed to allocate and map port 80-80: Bind for 0.0.0.0:80 failed: port is already allocated 
ESC[33mWARNESC[0m[0026] Could not rollback container connection to network pkb-phr 
ESC[33mWARNESC[0m[0026] failed to cleanup ipc mounts:
failed to umount /var/lib/docker/containers/cc39fe5306c1ba7633fa14b9bcddb66536153619bf57b84b30673e2328e9295a/shm: no such file or directory 
ESC[31mERROESC[0m[0026] Handler for POST /v1.22/containers/phr-nginx/start returned error: container cc39fe5306c1ba7633fa14b9bcddb66536153619bf57b84b30673e2328e9295a: endpoint create on GW Network failed: failed to create endpoint gateway_cc39fe5306c1 on network docker_gwbridge: Bind for 0.0.0.0:80 failed: port is already allocated 
ESC[33mWARNESC[0m[0847] exit status 1                                
ESC[31mERROESC[0m[0848] error locating sandbox id a084032ed558ddd147ac2d3087635abbb4e0799c2bf22077a1924d8ea55aa3ea: sandbox a084032ed558ddd147ac2d3087635abbb4e0799c2bf22077a1924d8ea55aa3ea not found 
ESC[33mWARNESC[0m[0848] failed to cleanup ipc mounts:
failed to umount /var/lib/docker/containers/9960f5ad7ef902361e2e033a5d4eae41ba866be29901942ee24c5abec5f4422d/shm: invalid argument 
ESC[31mERROESC[0m[0848] Error unmounting container 9960f5ad7ef902361e2e033a5d4eae41ba866be29901942ee24c5abec5f4422d: not mounted 
ESC[31mERROESC[0m[0848] Handler for POST /v1.22/containers/9960f5ad7ef902361e2e033a5d4eae41ba866be29901942ee24c5abec5f4422d/start returned error: Container command not found or does not exist. 
ESC[31mERROESC[0m[0854] Handler for POST /v1.22/containers/create returned error: No such image: net:latest 
ESC[33mWARNESC[0m[0931] Failed to allocate and map port 80-80: Bind for 0.0.0.0:80 failed: port is already allocated 
ESC[33mWARNESC[0m[0931] Could not rollback container connection to network pkb-phr 
ESC[33mWARNESC[0m[0932] failed to cleanup ipc mounts:
failed to umount /var/lib/docker/containers/cd7d5c05a82332496dde3a2499fb7a2d4b49d645a106363ec1a02fd7c8f4e37f/shm: no such file or directory 
ESC[31mERROESC[0m[0932] Handler for POST /v1.21/containers/cd7d5c05a82332496dde3a2499fb7a2d4b49d645a106363ec1a02fd7c8f4e37f/start returned error: container cd7d5c05a82332496dde3a2499fb7a2d4b49d645a106363ec1a02fd7c8f4e37f: endpoint create on GW Network failed: failed to create endpoint gateway_cd7d5c05a823 on network docker_gwbridge: Bind for 0.0.0.0:80 failed: port is already allocated 
ESC[33mWARNESC[0m[4417] Failed to allocate and map port 80-80: Bind for 0.0.0.0:80 failed: port is already allocated 
ESC[33mWARNESC[0m[4417] Could not rollback container connection to network pkb-phr 
ESC[33mWARNESC[0m[4418] failed to cleanup ipc mounts:
failed to umount /var/lib/docker/containers/3b6aaa8e169cc736a453557c0bc0bb2843c336113f9194738c61ddde418c3d61/shm: no such file or directory 
ESC[31mERROESC[0m[4418] Handler for POST /v1.21/containers/3b6aaa8e169cc736a453557c0bc0bb2843c336113f9194738c61ddde418c3d61/start returned error: container 3b6aaa8e169cc736a453557c
```

**Comment by HackToday** [comment]
@matevarga  I think you need provide related container configuration.

Could you show your `docker inspect **` output.


And it seems this container was built by youself. you need hav Dockerfile, is it possible to append that inforamtion here ?

**Comment by matevarga** [comment]
It's the standard nginx image (:latest), nothing custom. I can't provide useful info re. the containers as I had to solve this problem. When I ran the container, I explicitely EXPOSEd port 80, and also bound port 80 to the hosts port 80. After I've removed the EXPOSE part, everything started to work -- I don't know why.

**Comment by rutsky** [comment]
I'm experiencing similar behavior after power outage on Docker 1.9.1:

```
~# docker info
Containers: 15
Images: 219
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 249
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-76-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 1.955 GiB
Name: docker1
ID: 4EUM:PSMM:U3HV:65QS:UKCQ:TVZC:QPCN:46S3:QF7O:24BJ:CB7X:M7TG
Debug mode (server): true
 File Descriptors: 49
 Goroutines: 85
 System Time: 2016-04-04T16:50:01.88906464+03:00
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/bin/docker
 Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
```

```
time="2016-04-04T16:51:09.309984508+03:00" level=debug msg="Calling POST /v1.21/containers/shipyard_lb/start" 
time="2016-04-04T16:51:09.310021398+03:00" level=info msg="POST /v1.21/containers/shipyard_lb/start" 
time="2016-04-04T16:51:09.319728525+03:00" level=debug msg="Assigning addresses for endpoint shipyard_lb's interface on network bridge" 
time="2016-04-04T16:51:09.319856423+03:00" level=debug msg="RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[])" 
time="2016-04-04T16:51:09.325171830+03:00" level=debug msg="/sbin/iptables, [--wait -t nat -A DOCKER -p tcp -d 0/0 --dport 80 -j DNAT --to-destination 172.17.0.10:80 ! -i docker0]" 
time="2016-04-04T16:51:09.329769246+03:00" level=debug msg="/sbin/iptables, [--wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.10 --dport 80 -j ACCEPT]" 
time="2016-04-04T16:51:09.340349119+03:00" level=debug msg="/sbin/iptables, [--wait -t nat -A POSTROUTING -p tcp -s 172.17.0.10 -d 172.17.0.10 --dport 80 -j MASQUERADE]" 
time="2016-04-04T16:51:09.388240440+03:00" level=warning msg="Failed to allocate and map port 80-80: Bind for 0.0.0.0:80 failed: port is already allocated" 
time="2016-04-04T16:51:09.388978953+03:00" level=debug msg="/sbin/iptables, [--wait -t nat -D DOCKER -p tcp -d 0/0 --dport 80 -j DNAT --to-destination 172.17.0.10:80 ! -i docker0]" 
time="2016-04-04T16:51:09.393429608+03:00" level=debug msg="/sbin/iptables, [--wait -t filter -D DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.10 --dport 80 -j ACCEPT]" 
time="2016-04-04T16:51:09.395952539+03:00" level=debug msg="/sbin/iptables, [--wait -t nat -D POSTROUTING -p tcp -s 172.17.0.10 -d 172.17.0.10 --dport 80 -j MASQUERADE]" 
time="2016-04-04T16:51:09.429137575+03:00" level=debug msg="Releasing addresses for endpoint shipyard_lb's interface on network bridge" 
time="2016-04-04T16:51:09.429299075+03:00" level=debug msg="ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.10)" 
time="2016-04-04T16:51:09.431569709+03:00" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/d5567a30290af054bd6795c8d61616a31e47f28d3a0e6df942a358d3711a7da5/shm: invalid argument\nfailed to umount /var/lib/docker/containers/d5567a30290af054bd6795c8d61616a31e47f28d3a0e6df942a358d3711a7da5/mqueue: invalid argument" 
time="2016-04-04T16:51:09.452949532+03:00" level=error msg="Handler for POST /v1.21/containers/shipyard_lb/start returned error: Cannot start container shipyard_lb: failed to create endpoint shipyard_lb on network bridge: Bind for 0.0.0.0:80 failed: port is already allocated" 
time="2016-04-04T16:51:09.453002517+03:00" level=error msg="HTTP Error" err="Cannot start container shipyard_lb: failed to create endpoint shipyard_lb on network bridge: Bind for 0.0.0.0:80 failed: port is already allocated" statusCode=500 
```

**Comment by rutsky** [comment]
Ok, I think I found how to fix this issue in my case.

I had following `hostconfig.json`:

```
# cat /var/lib/docker/containers/d5567a30290af054bd6795c8d61616a31e47f28d3a0e6df942a358d3711a7da5/hostconfig.json | jq .
{
  "VolumeDriver": "",
  "ConsoleSize": [
    0,
    0
  ],
  "CgroupParent": "",
  "LogConfig": {
    "Config": null,
    "Type": ""
  },
  "Ulimits": null,
  "ReadonlyRootfs": false,
  "SecurityOpt": null,
  "RestartPolicy": {
    "MaximumRetryCount": 0,
    "Name": "no"
  },
  "Privileged": false,
  "MemorySwappiness": null,
  "OomKillDisable": false,
  "BlkioWeight": 0,
  "CpuQuota": 0,
  "CpusetMems": "",
  "CpusetCpus": "",
  "CpuPeriod": 0,
  "Binds": null,
  "ContainerIDFile": "",
  "LxcConf": [],
  "Memory": 0,
  "MemoryReservation": 0,
  "MemorySwap": 0,
  "KernelMemory": 0,
  "CpuShares": 0,
  "PortBindings": {
    "80/tcp": [
      {
        "HostPort": "80",
        "HostIp": "0.0.0.0"
      }
    ],
    "443/tcp": null
  },
  "Links": null,
  "PublishAllPorts": false,
  "Dns": [],
  "DnsOptions": [],
  "DnsSearch": [],
  "ExtraHosts": null,
  "VolumesFrom": null,
  "Devices": null,
  "NetworkMode": "default",
  "IpcMode": "",
  "PidMode": "",
  "UTSMode": "",
  "CapAdd": null,
  "CapDrop": null,
  "GroupAdd": null
}
```

Notice `"443/tcp": null`.
When I removed this the issue with port binding has been resolved.

Still I don't know how this issue appeared (after power outage), or how to reproduce it.

**Comment by iammerrick** [comment]
When you run `docker ps` are there other containers running from other projects?

**Comment by rutsky** [comment]
@iammerrick what do you mean? In my case I had around 10 container running on the failed host, and around 2 of them were broken with `"443/tcp": null` (other containers worked normally).

**Comment by iammerrick** [comment]
@rutsky I only asked because I stumbled on this issue with a similar error and it was because I had another container on the machine from another project which docker ps revealed (docker-compose did not).

**Comment by lindsaymarkward** [comment]
In my case, I had my project running, but then renamed the folder the containers were in. 
I got this message when I tried to up them as it wasn't replacing them (different names).
I removed the running containers (old names) and it worked again.

**Comment by cpuguy83** [comment]
It sounds like you are trying to start a container binding to a port that is already bound to. This is expected to error out.

Please check the output of `docker ps -a`.

**Comment by oliverhr** [comment]
@cpuguy83 nop, the same happen to me seems that docker open "ghost ports", I open this with a detailed screenshots:

https://github.com/docker/for-mac/issues/205

**Comment by andreas4all** [comment]
It's look like a have same issue.

Stopped and removed containers not freed ports.

I have container with mapped port 8880 - first works.
Then I stop and recreate container and port is used (bind for port 0.0.0.0:8880 failed: port is already allocated.
If I check netstat, there is no listening port.
Then I change port to 8881 and start container - this work's, but container listen on 8081.

```
# ps aux | grep 8880
// empty
```

```
# ps aux | grep 8881
root      6070  0.0  0.0  51836  3036 ?        Sl   11:08   0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8881 -container-ip 172.18.0.5 -container-port 80
```

```
# iptables -t nat -S | grep 8880
// empty
```

```
# iptables -t nat -S | grep 8881
-A DOCKER ! -i br-a6d8851970cb -p tcp -m tcp --dport 8881 -j DNAT --to-destination 172.18.0.5:80
```

```
# docker info
Containers: 51
 Running: 45
 Paused: 0
 Stopped: 6
Images: 100
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 352
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 15.67 GiB
Name: lupino
ID: V4LJ:2LDK:NTZZ:QOBM:Y6SB:OLSP:QGCC:RUQA:JKTV:WKAG:CHBE:XQ5C
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

```
# docker --version
Docker version 1.12.0, build 8eab29e
```

**Comment by netroby** [comment]
Got the same issue

**Comment by hopeseekr** [comment]
I have to delete all my containers, all my images, and start from scratch. It is infuriating and time consuming.

**Comment by andreas4all** [comment]
only what works for me is stop docker daemon, then delete `/var/lib/docker/network/files/local-kv.db` and after all recreate all containers :( .

**Comment by hopeseekr** [comment]
I just confirmed @andreas4all's work around works! And it definitely saves me time from having to `docker load` all of my images again. 

```#!/bin/bash
docker rm $(docker ps -aq)
sudo rm /var/lib/docker/network/files/local-kv.db```

**Comment by cpuguy83** [comment]
ping @aboch please have a look

**Comment by aboch** [comment]
@andreas4all 
My setup is especially similar to yours (from docker info). But I am not able to reproduce the issue neither with 1.12.0 nor with 1.12.1. While it seems it is consistent for you. 

If you stop the newly started container with mapped port 8081, are you able to start a new container with port mapped to 8081 ?

If no, then it must be the bridge driver consistently fails to release the mapped ports with portmanager, we should at least see a warning or error log somewhere.

If yes (only 8080 is affected), then there is some stale bridge driver endpoint in the store which has mapped port 8080. The stale endpoint exposed and mapped pots get automatically reserved with portmanager at daemon boot.

`sudo strings /var/lib/docker/network/files/local-kv.db | grep 8080` should give a clue if run when no container mapping to that port are running.

**Comment by kopax** [comment]
Same issue here

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:17:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:17:17 2016
 OS/Arch:      linux/amd64
```

Is there a way to delete the line when I do ?

    root@master:/home/me# iptables -t nat -S | grep 31890
    -A DOCKER -d 172.16.10.3/32 ! -i docker0 -p tcp -m tcp --dport 31890 -j DNAT --to-destination 172.17.0.3:5000

**Comment by saurabh1gupta** [comment]
I'm facing the same issue during spinning up a new container as:

`Bind for 0.0.0.0:6379 failed: port is already allocated`

While there is no running or exit docker container instance. Can anyone suggest, what should be the solution? This issue is intermittent which doesn't happen all the time.

Thanks.

**Comment by jiMuBao** [comment]
+1
Bind for 0.0.0.0:3306 failed: port is already allocated

**Comment by withinboredom** [comment]
I'm able to reproduce this consistently:

* Slow spinning disks (no fancy ssd)
* `sudo reboot` with the container in question set to `restart=always`

I'll see the container exits with code 1, I'm unable to restart it due to the port being in use by proc `docker-proxy`

``` sh
# output of `sudo netstat -npl | grep 8080`
tcp6       0      0 :::8080                 :::*                    LISTEN      1389/docker-proxy
```

``` sh
# output of `sudo docker ps -a | grep 8080`
```
Yes, you read that right, it's empty

``` sh
# output of `sudo strings /var/lib/docker/network/files/local-kv.db | grep 8080`
{"Addr":"172.17.0.2/16","Config":{"MacAddress":null},"ContainerConfig":{"ParentEndpoints":null,"ChildEndpoints":null},"ExternalConnConfig":{"PortBindings":[{"Proto":6,"IP":"","Port":8080,"HostIP":"","HostPort":8080,"HostPortEnd":8080}],"ExposedPorts":[{"Proto":6,"Port":8080},{"Proto":6,"Port":3306}]},"MacAddress":"02:42:ac:11:00:02","PortMapping":[{"Proto":6,"IP":"172.17.0.2","Port":8080,"HostIP":"0.0.0.0","HostPort":8080,"HostPortEnd":8080}],"SrcName":"vethac20767","id":"07a11f64812b570f66ce845aa9595da87be2148b0a5fb9c77dc89d8d6f079249","nid":"170815f03bbd30964559f318b717914135698f238a19b8d683008d0b252fdefc"}
{"anonymous":true,"disableResolution":true,"ep_iface":{"addr":"172.17.0.30/16","dstPrefix":"eth","mac":"02:9f:fb:6a:d7:55","routes":null,"srcName":"vethad9b1e6","v4PoolID":"LocalDefault/172.17.0.0/16","v6PoolID":""},"exposed_ports":[{"Proto":6,"Port":9010}],"generic":{"com.docker.network.endpoint.exposedports":[{"Proto":6,"Port":9010}],"com.docker.network.endpoint.macaddress":"Ap/7atdV","com.docker.network.portmap":[]},"id":"6e8d8aa4379f42ba6a12e8b54a3ff97da5073eac5417e65011c293e75a6f90a7","ingressPorts":[],"joinInfo":{"StaticRoutes":null,"disableGatewayService":false,"gw":"172.17.0.1"},"locator":"","myAliases":[],"name":"r-Prometheus_prometheus-rancher-exporter_1","sandbox":"08325850811f54baa2cb072cde89f29669fbdd4bf80804e377075e1cb7481e13","svcAliases":[],"svcID":"","svcName":"","virtualIP":"\u003cnil\u003e"}docker/network/v1.0/endpoint/170815f03bbd30964559f318b717914135698f238a19b8d683008d0b252fdefc/7684db6d31217abffd2e42e059575ba89e8fb4539a4956e9fc34495e440c80c6/
```

A reboot almost always fixes the issue, at least in my case. Let me know if logs would be helpful here (and where to find them: ubuntu 16)

**Comment by andreas4all** [comment]
I have problem when I have a classic disc in RAID 5 (one was failed, temporary solution), but when I change this disc to SSD (now I have all SSD disc's in this RAID), everything looks good.

**Comment by lucernae** [comment]
I also having trouble with this. So we don't have another solutions besides restarting docker services?

**Comment by thaJeztah** [comment]
ping @aboch any ideas?

**Comment by aboch** [comment]
Thanks @withinboredom for the valuable info and @andreas4all for confirming.
Then it looks like the delayed save to store for the driver network endpoints is the culprit in causing this issue.

Will look at the code and see if anything can be done faster, or in a way to be more tolerant to ungraceful shutdowns.

**Comment by ngoral** [comment]
Has [the same problem](https://github.com/docker/docker/issues/20486#issuecomment-248793982) as @withinboredom . `docker-proxy` hangs on 1935 and I can do nothing to free it from it. If I just killing `docker-proxy` by PID, it does nothing, I anyway see message about `port is already allocated`.
Doing `sudo service docker restart` revokes `docker-proxy` on 1935 port.
I can't work in that case. And afraid next production deploy will cause the same problems.

May be there are some ways at leastto fix it manually?

**Comment by saurabh1gupta** [comment]
@ngoral You can try to release the port by doing a graceful stop and remove the docker container. I was facing this issue very frequently and then graceful stop & remove before creating the new container solved this issue. 
If it doesn't work, you need to restart docker to release all assigned ports.

**Comment by hello-friend-py** [comment]
@hopeseekr hi, there I also got this issue here.

i tried your workaround but here's what i get on the second command

sudo docker rm $(docker ps -aq)
time="2016-09-29T23:22:06+03:00" level=fatal msg="Get http:///var/run/docker.sock/v1.18/containers/json?all=1: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS?" 
docker: "rm" requires a minimum of 1 argument. See 'docker rm --help'

**Comment by saurabh1gupta** [comment]
@hopeseekr Did you stopped the docker  first before removing it? Please try the below and it should work:

`
sudo docker stop $(docker ps -aq)
sudo docker rm $(docker ps -aq)
`
Please attached the log if this doesn't work.

Thanks.

**Comment by thaJeztah** [comment]
> `sudo docker rm $(docker ps -aq)` -> permission denied.

The permission denied comes from the "subshell", only `sudo docker rm` is run privileged, but `$(docker ps -aq)` is run without `sudo`, so fails. Because of that, no containers (ID's) are returned, which leads to:

> `docker: "rm" requires a minimum of 1 argument. See 'docker rm --help'`

Because effectively you're running `sudo rm <empty>`

**Comment by MrBlenny** [comment]
+1

```
ERROR: for mongodb  Cannot start service mongodb: driver failed programming external connectivity on endpoint stemndocker_mongodb_1 (6bde3e076c954164d75b8d49390dad5427b2bd24b391053845f6e1d74607b903): Bind for 0.0.0.0:27017 failed: port is already allocated

ERROR: for api  Cannot start service api: driver failed programming external connectivity on endpoint stemndocker_api_1 (57c438dd41a23443e04ec38b4b34fad7664434cf8d69724f85bca3f02f54f46a): Bind for 0.0.0.0:3000 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
```

Before running `docker-compose up`, all containers were removed i.e. started with a clean state.

**Comment by GottZ** [comment]
i just updated to 1.12.1 without knowing about this issue. well i confirm this on archlinux. docker build: 23cf638

**Comment by zackxu1** [comment]
I had this issue on Mac OSX.  Every time I start Docker engine, the port 5432 is being to listened to for some reason (BEFORE I start the containers).  I did Docker factory reset to defaults.  This did the trick.  (If you remove all your containers and images, it may work as well.)

**Comment by cirocosta** [comment]
As https://github.com/docker/libnetwork/issues/1504 was cherrypicked for 1.12.3 this issue should be fixed, right?

**Comment by aboch** [comment]
@cirocosta 
docker/libnetwork#1504 fixes one bug which yes would cause the problem tracked by this issue, but in a secific case: When the external conenctivity needs to be reprogrammed for the container (see description for more info).

From the reports on this issue I was not able to confirm reporters had a container being connected to multiple bridge networks.

**Comment by withinboredom** [comment]
@aboch I these containers were in multiple bridge networks. Didn't think about that in my original report. Thanks for fixing this! You guys are awesome!

**Comment by hartror** [comment]
I was having this issue with port 5432, upgrading to Version 1.12.3-beta29.3 (13640) fixed this for me.

**Comment by bimusiek** [comment]
Same problem here, version 1.12.3 fixed the issue <3

**Comment by anthmarques** [comment]
I'm using 1.12.3 version and isnt working for me. I'm trying to up one mysql container and having the same problem.

>`0.0.0.0:3306 failed: port is already allocated`

**Comment by mikeford** [comment]
@anthmarques I was having the same problem and it turns out my local MySQL server was running and conflicting with the MySQL container's 3306 port. You could either terminate your MySQL server locally or change the port in the docker file where you're configuring the mysql image.

**Comment by thaJeztah** [comment]
> or change the port in the docker file where you're configuring the mysql image.

There's no need to change the dockerfile, just mapping the port when running the image works;

```
docker run -p 3307:3306 -d mysql
```

**Comment by mikeford** [comment]
@thaJeztah Yup you're right! Thanks for clarifying that

**Comment by rremani** [comment]
I used this command:
#!/bin/bash
docker rm $(docker ps -aq)
sudo rm /var/lib/docker/network/files/local-kv.db

and now while running my docker container I am getting this error:
docker: Error response from daemon: failed to update store for object type *libnetwork.endpointCnt: Key not found in store.

**Comment by mribichich** [comment]
The same thing happened to me with no containers running.
In CoreOS restarting docker service fixes the problem:

`sudo systemctl restart docker.service`

**Comment by rremani** [comment]
@mribichich ya, I did the same and it worked.

**Comment by udaiveerS** [comment]
This is great stuff, but for stupid people like me. Just check that you turn off mysql from your host device. I still had MySql running as a service on my Mac.

**Comment by ngoral** [comment]
Nothing helped me.
What i do is all here:
```
anastasia@anastasia-Lapt:~/prj/vid$ sudo service docker restart
docker stop/waiting
docker start/running, process 5239
anastasia@anastasia-Lapt:~/prj/vid$ sudo netstat -pna | grep 3322
anastasia@anastasia-Lapt:~/prj/vid$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
anastasia@anastasia-Lapt:~/prj/vid$ docker-compose -f dcom-dev.yml up
Creating vid_records_1
Creating vid_bundler_cache_1
Creating vid_db_data_1
Creating vid_db_1
Creating vid_processor_1

ERROR: for processor  driver failed programming external connectivity on endpoint vid_processor_1 (af112a56e2ec01672c3f92c81fc593f3fae3daf2e01ec5ddedb7ef719359c4b8): Bind for 0.0.0.0:3322 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
anastasia@anastasia-Lapt:~/prj/vid$ sudo netstat -pna | grep 3322
tcp6       0      0 :::3322                 :::*                    LISTEN      5378/docker-proxy
```

So it grabs the port itself and cannot use it?.. how could I make it work?
I've just updated to `Docker version 1.12.6, build 78d1802` on my Ubuntu 14.04.

**Comment by aboch** [comment]
@ngoral Can you try `docker compose down` or manually deleting the compose created networks`docker network rm ...`, then run compose up.

If that does not help, as last resort `rm -rf /var/lib/docker/network` should fix it.

**Comment by ngoral** [comment]
@aboch Yes, I have to do `docker-compose down` but that drops all databases and settings that was ever made. I can do it locally, but if it ever happens on staging, I afraid of this.
So it doesn't seems as a solution for me

**Comment by jhli973** [comment]
have a similar issue:

 Error response from daemon: driver failed programming external connectivity on endpoint priceless_meitner (dbd8f4bcce40f61e661797e2ff68acb65ef42756c3dbdaacc554abedf7258cf2): Bind for 0.0.0.0:8888 failed: port is already allocated.

**Comment by mingdongt** [comment]
I did these and I got it fixed:
1. docker rm -fv $(docker ps -aq)
2. sudo lsof -i -P -n , find the ID of process using the port.
3. kill -9 PID
4. restart pc.
I don't know why, but without 4, it still doesn't get fixed.

**Comment by lucernae** [comment]
I think number 4 is needed because the PID becomes zombie :D.
Sadly I can't restart it if I'm using a shared VPS server.

**Comment by phpguru** [comment]
Docker for Windows version 1.31.1 (10072) Channel Stable 94675c5

Fresh reboot and `docker ps -a` is empty.

~~~
docker run --name db -e MYSQL_ROOT_PASSWORD=mypassword -d -p 3306:3306 mariadb:latest;;
380d879a8dcb7870080904f6d7287e710b3360d8a37ccc4c10367d467e89e816
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: driver failed programming external connectivity on endpoint db (4921feb8813cdfcbc47096e0cc60cd4e8212ff214dd05675d36c582c533880e7): Error starting userland proxy: Bind for 0.0.0.0:3306 failed: port is already allocated.
~~~

Hmm, odd. 

~~~
$ netstat

Active Connections

  Proto  Local Address          Foreign Address        State
  TCP    10.0.75.1:445          10.0.75.2:49960        ESTABLISHED
  TCP    127.0.0.1:6059         dme:49786              ESTABLISHED
  TCP    127.0.0.1:6059         dme:49790              ESTABLISHED
  TCP    127.0.0.1:6059         dme:49791              ESTABLISHED
  TCP    127.0.0.1:6059         dme:49858              ESTABLISHED
  TCP    127.0.0.1:6059         dme:50344              ESTABLISHED
  TCP    127.0.0.1:6064         dme:49775              ESTABLISHED
  TCP    127.0.0.1:49670        dme:49671              ESTABLISHED
  TCP    127.0.0.1:49671        dme:49670              ESTABLISHED
  TCP    127.0.0.1:49676        dme:49677              ESTABLISHED
  TCP    127.0.0.1:49677        dme:49676              ESTABLISHED
  TCP    127.0.0.1:49680        dme:49681              ESTABLISHED
  TCP    127.0.0.1:49681        dme:49680              ESTABLISHED
  TCP    127.0.0.1:49682        dme:57130              ESTABLISHED
  TCP    127.0.0.1:49709        dme:49710              ESTABLISHED
  TCP    127.0.0.1:49710        dme:49709              ESTABLISHED
  TCP    127.0.0.1:49775        dme:6064               ESTABLISHED
  TCP    127.0.0.1:49784        dme:49785              ESTABLISHED
  TCP    127.0.0.1:49785        dme:49784              ESTABLISHED
  TCP    127.0.0.1:49786        dme:6059               ESTABLISHED
  TCP    127.0.0.1:49788        dme:49789              ESTABLISHED
  TCP    127.0.0.1:49789        dme:49788              ESTABLISHED
  TCP    127.0.0.1:49790        dme:6059               ESTABLISHED
  TCP    127.0.0.1:49791        dme:6059               ESTABLISHED
  TCP    127.0.0.1:49792        dme:49870              ESTABLISHED
  TCP    127.0.0.1:49858        dme:6059               ESTABLISHED
  TCP    127.0.0.1:49870        dme:49792              ESTABLISHED
  TCP    127.0.0.1:49872        dme:62522              ESTABLISHED
  TCP    127.0.0.1:50195        dme:50196              ESTABLISHED
  TCP    127.0.0.1:50196        dme:50195              ESTABLISHED
  TCP    127.0.0.1:50214        dme:50215              ESTABLISHED
  TCP    127.0.0.1:50215        dme:50214              ESTABLISHED
  TCP    127.0.0.1:50344        dme:6059               ESTABLISHED
  TCP    127.0.0.1:50350        dme:50349              TIME_WAIT
  TCP    127.0.0.1:50351        dme:50349              TIME_WAIT
  TCP    127.0.0.1:50352        dme:50349              TIME_WAIT
  TCP    127.0.0.1:50353        dme:50349              TIME_WAIT
  TCP    127.0.0.1:50354        dme:50349              TIME_WAIT
  TCP    127.0.0.1:57130        dme:49682              ESTABLISHED
  TCP    127.0.0.1:62522        dme:49872              ESTABLISHED
  TCP    172.25.120.153:49706   8.36.116.77:https      ESTABLISHED
  TCP    172.25.120.153:49726   ec2-107-20-247-251:http  ESTABLISHED
  TCP    172.25.120.153:49760   msnbot-65-52-108-187:https  ESTABLISHED
  TCP    172.25.120.153:49767   ec2-107-20-247-251:http  ESTABLISHED
  TCP    172.25.120.153:49773   ec2-107-20-247-251:http  ESTABLISHED
  TCP    172.25.120.153:49812   pac:8080               ESTABLISHED
  TCP    172.25.120.153:49833   sippoolbn11a04:https   ESTABLISHED
  TCP    172.25.120.153:49935   pac:8080               ESTABLISHED
  TCP    172.25.120.153:50181   bn3sch020010556:https  ESTABLISHED
  TCP    172.25.120.153:50250   pac:8080               ESTABLISHED
  TCP    172.25.120.153:50251   pac:8080               ESTABLISHED
  TCP    172.25.120.153:50281   pac:http               ESTABLISHED
  TCP    172.25.120.153:50289   pac:8080               ESTABLISHED
  TCP    172.25.120.153:50295   pac:8080               ESTABLISHED
  TCP    172.25.120.153:50298   pac:8080               ESTABLISHED
  TCP    172.25.120.153:50300   pac:8080               ESTABLISHED
  TCP    172.25.120.153:50306   pac:8080               ESTABLISHED
  TCP    172.25.120.153:50310   pac:8080               ESTABLISHED
  TCP    172.25.120.153:50311   pac:8080               ESTABLISHED
  TCP    172.25.120.153:50312   pac:8080               ESTABLISHED
  TCP    172.25.120.153:50324   pac:8080               ESTABLISHED
  TCP    172.25.120.153:50358   pac:8080               TIME_WAIT
  TCP    172.25.120.153:50359   pac:8080               TIME_WAIT
  TCP    172.25.120.153:50360   pac:8080               TIME_WAIT
  TCP    172.25.120.153:50361   pac:8080               TIME_WAIT
  TCP    172.25.120.153:50362   pac:8080               TIME_WAIT
  TCP    172.25.120.153:50363   pac:8080               TIME_WAIT
  TCP    172.25.120.153:50364   pac:8080               TIME_WAIT
  TCP    172.25.120.153:50365   pac:8080               TIME_WAIT
  TCP    172.25.120.153:50366   pac:8080               TIME_WAIT
  TCP    172.25.120.153:50367   pac:8080               TIME_WAIT
  TCP    172.25.120.153:50368   pac:8080               TIME_WAIT
  TCP    172.25.120.153:50369   pac:8080               TIME_WAIT
  TCP    172.25.120.153:50370   pac:8080               ESTABLISHED
  TCP    172.25.120.153:50371   a3034653:7680          ESTABLISHED
~~~

Here's the container info:

~~~
$ docker inspect mariadb
[
    {
        "Id": "sha256:7eca0e0b51c9351ea6a3639b3229432a7f7180dcc3a90ee47b9dd062fcfb520a",
        "RepoTags": [
            "mariadb:latest"
        ],
        "RepoDigests": [
            "mariadb@sha256:ed04792bb13c111cbd1743c2921ea6cf777051a7f7f51f7b134efec9af7afdad"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2017-01-18T22:56:27.059716635Z",
        "Container": "aa12a2a617f1937f100493d350a90c0f135bf36f3223cc70c2f9319732d1187c",
        "ContainerConfig": {
            "Hostname": "33842653d6db",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "3306/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOSU_VERSION=1.7",
                "GPG_KEYS=199369E5404BD5FC7D2FE43BCBCB082A1BB943DB \t430BDF5C56E7C94E848EE60C1C4CBDCDCD2EFD2A \t4D1BB29D63D98E422B2113B19334A25F8507EFA5",
                "MARIADB_MAJOR=10.1",
                "MARIADB_VERSION=10.1.21+maria-1~jessie"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"mysqld\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:5b399835461acba9c0fcc443742b2fe654fa4372ca0c1b7c743ccb5a5aa94bf3",
            "Volumes": {
                "/var/lib/mysql": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "DockerVersion": "1.12.6",
        "Author": "",
        "Config": {
            "Hostname": "33842653d6db",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "3306/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOSU_VERSION=1.7",
                "GPG_KEYS=199369E5404BD5FC7D2FE43BCBCB082A1BB943DB \t430BDF5C56E7C94E848EE60C1C4CBDCDCD2EFD2A \t4D1BB29D63D98E422B2113B19334A25F8507EFA5",
                "MARIADB_MAJOR=10.1",
                "MARIADB_VERSION=10.1.21+maria-1~jessie"
            ],
            "Cmd": [
                "mysqld"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:5b399835461acba9c0fcc443742b2fe654fa4372ca0c1b7c743ccb5a5aa94bf3",
            "Volumes": {
                "/var/lib/mysql": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 393461946,
        "VirtualSize": 393461946,
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:a2ae92ffcd29f7ededa0320f4a4fd709a723beae9a4e681696874932db7aee2c",
                "sha256:5e2dd548cf80a10e271323a4e01c7748d168e98c158b2a1047179bd19949f072",
                "sha256:04e79522ec95e423f22b88740aa93f25e1052cb9bf360574e61c71ac4faa5df9",
                "sha256:eee3050405773bbfbd7c9802ef057d05e2d584a28600dd41c4a1620c29b51b5e",
                "sha256:42bba2fd38be931fc6cc12e106991fea5fe175135112660363263f80c8bfe13d",
                "sha256:4a98927a42e7f261a95ef177a3942c1ec56525f39a02349da39e33e81509f423",
                "sha256:f105a959a5a87374499a8aecfcab961c6644ee36a4599a22a297cc0521c52398",
                "sha256:5998d192c04e2ad6b013d8a1ee79df9dc7facba1d410a4b7cc0ccfe4ec170cc8",
                "sha256:357269a70feb04e6f0f36a350658fea23e64d20634df0b9efba7f06b44250342",
                "sha256:0a9d67de106e01b502fd3b188735136fbcdb9239f5ad974360c6f757b270ae15",
                "sha256:6deeeb2ae94392a276f52c21495efe8de9d599e555fa952926517ae052e5bd48",
                "sha256:fa3d500672da208c9c30c2110821e76010c79a6f45fd73dd132d05ad37312bda"
            ]
        }
    }
]
~~~

Here's my dump file

 B64A3FC5-3D24-47A3-AC32-D089A367F5EE/2017-02-10_09-02-01

Even after reboot I cannot use MySQL on 3306 or Nginx on 80. I can only run these containers by choosing new ports (3307 and 81 respectively, for example).

**Comment by gabrielgarza** [comment]
I quit Docker, then restarted Docker, and it worked again. Make sure you don't have another running container or app listening on that port

**Comment by JamesEarle** [comment]
My main resolution was to restart docker and try again. I found out If I force it to kill **all** my containers using `docker kill $(docker ps -q)` ([taken from here](https://gist.github.com/evanscottgray/8571828) then this frees the desired port.

**Comment by Atomox** [comment]
OSX runs with a native Apache service. When I turned that off, this resolved my problem: `sudo apachectl stop`

**Comment by Stunner** [comment]
None of the aformentioned commands to remedy the issue worked for me (running on OS X 10.11.6). I had installed the latest version of Docker right after rebooting (client and server is now 17.03.1-ce) so maybe that was a potential culprit? Merely quitting the Docker app and reopening the app ended up working for me (pressing Restart from the drop down Docker menu did not work).

**Comment by bobmacneal** [comment]
Running OS X 10.12.3 and Docker version 17.03.1-ce, build c6d412e. 

None of the remedies posted work for me. 

This has happened periodically, but intermittently over the past year. Somehow it magically fixes itself after all kinds of dorking around and rebooting.

Currently I have the latest docker for mac. It seems Port 5432 is being to listened before I start the container. I suspect Docker itself is using an instance of Postgres for something.

**Comment by fewspider** [comment]
same ubuntu

**Comment by koenvanderdrift** [comment]
I'm on macOS 10.12.4, and have the same issue:

`Error starting userland proxy: Bind for 0.0.0.0:5432 failed: port is already allocated`

My Docker version is `Docker version 17.03.1-ce, build c6d412e`

After restarting Docker from the menu, I got it to work.  YMMV.

**Comment by qkquannguyen** [comment]
I had the same problem trying to start my MySQL Container on my Mac.

It said I couldnt use 0.0.0.0:3306 because something was using that port.

I tried reseting docker, etc etc and nothing worked.

Then I realized its much simpler... I went to my Systems Preferences and clicked on "MySQL" button that starts and stops your server. I stopped the server and created the container with no problems.

Cheers!

**Comment by BSWANG** [comment]
I meet this issue too, only restart docker daemon can workaround it.

**Comment by wenjianhn** [comment]
Related to https://github.com/docker/libnetwork/issues/1790

Below is a potential fix for the problem.
https://github.com/docker/libnetwork/pull/1794

**Comment by Umkus** [comment]
This just bit me as well. Site just went down for no apparent reason.
Even though all the required containers were up and running they didn't receive any traffic, judging by `docker stats`.
Restarting nginx from within container with `nginx -s reload` helped for a couple of seconds, then blackout again.
Restarting containers worsened things, since they couldn't start back up anymore because of the issue in the title of this page.

The process blocking the port:
```bash
# lsof -i TCP:443
COMMAND     PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
docker-pr 15500 root    4u  IPv6 66002910      0t0  TCP *:https (LISTEN)
```
Reloading the daemon seemed to fix this.

Versions:
```bash
# docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```bash
# docker-compose version
docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Comment by jks3462** [comment]
just restart your docker. That solves the problem.

**Comment by bdeluca** [comment]
That's an interesting work around but a fix would be better.

**Comment by Umkus** [comment]
@jks3462 That is exactly what I did in the end.

> Reloading the daemon seemed to fix this.

But this is a guaranteed downtime.

**Comment by i-bar** [comment]
Same problem here...
`docker ps` => no container running,
`docker ps -a` => no container is using the port

```
docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true

$ docker-compose version
docker-compose version 1.16.1, build 6d1ac219
docker-py version: 2.5.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

Restart didn't fix it...

**Comment by thaJeztah** [comment]
@i-bar do you have swarm mode enabled? Could it be a container/service is running on another node?

**Comment by i-bar** [comment]
@thaJeztah Ah, indeed there was another service that was using the port, I only searched among containers... I apologize for the false alarm.

**Comment by jinukp06** [comment]
Execute a docker ps command and check the default ports are already in use or not,if its used stop the container using docker stop command.There after try to up the container.
It should work,its work for me

**Comment by Raj5921** [comment]
i'm having an error when i try to restart my unbuntu, the ucrm_web_app_1 is not running. i try to start it using this command:  "sudo docker start ucrm_web_app_1" 
but i still can't get access back to the UCRM Web interface back. 
short note: i had access to the UCRM web interface when the installation finish, but when i shutdown the unbuntu and restart it, the web GUI won't show up back.  
any solution?..... i'll be willing to pay anyone to solve this issue, thank you!

**Comment by thaJeztah** [comment]
@Raj5921 Please don't hijack an issue with an unrelated issue; keep in mind that the GitHub issue tracker is not intended as a general support forum, but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

**Comment by SilvioBuss** [comment]
I solved problem in win10 running the docker with administrative permissions.

**Comment by dzek69** [comment]
Had the same on Windows 10. After restarting computer docker containers refused to get up because of already used ports which weren't actually used.

Restarting everything didn't help. I postponed update so I decided it could be a good time to update. After update & restart it started to working again.

**Comment by moisesosorio** [comment]
Error:

`zookeeper is up-to-date
Starting hadoop ... done
Starting kafka  ... done
spark_master is up-to-date
Recreating spark_worker ... error

ERROR: for spark_worker  Cannot start service worker: driver failed programming external connectivity on endpoint spark_worker (02dad6e63c0bd1ff3feda7651bbc242aef66fc99722db533c195c41b7903151b): Error starting userland proxy: Bind for 0.0.0.0:8081 failed: port is already allocated

ERROR: for worker  Cannot start service worker: driver failed programming external connectivity on endpoint spark_worker (02dad6e63c0bd1ff3feda7651bbc242aef66fc99722db533c195c41b7903151b): Error starting userland proxy: Bind for 0.0.0.0:8081 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.`

I chose my docker-compose

`   ports:
      - 8082:8082`

Now

`Removing spark_worker
Starting hadoop ...
zookeeper is up-to-date
Starting hadoop ... done
spark_master is up-to-date
Recreating 38bf2b4bbef2_spark_worker ... done`

**Comment by Savageman** [comment]
I didn't see my case there, so I though I'd comment in case anyone has it.

We use multiple `docker-compose` files and for one of our service, the same host port was bound twice to 2 different ports in the container which lead to this error.

**Comment by BourbonCreams** [comment]
This worked for me:

Find out the Container ID that is blocking the port with:
`sudo docker ps`

Then stop that container:
`sudo docker stop Container_ID    # i.e. sudo docker stop 4e9472154508`

**Comment by Jerbil** [comment]
This is also a problem in 18.03.1-ce on arm64v8 Linux.

```
Aug 29 09:04:03 ies06776429 dockerd[7168]: time="2018-08-29T09:04:03.254291019-04:00" level=error msg="fatal task error" error="starting container failed: driver failed programming external connectivity on endpoint relaxed_hopper.0cunn4m78963il59gio1m15jc.ffgzh8gm54cb3ms0vkf0cgpy6 (f9a29ea92630c8e18b5133a5462e9484b437ec012453773b3556ccac9fec92cc): Bind for 0.0.0.0:10514 failed: port is already allocated" module=node/agent/taskmanager node.id=0cunn4m78963il59gio1m15jc service.id=plidh5ek3ijgtz33k3a3jlan3 task.id=ffgzh8gm54cb3ms0vkf0cgpy6
Aug 29 09:04:05 ies06776429 dockerd[7168]: time="2018-08-29T09:04:05.949769269-04:00" level=error msg="fatal task error" error="starting container failed: driver failed programming external connectivity on endpoint friendly_pare.0cunn4m78963il59gio1m15jc.2lht7ejifnu39zsbagbnxzzrz (3c52d14c52267a117c1cbf900c05e9b3c058e20deea9453bc58d4a49608f2287): Bind for 0.0.0.0:8123 failed: port is already allocated" module=node/agent/taskmanager node.id=0cunn4m78963il59gio1m15jc service.id=zhxi5gczhgwykzoi9r4ba22sh task.id=2lht7ejifnu39zsbagbnxzzrz
```
Containers running as a service under docker swarm are continuously restarting because the port is unavailable:

```
vsys@ies06776429:~$ docker ps -a | grep -a syslog
7220a128a03e        registry.internal.vsys.io:5000/vsys/ies-syslog-proxy-arm64v8:1.0.3     "/usr/bin/syslog -t …"   4 seconds ago        Created                                          relaxed_hopper.0cunn4m78963il59gio1m15jc.l2uatjsjtawijh5ptzf0hgyzq
ce5af16ad03d        registry.internal.vsys.io:5000/vsys/ies-syslog-proxy-arm64v8:1.0.3     "/usr/bin/syslog -t …"   About a minute ago   Created                                          relaxed_hopper.0cunn4m78963il59gio1m15jc.zri7nm8zq9t4i2dzbd55nu4g5
153b4f9353a4        registry.internal.vsys.io:5000/vsys/ies-syslog-proxy-arm64v8:1.0.3     "/usr/bin/syslog -t …"   26 minutes ago       Created                                          relaxed_hopper.0cunn4m78963il59gio1m15jc.zybw9wdlel3noyo785fz7lk59
vsys@ies06776429:~$ docker ps -a | grep -a syslog
8c038720537e        registry.internal.vsys.io:5000/vsys/ies-syslog-proxy-arm64v8:1.0.3     "/usr/bin/syslog -t …"   Less than a second ago   Created                                          relaxed_hopper.0cunn4m78963il59gio1m15jc.hev2o0mus9n8g2iwozc855vlg
ce5af16ad03d        registry.internal.vsys.io:5000/vsys/ies-syslog-proxy-arm64v8:1.0.3     "/usr/bin/syslog -t …"   2 minutes ago            Created                                          relaxed_hopper.0cunn4m78963il59gio1m15jc.zri7nm8zq9t4i2dzbd55nu4g5
153b4f9353a4        registry.internal.vsys.io:5000/vsys/ies-syslog-proxy-arm64v8:1.0.3     "/usr/bin/syslog -t …"   27 minutes ago           Created                                          relaxed_hopper.0cunn4m78963il59gio1m15jc.zybw9wdlel3noyo785fz7lk59
```
The port is held by a rogue instance of docker-proxy:

```
vsys@ies06776429:~$ sudo netstat -tulp | grep 10514
tcp6       0      0 [::]:10514              [::]:*                  LISTEN      7585/docker-proxy

```

**Comment by nalini13795** [comment]
I was getting the same error tried removing all the docker images and the docker networks still it didn't work then I tried stopping the docker and then starting it again it worked for me  you can do so by 
`systemctl stop docker` --- to stop the docker
`systemctl status docker` --- to see the docker status
`systemctl start docker`  --- to again start the docker

**Comment by jacohend** [comment]
Getting this in `Docker version 18.06.1-ce, build e68fc7a` on `4.15.0-36-generic #39-Ubuntu`. Whenever I try to bring up docker-compose, I get an "address already in use" error, and lsof shows "docker-pr" holding those ports.

**Comment by NinioDev** [comment]
long story short.. if you are using windows, simply run this command in cmd (as admin):
`netstat -a -b`
then locate the program that allocate your port, kill it, and run it again, it will work.

**Comment by persinac** [comment]
FWIW - I had this issue with MySQL, went through some of the steps that the users here said to go through without any luck (including resetting docker to factory...). I was too focused on troubleshooting docker, and I found out that I had an instance of MySQL installed and running on my Mac outside of my container.

I ran the following command: 
`sudo launchctl unload -F /Library/LaunchDaemons/com.oracle.oss.mysql.mysqld.plist`

Then ran my docker-compose script and it loaded the MySQL instance just fine.

**Comment by hitzoft** [comment]
for those errors about port  is already allocated:

1.- run docker ps -a
2.- copy the container_id for the process that is running on the port
3.- run docker stop container_id

now run it again and it should work

**Comment by Ezwen** [comment]
I encounter the `port is already allocated` error usually when I reboot my debian server: docker gets automatically restarted, but docker-proxy somehow keep using some ports, and containers that require these ports fail to start as a result. My only solution then is to `systemctl restart docker` :(.

**Comment by BiancaBilteanu** [comment]
Hello!
Here's what I did and it worked:
run Windows PowerShell as administrator and write the following lines:

Get-NetTCPConnection -LocalPort 80 | Format-List
Get-Process -Id 4
net stop http

Let me know if it worked!

**Comment by pipesanta** [comment]
I had the same problem and this occurs maybe because you have containers already using this ports, to stop all containers running  so far use the following comand
`docker stop $(docker ps -a -q)`
or if sudo is required ...
`sudo docker stop $(sudo docker ps -a -q)`

**Comment by dzek69** [comment]
Guys,

THERE IS a chance to actually **not running anything** yet still not being able to start the service at some time if it was already started before. Repeating responsnes like "stop your containers" aren't helping here anymore - once was enough, maybe this could be a problem for somebody.

And I'm not talking about 80 or other popular port. My application was on hight port, like 4001. No other thing was using that port. Docker like reserved that port for itself (altough it wasn't visible as listening in the system) [?]. And after stopping container I wasn't able to start my app again.

I twice-verified that:
- no container is running
- no "native" app is blocking the port (it was "custom", high port anyway)
- I checked with `netstat` what's using my port (nothing)
- restarting PC did not help

I did not try to:
- reset Docker state to factory defaults

But what helped:
- updating Docker version (I had postponed update before)

So please: don't repeat all the same solutions. It's not helping. It's more like flood/spam, making it harder to find useful information in this thread to find out where the problem lies in the Docker itself.

**Comment by Ezwen** [comment]
Small erratum regarding my previous message: I actually still encounter the problem even with `"userland-proxy": false`.

**Comment by huytran147** [comment]
I just `docker system prune -a --volume` and restart docker. I'm using docker on Mac.

**Comment by hopeseekr** [comment]
Well, since I posted this in August 2016, I found out that the problem was running Docker on BTRFS. Once I reformatted a separate partition to ext4, I haven't experienced this problem since mid-2017.

**Comment by Mattie112** [comment]
We had the same issue on CentOS 7.7 with docker 19.03.4. What we did: shutdown server -> boot server -> docker gets automatically started -> several containers "died" due to our RabbitMQ not yet being ready. For any reason they where unable to start after that due to the port being in use. I "fixed" it by restarting docker. I could see that `docker-proxy` was holding a certain port but only on ipv6 ("tcp6" when doing `netstat -tulpn`)

**Comment by mdtomo** [comment]
This happens to me after restarting my machine and my Postgres container fails to start with docker-compose. Stopping all running containers does not free up the port. A work around I have is to kill the process occupying the port.

`sudo lsof -i :5433`
`COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME`
`docker-pr 3496 root    4u  IPv6  43751      0t0  TCP *:5433 (LISTEN)`
`sudo kill 3496`

**Comment by yatesjr** [comment]
This happened to me as well.. and after much frustration I finally found my cause. I was trying to connect IDEA to my remote docker host (via docker-machine for Windows), and during setup it installed a new systemd service file under:

`/etc/systemd/system/docker.service.d/10-machine.conf`

After removing that file and reinstalling docker it was back to business as usual :).

**Comment by SR-G** [comment]
I got the same problem but with a somehow different situation.

My HDD (system partition) from my docker host died. I rebuilt the server with a new HDD, and plugged back my dedicated docker disk (mounted on /var/lib/docker).
When i restarted 20 containers : 10 started perfectly, 10 failed with that "port is already allocated".
Being a fresh (re)install for the operating system + a docker daemon started for the first time (but with old /var/lib/docker/ content !), there is no way that 10 random ports could be already used.

Querying the ports give me : 

```
netstat -a -n -p|grep 3128
tcp6       0      0 :::3128                 :::*                    LISTEN      1035/docker-proxy   
```

**Comment by sric0880** [comment]
After `service docker restart`, things back to normal.

**Comment by jis0324** [comment]
Hello, I have similar problem.

**Comment by edisonagamba** [comment]
Sometimes You only need to write in your terminal:
_docker restart container-name_
That´s it!!!

**Comment by tricoos** [comment]
@edisonagamba This issue is about a specific issue when there is no container running on the port but docker-proxy keeps the port open. In that case restart doesn't help as there is no running container that's causing the issue!

**Comment by David-Lor** [comment]
I'd say I was able to have this problem sorted by running `service docker restart`, but NOT by running `service docker stop` then `service docker start`. I neither was able to solve the problem by removing and recreating the offending containers; neither by searching and killing the PIDs using the offending ports. However, it just may be pure luck that it worked by running `restart` instead of `stop` and `start`. This issue usually happens when I (re)start my server...

**Comment by Hillaryudechukwu** [comment]
After different attempts, I stopped the docker engine and restarted it. and that fixed it for me

**Comment by seyfer** [comment]
@andreas4all @hopeseekr what is this command to remove docker containers and files for Mac?

**Comment by 2sheds** [comment]
Like in some other cases listed, my problem started when computer was not shut down cleanly. Any of the solutions above didn't work (restarting docker.service, docker.socket, rebooting, rm'ing and purge'ing all containers and images etc.) - the port sprung up again as soon as docker daemon started. What solved it in my case, was to remove and recreate user-defined bridge which had the problematic port open.

**Comment by shubham-cmyk** [comment]
> This happens to me after restarting my machine and my Postgres container fails to start with docker-compose. Stopping all running containers does not free up the port. A work around I have is to kill the process occupying the port.
> 
> `sudo lsof -i :5433` `COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME` `docker-pr 3496 root 4u IPv6 43751 0t0 TCP *:5433 (LISTEN)` `sudo kill 3496`

How exactly you solved this I am also facing same issues.

**Comment by doodlebro** [comment]
> > This happens to me after restarting my machine and my Postgres container fails to start with docker-compose. Stopping all running containers does not free up the port. A work around I have is to kill the process occupying the port.
> > `sudo lsof -i :5433` `COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME` `docker-pr 3496 root 4u IPv6 43751 0t0 TCP *:5433 (LISTEN)` `sudo kill 3496`
> 
> How exactly you solved this I am also facing same issues. @mdtomo

This did not work for me either. service docker restart did, however.

**Comment by louisburton** [comment]
Realise this is an old issue - however is it not the same as what is described here: https://github.com/moby/libnetwork/issues/1790

That issue has 2 open PRs. Any chance the latter can be merged to address this issue? 🙏 
https://github.com/moby/libnetwork/pull/1794
https://github.com/moby/libnetwork/pull/1805

Running into this and is a shame to have a fix worked on but not in place.

**Comment by IgorOhrimenko** [comment]
Now 2023, latest docker version 24.0.2, but problem steal here:

```
level=warning msg="Failed to allocate and map port 18888-18888: Error starting userland proxy: listen tcp4 0.0.0.0:18888: bind: address already in use"
level=error msg="Handler for POST /v1.43/containers/9be0d193c3ba4f7a575bd47c8f1b653766ee1e6f1fc3b20876a096cd53246fa0/start returned error: driver failed programming external connectivity on endpoint data-1 (d6927593b0696cc18417f5d431064a1c79ed6c663a0566d3f5d90c827f027a57): Error starting userland proxy: listen tcp4 0.0.0.0:18888: bind: address already in use"
```
The commands:
```
lsof -i :18888
ss sport 18888 or dport 18888
```
do nothing, but container does not start.

Ather 2-3 or 39 minutes container start
