### ISSUE TITLE
"New state of 'nil' is invalid" when attaching to container, probably related to UTF-8

### ISSUE THREAD

**Issue by AndreKR** [docker/docker#22345]
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:13:28 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:38:59 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 7
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.9 MiB
Name: digitalocean
ID: AFWT:NTMS:3WR4:VOPE:JHGQ:D46Z:GR5R:GZ6N:4FUO:OUQP:A5JK:3JGG
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=digitalocean
```

**Steps to reproduce the issue:**

Be on Windows. Have an active machine. Then run:

```
docker run -it ubuntu:14.04 bash
apt-get update
apt-get install -y mc
locale-gen en_US.UTF-8
export LANG=en_US.UTF-8
mc
```

**Describe the results you received:**
`< / New state of 'nil' is invalid.`
and the connection is closed.

When re-attaching to the container, the same error happens.

**Describe the results you expected:**
Connection stays open, interacting with Midnight Commander is possible.

**Comment by HackToday** [comment]
is it related with windows terminal or other client terminal encoding setting ?
maybe you use non-unicode for remote system ?

**Comment by AndreKR** [comment]
If there is any encoding setting in the docker console, I am not aware of it. The encoding inside the container is fixed as per my steps to reproduce. Do you mean you tried to reproduce the issue and could not?

**Comment by RichardWright** [comment]
OHH WEIRD, we've just hit the same bug!

**Comment by QianJin2013** [comment]
+1

**Comment by QianJin2013** [comment]
I have an docker image `osexp2000/mecab`, 
when i run it in Mac OS X via VirtualBox, it's OK

```
docker run -u 1000:1000 -v /Users/q/tmp/japanese.txt:/tmp/japanese.txt  osexp2000/mecab shirosum -f /tmp/japanese.txt
```
when in Windows 7, i met the `New state of 'nil' is invalid` error.
```
docker run -u 1000:1000 -v /c/Users/q/tmp/japanese.txt:/tmp/japanese.txt  osexp2000/mecab shirosum -f /tmp/japanese.txt
```

I have checked the mapped `/tmp/japanese.txt` in container, it's garbled. 
I have converted the japanese.txt to UTF-8, but still failed. 

Unfortunately i forgot to capture the od dump, finally i run it inside docker-machine ssh terminal successfully.

**Comment by Schnitzel** [comment]
same issue, we have a bash prompt with an emoji in and connecting to the container is not possible because of it, when I remove the emoji, connecting works

**Comment by ericsage** [comment]
I ran into this issue today while attached to a docker container and running the npm install command to download packages for a project. This was the most up to date version on the Windows native build.

**Comment by junjiemars** [comment]
I had same issue on Windows 10 native Terminal, run into the container with 
```sh
docker exec -it centos-dev /bin/bash
```
Docker version: 1.12.0

**Comment by dimkk** [comment]
Windows 7, same bug here, solved it with CMD+R -> Git Bash -> eval $(docker-machine env default) -> docker attach [cont id] and all ok - looks like russian symbols to console.log made this issue

**Comment by fresheneesz** [comment]
I get this when i run `npm install fibers` - it exits my bash session without any other output...

**Comment by fresheneesz** [comment]
Redirecting to /dev/null (eg `npm install > /dev/null`) seems to be a workaround. Super annoying.

**Comment by thaJeztah** [comment]
This looks like a duplicate of https://github.com/docker/docker/issues/21323, and according to https://github.com/docker/docker/issues/21323#issuecomment-259332004 should be fixed in docker 1.13

ping @jhowardmsft PTAL

**Comment by jhowardmsft** [comment]
@thaJeztah Not sure what you're asking? 😇

**Comment by thaJeztah** [comment]
@jhowardmsft i couldn't find the exact change that fixed the linked issue; perhaps you know more, and can confirm if this issue should be fixed

**Comment by jhowardmsft** [comment]
Ah right, I get it now. Have verified just now that this is still an issue on docker master, but only when using the legacy (go-ansiterm emulated) console. Which means on any version of Windows before Windows 10, or Windows 10 with the console explicitly set to legacy mode.  MC does run just fine on a Windows 10 client (with console in native/default mode) pointing to a Linux daemon:

![image](https://cloud.githubusercontent.com/assets/10522484/21655127/86b68d80-d26d-11e6-9252-6437af0ed447.png)


_The longer story and some history:_

I'm not aware of anyone actively maintaining the legacy emulation code, and it's know that it doesn't support the full range of ANSI terminal emulation escape sequences. It really was only developed to  support basic functionality and left on the shelf after that. The reality is that most investment is being/has been made in improving the native console support built into Windows itself (a lot of that is required separately for LXSS, but docker takes advantage of it and was used during the development of the native console support to verify compatibility). MC, similar to nyancat, makes extensive use of escape sequences/ANSI features to draw/update the screen. When using the emulator, it looks like something is sending the state machine into a bad state having taken a brief look at the code.

Probably the best thing to do is to open this issue against https://github.com/Azure/go-ansiterm as that is the emulator repo used by docker client. However, as I mentioned above, I'm not aware of anyone actively maintaining it these days, or whether it makes sense for someone to really invest a significant amount of time working on it and bringing it up to the level needed to support mc (if indeed it can be done with the legacy console itself on Windows prior to Windows 10, hence the efforts may be futile, but I'm not sure). The alternate, of course, is to use a Windows 10 client.

For that reason, I'm closing this issue here.

**Comment by craigbrett17** [comment]
I'm still running into this issue when starting containers on Win 7 using docker toolbox (which launches MinGW)

**Comment by jhowardmsft** [comment]
Right. See my comment above. Note that support for Windows 7 ended in Jan 2015.

**Comment by craigbrett17** [comment]
Wish we'd been told that when we got advised to use docker... the whole team here uses Win 7 and now we're being bitten by this issue :(

**Comment by AndreKR** [comment]
@craigbrett17 Yeah, probably not so good advice after all. Docker will consistently refuse to implement most basic functionality claiming it's not the core's responsibility and refuse to fix the most fundamental bugs, claiming they only happen in special environments. And now apparently Windows 7 is a "special environment" for them. (For comparison I pulled up some analytics for some websites I'm maintaining and they show 64% of all Windows users still use Windows 7 or Windows 8. It's certainly not being phased out any time soon.)
Maybe you should look into Vagrant with Alpine or something like that.

**Comment by craigbrett17** [comment]
@AndreKR: I ended up deleting my comment, sorry! But I fully agree. Win7 is hardly a historic platform. No support for XP and Vista and old stuff like that I can understand, but 7 is a fairly stable and popular OS. Asking for an upgrade to 10 just because of a docker bug seems a bit much.

In  our case, we're running a node API using [Micro](https://github.com/zeit/micro). It's output message must include some non-ascii characters, and it stops the containers working on Windows. Bit of a bummer really. I've poked through the source just now and found a silent switch, so I'll use that to get around it for now. But still... it's a bug.

**Comment by pcouas** [comment]
Hi,
I have same error message on Windows10pro + dockerToolbox + virtualbox 5.1.22

**Comment by jhowardmsft** [comment]
With native console?

**Comment by pcouas** [comment]
Hi
It's bash

**Comment by jhowardmsft** [comment]
And if you run from native Powershell or cmd?

**Comment by pcouas** [comment]
Hi I run dockerFiles from Windows Desktop then i run dockerFiles images from docker

**Comment by pcouas** [comment]
Hi
when i make an cd /home/jhipster/generator_jhipster i see my windows directory with dockerfiles ???
Regards

**Comment by pcouas** [comment]
Hi
 jhowardmsft could you explain me if i coudl change dockerfiles for replacing bash jhipster by powershell or orherwise ? I search an solution

**Comment by saysmth** [comment]
Hi, @pcouas.
I have the same issue. Have you managed to solve it? I'd appreciate any help because I'm a newby in docker but need it.

**Comment by averri** [comment]
This issue is still present on Docker 17.0.4. Please see: https://github.com/docker/toolbox/issues/695
