### ISSUE TITLE
Docker and runc get out of sync

### ISSUE THREAD

**Issue by duglin** [docker/docker#22643]
Given this test program (test.sh):
```
set -ex
docker run -d --name test -ti ubuntu top
while true ; do
  docker pause test
  docker unpause test
done
```

If I let it run for a while, around 30 minutes or so, I eventually see this:
```
...
++ docker pause test
test
++ docker unpause test
test
++ true
++ docker pause test
test
++ docker unpause test
Failed to unpause container (test): Error response from daemon: Cannot 
unpause container aca8355a0051211267b5784b5e4cf32ef04c1681dd0d867234a8f5b7c921681d: 
rpc error: code = 2 desc = ""
```

Then trying to unpause that container manually, I then see:
```
$ docker unpause test
Failed to unpause container (test): Error response from daemon: Cannot 
unpause container aca8355a0051211267b5784b5e4cf32ef04c1681dd0d867234a8f5b7c921681d: 
rpc error: code = 2 desc = "container not paused\n"
```

Notice the "desc" field has something this time.

When I go into `runc` and manually pause the container and restart my script it all works ok. So it looks like the issue is just that `runc` and the engine got out of sync somehow, everything seems to still be in an ok state.

I wanted to dig a little deeper before I posted the issue but I keep getting distracted so I decided to go ahead in case someone else has the time to track this down before I get a chance to.

I'm using master (post 1.11) that's only a few days old.

ping @crosbymichael @LK4D4

**Comment by duglin** [comment]
some info:
runtime/container_linux.go - Resume():
```
b, err := exec.Command(c.runtime, args...).CombinedOutput()

where params are:
runtime: "docker-runc"
args: []string{"resume", "ebd2ff5424196466818c1bcaccdddb0c8cdfd6eec5c6eb7b9a0246dd1e995c47"}
```
returns:
```
b: []byte{}
err: &os.SyscallError{Syscall:"wait", Err:0xa}
```
And I believe 0xa error maps to ECHILD: 
`The calling process does not have any unwaited-for children. `
or
`The process specified by pid (waitpid()) or idtype and id (waitid()) does not exist or is not a child of the calling process. (This can happen for one's own child if the action for SIGCHLD is set to SIG_IGN. See also the Linux Notes section about threads.) `

**Comment by duglin** [comment]
Doing some quick testing, it appears that if we allow for this error condition, meaning ignore it in runtime/container_linux.go, then things still work as expected. 

Another interesting thing I noticed is that when we get an error during unpause we get back an error but the engine itself is ok.  But if we the error during pause then the daemon is hung, at least for cmds against that container.  Still investigating this one - could be a lock not being removed upon an error.

**Comment by duglin** [comment]
@crosbymichael my testing shows that allowing for this one error condition (meaning we get an ECHILD error from exec.CombinedOutput() ) to be treated as successful (and thus we ignore it) does seem to work. It leaves the daemon in a state that's consistent with what runc has.  What do you think about this solution?

**Comment by crosbymichael** [comment]
@duglin 

Actually, that error "should" be fixed from this pr

https://github.com/docker/containerd/pull/223

There was a race between the wait in combinedOutput and the reaper, if the reaper got it first when the system was under load then you get hte ECHILD from CombinedOutput.  Containerd is now updated in docker master so your specific issue around ECHILD should be resolved.

**Comment by duglin** [comment]
@crosbymichael excellent - and that would explain why I wasn't able to reproduce it in a generic golang testcase.  Testing now just to make sure the latest stuff doesn't still show the issue... then I'll close this.

**Comment by duglin** [comment]
Appears to be fixed!
