### ISSUE TITLE
Problem with Windows 10 nano container reusing port mapping: HNS failed with error : The object already exists..

### ISSUE THREAD

**Issue by StefanScherer** [docker/docker#23086]
**Output of `docker version`:**

```
PS C:\Users\vagrant\Desktop\hello-node> docker version
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   8e92415
 Built:        Thu May 26 17:08:34 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   8e92415
 Built:        Thu May 26 17:08:34 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
PS C:\Users\vagrant\Desktop\hello-node> docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 6
Server Version: 1.12.0-dev
Storage Driver: Windows filter storage driver
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null
Kernel Version: 10.0 14352 (14352.1002.amd64fre.rs1_release.160522-1930)
Operating System: Windows 10 Pro Insider Preview
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 2 GiB
Name: vagrant-10
ID: TLTO:YUSN:2MUU:HZTU:MRDE:ZYRA:2XWC:SP46:RCKW:HHMF:7UPJ:X7PU
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VMware Fusion VM running Windows 10 Insider 14352 + Docker installed as described in the [Windows 10 Quick Start](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_10) guide

**Steps to reproduce the issue:**
1. Start a detached container with a port mapping, eg -p 3000:3000
2. Kill the container
3. Remove the container
4. Build an updated container image (eg. after changing some code of your app)
5. Start another detached container with the same port mapping, -p 3000:3000

```
PS C:\Users\vagrant\Desktop\hello-node> docker run -d --isolation=hyperv -p 3000:3000 hello
4fd90ba44448d8760f2c5e6c21318f3731015d9155b434749ae45971901f2d5a
PS C:\Users\vagrant\Desktop\hello-node> docker inspect 4f | sls IPAddress

            "SecondaryIPAddresses": null,
            "IPAddress": "",
                    "IPAddress": "172.22.46.160",


PS C:\Users\vagrant\Desktop\hello-node> start http://172.22.46.160:3000
PS C:\Users\vagrant\Desktop\hello-node> notepad .\app.js
PS C:\Users\vagrant\Desktop\hello-node> docker kill 4f
4f
PS C:\Users\vagrant\Desktop\hello-node> docker rm -vf 4f
4f
PS C:\Users\vagrant\Desktop\hello-node> docker build --isolation=hyperv -t hello .
Sending build context to Docker daemon 9.728 kB
Step 1 : FROM stefanscherer/node-windows:4.4-nano-onbuild
# Executing 3 build triggers...
Step 1 : COPY package.json package.json
 ---> Using cache
Step 1 : RUN npm install
 ---> Using cache
Step 1 : COPY . .
 ---> 617528d4f110
Removing intermediate container 09280c736a15
Successfully built 617528d4f110
PS C:\Users\vagrant\Desktop\hello-node> docker run -d --isolation=hyperv -p 3000:3000 hello
```

**Describe the results you received:**

The new container could not be started as the port mapping seems to still exist.

```
PS C:\Users\vagrant\Desktop\hello-node> docker run -d --isolation=hyperv -p 3000:3000 hello
4f94d7f3a8b2e44dac87d36eb2fa7e2c1659b2a1b94ef74a689459b99b81ee2a
C:\Program Files\Docker\docker.exe: Error response from daemon: failed to create endpoint grave_volhard on network nat: HNS failed with error : The object already exists..
```

**Describe the results you expected:**

The new container should start with the specified port mapping.

**Additional information you deem important (e.g. issue happens only occasionally):**

```
PS C:\Users\vagrant\Desktop\hello-node> get-netnat


Name                             : H27886532-6bc6-448a-9aab-548a9d87bba5
ExternalIPInterfaceAddressPrefix :
InternalIPInterfaceAddressPrefix : 172.16.0.1/12
IcmpQueryTimeout                 : 30
TcpEstablishedConnectionTimeout  : 1800
TcpTransientConnectionTimeout    : 120
TcpFilteringBehavior             : AddressDependentFiltering
UdpFilteringBehavior             : AddressDependentFiltering
UdpIdleSessionTimeout            : 120
UdpInboundRefresh                : False
Store                            : Local
Active                           : True

PS C:\WINDOWS\system32> get-vmswitch

Name SwitchType NetAdapterInterfaceDescription
---- ---------- ------------------------------
nat  Internal
```

The same issue occurs if you boot your Windows 10 / Windows 2016 TP5 machine and try to start a new container with the same host port mapping.

**Comment by thaJeztah** [comment]
ping @jhowardmsft

**Comment by jhowardmsft** [comment]
@msabansal

**Comment by thaJeztah** [comment]
Doh! My bad, sorry

**Comment by pkanavos** [comment]
I had the same issue with a NAT left over from a previous Hyper-V installation. I only wanted to test docker so I just removed the NAT object with `Get-NetNat |Remove-NetNat`. The docker service run without a problem after that

**Comment by msabansal** [comment]
@StefanScherer  I am not able to reproduce this. Can you please share the dockerfile and I will try with that.

PS C:\Windows\system32> docker version
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   6f67c13
 Built:        Thu Apr 21 18:03:55 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   6f67c13
 Built:        Thu Apr 21 18:03:55 2016
 OS/Arch:      windows/amd64
PS C:\Windows\system32> docker info
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 2
Server Version: 1.12.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat transparent null
Kernel Version: 10.0 14300 (14300.1016.amd64fre.rs1_release_svc.160428-1819)
Operating System: Windows Server 2016 Standard Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 12
Total Memory: 2.046 GiB
Name: WIN-DBIMKMS015R
ID: GNLM:YWNC:YVG7:P3LE:F23H:LC7N:EXD2:DFXJ:BU2J:IVDI:ESLT:KAV4
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 31
 System Time: 2016-05-31T11:58:38.8918755-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure registries:
 127.0.0.0/8

PS C:\Windows\system32> docker run -d --isolation=hyperv -p 8080:8080 nanoserver:10.0.14300.1000 cmd
09c756ad5531e6038cba1aa991cf67113bc2f97431b5177fc09f87447631a054
PS C:\Windows\system32> docker ps
CONTAINER ID        IMAGE                        COMMAND             CREATED             STATUS              PORTS                    NAMES
09c756ad5531        nanoserver:10.0.14300.1000   "cmd"               15 seconds ago      Up 3 seconds        0.0.0.0:8080->8080/tcp   clever_goldstine
PS C:\Windows\system32> docker kill 09
09
PS C:\Windows\system32> docker run -d --isolation=hyperv -p 8080:8080 nanoserver:10.0.14300.1000 cmd
4e0d05b2e75c844328df2bae5288b34513be1df7d171ea60ccb46f682f53e272
PS C:\Windows\system32>

**Comment by StefanScherer** [comment]
@msabansal Indeed, running this in TP5 it works. Here is my walkthrough:

```
git clone https://github.com/StefanScherer/dockerfiles-windows
cd dockerfiles-windows\node-hello-express
docker build -t hello-express -f Dockerfile.core .
docker run -d -p 3005:3000 --name=hello hello-express
docker kill hello
docker rm -vf hello
docker run -d -p 3005:3000 --name=hello hello-express
docker kill hello
docker rm -vf hello
```

Killing and removing the container works multipe times, reusing the same host port.
But then I tried restarting the host while the container is running:

```
docker run -d -p 3005:3000 --name=hello hello-express
```

Now restart the host and login again

```
docker ps -a
docker rm -vf hello
docker run -d -p 3005:3000 --name=hello hello-express
34fb5d0aa760fc2b0261be7b2badd94c5129e78b18fd4620706181860d713017
C:\Windows\system32\docker.exe: Error response from daemon: failed to create endpoint hello on network nat: HNS failed with error : Failed to create endpoint.
```

In that situation the port mapping seems to still exist.

```
Get-NetNatStaticMapping


StaticMappingID               : 0
NatName                       : Hff60d1c3-4269-4019-bb2a-51b643014677
Protocol                      : TCP
RemoteExternalIPAddressPrefix : 0.0.0.0/0
ExternalIPAddress             : 0.0.0.0
ExternalPort                  : 3000
InternalIPAddress             : 172.18.113.186
InternalPort                  : 3000
InternalRoutingDomainId       : {00000000-0000-0000-0000-000000000000}
Active                        : True

StaticMappingID               : 7
NatName                       : Hff60d1c3-4269-4019-bb2a-51b643014677
Protocol                      : TCP
RemoteExternalIPAddressPrefix : 0.0.0.0/0
ExternalIPAddress             : 0.0.0.0
ExternalPort                  : 3005
InternalIPAddress             : 172.28.123.17
InternalPort                  : 3000
InternalRoutingDomainId       : {00000000-0000-0000-0000-000000000000}
Active                        : True
```

Oops, there's also another one.

**Comment by mabead** [comment]
Note thatmy version of dockerd is the following:
```
PS C:\Users\Administrator> dockerd -v
Docker version 1.12.0-dev, build 8e92415
```

**Comment by msabansal** [comment]
@stefanberger Thanks for reporting this. This is a problem limited to HyperV containers. In case of host crash we don't cleanup the preexisting data. I have fixed this for RTM.

**Comment by StefanScherer** [comment]
@msabansal Thank you. So should I close this issue as it is resolved outside this GH project?

**Comment by msabansal** [comment]
@stefanberger Yes please.

**Comment by msabansal** [comment]
@StefanScherer  Yes please

**Comment by ravindravv** [comment]
Hello all,

I built SQL Docker on my windows TP5 machine. then I run ps as mentioned below
PS C:\Windows\system32> docker run -p 1434:1433 --env sa_password=Password1 sqlexpress-rajat
from morning onwards the script running now I did break but its appears under lists after executing docker ps coomand
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
2576eb582df1        sqlexpress-rajat    "cmd /S /C 'powershel"   7 hours ago         Up 7 hours          0.0.0.0:1434->1433/tcp   adoring_yonath
So, NOw, I would like to check the status. could you please let me know, which command I have to use to know the status, is SQL docker installed perfectly or not? and let me know how to access the sql docker instance from SQL Management studio? PLEASE DO THE NEEDFUL

**Comment by artisticcheese** [comment]
It's still happening on RTM version if docker service is forcefully stopped. Dead mappings are still there.

**Comment by msabansal** [comment]
@artisticcheese Forcefully stopping docker service requires a system reboot for proper cleanup. This is because the containers are not cleaned up until reboot if docker doesn't clean them up

**Comment by artisticcheese** [comment]
Would not this be considered a bug in docker service in such cases? Proper windows service can and shall implement "OnShutdown" event to properly clean up resources. But because it's as usual stuff they pulled from UNIX (executable which is not real Windows service) it's not the case.

**Comment by camposdaniel21** [comment]
Just do it.

docker rm -v -f $(docker ps -qa)
