### ISSUE TITLE
Ingress network MTU is not configurable

### ISSUE THREAD

**Issue by jfbibeau** [docker/docker#24906]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 1.12.0-rc4
Storage Driver: devicemapper
 Pool Name: docker-253:1-176165418-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 987.5 MB
 Data Space Total: 107.4 GB
 Data Space Available: 40.39 GB
 Metadata Space Used: 1.88 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: active
 NodeID: bhhed9vizh7mjdxve52lup55v
 IsManager: Yes
 Managers: 1
 Nodes: 3
 CACertHash: sha256:bbc6df07cdf4131d1cf5153b2edc95244c4f7966fa59cb7b6ea11515731d15d7
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 5.671 GiB
Name: jf-a.localdomain
ID: FWPJ:7UNB:OLBN:23Y6:JFNN:ARRB:7MW6:RWIC:RG3P:I36U:RU47:3KE6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 45
 Goroutines: 139
 System Time: 2016-07-21T15:19:10.688153846-04:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMs on OpenStack

**Steps to reproduce the issue:**
1. Spin up 3 node swarm mode cluster, including specifying the --listen-addr param
2. Create 1 instance of tomcat: `docker service create --replicas 1 --publish 8080:8080 --name first_tomcat tomcat:8.0.36-jre8-alpine`
3. Create 1 instance of tomcat (publish a different port): `docker service create --replicas 1 --publish 8081:8080 --name second_tomcat tomcat:8.0.36-jre8-alpine`
4. `docker exec -it <container id of first_tomcat> sh`
5. `wget -O - second_tomcat:8080` (using wget as alpine doesn't come with curl, sorry haha)

**Describe the results you received:**
Try using service VIP:

```
/usr/local/tomcat # wget -O - second_tomcat:8080
Connecting to second_tomcat:8080 (10.255.0.7:8080)
<timeout>
```

Try using fixed IP:

```
/usr/local/tomcat # wget -O - tasks.second_tomcat:8080
Connecting to tasks.second_tomcat:8080 (10.255.0.8:8080)
<timeout>
```

**Describe the results you expected:**
Should be able to reach the other service's instance!

**Additional information you deem important (e.g. issue happens only occasionally):**
Always happens. Happens with both an in-house Tomcat container and the public Tomcat container.

Docker inspect of the second_tomcat container:

```
# docker inspect 2f539696a2e0
[
    {
        "Id": "2f539696a2e0a228558cd1b25286d6637c88c6f124b3bd72d2f1b8737574b878",
        "Created": "2016-07-21T19:15:30.727331171Z",
        "Path": "catalina.sh",
        "Args": [
            "run"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 17356,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2016-07-21T19:15:31.380976163Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:b0ca4b09f74556a997ab35150b7995cd722a3d5aa98255404684341b8a5cd6a9",
        "ResolvConfPath": "/var/lib/docker/containers/2f539696a2e0a228558cd1b25286d6637c88c6f124b3bd72d2f1b8737574b878/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/2f539696a2e0a228558cd1b25286d6637c88c6f124b3bd72d2f1b8737574b878/hostname",
        "HostsPath": "/var/lib/docker/containers/2f539696a2e0a228558cd1b25286d6637c88c6f124b3bd72d2f1b8737574b878/hosts",
        "LogPath": "/var/lib/docker/containers/2f539696a2e0a228558cd1b25286d6637c88c6f124b3bd72d2f1b8737574b878/2f539696a2e0a228558cd1b25286d6637c88c6f124b3bd72d2f1b8737574b878-json.log",
        "Name": "/second_tomcat.1.b5u1k8vbr9zs7rcouuscht0d6",
        "RestartCount": 0,
        "Driver": "devicemapper",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": [
            "810f39444f184440e75361a2739178539a7d1c40410dbd1a2451dbad82660e4e"
        ],
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Name": "devicemapper",
            "Data": {
                "DeviceId": "37",
                "DeviceName": "docker-253:1-192941280-3a2635d8b7239a777fe02df652422d11fa7bb403fe040871b0997660e6fa284b",
                "DeviceSize": "10737418240"
            }
        },
        "Mounts": [],
        "Config": {
            "Hostname": "2f539696a2e0",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/tomcat/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin",
                "LANG=C.UTF-8",
                "JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk/jre",
                "JAVA_VERSION=8u92",
                "JAVA_ALPINE_VERSION=8.92.14-r1",
                "CATALINA_HOME=/usr/local/tomcat",
                "TOMCAT_NATIVE_LIBDIR=/usr/local/tomcat/native-jni-lib",
                "LD_LIBRARY_PATH=/usr/local/tomcat/native-jni-lib",
                "TOMCAT_MAJOR=8",
                "TOMCAT_VERSION=8.0.36",
                "TOMCAT_TGZ_URL=https://www.apache.org/dist/tomcat/tomcat-8/v8.0.36/bin/apache-tomcat-8.0.36.tar.gz"
            ],
            "Cmd": [
                "catalina.sh",
                "run"
            ],
            "Image": "tomcat:8.0.36-jre8-alpine",
            "Volumes": null,
            "WorkingDir": "/usr/local/tomcat",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.swarm.node.id": "70vxyod2eboxcxd8a0wo0ds7n",
                "com.docker.swarm.service.id": "5d01jg29r59l7d9rs7o0y2u25",
                "com.docker.swarm.service.name": "second_tomcat",
                "com.docker.swarm.task": "",
                "com.docker.swarm.task.id": "b5u1k8vbr9zs7rcouuscht0d6",
                "com.docker.swarm.task.name": "second_tomcat.1"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "6e37aebafcb111ca2e1fae9e377e0ff9f60857be123c45851e69719aee285d80",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "8080/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/6e37aebafcb1",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "ingress": {
                    "IPAMConfig": {
                        "IPv4Address": "10.255.0.8"
                    },
                    "Links": null,
                    "Aliases": [
                        "2f539696a2e0"
                    ],
                    "NetworkID": "dzsgwnyjip8yqi4893da420md",
                    "EndpointID": "0146171a88c911c30d8fc54abf87e51672cb9f4c4ed4146ff2b701d3751c0913",
                    "Gateway": "",
                    "IPAddress": "10.255.0.8",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:0a:ff:00:08"
                }
            }
        }
    }
]
```

Docker service inspect output:

```
# docker service inspect second_tomcat
[
    {
        "ID": "5d01jg29r59l7d9rs7o0y2u25",
        "Version": {
            "Index": 1043
        },
        "CreatedAt": "2016-07-21T19:13:14.020746042Z",
        "UpdatedAt": "2016-07-21T19:13:14.029082747Z",
        "Spec": {
            "Name": "second_tomcat",
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "tomcat:8.0.36-jre8-alpine"
                },
                "Resources": {
                    "Limits": {},
                    "Reservations": {}
                },
                "RestartPolicy": {
                    "Condition": "any",
                    "MaxAttempts": 0
                },
                "Placement": {}
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "UpdateConfig": {},
            "EndpointSpec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 8080,
                        "PublishedPort": 8081
                    }
                ]
            }
        },
        "Endpoint": {
            "Spec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 8080,
                        "PublishedPort": 8081
                    }
                ]
            },
            "Ports": [
                {
                    "Protocol": "tcp",
                    "TargetPort": 8080,
                    "PublishedPort": 8081
                }
            ],
            "VirtualIPs": [
                {
                    "NetworkID": "dzsgwnyjip8yqi4893da420md",
                    "Addr": "10.255.0.7/16"
                }
            ]
        }
    }
]
```

Anything else you need or want me to try, let me know!

**Comment by jfbibeau** [comment]
Another additional data point:

first_tomcat ends up on node a (port 8080)
second_tomcat ends up on node c (port 8081)

On node a, if I curl localhost:8080 - it works fine, but curl localhost:8081 - times out.
On node c, if I curl localhost:8081 - it works fine, but curl localhost:8080 - times out.

So clearly it's the connection "across worker nodes" which doesn't work... How can I troubleshoot this further?

**Comment by thaJeztah** [comment]
Are the ports required for overlay networking open between your nodes? https://docs.docker.com/engine/swarm/swarm-tutorial/#/open-ports-between-the-hosts

**Comment by jfbibeau** [comment]
@thaJeztah Yup - wide open between all the worker nodes. firewalld is disabled on RHEL. Security group is wide open for udp and tcp on OpenStack.

**Comment by thaJeztah** [comment]
Alright, there were similar reports, and it's possible this was resolved on master; would you be able to try installing a master build? https://master.dockerproject.org.

**Comment by jfbibeau** [comment]
@thaJeztah You know what's crazy? If I try the *exact* same test with the `nginx:alpine` container, it actually works just fine, so I know my connectivity is sane.

Yet I consistently can 100% reproduce it with jre based containers like tomcat. This doesn't make any sense, it should be transparent to the containers, no?

**Comment by jfbibeau** [comment]
@thaJeztah I sure can, let me see if I can swap in those master binaries.

**Comment by thaJeztah** [comment]
I see you're using devicemapper, and the static binaries don't allow that by default, so you may need to add a daemon flag to override that check (I'm assuming this is a test setup, so shouldn't be problematic https://docs.docker.com/engine/reference/commandline/dockerd/#/devicemapper-options - the `dm.override_udev_sync_check`)

**Comment by jfbibeau** [comment]
I'm back! Using master binaries now, and still see the issue:

```
# docker version
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.3
 Git commit:   8cbe654
 Built:        Thu Jul 21 19:37:32 2016
 OS/Arch:      linux/amd64
```

Here's something interesting, I'm digging down more into the vxlan level and I can see that the request is going from node a to node c properly over vxlan. However, when the container replies I'm seeing an error in the tcpdump (`IP truncated-ip - 104 bytes missing!`):

```
16:53:02.056247 IP 192.168.11.12.38912 > 192.168.11.10.4789: VXLAN, flags [I] (0x08), vni 256
IP 10.255.0.8.8180 > 10.255.0.6.38579: Flags [P.], seq 165:171, ack 83, win 219, options [nop,nop,TS val 2157327 ecr 1306471283], length 6
16:53:02.056314 IP 192.168.11.12.38912 > 192.168.11.10.4789: VXLAN, flags [I] (0x08), vni 256
IP truncated-ip - 104 bytes missing! 10.255.0.8.8180 > 10.255.0.6.38579: Flags [.], seq 171:1569, ack 83, win 219, options [nop,nop,TS val 2157327 ecr 1306471283], length 1398
16:53:02.056322 IP 192.168.11.12 > 192.168.11.10: ip-proto-17
16:53:02.056324 IP 192.168.11.12.38912 > 192.168.11.10.4789: VXLAN, flags [I] (0x08), vni 256
IP truncated-ip - 104 bytes missing! 10.255.0.8.8180 > 10.255.0.6.38579: Flags [.], seq 1569:2967, ack 83, win 219, options [nop,nop,TS val 2157327 ecr 1306471283], length 1398
16:53:02.056326 IP 192.168.11.12 > 192.168.11.10: ip-proto-17
16:53:02.056328 IP 192.168.11.12.38912 > 192.168.11.10.4789: VXLAN, flags [I] (0x08), vni 256
IP truncated-ip - 104 bytes missing! 10.255.0.8.8180 > 10.255.0.6.38579: Flags [.], seq 2967:4365, ack 83, win 219, options [nop,nop,TS val 2157327 ecr 1306471283], length 1398
16:53:02.056331 IP 192.168.11.12 > 192.168.11.10: ip-proto-17
16:53:02.056333 IP 192.168.11.12.38912 > 192.168.11.10.4789: VXLAN, flags [I] (0x08), vni 256
IP truncated-ip - 104 bytes missing! 10.255.0.8.8180 > 10.255.0.6.38579: Flags [.], seq 4365:5763, ack 83, win 219, options [nop,nop,TS val 2157327 ecr 1306471283], length 1398
16:53:02.056335 IP 192.168.11.12 > 192.168.11.10: ip-proto-17
16:53:02.056338 IP 192.168.11.12.38912 > 192.168.11.10.4789: VXLAN, flags [I] (0x08), vni 256
IP truncated-ip - 104 bytes missing! 10.255.0.8.8180 > 10.255.0.6.38579: Flags [.], seq 5763:7161, ack 83, win 219, options [nop,nop,TS val 2157327 ecr 1306471283], length 1398
16:53:02.056340 IP 192.168.11.12 > 192.168.11.10: ip-proto-17
```

Could this be why the reply is never making it back to the source worker node?

**Comment by thaJeztah** [comment]
That's a good question; it does sound dodgy. I'll have to pass that on to the networking team, as this is about where my expertise ends :relaxed:

**Comment by jfbibeau** [comment]
Sounds good, thanks for the initial triage help. If anyone from the networking team needs more details let me know, it's pretty easy to reproduce.

**Comment by justincormack** [comment]
What does `ifconfig` say inside one of the containers?

**Comment by jfbibeau** [comment]
@justincormack sorry I don't have ifconfig in any containers I'm using for testing. I can try to rebuild a new container quickly with those utils if needed. However keep reading...

I got even further in my troubleshooting and this appears to be a fragmentation issue. This explains why I see the connection issue with tomcat (which has a huge index page), and not nginx (which has a small index page).

I can see in my wireshark snoop that with Tomcat's large index page, the packets get fragmented and don't appear to be ack'd properly on the other side properly... There are TCP re-transmissions.

However, if I changes the payload to be much smaller (ie I change my container's html page to be really small), network connectivity actually works now! My curl calls start working. So it appears to me to be a problem with moving large payloads (> mtu?) over the overlay network.

Let me know if you still need the ifconfig output.

**Comment by justincormack** [comment]
Yes I was just wondering what the mtu was on the vxlan interface...

**Comment by jfbibeau** [comment]
@justincormack here you go:
```
[root@fc48031f62c3 tmp]# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 10.255.0.6  netmask 255.255.0.0  broadcast 0.0.0.0
        inet6 fe80::42:aff:feff:6  prefixlen 64  scopeid 0x20<link>
        ether 02:42:0a:ff:00:06  txqueuelen 0  (Ethernet)
        RX packets 148  bytes 20093 (19.6 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 138  bytes 44708 (43.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.18.0.3  netmask 255.255.0.0  broadcast 0.0.0.0
        inet6 fe80::42:acff:fe12:3  prefixlen 64  scopeid 0x20<link>
        ether 02:42:ac:12:00:03  txqueuelen 0  (Ethernet)
        RX packets 19  bytes 1482 (1.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8  bytes 648 (648.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 116  bytes 41177 (40.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 116  bytes 41177 (40.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by justincormack** [comment]
Ok, that is what I would expect, it *should* be ok, but obvioosly isnt...

**Comment by justincormack** [comment]
Very suspicious though that the 1398 byte packet has 104 bytes truncated, thats 1502. Can you drop the MTU by 2 on both ends and see if it makes a difference?

**Comment by jfbibeau** [comment]
Any tips on how I can decrease the MTU from within the container?
```
[root@de410b01606a ROOT]# ifconfig eth0 mtu 1448 up
SIOCSIFMTU: Operation not permitted
SIOCSIFFLAGS: Operation not permitted
```

**Comment by justincormack** [comment]
You need to run with `--cap-add CAP_NET_ADMIN`

**Comment by jfbibeau** [comment]
`docker service create` doesn't seem to support that (yet?) :S  Anything else I can try?

**Comment by justincormack** [comment]
argh no it doesnt. You might be able to add it when you `docker exec` into the container, I can't remember (some options work, some dont)

**Comment by justincormack** [comment]
Or you can run another container in its net namespace: `docker run --net=container:xxxx debian bash` where xxxx is the ID of the container you want, then you get the same network interfaces.

**Comment by jfbibeau** [comment]
Worked with `--privileged` and `docker exec`.

Curl still doesn't work. tcpdump now shows `102 bytes missing` haha

**Comment by justincormack** [comment]
ah ok, so if you take 104 off it might work? Thats very low

**Comment by jfbibeau** [comment]
Yikes. Yep, that did it. I actually only had to change it on the "source" end. Left the other end to 1450 and now I can transfer the large payload.

```
[root@fc48031f62c3 tomcat]# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1346
        inet 10.255.0.6  netmask 255.255.0.0  broadcast 0.0.0.0
        inet6 fe80::42:aff:feff:6  prefixlen 64  scopeid 0x20<link>
        ether 02:42:0a:ff:00:06  txqueuelen 0  (Ethernet)
        RX packets 311  bytes 89553 (87.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 355  bytes 61076 (59.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by justincormack** [comment]
Ok well that makes no sense to me at all... it is much too low. Maybe you could update the issue title to reflect that it seems to be mtu related.

Ping @mrjana

**Comment by jfbibeau** [comment]
FWIW after a decrease to 1346 mtu, it worked for a few seconds I was able to transfer data, then the network dropped and getting "Connection refused" between the 2 services. 

I updated the title, hopefully @mrjana and shed some light on this.

**Comment by mavenugo** [comment]
@jfbibeau could it be specific to the openstack networking stack adding to the extra overhead ?
104 bytes seems way too high though. What is the openstack networking that you are using ?

**Comment by jfbibeau** [comment]
Hmm that also crossed my mind, but I thought it should be transparent to the VMs. I'm using out of the box Neutron.

**Comment by sprohaska** [comment]
I've observed this problem, too. Maybe the following helps.

It seems that swam mode partially ignores the `--mtu` flag when used with port mapping.

I'm running dockerd with `--mtu`.  A normal `docker run` respects the `--mtu` flag.  Example:

```
$ docker run -it alpine ifconfig
# ifconfig
eth0      Link encap:Ethernet  HWaddr ...
          UP BROADCAST RUNNING MULTICAST  MTU:1454  Metric:1
          ...
```

But with swarm, eth1 gets a different mtu:

```
$ docker service create -p 8000:80 --name test alpine ping -c 1000 google.com
$ docker exec -it $(docker ps -q) ifconfig
eth0      Link encap:Ethernet ...
          inet addr:10.255.0.6 ...
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          ...

eth1      Link encap:Ethernet ...
          inet addr:172.19.0.3 ...
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          ...

$ docker exec -it $(docker ps -q) route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         172.19.0.1      0.0.0.0         UG    0      0        0 eth1
...
```

The problem only appears when port mapping is used. The mtu for eth0 seems fine. But eth1 has the default mtu 1500. eth1 gets only created when port mapping is used.

**Comment by sprohaska** [comment]
The discussion around issue <https://github.com/docker/docker/issues/22028> may also be relevant.

**Comment by sprohaska** [comment]
@mavenugo It unfortunately doesn't work.  Even after reinstalling from scratch, I get the following error right after `docker swarm init`:

```
$ docker network rm docker_gwbridge
Error response from daemon: network docker_gwbridge has active endpoints
```

**Comment by sprohaska** [comment]
@mavenugo The error 'network docker_gwbridge has active endpoints' might be related to the `ingress-sbox`:

```
$ docker network inspect docker_gwbridge
[
    {
        "Name": "docker_gwbridge",
...
        "Containers": {
            "ingress-sbox": {
                "Name": "gateway_ingress-sbox",
                "EndpointID": "45d39152f5769a38d8dcdbd5429f45c471230c4d758f908adef71cfb994a9560",
                "MacAddress": "02:42:ac:13:00:02",
                "IPv4Address": "172.19.0.2/16",
                "IPv6Address": ""
            }
        },
...
]
```

Is there a trick to get rid of it?

**Comment by mavenugo** [comment]
@sprohaska yes. do it before initializing the swarm-mode.

**Comment by sprohaska** [comment]
@mavenugo Ok, seems to work; with all the other options, as discussed in <https://github.com/docker/docker/issues/24046>:

```
docker network create \
    -o com.docker.network.bridge.enable_icc=false \
    -o com.docker.network.bridge.name=docker_gwbridge \
    -o com.docker.network.driver.mtu=xxx \
    docker_gwbridge
```

**Comment by mavenugo** [comment]
@sprohaska cool. I know this is not ideal UX. But these are niche configuration requirements and this is the best workaround we have atm.

**Comment by sprohaska** [comment]
@mavenugo I'm still experiencing problems related to the routing mesh. I have a vague suspicion that they might be related to the `ingress` overlay network.

Is there a similar trick to tune the MTU of the `ingress` network?

The following discussions in libnetwork seem to be related:
<https://github.com/docker/libnetwork/issues/1021>,
<https://github.com/docker/libnetwork/pull/1349>

**Comment by aluzzardi** [comment]
I guess the issue is that ingress network is not configurable by the user, right? /cc @mrjana @mavenugo

**Comment by mavenugo** [comment]
@aluzzardi we dont have any options today to configure ingress network. That is infact a problem not just for MTU. But also for all other network settings. I think we should allow the user to remove the automatically created ingress network & create it again (or) have ability to change the network configuration.

**Comment by zcola** [comment]
docker network create \
>  -d overlay \
>     -o com.docker.network.driver.mtu=1418 \
>      ingress
Error response from daemon: ingress is a pre-defined network and cannot be created

how to define ingress mtu?

**Comment by thaJeztah** [comment]
also see https://github.com/docker/docker/issues/24220, maybe we should close one of these to keep the discussion on a single location; any preference @mavenugo ?

**Comment by mavenugo** [comment]
Yes. this is a dupe of #24220. @aboch is working on making the ingress network configurable for not just for subnet or mtu, but for all the configurable parameters that a docker network allows.

Closing it as a dupe of #24220
