### ISSUE TITLE
Error response from daemon "crypto/rsa: verification error" while accessing registry using auth and tls

### ISSUE THREAD

**Issue by ashishjain14** [docker/docker#25682]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.0
Storage Driver: devicemapper
 Pool Name: docker-202:1-149183-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 307.6 MB
 Data Space Total: 107.4 GB
 Data Space Available: 6.981 GB
 Metadata Space Used: 753.7 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-92-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.5 MiB
Name: xxxxxxxxxx
ID: AD22:WPB5:ZKMQ:4YW7:GYRI:JLQI:TOJD:YS5M:4NIR:3WNR:66HW:FOYF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Environment : AWS

**Steps to reproduce the issue:**
1. Set up a secure docker registry with auth & tls
2. Set up cessanta docker auth server 
3. Do Not set --insecure-registry option in DOCKER_OPTS
4. docker push or pull fails with the following error
Error response from daemon: Get https://xxxxxxxxxxxx:5000/v2/: Get https://xxxxxxxxxxx:5001/auth?account=admin&client_id=docker&offline_token=true&service=Docker+registry: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "xxxxxxxxxxx")
5. If I set up --insecure-registry it works without any issues

**Comment by thaJeztah** [comment]
This doesn't look like a bug, but a configuration issue, and a possible duplicate of many others; https://github.com/docker/docker/issues?utf8=✓&q=is%3Aissue%20%22unknown%20authority%22%20, which may contain useful information.

Please keep in mind that the GitHub issue tracker is not a support forum, but for tracking bugs in the docker engine codebase. For help on using docker, consider using;

- https://forums.docker.com
- the #docker IRC channel
- StackOverflow

I'll close this issue because of the above, but feel free to comment after I closed

**Comment by ashishjain14** [comment]
This seems to be a valid issue and I am suspecting docker client is unable to reorganize the certificate of auth server and hence the error. I am able to use openssl client to verify and it works fine. This seems more at the docker client end.

**Comment by thaJeztah** [comment]
Did you follow the instructions here to install the certificates in the right location; https://docs.docker.com/engine/security/certificates/ ?

**Comment by ashishjain14** [comment]
I am following the link since this is a self signed certificate. https://docs.docker.com/registry/insecure/#/using-self-signed-certificates
Yes the certificates are present in /etc/docker/certs.d/registryHost:registryPort/. I have also added the certificate to /usr/local/share/ca-certificates and have run update. 

This issue I suspect is coming from docker client unable to recoganize the auth server certificate. Once I enable a http connection with auth server I could see things working. The auth-server certificate is very well present in /usr/local/share/ca-certificates.

**Comment by thaJeztah** [comment]
ping @dmcgowan any other hints, or things to debug?

**Comment by dmcgowan** [comment]
Is the auth server and registry using the same certificate? If there is a certificate in `/etc/docker/certs.d/registryHost:registryPort/` but not the certificate needed for the auth server, then you will get a certificate issue.

**Comment by ashishjain14** [comment]
No both of them use different certificate. So you mean I should use the same set of certificate for auth server as well docker registry.

**Comment by dmcgowan** [comment]
@ashishjain14 they don't have to use the same certificate, but either the auth certificate needs to be placed in `/etc/docker/certs.d/registryHost:registryPort/` with the registry certificate, or the registry certificate needs to be removed from `/etc/docker/certs.d/registryHost:registryPort/` and added to the system certs. This should be fixed soon now that Golang has made it possible to create a cert pool made up of the system loaded certs and custom certs.

**Comment by ashishjain14** [comment]
@dmcgowan, @thaJeztah   thanks for your prompt help on this.
Somehow  I am unable to test this further because of some setup issues. We can close this off for now and I will reopen it if required.

**Comment by baisha1990** [comment]
I am still seeing this issue. My private registry is hosted on AWS. I am using self-signed certificate. I have copied the certs into the /etc/docker/certs.d/registryHost:resistryPort/. I am unable to login to the registry host 

Error response from daemon: Get https://registryIPaddress:registryPort/v2/: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "registryHost")

I tried to login using the registryHostName but I get this error - 

Error response from daemon: Get https://registryHost:registryPort/v2/: x509: certificate is not valid for any names, but wanted to match registryHost
