### ISSUE TITLE
Docker build cannot COPY the file to `/` directory

### ISSUE THREAD

**Issue by perigee** [docker/docker#25925]
Dear all,

I'm running docker inside an ubuntu (16.04) VM (vmware player), here is my docker version

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64
```

the output of `docker info`

```
Containers: 11
 Running: 1
 Paused: 0
 Stopped: 10
Images: 161
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 85
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-34-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.66 GiB
Name: ubuntu
ID: NAWG:CZGX:MIW2:B6XJ:FBKQ:5FCP:UP6W:JWLO:R63J:ZUSC:D4Y7:3VXJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

I have a simple `Dockerfile`

```
FROM alpine:3.4
COPY start.sh /
```

the `start.sh` is inside same folder as `Dockerfile`

when `docker build`, it shows:

```
Step 1 : FROM alpine:3.4
 ---> 4e38e38c8ce0
Step 2 : COPY start.sh /
stat /var/lib/docker/aufs/mnt/6379713235a0e7c418874544c96e44a92a142955b78251e8ccb8145b760db7ed/start.sh: no such file or directory
```

it worked before, while after installing `docker-machine` and `virtualbox`, it doesn't work, don't know if it related or not. Any idea, thank you in advance.

**Comment by perigee** [comment]
while copying to another path works, ex:

```
FROM alpine:3.4
COPY start.sh /usr/bin
```

it work.

**Comment by justincormack** [comment]
Ok, as it is working I will close this now.

**Comment by remram44** [comment]
I'm running into this exact issue:
```
Sending build context to Docker daemon 23.42 MB
Step 1 : FROM debian:jessie
 ---> 031143c1c662
Step 2 : COPY busybox /var/
 ---> 520b29bd5bb8
Removing intermediate container fe7af2ed4401
Step 3 : COPY busybox /
stat /var/lib/docker/aufs/mnt/b1dbf331f8bfd73770d946c06adc4d51670282559fe2364a7f7fe880516afffc/busybox: no such file or directory
```
Is latest Docker just f*ed up? Do we know which versions are affected?

**Comment by thaJeztah** [comment]
@remram44 I'm unable to reproduce your issue, but if you're still having this, please open a new issue with more information (at least the output of `docker version`, and `docker info`; possibly it's related to your system's configuration / kernel / aufs version

**Comment by remram44** [comment]
As far as I can see 1.11.2 is no longer affected. I had this with 1.11.1 on Ubuntu 16.04.

**Comment by thaJeztah** [comment]
Thanks @remram44

**Comment by GaretJax** [comment]
@remram44 just for clarity, where you referring to 1.11.2 or 1.12.2. I'm affected by this on 1.12.0 and 1.12.1, but not on 1.11.1. Did not try 1.12.2 yet.

**Comment by remram44** [comment]
Can't get the precise version now; it was the latest available from apt.dockerproject.org for Ubuntu 16.04 on September 20.

It was definitely one of 1.11.1 or 1.12.1.

**Comment by GaretJax** [comment]
Thanks. In that case it was very probably 1.12.1 :)

**Comment by thxmasj** [comment]
I have a similar issue. `COPY somefile /` works on Docker 1.12.1 running on RHEL 7.2, but it fails on Ubuntu 16.04.1 LTS.

Dockerfile:
```
FROM alpine:3.4
COPY somefile /
```
Output:
```
$ docker build .
Sending build context to Docker daemon  2.56 kB
Step 1 : FROM alpine:3.4
3.4: Pulling from library/alpine
c0cb142e4345: Already exists
Digest: sha256:ca7b185775966003d38ccbd9bba822fb570766e4bb69292ac23490f36f8a742e
Status: Downloaded newer image for alpine:3.4
 ---> ee4603260daa
Step 2 : COPY somefile /
stat /var/lib/docker/aufs/mnt/79778e284af03f5a64dba7579287f6802a0a59c154848e476e21d423c25c7eb8/somefile: no such file or directory
```

@justincormack, Reopen, please?

**Comment by zigarn** [comment]
I can reproduce too, but only some times.
The problem is only when copying to `/`

```Dockerfile
# Dockerfile
FROM scratch
COPY file /
```

```bash
$ ls -l
total 4
-rw-rw-r-- 1 ubuntu ubuntu 25 Oct 11 09:08 Dockerfile
-rw-rw-r-- 1 ubuntu ubuntu  0 Oct 11 09:07 file

$ docker build .
Sending build context to Docker daemon  2.56 kB
Step 1 : FROM scratch
 ---> 
Step 2 : COPY file /
stat /var/lib/docker/aufs/mnt/324804e5114539210d4a34a5f77fee45ebda8b01a39ba0ce8f2e4b915f035a43/file: no such file or directory
```

```bash
$ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```

```bash
$ docker info
Containers: 24
 Running: 3
 Paused: 0
 Stopped: 21
Images: 27
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 77
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.675 GiB
Name: base
ID: QFVU:KVKZ:JBFV:2MAX:NLPK:TMDM:72K2:F2KU:7RHE:XZK2:X27L:23W4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

```bash
$ uname -a
Linux base 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
```

I can confirm that the problem is solved by restarting the daemon:

```bash
$ sudo service docker restart

$ docker build .
Sending build context to Docker daemon  2.56 kB
Step 1 : FROM scratch
 ---> 
Step 2 : COPY file /
 ---> 97b1524cb66b
Removing intermediate container f25ef8d2b715
Successfully built 97b1524cb66b
```

**Comment by thaJeztah** [comment]
Let me reopen this issue; if I see correctly, everyone is on aufs? If you're not on aufs please comment

**Comment by thaJeztah** [comment]
ping @anusha-ragunathan @dmcgowan PTAL perhaps you have some thoughts as to what may cause this

**Comment by AleksandrIakhnev** [comment]
@thaJeztah this issue can appear on overlay driver  as well.

**Comment by dastrasmue** [comment]
I had the same issue with 1.12.1 on Ubuntu 16.04.
Here was the Dockerfile to reproduce the error:
```
FROM ubuntu:14.04
COPY start.sh /start.sh
```

Updating to 1.12.2 fixed it.

**Comment by remram44** [comment]
A lot of us fixed the issue by upgrading (or in my case downgrading) while really restarting the daemon might have made the problem disappear. @zigarn confirmed that this doesn't happen every time and that restarting the daemon usually fixes it.

**Comment by pchico83** [comment]
@thaJeztah could these errors be noise because the original errors is lost? 
https://github.com/docker/docker/pull/27075

**Comment by thaJeztah** [comment]
@pchico83 hm, I don't know, @tonistiigi do you think that's plausible?

**Comment by tonistiigi** [comment]
@thaJeztah Yes, I helps to get the correct error.

**Comment by pchico83** [comment]
I collected the docker daemon logs when building a small dockerfile that failed this this issue:
```
FROM ubuntu
COPY start.sh /
ENTRYPOINT ["/start.sh"]
```
Logs are:
```
time="2016-10-19T19:54:29.636920520Z" level=debug msg="Calling POST /v1.23/build?buildargs=%7B%7D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&rm=1&shmsize=0&ulimits=null" 
time="2016-10-19T19:54:29.636959658Z" level=debug msg="Client and server don't have the same version (client: 1.11.2, server: 1.12.0)" 
time="2016-10-19T19:54:29.650847062Z" level=debug msg="Increasing token expiration to: 60 seconds" 
time="2016-10-19T19:54:29.662304818Z" level=debug msg="Trying to pull ubuntu from https://registry-1.docker.io v2" 
time="2016-10-19T19:54:29.708070016Z" level=debug msg="Increasing token expiration to: 60 seconds" 
time="2016-10-19T19:54:29.785920017Z" level=debug msg="Pulling ref from V2 registry: ubuntu:latest" 
time="2016-10-19T19:54:29.786843745Z" level=debug msg="pulling blob \"sha256:6bbedd9b76a496816d86a0af731ea984f40467ef8fb23be752f801cb80436ac6\"" 
time="2016-10-19T19:54:29.787031340Z" level=debug msg="pulling blob \"sha256:fc19d60a83f11bbddc7bd2dfca6095b49100314bfde61d83729112a6b6e11d48\"" 
time="2016-10-19T19:54:29.787165884Z" level=debug msg="pulling blob \"sha256:de413bb911fd848383ef2e5068a42c258c898d6ee869fb441fb2391eb327b576\"" 
time="2016-10-19T19:54:29.885955549Z" level=debug msg="Downloaded fc19d60a83f1 to tempfile /var/lib/docker/tmp/GetImageBlob107596622" 
time="2016-10-19T19:54:29.886004825Z" level=debug msg="pulling blob \"sha256:2879a7ad31445fe2cea410b8ba76704003c11ee05c0a4d32d1113009ea1a1aae\"" 
time="2016-10-19T19:54:29.888180343Z" level=debug msg="Downloaded de413bb911fd to tempfile /var/lib/docker/tmp/GetImageBlob187930709" 
time="2016-10-19T19:54:29.888215537Z" level=debug msg="pulling blob \"sha256:668604fde02e75dddb4b44c80d4ce20baaac4832c41c3a945f4a236cd7d2f164\"" 
time="2016-10-19T19:54:29.961275372Z" level=debug msg="Downloaded 668604fde02e to tempfile /var/lib/docker/tmp/GetImageBlob451073359" 
time="2016-10-19T19:54:29.972525272Z" level=debug msg="Downloaded 2879a7ad3144 to tempfile /var/lib/docker/tmp/GetImageBlob858733488" 
time="2016-10-19T19:54:31.974779822Z" level=debug msg="Downloaded 6bbedd9b76a4 to tempfile /var/lib/docker/tmp/GetImageBlob160963307" 
time="2016-10-19T19:54:31.975354000Z" level=debug msg="Start untar layer" 
time="2016-10-19T19:54:36.813168159Z" level=debug msg="Untar time: 4.837809149s" 
time="2016-10-19T19:54:36.813221865Z" level=debug msg="Failed to unmount 463a5057ea65bc01bd8fe7e5e3164f47f829f80c745fdca7567f069a69ae4218 overlay: no such file or directory" 
time="2016-10-19T19:54:36.813250305Z" level=debug msg="Applied tar sha256:c854e44a1a5a22c9344c90f68ef6e07fd479e8ce1030fe141e3236887f1a4920 to 463a5057ea65bc01bd8fe7e5e3164f47f829f80c745fdca7567f069a69ae4218, size: 127133103" 
time="2016-10-19T19:54:37.036672442Z" level=debug msg="Applied tar sha256:8ba4b4ea187c5ea58c11ee99bbc159b88b303c290b18c2220c9b477f4427bb9e to 34758f767fb2321d7a3c51a27c95b40e5548216523f8a0159b45e1983459e70e, size: 745" 
time="2016-10-19T19:54:37.247664367Z" level=debug msg="Applied tar sha256:46c98490f5756634de1b1b9ed02a9fae2732984049f4f8fa182959fea924a45c to 31b84903a2d867568b35c7f3ed19c9aa310d350735c6b039bd1c99870f1eccf8, size: 0" 
time="2016-10-19T19:54:37.463045101Z" level=debug msg="Applied tar sha256:1633f88f8c9fa73c5c0c24f314e81b10dda6c310d41fb87eba02421e1652f6dc to 27294d7a35d65a385ed68568e8e83a70fc53efad09a106b71c06642102a46e49, size: 1895" 
time="2016-10-19T19:54:37.720980975Z" level=debug msg="Applied tar sha256:0e20f4f8a593705219d1b3c5b1d2f7b8664eb04d706e99add87adbdcceea4a9f to 50e349d508338c7e2c17474eca4166862d4790691a1bc0bbb40d128cbb80cfd7, size: 7" 
time="2016-10-19T19:54:37.753010789Z" level=debug msg="[BUILDER] Cache miss: [/bin/sh -c #(nop) COPY file:9297424bd6a8758ac359d9a57b49678c9280dcb6bf7d6c07af7635e484e66f60 in / ]" 
time="2016-10-19T19:54:37.778073235Z" level=debug msg="container mounted via layerStore: /var/lib/docker/overlay/2955cf282c3aa3abb72fc25642ca52cd64d66635e65e4ebc4ad3ac50a3cfd142/merged" 
time="2016-10-19T19:54:37.784781810Z" level=debug msg="container mounted via layerStore: /var/lib/docker/overlay/2955cf282c3aa3abb72fc25642ca52cd64d66635e65e4ebc4ad3ac50a3cfd142/merged" 
time="2016-10-19T19:54:37.784819488Z" level=debug msg="CopyFileWithTar(/var/lib/docker/tmp/docker-builder294517436/start.sh, /var/lib/docker/overlay/2955cf282c3aa3abb72fc25642ca52cd64d66635e65e4ebc4ad3ac50a3cfd142/merged/start.sh)" 
time="2016-10-19T19:54:37.801199233Z" level=debug msg="Failed to unmount 2955cf282c3aa3abb72fc25642ca52cd64d66635e65e4ebc4ad3ac50a3cfd142 overlay: invalid argument" 
```

**Comment by gopinatht** [comment]
Guys, I see the issue is closed and some implication that there is a fix for it in 1.12.3. Am I correct? Is 27609 the fix? If so, is there a release date for 1.12.3?

**Comment by thaJeztah** [comment]
@gopinatht yes, there's a patch in 1.12.3 that hopefully resolves this issue; a release candidate for 1.12.3 will be released later today, or tomorrow, we don't have a definitive date for 1.12.3 "GA"

**Comment by gopinatht** [comment]
Thanks @thaJeztah! I will wait for the patch to become available.

**Comment by ryansanford** [comment]
@thaJeztah Is it known what version introduced this issue? I'd like to downgrade to the latest version not impacted until this fix is in a "GA" release. Thanks.

**Comment by udp** [comment]
Same problem for me on Xubuntu 16.04.  Fixed with `sudo systemctl restart docker`.

**Comment by shotor** [comment]
Same error using `docker 1.12.5` and `Ubuntu 16.04` with `aufs`.

Restarting docker service has no effect. Docker image builds fine elsewhere.

**Comment by tonistiigi** [comment]
@shotor Can you put together a new reproducer script and full report data(you can create a new issue as well). We are quite confident that we traced some of the previous reports to storage dir having wrong mount propagation that was fixed with #27609 so this may be something quite different. Please include `cat /proc/$(pgrep dockerd)/mountinfo` as well when you get the issue.

**Comment by shotor** [comment]
@tonistiigi: Thanks for your response.

Just to be sure, do you mean: Create and run a new Dockerfile including the command you posted. Then create an issue with the entire output?

**Comment by tonistiigi** [comment]
@shotor No, create a new issue with your own reproducing steps. That includes `COPY ./dist /var/www` but this line itself doesn't seem to be enough to cause the problem. Include daemon logs and output of `docker version && docker info` with your report and also include the output of `cat /proc/$(pgrep dockerd)/mountinfo`. This command lists all the mountpoints visible to the docker daemon process. Previous reports were traced to a wrong propagation on some of the mounts so this debug info lets us see if the problem you are seeing may be related or not.

**Comment by shotor** [comment]
Okay, I can run with that. Cheers!

**Comment by jeremymills** [comment]
Same error Ubuntu `16.04` and docker `1.12.*`

Restarting docker didn't solve anything, downgrading docker-machine version didn't solve anything. Seems the `COPY` command is not copying any files running:

```sh
WORKDIR /mydir
COPY . .
```

**Comment by tugrulcan** [comment]
Same issue when I try to copy or add with multiple lines. Fixed with trying add&copy lines single.

**Comment by porridge** [comment]
Started happening here, apparently once the number of concurrent `docker build`s increased a little.

```
Step 3/8 : COPY . /some/path/does/not/exist/yet
time="2017-03-07T15:01:46Z" level=info msg="device or resource busy" 
```

interestingly, `level` is info, not `fatal`

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:57:47 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:57:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by mlaventure** [comment]
@porridge this seems to be a different issue since you're not copying to `/` but an arbitrary non-existent one. Do mind opening a new one with reproduction steps if you have any?

Thanks!

**Comment by porridge** [comment]
Sounded like
https://github.com/docker/docker/issues/25925#issuecomment-270045906 is
similarly non-root, but OK, I can file a new one if it happens again for me.
Any debugging flags I can set beforehand?

**Comment by mlaventure** [comment]
@porridge please do, it'd be easier to follow, this thread is already quite long.

If you can put your daemon in debug mode so the log can be more verbose, it'd be helpful.

**Comment by ralfthewise** [comment]
I believe I was having this same problem and specifying the full path for the destination fixed it for me.  For example changing:
```
COPY api api
```
to:
```
COPY api /api
```
did the trick

**Comment by porridge** [comment]
FTR, I think in my case a reboot or docker service restart helped. :-/

**Comment by FedericoCaldas** [comment]
Having a similar issue with Docker Toolbox on Windows on docker build:

```
Step 5/6 : COPY ${source:-obj/Docker/publish} .
COPY failed: stat /mnt/sda1/var/lib/docker/tmp/docker-builder562750387/obj/Docker/publish: no such file or directory
```

**Comment by thaJeztah** [comment]
@FredericoCaldas doesn't look related; looks like you tried specifying a host path, not a path local to the build context.

In any case, if you still suspect there's a bug, please open a new issue instead

**Comment by thaJeztah** [comment]
@FedericoCaldas might be worth opening an issue with them (Visual Studio); sounds like a bug.

I am locking the conversation on this issue; the original issue was resolved; if you're running into this with an up-to-date install, please open a new issue with details, so that it doesn't go unnoticed (you can refer / link to this issue if you think it's related).
