### ISSUE TITLE
docker daemon in swarm mode is crashing periodically

### ISSUE THREAD

**Issue by vitan** [docker/docker#27486]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

docker 1.12 in swarm mode is crashing periodically

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

docker exited unexpected

**Describe the results you expected:**

docker daemon running constantly

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

Exec command is forbidden for me, but I am sure the server version is
 
docker 1.12.1

**Output of `docker info`:**

I have to upload a snapshot for some reason.

![b03bbc34-9ccd-4887-9d6d-97d6f7724351](https://cloud.githubusercontent.com/assets/1930578/19471960/dd16a92e-9557-11e6-8cc0-76e016c7b860.jpg)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical CentOS 7.2  

**Logs triggered** 

http://pastebin.com/s71CxSaq

**Comment by justincormack** [comment]
Judging from the trace:

```
Oct 14 12:56:41 DKRMSTT03 dockerd: fatal error: concurrent map read and map write
Oct 14 12:56:41 DKRMSTT03 dockerd: goroutine 2743747 [running]:
Oct 14 12:56:41 DKRMSTT03 dockerd: runtime.throw(0x1f42fa0, 0x21)
Oct 14 12:56:41 DKRMSTT03 dockerd: /usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc83286eca0 sp=0xc83286ec88
Oct 14 12:56:41 DKRMSTT03 dockerd: runtime.mapaccess2_faststr(0x16e7480, 0xc82da41d40, 0xc835524e80, 0x40, 0xc82043e960, 0xc82a1cc2c0)
Oct 14 12:56:41 DKRMSTT03 dockerd: /usr/local/go/src/runtime/hashmap_fast.go:307 +0x5b fp=0xc83286ed00 sp=0xc83286eca0
Oct 14 12:56:41 DKRMSTT03 dockerd: github.com/docker/libnetwork.(*sandbox).isEndpointPopulated(0xc83dafa1e0, 0xc83376fa20, 0x1)
Oct 14 12:56:41 DKRMSTT03 dockerd: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/libnetwork/sandbox.go:967 +0x85 fp=0xc83286ed50 sp=0xc83286ed00
Oct 14 12:56:41 DKRMSTT03 dockerd: github.com/docker/libnetwork.(*network).rmLBBackend.func1(0x7f6b24c650e8, 0xc83376fa20, 0x0)
Oct 14 12:56:41 DKRMSTT03 dockerd: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/libnetwork/service_linux.go:301 +0xd1 fp=0xc83286ee38 sp=0xc83286ed50
Oct 14 12:56:41 DKRMSTT03 dockerd: github.com/docker/libnetwork.(*network).WalkEndpoints(0xc82849c780, 0xc83286eed8)
Oct 14 12:56:41 DKRMSTT03 dockerd: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/libnetwork/network.go:937 +0xb5 fp=0xc83286eec8 sp=0xc83286ee38
```

This looks like a libnetwork hash map access bug. It is possible it was fixed in 1.12.2 @aboch @mavenugo any ideas if you have seen this before?

**Comment by mavenugo** [comment]
I have never seen this before. the offending code is introduced via https://github.com/docker/libnetwork/pull/1269 which is present prior to 1.12.0 and is not modified since. Idk if 1.12.2 is going to solve this. but @mrjana might know better.

**Comment by xiaods** [comment]
https://github.com/kubernetes/minikube/issues/368

**Comment by mrjana** [comment]
Looks like delete from the map when we cleanup is mistakenly happening outside the lock and this is the cause of the problem: https://github.com/docker/libnetwork/blob/master/sandbox.go#L851

And this is still the case so yeah it is not fixed in 1.12.2. Will fix it.

**Comment by mrjana** [comment]
Created libnetwork PR https://github.com/docker/libnetwork/pull/1512 to fix this.
