### ISSUE TITLE
Containerd unable to save during Packer docker image build within docker container

### ISSUE THREAD

**Issue by cprenzberg** [docker/docker#28962]
Hi,

I already asked this on the packer project page but I will also ask here since this seems to be a very docker-centric problem. I am trying to use packer inside a docker container to build docker images as follows:

```
cat > bla.sh<<EOL
#!/bin/bash -xe


echo "Hello folks"

exit 0
EOL

chmod +x bla.sh

cat > manifest.json<<EOL
{
  "builders":[
      {
         "commit":true,
         "image":"ubuntu:14.04.5",
         "type":"docker"
      }
   ],
   "provisioners":[
      {
         "type":"shell",
         "scripts":[
            "bla.sh"
         ]
      }
   ],
   "post-processors":[
      [
         {
            "only":[
               "docker"
            ],
            "tag":"0.0.1",
            "type":"docker-tag",
            "repository":"docker-registry.example.com/ubuntu-base"
         },
         {
            "login_password":"foo",
            "login_email":"team@example.com",
            "only":[
               "docker"
            ],
            "login_server":"https://docker-registry.example.com",
            "login_username":"foo",
            "login":true,
            "type":"docker-push"
         }
      ],
      [{
            "only":[
               "docker"
            ],
            "tag":"latest",
            "type":"docker-tag",
            "repository":"docker-registry.example.com/ubuntu-base"
         },
         {
            "login_password":"foo",
            "login_email":"team@example.com",
            "only":[
               "docker"
            ],
            "login_server":"https://docker-registry.example.com",
            "login_username":"foo",
            "login":true,
            "type":"docker-push"
         }
      ]
   ]
}
EOL

packer validate manifest.json &&  packer build -color=false manifest.json
```

However the provisioning gets stuck when trying to provision *bla.sh*. 

I run docker inside the container by mounting the host's /var/run/docker.sock into the container and just using the docker binaries available from the docker release repositories as follows:

```
docker run -it -v /var/run/docker.sock:/var/run/docker.sock --privileged --dns 10.10.12.6 -w /home/jenkins-agent/ docker-registry.example.com/jenkins-agent:0.0.7 bash
```

I can therefore push and pull and do all docker stuff within the container without problems. Here is the regular output from attempting the packer build specified in manifest.json from above

```
Template validated successfully.
docker output will be in this color.

==> docker: Creating a temporary directory for sharing data...
==> docker: Pulling Docker image: ubuntu:14.04.5
    docker: 14.04.5: Pulling from library/ubuntu
    docker: Digest: sha256:062bba17f92e749bd3092e7569aa06c6773ade7df603958026f2f5397431754c
    docker: Status: Image is up to date for ubuntu:14.04.5
==> docker: Starting docker container...
    docker: Run command: docker run -v /home/jenkins-agent/.packer.d/tmp/packer-docker731907216:/packer-files -d -i -t ubuntu:14.04.5 /bin/bash
    docker: Container ID: de0da5d8b98dd11cb350d8e62e174b17d7f31bb9a1a37f166d16d33a0253114f
==> docker: Provisioning with shell script: bla.sh
Build was aborted
```

When I look at the syslogs of the host, I see errors about **containerd** not being able to save the container. This error always appears whenever I try to run the packer build with a shell provisioner. The logs are as follows:

```
Nov 27 16:06:15 BER-LX-01 dockerd[13546]: time="2016-11-27T16:06:15.038205355+01:00" level=warning msg="containerd: unable to save 24f8fa06db96506734222dcf792b7b2ee1816bb32e50fb0f5f5ded471b4cca36:18e39664a701ed59ab176513c54ead3a98f9c65b97c40f7eafa42d95d4a1f529 starttime: open /proc/2127/stat: no such file or directory"
Nov 27 16:06:15 BER-LX-01 dockerd[13546]: time="2016-11-27T16:06:15.038266574+01:00" level=info msg="containerd: 24f8fa06db96506734222dcf792b7b2ee1816bb32e50fb0f5f5ded471b4cca36:18e39664a701ed59ab176513c54ead3a98f9c65b97c40f7eafa42d95d4a1f529 (pid 2127) has become an orphan, killing it"
Nov 27 16:06:17 BER-LX-01 dockerd[13546]: time="2016-11-27T16:06:17.110429824+01:00" level=warning msg="containerd: unable to save 24f8fa06db96506734222dcf792b7b2ee1816bb32e50fb0f5f5ded471b4cca36:266b063d3416af7c7c1450a3db71cd2708e5ad3907bd2e540159ca07f1a7c14f starttime: open /proc/2215/stat: no such file or directory"
Nov 27 16:06:17 BER-LX-01 dockerd[13546]: time="2016-11-27T16:06:17.110517715+01:00" level=info msg="containerd: 24f8fa06db96506734222dcf792b7b2ee1816bb32e50fb0f5f5ded471b4cca36:266b063d3416af7c7c1450a3db71cd2708e5ad3907bd2e540159ca07f1a7c14f (pid 2215) has become an orphan, killing it"
Nov 27 16:06:17 BER-LX-01 ntpd[1300]: Listen normally on 335 veth4b1b166 [fe80::80c6:22ff:fe17:1f9%625]:123
Nov 27 16:06:17 BER-LX-01 ntpd[1300]: new interface(s) found: waking up resolver
Nov 27 16:06:19 BER-LX-01 dockerd[13546]: time="2016-11-27T16:06:19.167605128+01:00" level=warning msg="containerd: unable to save 24f8fa06db96506734222dcf792b7b2ee1816bb32e50fb0f5f5ded471b4cca36:cf76c52ca2f0184d58f3292f958ce31de46e36c1efcf0f5100b2ed1b852d1f34 starttime: open /proc/2332/stat: no such file or directory"
Nov 27 16:06:19 BER-LX-01 dockerd[13546]: time="2016-11-27T16:06:19.167757064+01:00" level=info msg="containerd: 24f8fa06db96506734222dcf792b7b2ee1816bb32e50fb0f5f5ded471b4cca36:cf76c52ca2f0184d58f3292f958ce31de46e36c1efcf0f5100b2ed1b852d1f34 (pid 2332) has become an orphan, killing it"
Nov 27 16:06:21 BER-LX-01 dockerd[13546]: time="2016-11-27T16:06:21.208221241+01:00" level=warning msg="containerd: unable to save 24f8fa06db96506734222dcf792b7b2ee1816bb32e50fb0f5f5ded471b4cca36:db061d738df6e973753ebb376462fa178874bbbe8775bb17c895ae9ebc8d202c starttime: open /proc/2419/stat: no such file or directory"
Nov 27 16:06:21 BER-LX-01 dockerd[13546]: time="2016-11-27T16:06:21.208344182+01:00" level=info msg="containerd: 24f8fa06db96506734222dcf792b7b2ee1816bb32e50fb0f5f5ded471b4cca36:db061d738df6e973753ebb376462fa178874bbbe8775bb17c895ae9ebc8d202c (pid 2419) has become an orphan, killing it"
Nov 27 16:06:23 BER-LX-01 dockerd[13546]: time="2016-11-27T16:06:23.264529024+01:00" level=warning msg="containerd: unable to save 24f8fa06db96506734222dcf792b7b2ee1816bb32e50fb0f5f5ded471b4cca36:e19832ac3ae22645939999d5b27f313b51d81618faf2d25357263782674b5c18 starttime: open /proc/2507/stat: no such file or directory"
Nov 27 16:06:23 BER-LX-01 dockerd[13546]: time="2016-11-27T16:06:23.264670439+01:00" level=info msg="containerd: 24f8fa06db96506734222dcf792b7b2ee1816bb32e50fb0f5f5ded471b4cca36:e19832ac3ae22645939999d5b27f313b51d81618faf2d25357263782674b5c18 (pid 2507) has become an orphan, killing it"
Nov 27 16:06:25 BER-LX-01 dockerd[13546]: time="2016-11-27T16:06:25.304801578+01:00" level=warning msg="containerd: unable to save 24f8fa06db96506734222dcf792b7b2ee1816bb32e50fb0f5f5ded471b4cca36:4046c8aa6bc602535f4f94833dc1e640e965f18d094ca82e0510e3ed26bfee0a starttime: open /proc/2596/stat: no such file or directory"
Nov 27 16:06:25 BER-LX-01 dockerd[13546]: time="2016-11-27T16:06:25.305068372+01:00" level=info msg="containerd: 24f8fa06db96506734222dcf792b7b2ee1816bb32e50fb0f5f5ded471b4cca36:4046c8aa6bc602535f4f94833dc1e640e965f18d094ca82e0510e3ed26bfee0a (pid 2596) has become an orphan, killing it"
Nov 27 16:06:27 BER-LX-01 dockerd[13546]: time="2016-11-27T16:06:27.362358401+01:00" level=warning msg="containerd: unable to save 24f8fa06db96506734222dcf792b7b2ee1816bb32e50fb0f5f5ded471b4cca36:1a58ce35b24b7f59756bf9f1896fdc2d2b8074925efb017687ce7fb681025d24 starttime: open /proc/2683/stat: no such file or directory"
Nov 27 16:06:27 BER-LX-01 dockerd[13546]: time="2016-11-27T16:06:27.362476338+01:00" level=info msg="containerd: 24f8fa06db96506734222dcf792b7b2ee1816bb32e50fb0f5f5ded471b4cca36:1a58ce35b24b7f59756bf9f1896fdc2d2b8074925efb017687ce7fb681025d24 (pid 2683) has become an orphan, killing it"
Nov 27 16:06:29 BER-LX-01 dockerd[13546]: time="2016-11-27T16:06:29.418260661+01:00" level=warning msg="containerd: unable to save 24f8fa06db96506734222dcf792b7b2ee1816bb32e50fb0f5f5ded471b4cca36:d7af093901c4210660bde7973d882433616a5782bdc0743f4edcf18657a5dc6f starttime: open /proc/2776/stat: no such file or directory"
Nov 27 16:06:29 BER-LX-01 dockerd[13546]: time="2016-11-27T16:06:29.418387581+01:00" level=info msg="containerd: 24f8fa06db96506734222dcf792b7b2ee1816bb32e50fb0f5f5ded471b4cca36:d7af093901c4210660bde7973d882433616a5782bdc0743f4edcf18657a5dc6f (pid 2776) has become an orphan, killing it"
Nov 27 16:06:29 BER-LX-01 kernel: [685940.982746] docker0: port 8(veth4b1b166) entered forwarding state
Nov 27 16:06:31 BER-LX-01 dockerd[13546]: time="2016-11-27T16:06:31.494697239+01:00" level=warning msg="containerd: unable to save 24f8fa06db96506734222dcf792b7b2ee1816bb32e50fb0f5f5ded471b4cca36:0c7e6de2ee342c73a59c72dc945ca76fb597f4ed98f5b604ec92f5446e620331 starttime: open /proc/2864/stat: no such file or directory"
Nov 27 16:06:31 BER-LX-01 dockerd[13546]: time="2016-11-27T16:06:31.494792097+01:00" level=info msg="containerd: 24f8fa06db96506734222dcf792b7b2ee1816bb32e50fb0f5f5ded471b4cca36:0c7e6de2ee342c73a59c72dc945ca76fb597f4ed98f5b604ec92f5446e620331 (pid 2864) has become an orphan, killing it"
Nov 27 16:06:32 BER-LX-01 kernel: [685943.690146] docker0: port 8(veth4b1b166) entered disabled state
Nov 27 16:06:32 BER-LX-01 kernel: [685943.690183] vethd6868f9: renamed from eth0
Nov 27 16:06:32 BER-LX-01 kernel: [685943.762877] docker0: port 8(veth4b1b166) entered disabled state
Nov 27 16:06:32 BER-LX-01 kernel: [685943.764246] device veth4b1b166 left promiscuous mode
Nov 27 16:06:32 BER-LX-01 kernel: [685943.764249] docker0: port 8(veth4b1b166) entered disabled state
Nov 27 16:06:34 BER-LX-01 ntpd[1300]: Deleting interface #335 veth4b1b166, fe80::80c6:22ff:fe17:1f9%625#123, interface stats: received=0, sent=0, dropped=0, active_time=17 secs
```

**Host Platform**

```
root@41b8a538733d:/# docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

root@41b8a538733d:/# docker info
Containers: 214
 Running: 3
 Paused: 0
 Stopped: 211
Images: 198
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1062
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.44 GiB
Name: work-laptop
ID: GWZO:74ZX:YVTM:ZI2C:FLCT:MGLU:HM46:NM7Q:NXKC:CIDD:2X47:WWUA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8


root@41b8a538733d:/# packer version
Packer v0.12.0

root@41b8a538733d:/# docker-runc --version
runc version 1.0.0-rc2
commit: f59ba3cdd76fdc08c004f42aa915996f6f420899
spec: 1.0.0-rc2-dev


root@41b8a538733d:/# docker-containerd --version
containerd version 0.2.4 commit: b818e749726ba18e430bb825396c85408dfaf2a4

root@41b8a538733d:/# docker-containerd-ctr --version
ctr version 0.2.4 commit: b818e749726ba18e430bb825396c85408dfaf2a4

uname -a
Linux work-laptop 4.4.0-51-generic #72-Ubuntu SMP Thu Nov 24 18:29:54 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```

Packer debug output log can be found at: https://gist.github.com/cprenzberg/27c53c4169c5c05ae8d88ff1d7ef657f

I look forward to any help you have to offer.

Best regards
Charles

**Comment by mlaventure** [comment]
The `containerd` messages are just warning and can be ignored. The logic has been fixed to avoid them to be shown for short lived processes (which is what's happening there).

It does seem that packer's `docker exec` with `bla.sh` fails though. Do you have the rest of the daemon logs for that particular instance? (it should have reference to a container named `de0da5d8b98dd11cb350d8e62e174b17d7f31bb9a1a37f166d16d33a0253114f`)

**Comment by cprenzberg** [comment]
Hi @mlaventure 

sorry i think I copy pasted the logs from another packer build. I have fixed the logs i posted earlier. The container named de0da5d8b98dd11cb350d8e62e174b17d7f31bb9a1a37f166d16d33a0253114f shows up in the logs just fine. 

The exact code snippet above works just fine when I run it on the host so I don't think it is a packer issue. What do you think about the portions of the docker logs containing the following?

```
starttime: open /proc/2127/stat: no such file or directory
```

**Comment by mlaventure** [comment]
@cprenzberg I'll have a look at the updated logs.

Like I stated in my previous command the `starttime` related messages can safely be ignored

**Comment by mlaventure** [comment]
@cprenzberg You haven't added the rest of the daemon logs :)

**Comment by cprenzberg** [comment]
@mlaventure here are the logs I have (restarted the docker engine and tried to reproduce this problem):

```
Dec 05 18:08:37 work-laptop systemd[1]: Stopping Docker Application Container Engine...
Dec 05 18:08:37 work-laptop dockerd[1110]: time="2016-12-05T18:08:37.629310100+01:00" level=info msg="Processing signal 'terminated'"
Dec 05 18:08:37 work-laptop dockerd[1110]: time="2016-12-05T18:08:37.677208043+01:00" level=warning msg="libcontainerd: container 9e2a85b72a07c04796ed0eb7d08c0a5fa08a8a7556815d57b2cfec751e214c6f restart c
Dec 05 18:08:41 work-laptop dockerd[1110]: time="2016-12-05T18:08:41.289574351+01:00" level=warning msg="libcontainerd: container 0d328a11cb784870ec98bfc28bb4823d999f5de14121890e7af4a9037b64b81d restart c
Dec 05 18:08:42 work-laptop dockerd[1110]: time="2016-12-05T18:08:42.644097645+01:00" level=error msg="Error during layer Store.Cleanup(): device or resource busy"
Dec 05 18:08:42 work-laptop dockerd[1110]: time="2016-12-05T18:08:42.644670792+01:00" level=info msg="stopping containerd after receiving terminated"
Dec 05 18:08:43 work-laptop systemd[1]: Stopped Docker Application Container Engine.
Dec 05 18:08:43 work-laptop systemd[1]: Starting Docker Application Container Engine...
Dec 05 18:08:43 work-laptop dockerd[31379]: time="2016-12-05T18:08:43.699486257+01:00" level=info msg="libcontainerd: new containerd process, pid: 31386"
Dec 05 18:08:44 work-laptop dockerd[31379]: time="2016-12-05T18:08:44.736986128+01:00" level=info msg="[graphdriver] using prior storage driver \"aufs\""
Dec 05 18:08:44 work-laptop dockerd[31379]: time="2016-12-05T18:08:44.895635664+01:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Dec 05 18:08:44 work-laptop dockerd[31379]: time="2016-12-05T18:08:44.895869490+01:00" level=warning msg="Your kernel does not support swap memory limit."
Dec 05 18:08:44 work-laptop dockerd[31379]: time="2016-12-05T18:08:44.896256469+01:00" level=info msg="Loading containers: start."
Dec 05 18:08:44 work-laptop dockerd[31379]: ................................................................................................................................................................
Dec 05 18:08:45 work-laptop dockerd[31379]: time="2016-12-05T18:08:45.092802266+01:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be use
Dec 05 18:08:45 work-laptop dockerd[31379]: time="2016-12-05T18:08:45.796692743+01:00" level=warning msg="Failed to allocate and map port 8529-8529: Bind for 0.0.0.0:8529 failed: port is already allocated
Dec 05 18:08:45 work-laptop dockerd[31379]: time="2016-12-05T18:08:45.831574197+01:00" level=warning msg="Failed to allocate and map port 8529-8529: Bind for 0.0.0.0:8529 failed: port is already allocated
Dec 05 18:08:45 work-laptop dockerd[31379]: time="2016-12-05T18:08:45.870720968+01:00" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/0d328a11cb784870ec98bfc
Dec 05 18:08:45 work-laptop dockerd[31379]: time="2016-12-05T18:08:45.892623668+01:00" level=error msg="Failed to start container 0d328a11cb784870ec98bfc28bb4823d999f5de14121890e7af4a9037b64b81d: driver f
Dec 05 18:08:45 work-laptop dockerd[31379]: time="2016-12-05T18:08:45.922266510+01:00" level=error msg="Failed to start container 271a4eaf3572821fa45f7a1b89c46b45e086e3cd2d10cd144b9bf3e273877f23: driver f
Dec 05 18:08:46 work-laptop dockerd[31379]: time="2016-12-05T18:08:46.077708464+01:00" level=info msg="Loading containers: done."
Dec 05 18:08:46 work-laptop dockerd[31379]: time="2016-12-05T18:08:46.077783132+01:00" level=info msg="Daemon has completed initialization"
Dec 05 18:08:46 work-laptop dockerd[31379]: time="2016-12-05T18:08:46.077816772+01:00" level=info msg="Docker daemon" commit=6b644ec graphdriver=aufs version=1.12.3
Dec 05 18:08:46 work-laptop systemd[1]: Started Docker Application Container Engine.
Dec 05 18:08:46 work-laptop dockerd[31379]: time="2016-12-05T18:08:46.097517901+01:00" level=info msg="API listen on /var/run/docker.sock"
Dec 05 18:12:14 work-laptop dockerd[31379]: time="2016-12-05T18:12:14.11878143+01:00" level=warning msg="containerd: unable to save 58246f229e135c09adf28c4944c8d749aaf4a71815255a3fc1a51fcce7b2a541:438b25c
Dec 05 18:12:14 work-laptop dockerd[31379]: time="2016-12-05T18:12:14.119091926+01:00" level=info msg="containerd: 58246f229e135c09adf28c4944c8d749aaf4a71815255a3fc1a51fcce7b2a541:438b25c7879ae27299657f69
Dec 05 18:12:16 work-laptop dockerd[31379]: time="2016-12-05T18:12:16.181337264+01:00" level=warning msg="containerd: unable to save 58246f229e135c09adf28c4944c8d749aaf4a71815255a3fc1a51fcce7b2a541:01b4df
Dec 05 18:12:16 work-laptop dockerd[31379]: time="2016-12-05T18:12:16.181648463+01:00" level=info msg="containerd: 58246f229e135c09adf28c4944c8d749aaf4a71815255a3fc1a51fcce7b2a541:01b4df547f346e25988b4490
Dec 05 18:12:18 work-laptop dockerd[31379]: time="2016-12-05T18:12:18.248056563+01:00" level=warning msg="containerd: unable to save 58246f229e135c09adf28c4944c8d749aaf4a71815255a3fc1a51fcce7b2a541:e8e329
Dec 05 18:12:18 work-laptop dockerd[31379]: time="2016-12-05T18:12:18.248238168+01:00" level=info msg="containerd: 58246f229e135c09adf28c4944c8d749aaf4a71815255a3fc1a51fcce7b2a541:e8e32983eaae322fc42a38a4
Dec 05 18:12:20 work-laptop dockerd[31379]: time="2016-12-05T18:12:20.312011622+01:00" level=warning msg="containerd: unable to save 58246f229e135c09adf28c4944c8d749aaf4a71815255a3fc1a51fcce7b2a541:7c5754
Dec 05 18:12:20 work-laptop dockerd[31379]: time="2016-12-05T18:12:20.312209523+01:00" level=info msg="containerd: 58246f229e135c09adf28c4944c8d749aaf4a71815255a3fc1a51fcce7b2a541:7c575442f2dc8f7e042607f2
Dec 05 18:12:22 work-laptop dockerd[31379]: time="2016-12-05T18:12:22.380769866+01:00" level=warning msg="containerd: unable to save 58246f229e135c09adf28c4944c8d749aaf4a71815255a3fc1a51fcce7b2a541:81e0e2
Dec 05 18:12:22 work-laptop dockerd[31379]: time="2016-12-05T18:12:22.380961122+01:00" level=info msg="containerd: 58246f229e135c09adf28c4944c8d749aaf4a71815255a3fc1a51fcce7b2a541:81e0e2797f386e38d3396c77
Dec 05 18:12:24 work-laptop dockerd[31379]: time="2016-12-05T18:12:24.446013918+01:00" level=warning msg="containerd: unable to save 58246f229e135c09adf28c4944c8d749aaf4a71815255a3fc1a51fcce7b2a541:319ecf
Dec 05 18:12:24 work-laptop dockerd[31379]: time="2016-12-05T18:12:24.446193703+01:00" level=info msg="containerd: 58246f229e135c09adf28c4944c8d749aaf4a71815255a3fc1a51fcce7b2a541:319ecf2e15bde13b77056ef6
Dec 05 18:12:26 work-laptop dockerd[31379]: time="2016-12-05T18:12:26.50791767+01:00" level=warning msg="containerd: unable to save 58246f229e135c09adf28c4944c8d749aaf4a71815255a3fc1a51fcce7b2a541:bb268fe
Dec 05 18:12:26 work-laptop dockerd[31379]: time="2016-12-05T18:12:26.508064207+01:00" level=info msg="containerd: 58246f229e135c09adf28c4944c8d749aaf4a71815255a3fc1a51fcce7b2a541:bb268fe2b5df777066a4891a
Dec 05 18:12:28 work-laptop dockerd[31379]: time="2016-12-05T18:12:28.586558019+01:00" level=warning msg="containerd: unable to save 58246f229e135c09adf28c4944c8d749aaf4a71815255a3fc1a51fcce7b2a541:d31189
Dec 05 18:12:28 work-laptop dockerd[31379]: time="2016-12-05T18:12:28.586857165+01:00" level=info msg="containerd: 58246f229e135c09adf28c4944c8d749aaf4a71815255a3fc1a51fcce7b2a541:d311895a887c817cd671aa1a
```

**Comment by mlaventure** [comment]
@cprenzberg those lofs still don't include the needed information about `de0da5d8b98dd11cb350d8e62e174b17d7f31bb9a1a37f166d16d33a0253114f`.

Could you try to reproduce the issue while having the daemon in debug mode?

**Comment by cprenzberg** [comment]
@mlaventure debug logs are available [here](https://gist.github.com/cprenzberg/a4539d72d9b1a35b12c3f60d815aa130)

thanks

**Comment by thaJeztah** [comment]
ping @mlaventure ^^

**Comment by mlaventure** [comment]
Looking at the log, your issue is that the script doesn't get properly "uploaded" to the `ubuntu:14.04.5` container created by packer.

My guess is that `bla.sh` is within the first container, docker is on the host, the 2nd container is running on the host and not withing the packer container, so when packer does its upload thing, it somehow doesn't make it through into the second container.

Not knowing how packer does the "upload" part, I can't really go further than that.

**Comment by bobbydeveaux** [comment]
I'm pretty sure docker within docker (which is required for packer to create a docker container when running within docker container) - is not going to work, and MitchellH tweeted about it last year, and still planning on resolving this... I have had this same issue, but docker within docker, for packer purposes, just isn't going to work AFAIK.

**Comment by evmin** [comment]
Got the same issue. Unrelated to packer - just an ordinary container running.

**Comment by thaJeztah** [comment]
Let me close this issue for now, as it seems this is not supported by packer.

@evmin there's many possible causes for a file to not be uploaded, or mounted into a container, if you suspect there's a bug, please open a new issue with details (be sure to include the information that's requested in our issue template  https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md)
