### ISSUE TITLE
Xenial (16.04) Failed to start systemd docker.service after security updates

### ISSUE THREAD

**Issue by maccradar** [docker/docker#29179]
Started after a server reboot which install security updates / kernel updates. Currently running Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-53-generic x86_64).
Reinstall of docker also fails. Might be related to #22371 but solutions offered there, do not work for me...
Starting dockerd from shell works.

```sh
~$ uname -r
4.4.0-53-generic
~$ sudo service docker restart 
A dependency job for docker.service failed. See 'journalctl -xe' for details.
~$ journalctl -xe
-- 
-- Unit docker.socket has begun starting up.
Dec 06 15:42:30 PMA-ROB-BUILD systemd[5866]: Failed to chown socket at step GROUP: No such process
Dec 06 15:42:30 PMA-ROB-BUILD systemd[1]: docker.socket: Control process exited, code=exited status=216
Dec 06 15:42:30 PMA-ROB-BUILD systemd[1]: Failed to listen on Docker Socket for the API.
-- Subject: Unit docker.socket has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has failed.
-- 
-- The result is failed.
Dec 06 15:42:30 PMA-ROB-BUILD systemd[1]: Dependency failed for Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.
-- 
-- The result is dependency.
Dec 06 15:42:30 PMA-ROB-BUILD systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Dec 06 15:42:30 PMA-ROB-BUILD systemd[1]: docker.socket: Unit entered failed state.
Dec 06 15:42:30 PMA-ROB-BUILD sudo[5859]: pam_unix(sudo:session): session closed for user root
```

**Output of `docker version`:**

```
~$ sudo docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```
After I manually start dockerd:
```sh
~$ sudo docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
~$ sudo docker info
Containers: 120
 Running: 1
 Paused: 0
 Stopped: 119
Images: 100
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 428
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-53-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.795 GiB
Name: PMA-ROB-BUILD
ID: XUCI:ISDS:BDX6:TOFO:K4FA:QUTL:WOLC:VLZQ:EAPP:NEPK:XIUL:L5UG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running Xenial on a Citrix VM.

**Comment by 506764932** [comment]
`#edit docker.service
sudo vim /lib/systemd/system/docker.service
# update ExecStart
$ ExecStart=/usr/bin/dockerd -H fd:// --bip=172.17.42.1/16 --storage-driver=overlay
# done
`

**Comment by maccradar** [comment]
Nope, tried this before...

```sh
~$ sudo systemctl daemon-reload 
jphilips@PMA-ROB-BUILD:~$ sudo systemctl start docker
A dependency job for docker.service failed. See 'journalctl -xe' for details.
jphilips@PMA-ROB-BUILD:~$ journalctl -xe
-- 
-- Unit docker.socket has begun starting up.
Dec 07 06:43:43 PMA-ROB-BUILD systemd[16367]: Failed to chown socket at step GRO
Dec 07 06:43:43 PMA-ROB-BUILD systemd[1]: docker.socket: Control process exited,
Dec 07 06:43:43 PMA-ROB-BUILD systemd[1]: Failed to listen on Docker Socket for 
-- Subject: Unit docker.socket has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has failed.
-- 
-- The result is failed.
Dec 07 06:43:43 PMA-ROB-BUILD systemd[1]: Dependency failed for Docker Applicati
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.
-- 
-- The result is dependency.
Dec 07 06:43:43 PMA-ROB-BUILD systemd[1]: docker.service: Job docker.service/sta
Dec 07 06:43:43 PMA-ROB-BUILD systemd[1]: docker.socket: Unit entered failed sta
Dec 07 06:43:43 PMA-ROB-BUILD sudo[16364]: pam_unix(sudo:session): session close
lines 1118-1140/1140 (END)
-- 
-- Unit docker.socket has begun starting up.
Dec 07 06:43:43 PMA-ROB-BUILD systemd[16367]: Failed to chown socket at step GRO
Dec 07 06:43:43 PMA-ROB-BUILD systemd[1]: docker.socket: Control process exited,
Dec 07 06:43:43 PMA-ROB-BUILD systemd[1]: Failed to listen on Docker Socket for 
-- Subject: Unit docker.socket has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has failed.
-- 
-- The result is failed.
Dec 07 06:43:43 PMA-ROB-BUILD systemd[1]: Dependency failed for Docker Applicati
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.
-- 
-- The result is dependency.
Dec 07 06:43:43 PMA-ROB-BUILD systemd[1]: docker.service: Job docker.service/sta
Dec 07 06:43:43 PMA-ROB-BUILD systemd[1]: docker.socket: Unit entered failed sta
Dec 07 06:43:43 PMA-ROB-BUILD sudo[16364]: pam_unix(sudo:session): session close
~
lines 1118-1140/1140 (END)
-- 
-- Unit docker.socket has begun starting up.
Dec 07 06:43:43 PMA-ROB-BUILD systemd[16367]: Failed to chown socket at step GRO
Dec 07 06:43:43 PMA-ROB-BUILD systemd[1]: docker.socket: Control process exited,
Dec 07 06:43:43 PMA-ROB-BUILD systemd[1]: Failed to listen on Docker Socket for 
-- Subject: Unit docker.socket has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has failed.
-- 
-- The result is failed.
Dec 07 06:43:43 PMA-ROB-BUILD systemd[1]: Dependency failed for Docker Applicati
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.
-- 
-- The result is dependency.
Dec 07 06:43:43 PMA-ROB-BUILD systemd[1]: docker.service: Job docker.service/sta
Dec 07 06:43:43 PMA-ROB-BUILD systemd[1]: docker.socket: Unit entered failed sta
Dec 07 06:43:43 PMA-ROB-BUILD sudo[16364]: pam_unix(sudo:session): session close
```

**Comment by thaJeztah** [comment]
The error logs there don't provide a lot of information, but it looks like the `docker.socket` service fails to start, and therefore the main `docker` service fails to start, because it has `docker.socket` as a dependency;

> systemd[1]: Dependency failed for Docker Application Container Engine.

Which fails here;

> Failed to chown socket at step GROUP: No such process

Just to try finding what can cause this;

- do you know the version of `systemd` that you are running?
- can you show the content of your systemd units for `docker.socket` and `docker.service` ?
- do the logs show anything useful (e.g. `journalctl -u docker.socket` and `journalctl -u docker.service`) (you may have to "tail" that output, e.g. `-n 500`)

**Comment by maccradar** [comment]
- do you know the version of systemd that you are running?
```sh
~$ systemd --version
systemd 229
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN
```
- can you show the content of your systemd units for docker.socket and docker.service ?
I made one change, based on other people's suggestions, by adding overlay as storage-driver, but does not solve the issue.
docker.service:
```sh
~$ cat /lib/systemd/system/docker.service 
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
Type=notify
# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/bin/dockerd -H fd:// --bip=172.17.42.1/16 --storage-driver=overlay
ExecReload=/bin/kill -s HUP $MAINPID
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
TasksMax=infinity
TimeoutStartSec=0
# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes
# kill only the docker process, not all processes in the cgroup
KillMode=process

[Install]
WantedBy=multi-user.target
```
docker.socket:
```sh
~$ cat /lib/systemd/system/docker.socket 
[Unit]
Description=Docker Socket for the API
PartOf=docker.service

[Socket]
ListenStream=/var/run/docker.sock
SocketMode=0660
SocketUser=root
SocketGroup=docker

[Install]
WantedBy=sockets.target
```
- do the logs show anything useful (e.g. journalctl -u docker.socket and journalctl -u docker.service) (you may have to "tail" that output, e.g. -n 500)
Log below is repeated for numerous times without any other information
```sh
Dec 06 19:26:55 PMA-ROB-BUILD systemd[1]: Starting Docker Socket for the API.
Dec 06 19:26:55 PMA-ROB-BUILD systemd[1]: docker.socket: Control process exited, code=exited status=216
Dec 06 19:26:55 PMA-ROB-BUILD systemd[1]: Failed to listen on Docker Socket for the API.
Dec 06 19:26:55 PMA-ROB-BUILD systemd[1]: docker.socket: Unit entered failed state.
Dec 06 19:26:55 PMA-ROB-BUILD systemd[1]: Starting Docker Socket for the API.
Dec 06 19:26:55 PMA-ROB-BUILD systemd[1]: docker.socket: Control process exited, code=exited status=216
```
docker.service log:
```sh
Dec 06 19:19:23 PMA-ROB-BUILD systemd[1]: Started docker.service.
Dec 06 19:19:23 PMA-ROB-BUILD docker[3179]: time="2016-12-06T19:19:23.206333449+01:00" level=fatal msg="no sockets f
Dec 06 19:19:23 PMA-ROB-BUILD systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Dec 06 19:19:23 PMA-ROB-BUILD systemd[1]: docker.service: Unit entered failed state.
Dec 06 19:19:23 PMA-ROB-BUILD systemd[1]: docker.service: Failed with result 'exit-code'.
Dec 06 19:19:52 PMA-ROB-BUILD systemd[1]: Dependency failed for Docker Application Container Engine.
Dec 06 19:19:52 PMA-ROB-BUILD systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
```

**Comment by maccradar** [comment]
Only way to bypass this issue is to run `sudo dockerd -s aufs` in a `screen` session.

**Comment by thaJeztah** [comment]
Note that (looking at https://github.com/docker/docker/issues/29179#issuecomment-265346679) it's **not recommended** to edit the main systemd unit file directly; Editing the main unit file directly prevents it from being automatically updated if you update the docker package, so possibly leading to it getting outdated.

To modify those settings, either use a `daemon.json` configuration file (see the [dockerd documentation](https://docs.docker.com/engine/reference/commandline/dockerd/#/daemon-configuration-file), or use a systemd "drop-in" file to override settings (see the ["configure Docker with systemd"](https://docs.docker.com/engine/admin/systemd/#/custom-docker-daemon-options) documentation). Using a `daemon.json` file is the most portable way, and has certain advantages, because if allows to reload some configuration changes without restarting the daemon.


> Only way to bypass this issue is to run sudo dockerd -s aufs in a screen session.

I wonder if the `docker` group could be missing, because the `docker.socket` unit file tries to set the ownership of the `docker.socket` to `root:docker`, which probably fails if that group is not there.

Can you check if that group exists? Something like this should work;

```bash
cat /etc/group | grep docker
    
docker:x:999:
```

**Comment by maccradar** [comment]
My god, you found the cause! simply running `sudo groupadd docker` solved the whole issue :-o
Thanks a lot @thaJeztah !!

**Comment by thaJeztah** [comment]
Good to hear! I'm still not sure how it would be possible that the group was missing; what procedure did you use originally to install docker? did you use the script at https://get.docker.com, or follow the manual installation procedure? (https://docs.docker.com/engine/installation/linux/ubuntulinux)

**Comment by maccradar** [comment]
I followed the instructions at docs.docker but the missing docker group was probably a byproduct of something totally different during user/group maintenance.

**Comment by scottstensland** [comment]
Am seeing this exact issue with same solution on a virgin install of  Ubuntu 16.04  

```
root@babochka /usr/lib # docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.11.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-98-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 4.844GiB
Name: babochka
ID: 42DY:ZMTK:NCUQ:BLEI:6LO5:LC25:FEG3:TTJ6:EFLS:X65P:DWH4:7UQB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Comment by ianmaddox** [comment]
Same issue on a fresh install of Ubuntu 17.10:

```~# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-32-generic
Operating System: Ubuntu 17.10
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 125.8 GiB
Name: yotta
ID: BANA:46MV:YW4S:JTTW:FF2X:PQEW:G7XF:DZB3:5PS7:GQGM:RXCE:EOO5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false```

**Comment by thaJeztah** [comment]
@ianmaddox Docker 1.13 was never released for Ubuntu 17.10 (and Docker 1.13 has been EOL'd since March of last year); perhaps you're trying to install a distro package of Docker, not the official packages? 

See the [installation docs](https://docs.docker.com/install/linux/docker-ce/ubuntu/);

> OS requirements
> Artful 17.10 (Docker CE 17.11 Edge and higher only)


If you're still running into issues, make sure to check the system logs, as they may provide more information as to why docker fails to start; without that, there's not much to look into

**Comment by paulmerlyn** [comment]
I had the exact same experience as the OP, using Xenial and the official docker installation instructions. The docker group wasn't automatically created, but your suggestion of adding it (i.e. $ sudo groupadd docker) followed by $ sudo systemctl start docker was enough to get me airborne. Many thanks, @thaJeztah, for working through this and to @maccradar for sharing what worked for you.

**Comment by antoniosap** [comment]
no go on QNAP vm ubuntu 16.04.4 LTS

**Comment by mfpereira** [comment]
I got the same issue. Thanks for the solution.

**Comment by RashikShahjahan** [comment]
I have the exact same problem but I already have a docker group.

**Comment by thaJeztah** [comment]
@RashikShahjahan be sure to check the full logs of the docker service, and also system logs; if the daemon fails to start, there should likely be an error message somewhere that gives an indication what went wrong

**Comment by mickeyze** [comment]
Try this: 
sudo mount -o rw,remount /

**Comment by gdmello** [comment]
This comment is nearly a year after the last comment, but I encountered the same issue on CentOS, and came across this issue.

For me, the fix was to add the `docker` group to `/etc/group` as well, but my CentOS box had Active Directory (AD) integration which included the `docker` group, so the `groupadd` command failed. I had to use `lgroupadd --gid <GID> docker` instead.

**Comment by yogesh-baroqe** [comment]
`sudo groupadd docker` worked like a charm !!
