### ISSUE TITLE
docker-compose does not accept variable substitution in some cases

### ISSUE THREAD

**Issue by IOAyman** [docker/docker#32118]
**Description**
I'd like to use some variable substitutions in my `docker-compose.yml` to define how my stack should be deployed. However, some keys must be of a certain type, for instance integers.

**Steps to reproduce the issue:**
```bash
$ cat > demo.yml << EOF
version: "3"
services:
  nc:
    image: alpine
    command: nc -lp1789
    ports:
      - "${NC_PORT:-80}:1789"
    deploy:
      replicas: ${NC_REPLICAS:-1}
EOF

$ docker-compose -f demo.yml up
```

**Describe the results you received:**
```
ERROR: The Compose file './demo.yml' is invalid because:
services.nc.deploy.replicas contains an invalid type, it should be an integer
```

**Describe the results you expected:**
`docker-compose` not to show the error above

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:00:11 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 39
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 256
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.52-boot2docker
Operating System: Boot2Docker 17.03.0-ce (TCL 7.2); HEAD : f11a204 - Thu Mar  2 00:14:47 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8 MiB
Name: default
ID: N7K3:5I27:WVFR:D24U:SNJG:DCYL:47SL:HCS4:RQFJ:XV45:DN3K:STTK
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 26
 System Time: 2017-03-26T20:12:44.991356647Z
 EventsListeners: 0
Username: ioayman
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox

**Comment by vdemeester** [comment]
@IOAyman it should be fix with 17.04, fixed by https://github.com/docker/docker/pull/30781 that is in 17.04 😉 (cherry-picked).

```
root@acb07105e12c:/go/src/github.com/docker/docker# docker stack deploy --compose-file demo.yml foo
Creating network foo_default
Creating service foo_nc
```

**Comment by thaJeztah** [comment]
Thanks for checking @vdemeester; I'll go ahead and close then, but feel free to continue the conversation :+1:

**Comment by IOAyman** [comment]
Thank you 😄

**Comment by seriousben** [comment]
Was there a regression for this? This is still not working in 17.06 rc5

**Comment by seriousben** [comment]
Was there a regression? this is still not working in 17.06 rc5.
I think the initial script to generate the demo.yml was flawed since it evaluated the variable expansion tags.

This is a fixed version of the script:
```
echo '
version: "3"
services:
  nc:
    image: alpine
    command: nc -lp1789
    ports:
      - "${NC_PORT:-80}:1789"
    deploy:
      replicas: ${NC_REPLICAS:-1}
' > demo.yml
```

**Comment by thaJeztah** [comment]
@seriousben thanks! Can you open an issue in the docker/cli repository? The CLI code (and handling of the docker-compose files) now lives in that repository; https://github.com/docker/cli/issues

**Comment by seriousben** [comment]
Done, thanks
