### ISSUE TITLE
Docs syntax issue

### ISSUE THREAD

**Issue by Fank** [docker/docker#32311]
https://github.com/docker/docker/blob/17.03.x/docs/reference/commandline/service_create.md
![image](https://cloud.githubusercontent.com/assets/1900106/24601239/6c42dcac-1858-11e7-8cfe-79ca04a46b90.png)
OK with no issues

https://docs.docker.com/engine/reference/commandline/service_create/#specify-service-constraints---constraint
![image](https://cloud.githubusercontent.com/assets/1900106/24601250/79eaf074-1858-11e7-929f-b6a20e74b064.png)
Table is messed up
And `<tdnode.role</td>` is above the table

This is the table in HTML:
```html
<table>
  <tr>
    <th>node attribute</th>
    <th>matches</th>
    <th>example</th>
  </tr>
  <tr>
    <td><tt>node.id</tt></td>
    <td>Node ID</td>
    <td><tt>node.id == 2ivku8v2gvtg4</tt></td>
  </tr>
  <tr>
    <td><tt>node.hostname</tt></td>
    <td>Node hostname</td>
    <td><tt>node.hostname != node-2</tt></td>
  </tr>
  <tr>
    &lt;td<tt>node.role</tt>&lt;/td&gt;
    <td><tt>node role: manager</tt></td>
    <td><tt>node.role == manager</tt></td>
  </tr>
  <tr>
    <td><tt>node.labels</tt></td>
    <td>user defined node labels</td>
    <td><tt>node.labels.security == high</tt></td>
  </tr>
  <tr>
    <td><tt>engine.labels</tt></td>
    <td>Docker Engine's labels</td>
    <td><tt>engine.labels.operatingsystem == ubuntu 14.04</tt></td>
  </tr>
</table>
```

**Comment by TristanCP** [comment]
And there are layout issues relative the the new reference docs, maybe related the same problem : When you have a zoom activated (like +140%) and you click on a link with an anchor (like https://docs.docker.com/engine/reference/commandline/service_create/#set-service-mode---mode), the left part of the page body will be truncated. If you zoom out til 100%, it will "un-truncate", but if you zoom again, it's the right part which will be truncated.

**Comment by thaJeztah** [comment]
This looks to be fixed on "master", and the 17.03.x branch but not yet in the 17.04.x branch (https://github.com/docker/docker/pull/31875)

**Comment by thaJeztah** [comment]
cherry-picked the fix into the 17.04.x branch as well (https://github.com/docker/docker/pull/31902), so this should be fixed the next time the CLI reference-docs are redeployed.

@TristanCP can you open an issue for the layout issues in the documentation issue tracker (https://github.com/docker/docker.github.io/issues)? If possible with screenshots to explain the issue.

I'll close this issue here, because all fixes will be in when that PR is merged, and now depends on the docs to be redeployed. Thanks for reporting!

**Comment by TristanCP** [comment]
@thaJeztah It looks fixed as far as I can see on Chrome. I'll check again on Firefox later.

**Comment by thaJeztah** [comment]
Perfect, thanks!

**Comment by Fank** [comment]
@thaJeztah i still see this issue
![image](https://cloud.githubusercontent.com/assets/1900106/24766493/ce3b219e-1afb-11e7-9f57-850f6ee9af34.png)
