### ISSUE TITLE
dockerd shutdown-timeout option does not work as expected

### ISSUE THREAD

**Issue by christidis** [docker/docker#32357]
**Description**

`dockerd` option `shutdown-timeout` does not seem to work as expected on service shutdown.

**Steps to reproduce the issue:**
1. setup systemd with a configuration that includes the `--shutdown-timeout=30` option. In my case 
```
ExecStart=/usr/bin/dockerd -D -H unix:///var/run/docker-${USER_NAME}.sock --userns-remap=default --exec-root=/var/run/docker/${USER_NAME} -g /home/${USER_NAME}/docker/ --pidfile=/var/run/docker-${USER_NAME}.pid --insecure-registry=dregistry:5000 --fixed-cidr=${DOCKER_NETWORK} --shutdown-timeout=30 
```
2. Run a container which is not handling SIGTERM by default, so it always gets killed.
```
docker run -d -ti --name=zkui goodguide/zk-web:latest
```
3. stop `docker.service` measuring time statistics
```
time systemctl stop docker.service

real	0m11.846s
user	0m0.000s
sys	0m0.000s
```

**Describe the results you received:**

`journalctl` logs mention this

> "start clean shutdown of all containers with a 30 seconds timeout...

but container gets stopped after 10 seconds (instead of 30).
> msg="Container 23e4f3e7529471356ae0069197e77f6939d7d8176d49422c59b9b93d3afbb63b failed to exit within 10 seconds of signal 15 - using the force"
> Apr 04 09:30:35 qa22 dockerd[28264]: time="2017-04-04T09:30:35.316828071-07:00" level=debug msg="Sending kill signal 9 to container 

```
Apr 04 09:30:25 qa22 systemd[1]: Stopping Docker Application Container Engine...
Apr 04 09:30:25 qa22 dockerd[28264]: time="2017-04-04T09:30:25.315742282-07:00" level=info msg="Processing signal 'terminated'"
Apr 04 09:30:25 qa22 dockerd[28264]: time="2017-04-04T09:30:25.315887135-07:00" level=debug msg="start clean shutdown of all containers with a 30 seconds timeout..."
Apr 04 09:30:25 qa22 dockerd[28264]: time="2017-04-04T09:30:25.315980272-07:00" level=debug msg="stopping 23e4f3e7529471356ae0069197e77f6939d7d8176d49422c59b9b93d3afbb63b"
Apr 04 09:30:25 qa22 dockerd[28264]: time="2017-04-04T09:30:25.316012651-07:00" level=debug msg="Sending kill signal 15 to container 23e4f3e7529471356ae0069197e77f6939d7d8176d49422c59b9b93d3afbb63b"

Apr 04 09:30:35 qa22 dockerd[28264]: time="2017-04-04T09:30:35.316780128-07:00" level=info msg="Container 23e4f3e7529471356ae0069197e77f6939d7d8176d49422c59b9b93d3afbb63b failed to exit within 10 seconds of signal 15 - using the force"
Apr 04 09:30:35 qa22 dockerd[28264]: time="2017-04-04T09:30:35.316828071-07:00" level=debug msg="Sending kill signal 9 to container 23e4f3e7529471356ae0069197e77f6939d7d8176d49422c59b9b93d3afbb63b"
Apr 04 09:30:35 qa22 dockerd[28264]: time="2017-04-04T09:30:35.44054447-07:00" level=debug msg="containerd: process exited" id=23e4f3e7529471356ae0069197e77f6939d7d8176d49422c59b9b93d3afbb63b pid=init status=137 systemPid=3870
Apr 04 09:30:35 qa22 dockerd[28264]: time="2017-04-04T09:30:35.446673243-07:00" level=debug msg="libcontainerd: received containerd event: &types.Event{Type:\"exit\", Id:\"23e4f3e7529471356ae0069197e77f6939d7d8176d49422c59b9b93d3afbb63b\", Status:0x89, Pid:\"init\", Timestamp:(*timestamp.Timestamp)(0xc421372b50)}"
Apr 04 09:30:35 qa22 dockerd[28264]: time="2017-04-04T09:30:35.447517766-07:00" level=debug msg="Revoking external connectivity on endpoint zkui (5bd33a9b2b7571fbf24661ae18fdedc0f67ab412a4bd0b1604fcb1d192809441)"
Apr 04 09:30:35 qa22 dockerd[28264]: time="2017-04-04T09:30:35.623431528-07:00" level=debug msg="Releasing addresses for endpoint zkui's interface on network bridge"
Apr 04 09:30:35 qa22 dockerd[28264]: time="2017-04-04T09:30:35.623473594-07:00" level=debug msg="ReleaseAddress(LocalDefault/172.17.0.0/16/172.17.15.0/24, 172.17.15.19)"
Apr 04 09:30:36 qa22 dockerd[28264]: time="2017-04-04T09:30:36.092134694-07:00" level=debug msg="GetMountID id: 23e4f3e7529471356ae0069197e77f6939d7d8176d49422c59b9b93d3afbb63b -> mountID: ecfc1dff8eae821378ed76e5e6d6813f9ee733edfe635da43e0472022b241385"
Apr 04 09:30:36 qa22 dockerd[28264]: time="2017-04-04T09:30:36.092170115-07:00" level=debug msg="Cleaning up old mountid ecfc1dff8eae821378ed76e5e6d6813f9ee733edfe635da43e0472022b241385: start."
Apr 04 09:30:36 qa22 dockerd[28264]: time="2017-04-04T09:30:36.092612747-07:00" level=debug msg="Cleaning up old mountid ecfc1dff8eae821378ed76e5e6d6813f9ee733edfe635da43e0472022b241385: done."
Apr 04 09:30:36 qa22 dockerd[28264]: time="2017-04-04T09:30:36.092629491-07:00" level=debug msg="container stopped 23e4f3e7529471356ae0069197e77f6939d7d8176d49422c59b9b93d3afbb63b"
Apr 04 09:30:36 qa22 dockerd[28264]: time="2017-04-04T09:30:36.117212427-07:00" level=debug msg="Cleaning up old mountid : start."
Apr 04 09:30:36 qa22 dockerd[28264]: time="2017-04-04T09:30:36.117318455-07:00" level=debug msg="Unix socket /run/docker/libnetwork/bfa6d768c2dd0afb1c12c2e69b9c0b2781361d2de54afd8a327f0e2c024b0cab.sock doesn't exist. cannot accept client connections"
Apr 04 09:30:36 qa22 dockerd[28264]: time="2017-04-04T09:30:36.117564226-07:00" level=debug msg="Cleaning up old mountid : done."
Apr 04 09:30:36 qa22 dockerd[28264]: time="2017-04-04T09:30:36.117588043-07:00" level=debug msg="Clean shutdown succeeded"
Apr 04 09:30:36 qa22 dockerd[28264]: time="2017-04-04T09:30:36.117850074-07:00" level=info msg="stopping containerd after receiving terminated"
Apr 04 09:30:36 qa22 dockerd[28264]: time="2017-04-04T09:30:36.411530576-07:00" level=debug msg="libcontainerd: containerd health check returned error: rpc error: code = 9 desc = grpc: the client connection is closing"
Apr 04 09:30:37 qa22 systemd[1]: Stopped Docker Application Container Engine.
```
container stopped 

**Describe the results you expected:**

I was expecting command  `time systemctl stop docker-litservices.service` to finish after 30 seconds.

Even if I run the container with a container level timeout of 60s using `docker run --stop-timeout=60`, still `time systemctl stop docker-litservices.service` is shutting down after 60s (instead of 30s).

it seems that the container level timeout option `stop-timeout`, overpowers the `shutdown-timeout` `dockerd` value and the later is not making any difference at all. Is this normal? 
Which timeout is the `dockerd`/ `--shutdown-time` option is setting?

**Additional information you deem important (e.g. issue happens only occasionally):**

`--shutdown-timeout` exists in man/help page but is not documented in the [documentation](https://docs.docker.com/engine/reference/commandline/dockerd/)

```
[~]>dockerd --help | grep shut
      --shutdown-timeout int                  Set the default shutdown timeout (default 15)
```

**Output of `docker version`:**

```
# docker --version
Docker version 17.03.1-ce, build c6d412e

```

**Output of `docker info`:**

```
[~]>docker info
Containers: 22
 Running: 20
 Paused: 0
 Stopped: 2
Images: 6
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /home/services/docker/1083040.1083040/aufs
 Backing Filesystem: extfs
 Dirs: 143
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 userns
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 94.6 GiB
Name: qa22
ID: J34K:LKP5:Y6A5:IWIO:KT5H:WMRH:YSZJ:6QOA:EHYP:ZLBH:XGOA:EANL
Docker Root Dir: /home/services/docker/1083040.1083040
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 135
 Goroutines: 102
 System Time: 2017-04-04T09:36:55.73437204-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Experimental: false
Insecure Registries:
 docker-registry:41238
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical debian 
```
SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
```

**Comment by cpuguy83** [comment]
Shutdown timeout is the period of time that is given for the daemon to shutdown before it just proceeds with exiting. This is not related to container shutdown time.
To change a container's stop timeout, you need to set `--stop-timeout`.

Shutdown timeout is adjusted for the max stop-timeout of a container.

**Comment by hdimitriou** [comment]
So if shutdown timeout will be the max('Shutdown timeout', max('stop-timeout')) what is its use? 
If max(stop timeout) is less that shutdown timeout, all containers would be stopped before we reach shutdown timeout anyway so we wouldnt reach it. 

For example if the max stop-timeout for containers is 10 seconds and shutdown-timeout for the service is 20 seconds.
If we issue a service stop, then after 10 seconds all containers will have been stopped and the service will stop at that time too. Thus, it will not reach 20 sec.
What am i missing?

**Comment by cpuguy83** [comment]
@hdimitriou There's more work to do than just shutdown containers on exit.

**Comment by thaJeztah** [comment]
@cpuguy83 ; `--shutdown-timeout` was added in https://github.com/docker/docker/pull/23036, and overrides the default 10 seconds + 5 seconds grace before `SIGKILL` the container; https://github.com/docker/docker/pull/22566 also adds a per-container option; if that option is set and is longer than shutdown-timeout, the shutdown-timeout is extended to be sure it's not shorter than that.

However, the daemon shutdown takes the stop-timeout into account that was set on a container, and I _think_ this is where the mistake is; that timeout defaults to 10 seconds, so the `shutdown-timeout` won't be used.

ping @yongtang perhaps you can take a look if we're mis-interpreting it?

**Comment by yongtang** [comment]
Thanks @thaJeztah I will take a look.

**Comment by thaJeztah** [comment]
When stopping a container, either the user-specified (`--stop-timeout`) timeout is used, or if no timeout is set, the default (fixed) timeout of 10 seconds is used;

https://github.com/moby/moby/blob/930e6896685f614d8f15ed10207596b1a151cbc8/container/container.go#L462-L468

https://github.com/moby/moby/blob/930e6896685f614d8f15ed10207596b1a151cbc8/container/container.go#L54-L55


During shutdown, the longest timeout is taken; which can be either the value set on the daemon (`--shutdown-timeout`), or set by a container (`--stop-timeout`). After all containers are terminated, the daemon shuts down;
https://github.com/moby/moby/blob/147443a42665419d8b3c2047a7d345440bfb63c0/cmd/dockerd/daemon.go#L408-L429

Here's the tricky bit:

- if the timeout set on the daemon is shorter than the timeout of any of the containers, the shutdown-timeout is extended to allow the container to shutdown gracefully (https://github.com/moby/moby/pull/22566)
- effectively, seting the `--shutdown-timeout` to anything shorter than 15 seconds (default container stop-timeout + grace period) does not have any effect
- setting `--shutdown-timeout` to anything _longer_ than the longest `--stop-timeout` of a container does not do much either; containers are killed before the `--shutdown-timeout` expires, in which case the daemon also shuts down.



#### Observations

1. From the above, it becomes clear that the `--shutdown-timeout` option currently doesn't do anything.
2. The `--stop-timeout` and `--shutdown-timeout` options were implemented to allow stateful services/containers to be shutdown cleanly (e.g. don't kill a `mysql` container while it's still writing data to disk, because that may lead to data corruption).
3. By always accepting the longest timeout, a container started with `--stop-timeout=-1` potentially prevents the daemon from shutting down; this may be a concern because the person managing the daemon has no control over this.
4. It's not possible to override the _default_ stop-timeout for containers (if that's desirable), the default is fixed to 10 seconds

#### Possible solutions

We can _remove_ the default value for `--shutdown-timeout` (e.g., set it to `0`);

- If no value is set for `--shutdown-timeout`. Containers are killed after 10 seconds by default, and the daemon shuts down after the last container was terminated. It may thus not even be needed to calculate the actual shutdown time (just wait until all containers terminated).
- If a value is set for `--shutdown-timeout`, that value overrides the `--stop-timeout` for containers, which means that `--shutdown-timeout=10` kills any container that did not stop after 10 seconds (including, e.g., a `mysql` container with a `--stop-timeout=60`). Allowing to override the timeout on the daemon puts the person managing the daemon back in control ().

Alternatively; use `--shutdown-timeout` as the default value for containers that don't specify a `--stop-timeout`. This makes the default configurable (item 4. on the list above), allows the timeout to be customized for stateful containers (item 2.) but doesn't solve 3.

- do we _need_ the default to be configurable? It may be best to leave this to the container configuration; the desired timeout strongly depends on the type of container (stateful, ephemeral)

**Comment by interone-ms** [comment]
Hello,

just wanted to chime in - I believe that this is a valid bug, I just have hit the same issue.

Problem 1: the documentation for "--shutdown-timeout" on https://docs.docker.com/engine/reference/commandline/dockerd/ is non-existing, leading users to believe that this indeed is the option to set the time between sig 15 and sig 9 for all containers. This should be fixed by putting the documentation @thaJeztah wrote here into the docs (and to me looks like it falls in the scope of #26828).

Problem 2: there is no way to globally set the stop timeout for all containers. This impacts people running Docker with orchestrators, frameworks or other controllers on top that do/can not issue --time when running `docker stop`, which in our case led to data loss multiple times as databases were not shutdown cleanly.

As for your question

> do we need the default to be configurable? It may be best to leave this to the container configuration; the desired timeout strongly depends on the type of container (stateful, ephemeral)

I'd say the system operator knows what kinds of containers will be run on the machine and so should be free to set the default value to something that will work for his/her workload.

**Comment by chanjarster** [comment]
@thaJeztah Thanks for detailed explanation, but I still have a question:

If there are 3 containers, what will the actual `shutdown timeout` be?

1. max(max(3 containers' `stop timeout`), `--shutdown-timeout`)
1. or max(sum(3 containers' `stop timeout`), `--shutdown-timeout`)

**Comment by djs55** [comment]
I have a similar problem, I hope you don't mind me adding it here (although I'm happy to create a separate issue or propose a PR). I have set the daemon's `shutdown-timeout: 2` and have arranged to set every container's `stop timeout` to `1` but I still see a 5s HTTP server timeout which manifests as:
```
{"component":"dockerd","error":"context canceled","level":"error","msg":"Error shutting down http server","time":"2025-11-06T11:26:52.457776878Z"}
```
from [here](https://github.com/moby/moby/blob/0035b5eed62b87273bcbbd51d73b880ce1a8d8cf/daemon/command/daemon.go#L201) (in main, I'm actually testing v28.5.1 but the code look similar)

The policy comes from 12bf850c8478aea31f7703ede169e496afdcbfb3 which uses the [http.Shutdown](https://pkg.go.dev/net/http#Server.Shutdown) API to give

> in-flight requests up to five seconds to finish up after all containers have been shut down.

So it's working as designed, and  this makes a lot of sense for short-lived RPC-style APIs but is less good for long-lived blocking poll style APIs like `docker events`. In my case the layers above `dockerd` have retry loops like [this](https://github.com/linuxkit/linuxkit/blob/238449c2d6f21e163ffde04415807f9145b34557/pkg/trim-after-delete/main.go#L118) which block so I'm always guaranteed to have an in-flight request and therefore to hit the 5s timeout and log the error.

In my app I've actually wrapped `dockerd` to workaround this policy, by adding a proxy which tracks all open connections and abruptly closes them on context done but this feels like a complicated && brittle hack. Several times I've accidentally bypassed the proxy and re-triggered the bug, and it's difficult to debug.

In my case I'd be happy closing these connections immediately with a hacky patch like [this](https://github.com/djs55/docker/commit/78eba93752db556dc1fc85c38854b9355bd68aac) which replaces the `http.Shutdown` with a more abrupt [http.Close](https://pkg.go.dev/net/http#Server.Close) but I appreciate this approach might not be to everyone's taste!

WDYT? Is this something which
- you don't want to change at all (so I should wrap `dockerd` or apply my hacky patch locally)
- you'd consider making (another) config option (if so I could propose something), even though I realise the shutdown  situation is clearly already complicated, as evidenced by this issue...

**Comment by akerouanton** [comment]
> In my case I'd be happy closing these connections immediately with a hacky patch like [this](https://github.com/djs55/docker/commit/78eba93752db556dc1fc85c38854b9355bd68aac) which replaces the http.Shutdown with a more abrupt [http.Close](https://pkg.go.dev/net/http#Server.Close) but I appreciate this approach might not be to everyone's taste!

@djs55 I played a bit with your patch and it causes the CLI to log the following when running a container in non-detached mode:

> time="2025-11-06T18:12:48Z" level=error msg="error waiting for container: unexpected EOF"

`ContainerAttach` uses an hijacked connection, so (*Server).Close() doesn't attempt to close these connections. I guess this error log comes from the `ContainerWait` API call.

Beside the weird semantic of `--shutdown-timeout` described above, I think the real issue in your case is that event requests are never terminated when shutting down.

As shared privately, my initial thought was that we could probably close these connections prematurely on shutdown. But I think there are a few use cases where a client listening for events would like to receive the final events for containers stopped during shutdown (e.g. a software orchestrating containers through the Engine API and that needs to clean up some resources).

---

As an aside, without your patch, the CLI logs the following error when container exits:

> time="2025-11-06T18:04:58Z" level=error msg="Error waiting for container: Canceled: grpc: the client connection is closing: context canceled"

I think that's wrong too.
