### ISSUE TITLE
short running containers with -rm failed to destroy

### ISSUE THREAD

**Issue by ekle** [docker/docker#3968]
if you run the following command two times PARALLEL you will get many errors like:
Error: container_delete: Cannot destroy container ... Driver aufs failed to remove root filesystem ...

while [ 1 ] ; do 
  time docker run --rm -t ubuntu /bin/echo 1
done

**Comment by jfrazelle** [comment]
can reproduce on latest

**Comment by nomeata** [comment]
Also see #9665, which seems to be related.

**Comment by Gig77** [comment]
Reproduced with docker 1.5.0.

```
# uname -a
Linux biowaste 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u2 x86_64 GNU/Linux
```
```
# docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```
```
# docker info
Containers: 4
Images: 520
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 648
Execution Driver: native-0.2
Kernel Version: 3.2.0-4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
CPUs: 24
Total Memory: 63.01 GiB
Name: biowaste
ID: WDBO:CL4R:TEP2:3P6W:PJ3E:ABXT:GBY6:KTMN:2MYE:OW6P:VOV4:TGBL
Username: cfrech
Registry: [https://index.docker.io/v1/]
```

**Comment by anandkumarpatel** [comment]
reproduced with docker 1.6.0
```
uname -a
Linux Moltres 3.13.0-29-generic #53-Ubuntu SMP Wed Jun 4 21:00:20 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
```
root@Moltres:/home/Moltres# docker -D version && docker -D info
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64
Containers: 514
Images: 8324
Storage Driver: aufs
 Root Dir: /docker/aufs
 Backing Filesystem: extfs
 Dirs: 9376
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-29-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 32
Total Memory: 58.81 GiB
Name: Moltres
ID: MMMM:OOOO:LLLL:TTTT:RRRR:EEEE:SSSS:1111:1111:1111:1111:1111
Debug mode (server): false
Debug mode (client): true
Fds: 1358
Goroutines: 4312
System Time: Wed Jul 15 19:01:47 UTC 2015
EventsListeners: 1
Init SHA1: 1111571111383d1111cede3b111186061111027c
Init Path: /usr/bin/docker
Docker Root Dir: /docker
WARNING: No swap limit support
```

**Comment by vellamike** [comment]
Reproduced with Docker 1.9.1.

This issue seems to be more severe when container run times are shorter. Running 32 containers with a 1s mean run time and I see the error for almost every container, if the mean run time is 75s it is a rare occurence.

@rakeshcusat mentioned that [a related issue was solved when using `3.19.0-25-generic`](https://github.com/docker/docker/issues/9665) - has anyone found this to be the case?
```
# uname -a
Linux ip-10-130-12-223 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
docker -D version && docker -D info
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
Containers: 41
Images: 21
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 103
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-68-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 32
Total Memory: 58.97 GiB
WARNING: No swap limit support
```

**Comment by vellamike** [comment]
For me upgrading to kernel 3.19.0-25-generic appears to have solved the problem.

**Comment by zfil** [comment]
I'm using kernel 3.19.0-39-generic and the bug is still there for me.

Kernel Version: 3.19.0-39-generic
Operating System: Ubuntu 14.04.3 LTS

**Comment by zfil** [comment]
Reproduced again, today.

I'm running 2 containers (a postgres and an nginx) not linked.

Docker daemon failed with a stack overflow when I tried launching
`docker run -it --link postgres --rm postgres:9.4 sh -c 'exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -U postgres'`

```
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                      NAMES
0019145e8a8d        postgres:9.4        "/docker-entrypoint.s"   15 minutes ago      Dead                                                           
ded20ccb105c        nginx-shepard       "nginx -g 'daemon off"   13 hours ago        Up 15 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   nginx
f6447948a433        postgres:9.4        "/docker-entrypoint.s"   2 days ago          Up 15 minutes       0.0.0.0:5432->5432/tcp
```

```
$ docker info
Containers: 3
Images: 37
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 43
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-39-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 31.43 GiB
Name: shepard
ID: YAWF:OY7V:IGZ5:GGI4:3RYT:2K3W:UU3N:ZKKH:BFST:S6PF:YCYU:UAYO
Username: zfil
Registry: https://index.docker.io/v1/
```

[docker.log.zip](https://github.com/docker/docker/files/65066/docker.log.zip)

After that it is impossible to remove the container:
```
Error response from daemon: Driver aufs failed to remove root filesystem 0019145e8a8dd551c1da0e5fcce49d63fab3f32301db763f0598902d6b739870: rename /var/lib/docker/aufs/mnt/0019145e8a8dd551c1da0e5fcce49d63fab3f32301db763f0598902d6b739870 /var/lib/docker/aufs/mnt/0019145e8a8dd551c1da0e5fcce49d63fab3f32301db763f0598902d6b739870-removing: device or resource busy
Error: failed to remove containers: [0019145e8a8d]
```

**Comment by zfil** [comment]
Got again the error after a machine reboot (kernel version is now 3.19.0-42-generic).
2 containers are configured to restart automatically, both failed in the daemon log same problem stuck in an infinite loop while trying to configure cgroups.

Rebooting the machine fixes the issue.

From what I see I don't think it related to auf actually, looks more a racing issue in the native driver cgroup setup.

**Comment by thaJeztah** [comment]
ping @WeiZhang555 should this be fixed by https://github.com/docker/docker/pull/20848 as well?

**Comment by ekle** [comment]
i cannot reproduce it anymore:
````
$ docker info
Containers: 16
 Running: 0
 Paused: 0
 Stopped: 16
Images: 106
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.7.4-towo.1-siduction-amd64
Operating System: Debian GNU/Linux stretch/sid
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.692 GiB
Name: 
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/

$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   b9f10c9
 Built:        Wed, 20 Jul 2016 16:34:52 -0700
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   b9f10c9
 Built:        Wed, 20 Jul 2016 16:34:52 -0700
 OS/Arch:      linux/amd64
````

**Comment by LK4D4** [comment]
@ekle thanks for update!
