### ISSUE TITLE
docker volumes w remote daemon

### ISSUE THREAD

**Issue by bradfitz** [docker/docker#4023]
This seems like a tricky one, but I noticed that I can't use "docker run -v ..." with Docker 0.8 on OS X with boot2docker.

Also, I get no error message.  My docker container just fails to run properly because paths are missing.  At minimum, docker run should fail with an "unsupported on OS X" error message.

But ideally, since boot2docker in VirtualBox is on a different (virtual) machine than the OS X host and we can't simply bind mount between them, perhaps a FUSE filesystem can be mounted in the Linux VM that forwards back to the  OS X host.

**Comment by sminnee** [comment]
@vieux if you had a chance, it would be great to get an update on whether the FUSE work was still something you planned to work on in the near future

**Comment by justjacksonn** [comment]
So this is a few months later and I still don't see/read anything related to whether or not docker on Mac can use the -v option to share host volumes with docker volumes... is there anything other than the sshfs solution? I've tried that and it is not working for me either. Can't write to the mapped folder despite use defer_permissions and other options. It's not easy to understand how to use that process and it seems silly that we have to run an external app and ssh to boot2docker to get host volumes working. Hopefully I have an old boot2docker build and it's now resolved?

**Comment by fyddaben** [comment]
sshfs is so slow .

**Comment by cpuguy83** [comment]
Docker 1.8 supports volume plugins which you can use to implement remote volumes (of which there are a few implementations already).
This doesn't generally give you any client-side magic but is still extremely useful.
For example `docker run -v <some name>:/foo --volume-driver=smb`.

Docker 1.9 will allow you to do `docker run -v $(docker volume create --name <some name> --driver smb --opt <some opt> --opt <some other opt>):/foo`

**Comment by fyddaben** [comment]
Thansk @homerjam sshfs is very useful. my code is on my container, and i sshfs my container  on my OSX. so thank you .thank you thank you 
my command is 

```
sshfs -p 2023 -o allow_other work@$(boot2docker ip):/home/work/data/vi/  /Volumes/01/vc
```

so i can share my file(in my container)  on my OSX .

**Comment by docteurklein** [comment]
BTW, there is https://github.com/vieux/docker-volume-sshfs from @vieux

**Comment by docteurklein** [comment]
Talking about that: how would it look like to use docker-machine's ssh config with this docker-volume plugin?

**Comment by homerjam** [comment]
This tool looks useful https://github.com/codekitchen/dinghy it appears to use NFS under the hood to work around the shared folders issue

**Comment by icecrime** [comment]
@bradfitz Do you consider this one solved by [Docker 4 Mac](https://docs.docker.com/engine/installation/mac/)?

**Comment by thaJeztah** [comment]
closing because there's no activity, but happy to reopen if you think there's still something to be done

**Comment by bradfitz** [comment]
Yeah, I'm happy enough. xhyve is fun.

**Comment by thaJeztah** [comment]
Thanks @bradfitz

**Comment by irjudson** [comment]
The solutions for docker for windows have not resolved this family of issues, most of which were closed as a duplicate of this one.

What's the current thinking or solution for volume sharing not working on docker for windows?

**Comment by thaJeztah** [comment]
@irjudson if there are still issues, the best way is to check the docker for windows issue tracker (https://github.com/docker/for-win/issues). Implementing / fixing that is specific for Docker for Windows, and cannot be resolved in this repository, so for that reason it's not needed to keep this issue open here
