### ISSUE TITLE
unexpected EOF on docker push

### ISSUE THREAD

**Issue by vincentwoo** [docker/docker#8793]
Pretttty bizarre - never seen this one before. Kind of game-breaking for me right now. Would love some adult supervision.

```
vwoo@execute4:~/coderpad-tty/docker$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
coderpad/coderpad   easypost_ruby       ca811f9f1e5e        4 minutes ago       489.7 MB
coderpad/coderpad   erlang              984b3eda36ec        5 minutes ago       1.556 GB
coderpad/coderpad   ruby                f1c184a171f3        14 minutes ago      488.2 MB
coderpad/coderpad   r                   c06adcbf3690        15 minutes ago      630 MB
coderpad/coderpad   python              6f92af11ca2a        16 minutes ago      577.5 MB
coderpad/coderpad   php                 c1c4f3e79bfd        29 minutes ago      471.5 MB
coderpad/coderpad   perl                d9edd4a04fda        30 minutes ago      517.6 MB
coderpad/coderpad   scala               b14c926f2b66        33 minutes ago      976.2 MB
coderpad/coderpad   clojure             7686a81e7a55        33 minutes ago      953.6 MB
coderpad/coderpad   java                0939fc1b3e09        33 minutes ago      944 MB
coderpad/coderpad   haskell             f502298865cd        33 minutes ago      1.693 GB
coderpad/coderpad   go                  343b13fb2682        34 minutes ago      637.8 MB
coderpad/coderpad   mysql               6427caac4a50        34 minutes ago      601.7 MB
coderpad/coderpad   coffeescript        31aed62ca004        39 minutes ago      491.7 MB
coderpad/coderpad   javascript          b8cfbc031336        39 minutes ago      481.5 MB
coderpad/coderpad   csharp              af76a86faec3        40 minutes ago      529.4 MB
coderpad/coderpad   objc                93d3abe4ed54        40 minutes ago      742.8 MB
coderpad/coderpad   cpp                 a6cd0c3b7b4a        42 minutes ago      513.3 MB
coderpad/coderpad   c                   dea17ab74ef5        42 minutes ago      513.3 MB
coderpad/coderpad   base                56010717816b        42 minutes ago      441 MB
ubuntu              12.04               0b310e6bf058        3 days ago          126.7 MB
vwoo@execute4:~/coderpad-tty/docker$ docker push coderpad/coderpad
The push refers to a repository [coderpad/coderpad] (len: 20)
Sending image list
2014/10/27 04:35:05 unexpected EOF
vwoo@execute4:~/coderpad-tty/docker$ docker info
Containers: 0
Images: 123
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 123
Execution Driver: native-0.2
Kernel Version: 3.13.0-36-generic
Operating System: Ubuntu 14.04.1 LTS
WARNING: No swap limit support
vwoo@execute4:~/coderpad-tty/docker$ docker --version
Docker version 1.3.0, build c78088f
```

and from `/var/log/upstart/docker.log`:

```
[info] POST /v1.15/images/coderpad/coderpad/push?tag=
[34b70da1] +job push(coderpad/coderpad)
unexpected EOF
[34b70da1] -job push(coderpad/coderpad) = ERR (1)
```

**Comment by vincentwoo** [comment]
@metalivedev was this ever addressed?

**Comment by metalivedev** [comment]
Not that I know of. You're welcome to look for the place in the docker source code that emits the error message and update the detection of missing `.dockercfg` files and to improve the error message. We're always happy to get pull requests, especially from new contributors.

**Comment by jfrazelle** [comment]
ping @jlhawn @dmcgowan @dmp42

**Comment by metasim** [comment]
Also having this problem, and not sure from this transcript what I need to do to work around it. Is there a work-around?

**Comment by askb** [comment]
Not sure, if this issue is still valid, as I was trying to reproduce it on 1.8.2 with non-root user and `.dockercfg` file in the user home dirictory and get an error which is quite reasonable "Image push failed ... unauthorized: access to the requested resource is not authorized".

**Comment by thaJeztah** [comment]
@vincentwoo is this still an issue for you?

**Comment by vincentwoo** [comment]
I no longer use this flow, I moved to a private registry. I think the repro case was very reproducible though, so if those steps no longer cause an error I'd assume the problem was resolved.

**Comment by equivalent** [comment]
I had similar problem `unexpected EOF` when I was pushing to docker repo 

this was due to fact I've been building docker images from 2 machines (one had `docker -v` 1.6, the other one was `docker -v` 1.9). When I've upgraded the `1.6` machine to `1.9` suddenly this problem started when I done `docker push ....` from it.  

I've ended up doing `docker build --no-cache -t=myapp:latest . ` and after that push worked

**Comment by vpalos** [comment]
Well, now it seems the 1.10 release also causes this problem to appear then pushing. Rolling back to 1.9 works.

**Comment by kklepper** [comment]
This is my first attempt to push, as far as I remember (I did some tests 2 years ago).

I forked vegasbrianc/docker-hello-world (itself forked from tutumcloud/hello-world), pulled the git to a Digital Ocean droplet, built without any change to the source and pushed with EOF error.

This can be reproduced ad infinitum. It looks like it is always the last layer 8698b31c92d5 causing the problem. Adding --no-cache or building again did not help. Pulling vegasbrianc/docker-hello-world went fine.

To change my setup, I replaced the maintainer in Dockerfile and built again, to no avail. The following pattern can be observed:

All 4 Layers 5f70bf18a086 ff. switch to Waiting first, then retrying immediately; only the last one, 8698b31c92d5, picks up pushing. The others keep retrying and pushing in sync, 4 seconds, 10, 15, 19 seconds, whereas 8698b31c92d5 pushes all the way through (as far as I can tell - I was able to spot 187.3/187.7, then even beyond to 191.1 MB -- I could record this via screenshot), then this also switches to retry, while the others keep retrying and begin pushing after waiting at last 19 seconds. At second try, however, 8698b31c92d5 fails sooner or later. 

Interestingly, depending on the appearance of the EOF error, the other layers seem to be uploaded totally, but are not marked as Pushed, instead keep retrying. All this looks very mystifying.

Here are some records, from the first try (changing Dockerfile in between did not result in any different behavior):

    wp@ubuntu-512mb-fra1-01:~/docker-hello-world$ sudo docker push kklepper/docker-hello-world:latest
    The push refers to a repository [docker.io/kklepper/docker-hello-world]
    c7e5bab43295: Pushed
    3ed9b499d3d6: Pushed
    9d2e7f239390: Pushed
    b5c4d12d5aad: Pushed
    7cd0a716db26: Pushed
    2798dde3b07a: Pushed
    5f70bf18a086: Pushing
    0d81735d8272: Pushing [==================================================>] 1.895 kB/1.895 kB
    982549bd6b32: Pushing [==================================================>] 194.5 kB/194.5 kB
    8698b31c92d5: Pushing [==========>                                        ] 39.73 MB/187.7 MB
    unexpected EOF
    
    sudo docker push kklepper/docker-hello-world:latest
    The push refers to a repository [docker.io/kklepper/docker-hello-world]
    c7e5bab43295: Layer already exists
    3ed9b499d3d6: Layer already exists
    9d2e7f239390: Layer already exists
    b5c4d12d5aad: Layer already exists
    7cd0a716db26: Layer already exists
    2798dde3b07a: Layer already exists
    5f70bf18a086: Pushing
    0d81735d8272: Pushing [==================================================>] 1.895 kB/1.895 kB
    982549bd6b32: Pushing [==================================================>] 194.5 kB/194.5 kB
    8698b31c92d5: Pushing [========================>                          ] 90.73 MB/187.7 MB
    unexpected EOF
    
    5f70bf18a086: Pushing
    0d81735d8272: Pushing [==================================================>] 1.895 kB/1.895 kB
    982549bd6b32: Pushing [>                                                  ]      0 B/194.5 kB
    8698b31c92d5: Pushing [========================>                          ] 91.79 MB/187.7 MB
    unexpected EOF
    
    5f70bf18a086: Pushing
    0d81735d8272: Pushing [==================================================>] 1.895 kB/1.895 kB
    982549bd6b32: Pushing [==================================================>] 194.5 kB/194.5 kB
    8698b31c92d5: Pushing [=========================>                         ] 97.12 MB/187.7 MB
    unexpected EOF
    
    
    5f70bf18a086: Pushing
    0d81735d8272: Pushing [>                                                  ]      0 B/1.895 kB
    982549bd6b32: Pushing [>                                                  ]      0 B/194.5 kB
    8698b31c92d5: Pushing [=================>                                 ] 64.12 MB/187.7 MB
    unexpected EOF
    
    
    5f70bf18a086: Pushing
    0d81735d8272: Pushing [==================================================>] 1.895 kB/1.895 kB
    982549bd6b32: Pushing [>                                                  ]      0 B/194.5 kB
    8698b31c92d5: Pushing [====================>                              ]  78.4 MB/187.7 MB
    unexpected EOF
    
    5f70bf18a086: Pushing
    0d81735d8272: Pushing [==================================================>] 1.895 kB/1.895 kB
    982549bd6b32: Pushing [==================================================>] 194.5 kB/194.5 kB
    8698b31c92d5: Pushing [========================>                          ] 92.85 MB/187.7 MB
    unexpected EOF
    
    
    5f70bf18a086: Pushing
    0d81735d8272: Pushing [==================================================>] 1.895 kB/1.895 kB
    982549bd6b32: Pushing [>                                                  ]      0 B/194.5 kB
    8698b31c92d5: Pushing [=====================>                             ] 80.55 MB/187.7 MB
    unexpected EOF
    
    5f70bf18a086: Pushing
    0d81735d8272: Pushing [==================================================>] 1.895 kB/1.895 kB
    982549bd6b32: Pushing [==================================================>] 194.5 kB/194.5 kB
    8698b31c92d5: Pushing [======================>                            ] 85.35 MB/187.7 MB
    unexpected EOF
    
    5f70bf18a086: Pushing
    0d81735d8272: Pushing [==================================================>] 1.895 kB/1.895 kB
    982549bd6b32: Pushing [>                                                  ]      0 B/194.5 kB
    8698b31c92d5: Pushing [=======================>                           ] 86.41 MB/187.7 MB
    unexpected EOF
    
    5f70bf18a086: Pushing
    0d81735d8272: Pushing [>                                                  ]      0 B/1.895 kB
    982549bd6b32: Pushing [==================================================>] 194.5 kB/194.5 kB
    8698b31c92d5: Pushing [====================>                              ] 77.88 MB/187.7 MB
    unexpected EOF
    
    5f70bf18a086: Pushing
    0d81735d8272: Pushing [>                                                  ]      0 B/1.895 kB
    982549bd6b32: Pushing [==================================================>] 194.5 kB/194.5 kB
    8698b31c92d5: Pushing [========================>                          ] 93.39 MB/187.7 MB
    unexpected EOF
    
    5f70bf18a086: Pushing
    0d81735d8272: Pushing [==================================================>] 1.895 kB/1.895 kB
    982549bd6b32: Pushing [>                                                  ]      0 B/194.5 kB
    8698b31c92d5: Pushing [=============================>                     ]   110 MB/187.7 MB
    unexpected EOF
    
    5f70bf18a086: Pushing
    0d81735d8272: Pushing [>                                                  ]      0 B/1.895 kB
    982549bd6b32: Pushing [>                                                  ]      0 B/194.5 kB
    8698b31c92d5: Pushing [=============================>                     ]   110 MB/187.7 MB
    unexpected EOF
    
    5f70bf18a086: Pushing
    0d81735d8272: Pushing [==================================================>] 1.895 kB/1.895 kB
    982549bd6b32: Pushing [==================================================>] 194.5 kB/194.5 kB
    8698b31c92d5: Pushing [===============================>                   ] 117.4 MB/187.7 MB
    unexpected EOF

![docker1](https://cloud.githubusercontent.com/assets/6130319/13171270/1ff5ca9c-d6f2-11e5-9575-b2c43967d0df.png)

**Comment by thaJeztah** [comment]
@vpalos @kklepper if you're having this issue on docker 1.10, that may be https://github.com/docker/docker/issues/20104. A fix has been merged already and will be included in a patch update soon

**Comment by kklepper** [comment]
@thaJeztah Thanks a lot!

**Comment by tugberkugurlu** [comment]
I occasionally get this while pushing to AWS ECR:

````
d7e2065b375e: Pushed 
5f70bf18a086: Layer already exists 
4b46b70c720f: Layer already exists 
a49c7743279a: Pushed 
ddef881aeaff: Pushed 
unexpected EOF
```

I am not sure what would help to understand why this happens.

**Comment by thaJeztah** [comment]
@tugberkugurlu can you try updating to docker 1.10.2? That release carries the patch I referred to (https://github.com/docker/docker/issues/20104)

**Comment by jbruggem** [comment]
@thaJeztah for me 1.10.2 did not solve the problem (see https://github.com/docker/docker/issues/20104#issuecomment-187705710 )

**Comment by thaJeztah** [comment]
@jbruggem thanks for testing; I left a comment there

**Comment by ekristen** [comment]
I am seeing this problem too with v1 registry.

**Comment by ekristen** [comment]
@thaJeztah @stevvooe this is a pretty big problem IMO. We've migrated to v2, but some tooling we use unfortunately only knows how to communicate with v1, so we are left supporting v1 for a little bit right now and having our build server crash every time it tries to push to v1 is not good.

**Comment by ghostbar** [comment]
Pushing to registry v1, `unexpected EOF` and on logs `panic: runtime error: index out of range`; full log:

```
time="2016-03-10T14:07:47.594494710Z" level=debug msg="Applied tar sha256:391fb2eed92cfaf70b6bcdd03797b33aefc741813f0a2dbe853e99b523d6d523 to af410abeeb85ff7d0471917b60c0cc343639cf73f81d96f9fc23ebcc2fd65f13, size: 11870527"
time="2016-03-10T14:07:47.946534109Z" level=debug msg="Calling POST /v1.22/images/index.private.io/name/tag/push"
time="2016-03-10T14:07:47.946574962Z" level=debug msg="POST /v1.22/images/index.private.io/name/tag/push?tag="
time="2016-03-10T14:07:47.946596442Z" level=debug msg="Warning: client and server don't have the same version (client: 1.10.0, server: 1.10.2)"
time="2016-03-10T14:07:48.231443336Z" level=debug msg="hostDir: /etc/docker/certs.d/index.private.io"
time="2016-03-10T14:07:48.372738272Z" level=debug msg="hostDir: /etc/docker/certs.d/index.private.io"
time="2016-03-10T14:07:48.372894424Z" level=debug msg="Trying to push index.private.io/name/tag to https://index.private.io v2"
time="2016-03-10T14:07:49.261532828Z" level=debug msg="Pushing repository: index.private.io/name/tag:latest"
time="2016-03-10T14:07:49.264287984Z" level=debug msg="Pushing layer: sha256:391fb2eed92cfaf70b6bcdd03797b33aefc741813f0a2dbe853e99b523d6d523"
time="2016-03-10T14:07:49.265548079Z" level=debug msg="Pushing layer: sha256:f58047ace956ade48f64644352de00174ee32329faa7cd4b23ed5c855a980af0"
time="2016-03-10T14:07:49.265891814Z" level=debug msg="Pushing layer: sha256:a1458647a86323670ad3bacc3a83d4a896a31952a862b54f538670f8d1a5ebc9"
time="2016-03-10T14:07:49.266233680Z" level=debug msg="Pushing layer: sha256:690d9849888450d080a5cff82ffe526f18b15d56a04bd0e68bb2e2bf0579b43c"
time="2016-03-10T14:07:49.266682746Z" level=debug msg="Pushing layer: sha256:3275442d02e61cd78d2cd622a9563421d175b0ea5fe8c427903b82f46246adc2"
panic: runtime error: index out of range
goroutine 355 [running]:
github.com/docker/docker/distribution.retryOnError(0x7fce80f2bba8, 0xc821013d00, 0x0, 0x0)
        /go/src/github.com/docker/docker/distribution/registry.go:143 +0x138
github.com/docker/docker/distribution.(*v2PushDescriptor).Upload(0xc8212b3980, 0x7fce82764f78, 0xc8212b3c40, 0x7fce82764fb8, 0xc8201fba40, 0x0, 0x0)
        /go/src/github.com/docker/docker/distribution/push_v2.go:335 +0x12fb
github.com/docker/docker/distribution/xfer.(*LayerUploadManager).makeUploadFunc.func1.1(0xc8201fba40, 0xc8201fb980, 0x7fce80f2b9e0, 0xc8212b3980, 0xc821bdb5f0)
        /go/src/github.com/docker/docker/distribution/xfer/upload.go:108 +0x1a6
created by github.com/docker/docker/distribution/xfer.(*LayerUploadManager).makeUploadFunc.func1
        /go/src/github.com/docker/docker/distribution/xfer/upload.go:150 +0x13e
goroutine 1 [chan receive, 2 minutes]:
main.(*DaemonCli).CmdDaemon(0xc820309840, 0xc82000a140, 0xf, 0x10, 0x0, 0x0)
        /go/src/github.com/docker/docker/docker/daemon.go:305 +0x20a7
reflect.callMethod(0xc82063ce40, 0xc820785c78)
        /usr/local/go/src/reflect/value.go:628 +0x1fc
reflect.methodValueCall(0xc82000a140, 0xf, 0x10, 0x1, 0xc82063ce40, 0x0, 0x0, 0xc82063ce40, 0x0, 0x4745b4, ...)
        /usr/local/go/src/reflect/asm_amd64.s:29 +0x36
github.com/docker/docker/cli.(*Cli).Run(0xc82063cdb0, 0xc82000a130, 0x10, 0x11, 0x0, 0x0)
        /go/src/github.com/docker/docker/cli/cli.go:89 +0x383
main.main()
        /go/src/github.com/docker/docker/docker/docker.go:63 +0x43c
goroutine 17 [syscall, 2 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
goroutine 12 [chan receive, 2 minutes]:
github.com/docker/docker/daemon.setupDumpStackTrap.func1(0xc8206580c0)
        /go/src/github.com/docker/docker/daemon/debugtrap_unix.go:17 +0x4d
created by github.com/docker/docker/daemon.setupDumpStackTrap
        /go/src/github.com/docker/docker/daemon/debugtrap_unix.go:20 +0x12a
goroutine 6 [syscall, 2 minutes]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37
goroutine 11 [select, 2 minutes, locked to thread]:
runtime.gopark(0x1a01bd0, 0xc82001f728, 0x16ffa58, 0x6, 0x18, 0x2)
        /usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82001f728, 0x0, 0x18)
        /usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc82001f728)
        /usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
goroutine 13 [select]:
github.com/docker/libnetwork.(*controller).watchLoop(0xc820104630)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/store.go:409 +0x140
created by github.com/docker/libnetwork.(*controller).startWatch
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/store.go:423 +0x100
goroutine 34 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7fce8379fdd0, 0x72, 0xc82000e1a0)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8202a5800, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202a5800, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8202a57a0, 0x0, 0x7fce8379e928, 0xc8206a0120)
        /usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*UnixListener).AcceptUnix(0xc82068dec0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/unixsock_posix.go:304 +0x53
net.(*UnixListener).Accept(0xc82068dec0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/unixsock_posix.go:314 +0x41
github.com/docker/libnetwork.(*controller).acceptClientConnections(0xc820104630, 0xc8202a5730, 0x63, 0x7fce8379f018, 0xc82068dec0)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/sandbox_externalkey_unix.go:130 +0x45
created by github.com/docker/libnetwork.(*controller).startExternalKeyListener
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/sandbox_externalkey_unix.go:124 +0x28a
goroutine 54 [chan receive]:
github.com/docker/docker/daemon.(*statsCollector).run(0xc820711480)
        /go/src/github.com/docker/docker/daemon/stats_collector_unix.go:99 +0xcd
created by github.com/docker/docker/daemon.(*Daemon).newStatsCollector
        /go/src/github.com/docker/docker/daemon/stats_collector_unix.go:38 +0x1af
goroutine 55 [chan receive, 2 minutes]:
github.com/docker/docker/daemon.(*Daemon).execCommandGC(0xc820001c80)
        /go/src/github.com/docker/docker/daemon/exec.go:237 +0x8e
created by github.com/docker/docker/daemon.NewDaemon
        /go/src/github.com/docker/docker/daemon/daemon.go:807 +0x30f1
goroutine 56 [chan receive, 2 minutes]:
main.setupConfigReloadTrap.func1(0xc82072b140, 0x17dfbc0, 0x17, 0xc820072700, 0xc820733620)
        /go/src/github.com/docker/docker/docker/daemon_unix.go:62 +0x68
created by main.setupConfigReloadTrap
        /go/src/github.com/docker/docker/docker/daemon_unix.go:67 +0x162
goroutine 57 [chan receive, 2 minutes]:
github.com/docker/docker/api/server.(*Server).serveAPI(0xc82064dec0, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/server/server.go:102 +0x1af
github.com/docker/docker/api/server.(*Server).Wait(0xc82064dec0, 0xc82072b1a0)
        /go/src/github.com/docker/docker/api/server/server.go:217 +0x2b
created by main.(*DaemonCli).CmdDaemon
        /go/src/github.com/docker/docker/docker/daemon.go:287 +0x1f7a
goroutine 58 [chan receive, 2 minutes]:
github.com/docker/docker/pkg/signal.Trap.func1(0xc82072b200, 0xc82074f890)
        /go/src/github.com/docker/docker/pkg/signal/trap.go:29 +0x71
created by github.com/docker/docker/pkg/signal.Trap
        /go/src/github.com/docker/docker/pkg/signal/trap.go:55 +0x21a
goroutine 61 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7fce8379ff50, 0x72, 0xc82000e1a0)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820317250, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820317250, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8203171f0, 0x0, 0x7fce8379e928, 0xc82092bac0)
        /usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*UnixListener).AcceptUnix(0xc8201cdf40, 0xc820787dc8, 0x0, 0x0)
        /usr/local/go/src/net/unixsock_posix.go:304 +0x53
net.(*UnixListener).Accept(0xc8201cdf40, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/unixsock_posix.go:314 +0x41
net/http.(*Server).Serve(0xc82064df20, 0x7fce8379f018, 0xc8201cdf40, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1887 +0xb3
github.com/docker/docker/api/server.(*HTTPServer).Serve(0xc82013c100, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/server/server.go:121 +0x47
github.com/docker/docker/api/server.(*Server).serveAPI.func1(0xc8208ef620, 0xc82013c100)
        /go/src/github.com/docker/docker/api/server/server.go:94 +0x13d
created by github.com/docker/docker/api/server.(*Server).serveAPI
        /go/src/github.com/docker/docker/api/server/server.go:98 +0x148
goroutine 62 [IO wait]:
net.runtime_pollWait(0x7fce8379fe90, 0x72, 0xc82000e1a0)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820317480, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820317480, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820317420, 0x0, 0x7fce8379e928, 0xc820f32b80)
        /usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820026128, 0xc8208ef680, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820026128, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
crypto/tls.(*listener).Accept(0xc82013c180, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/tls.go:46 +0x60
net/http.(*Server).Serve(0xc820658060, 0x7fce837a00c0, 0xc82013c180, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1887 +0xb3
github.com/docker/docker/api/server.(*HTTPServer).Serve(0xc82013c260, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/server/server.go:121 +0x47
github.com/docker/docker/api/server.(*Server).serveAPI.func1(0xc8208ef620, 0xc82013c260)
        /go/src/github.com/docker/docker/api/server/server.go:94 +0x13d
created by github.com/docker/docker/api/server.(*Server).serveAPI
        /go/src/github.com/docker/docker/api/server/server.go:98 +0x148
goroutine 324 [select]:
github.com/docker/docker/distribution/xfer.(*LayerUploadManager).Upload(0xc820665410, 0x7fce82764f78, 0xc821b0a500, 0xc821547d00, 0xb, 0x10, 0x7fce82764fb8, 0xc820659a40, 0x0, 0x0)
        /go/src/github.com/docker/docker/distribution/xfer/upload.go:72 +0x48b
github.com/docker/docker/distribution.(*v2Pusher).pushV2Tag(0xc821835500, 0x7fce82764f78, 0xc821b0a500, 0x7fce82757688, 0xc820ddcaa0, 0xc820661e00, 0x47, 0x0, 0x0)
        /go/src/github.com/docker/docker/distribution/push_v2.go:149 +0x847
github.com/docker/docker/distribution.(*v2Pusher).pushV2Repository(0xc821835500, 0x7fce82764f78, 0xc821b0a500, 0x0, 0x0)
        /go/src/github.com/docker/docker/distribution/push_v2.go:97 +0x659
github.com/docker/docker/distribution.(*v2Pusher).Push(0xc821835500, 0x7fce82764f78, 0xc821b0a500, 0x0, 0x0)
        /go/src/github.com/docker/docker/distribution/push_v2.go:70 +0x37e
github.com/docker/docker/distribution.Push(0x7fce82764f78, 0xc821b0a500, 0x7fce82757498, 0xc820c17da0, 0xc8217214d0, 0x0, 0x0)
        /go/src/github.com/docker/docker/distribution/push.go:138 +0xc0e
github.com/docker/docker/daemon.(*Daemon).PushImage(0xc820001c80, 0x7fce82757498, 0xc820c17da0, 0xc8206925d0, 0xc8206599e0, 0x7fce82764928, 0xc821b0a4c0, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/daemon.go:1070 +0x440
github.com/docker/docker/api/server/router/local.(*router).postImagesPush(0xc8207335c0, 0x7fce82752ff8, 0xc820692540, 0x7fce82752f48, 0xc8218526e0, 0xc821efa9a0, 0xc8206b31d0, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/server/router/local/image.go:238 +0xa77
github.com/docker/docker/api/server/router/local.(*router).(github.com/docker/docker/api/server/router/local.postImagesPush)-fm(0x7fce82752ff8, 0xc820692540, 0x7fce82752f48, 0xc8218526e0, 0xc821efa9a0, 0xc8206b31d0, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/server/router/local/local.go:102 +0x74
github.com/docker/docker/api/server.versionMiddleware.func1(0x7fce82752ff8, 0...
```

**Comment by aaronlehmann** [comment]
@ghostbar: Based on the trace, this is an issue that was just fixed in #21030 for the 1.10.3 release.

**Comment by ekristen** [comment]
It seems to work but has very very odd behavior

```
c2cf220e05d: Retrying in 8 seconds
37beb931a0ec: Retrying in 8 seconds
3b8236726630: Retrying in 8 seconds
45c65a8e2f8f: Retrying in 8 seconds
138b8807a375: Retrying in 8 seconds
13945f14cb88: Waiting
2f09382363fe: Waiting
828922308e61: Waiting
1c2206890b5c: Waiting
0d4e22451772: Waiting
9c0553043bb7: Waiting
745737c319fa: Waiting```

But eventually all layers go to Waiting, and then it starts pushing from the bottom up..

```dc2cf220e05d: Waiting
37beb931a0ec: Waiting
3b8236726630: Waiting
45c65a8e2f8f: Waiting
138b8807a375: Waiting
13945f14cb88: Waiting
2f09382363fe: Waiting
828922308e61: Pushing [==================================================>] 294.2 kB
1c2206890b5c: Image successfully pushed
0d4e22451772: Image successfully pushed
9c0553043bb7: Image successfully pushed
745737c319fa: Image successfully pushed```

**Comment by advancingu** [comment]
Just ran across the same issue consistently with `Docker version 1.10.1, build 9e83765` when pushing images built on base images that were downloaded with an older version of Docker (as described in #20104) to a private Docker Hub repository. Deleting all base images and then rebuilding solved the push issues for us.

**Comment by thaJeztah** [comment]
@advancingu try updating to 1.10.3; see https://github.com/docker/docker/issues/8793#issuecomment-194976405

**Comment by ekristen** [comment]
I can confirm that 1.10.3 fixes the push issue, but the v1 registry support is horrible now. It goes into a forget long retry that lasts over a minute before it actually pushes the layers.

**Comment by thaJeztah** [comment]
@ekristen have you opened a separate issue for that?

**Comment by runcom** [comment]
I'm not sure what this is issue is about now, can we close it? 1.10.3 and current master code solve the panic and the unexpected EOF, @ekristen sounds like yours is a different issue.

@vincentwoo shall we close this issue?

**Comment by ekristen** [comment]
+1 to close, I opened https://github.com/docker/docker/issues/21147 for the other issue

**Comment by vincentwoo** [comment]
Uh, I have no idea what these other people are talking about. I imagine they just googled an error and piled into this ticket. The root cause of my original problem turned out to be a very specific edge case involving the presence or absence of a `.dockercfg`. The original issue submission was from like 18 months ago so I'm just gonna go ahead and close this since I figure there should be like a statute of limitations on this shit or something.

**Comment by danday74** [comment]
still having this issue

**Comment by thaJeztah** [comment]
@danday74 please open a new issue; this is a very old issue now, and as stated above, this issue has been collecting issues that are not related to the original issue (but can have a similar effect). When reporting, please provide as much information as possible.

I'm going to lock this issue for the above reason, for others arriving here; please open a new issue (but search for existing, non-resolved issues first to prevent duplicates)
