### ISSUE TITLE
docker save myimage has nondeterministic output

### ISSUE THREAD

**Issue by nh2** [docker/docker#8819]
Repeated `docker save` on the same image create different tar files because the current time is present in the tar file.

It would be great if `docker save` was deterministic because then you can easily publish `sha1sum`s of your containers etc; currently, each `docker save ... | sha1sum` has a different output.

This is usually solved using `tar` by using its `--mtime` option to set the time to 0.

**Comment by jfrazelle** [comment]
ping @jlhawn

**Comment by jfrazelle** [comment]
closing as stale please ping me with exact steps to reproduce on the latest version and I will reopen

**Comment by nh2** [comment]
@jfrazelle When you `run docker save myimage | sha1sum` twice on any `myimage` of your choice, does it produce the same output across the two times?

**Comment by jfrazelle** [comment]
trying now

**Comment by jfrazelle** [comment]
reopening, ping @jlhawn @dmcgowan is this a tarsum thing?

**Comment by jlhawn** [comment]
@jfrazelle I wouldn't add the `bug` label. It's not a bug, it's just the behavior of `docker save`. This is more of a feature request. It would be nice if the output of `docker save` was deterministic and reproducible.

@nh2 `docker save` has to generate each `layer.tar` on the fly from the rootfs snapshots that already exist. These `layer.tar` files represent diffs of the filesystem between build commands and so some entries in these archives may have different created/access/modified times though it would be nice if we just used the time that the image was created OR just zeroed them out.

These `layer.tar` files are placed in a directory named by their image ID along with a JSON file of image metadata so the `layer.tar` and `json` files will have created/access/modified times of when `docker save` was invoked.

This is done for each dependent image layer. Then all of the tags you specified as arguments to `docker save ...` are placed in a single `repositories` JSON file (again with created/access/modified time of when `docker save` was invoked) which maps a `repository_name:tag` to an image ID.

Even if we did reset the created/accessed/modified time of each of the files that are generated, we still need to worry about the content of the rootfs diffs in each `layer.tar` file. This is more of a design issue with the way that Docker stores images locally.

If you're interested, another contributor (@vbatts) has made a helpful little tool that does exactly what I think you're looking for @nh2: https://github.com/vbatts/docker-utils Checkout the `dockertarsum` utility.

It parses each of the `layer.tar` files in a way which ignores modified times and hashes the content of each of the image JSON files in a deterministic way to get a special `tarsum` checksum. While I wouldn't call tarsum a "cryptographically-secure" digest algorithm it can certainly be used to help you detect changes in `docker save` content that you already trust.

**Comment by nh2** [comment]
OK, let's make this a feature request.

@jlhawn Do you think this can be sensibly implemented by using tar's `--mtime` option on the `layer.tar`s and then the final tar, too? From your description, it seems to me that it could.

> If you're interested, another contributor (@vbatts) has made a helpful little tool that does exactly what I think you're looking for @nh2: https://github.com/vbatts/docker-utils Checkout the dockertarsum utility.

Thanks, that is useful!

**Comment by jlhawn** [comment]
> Do you think this can be sensibly implemented by using tar's --mtime option on the layer.tars and then the final tar, too? From your description, it seems to me that it could.

Docker doesn't shell out to a `tar` binary so we can't use that option (we use the golang `archive/tar` library instead), but the "archive/tar" library does give us control over what values are set for the access and modified times.

While I can't speak for the "layer.tar" files (those are created using a specialized directory diff-ing algorithm - I'll look into this separately) we can certainly generate consistent values for the other files in the `docker save` output.

The test case for this feature/improvement should be relatively simple too.

**Comment by vbatts** [comment]
in the `./pkg/archive` package most of that logic occurs. and for the
layer.tar, they got a lot more deterministic with
commit 32d6d49539f5876e6ef75f00db917d8a3aaa0569

**Comment by termie** [comment]
+1

**Comment by vbatts** [comment]
per my previous comment, try it out (using your own image of choice) ((see the file list first, like so `docker save busybox | tar tv`)):
```
vbatts@noyee ~ (master *) $ docker save vbatts/mutt | tar xO 44f48d2a54284d367ab8b96a0e83b66b902d1761eb1b9c2d543ffbe202e2b058/layer.tar | md5sum 
7101a626206689ffaf0f55f87c380b1f  -
vbatts@noyee ~ (master *) $ docker save vbatts/mutt | tar xO 44f48d2a54284d367ab8b96a0e83b66b902d1761eb1b9c2d543ffbe202e2b058/layer.tar | md5sum 
7101a626206689ffaf0f55f87c380b1f  -
```

The archives will never be perfectly deterministic, but I think we can close this issue as *close enough*.

**Comment by termie** [comment]
Sure, I'm willing to accept that. I suppose `dockertarsum` can be used if I want to diff the contents irrespective of mtime.

**Comment by vbatts** [comment]
I think this is ready for closing, with #14067 being merged (will be released in v1.8.0).

As of right now, the only non-deterministic piece of this will be the exterior-tar archive of the saved layers. Example, I'll pull an image:
```bash
$ docker pull docker.io/ubuntu
latest: Pulling from library/ubuntu

83e4dde6b9cf: Pull complete
b670fb0c7ecd: Pull complete
29460ac93442: Pull complete
d2a0ecffe6fa: Already exists
Digest: sha256:cb90b1a107073ab3e17271e45a6177b23f548b44157d88d955b7e8bcdbcfd14a
Status: Downloaded newer image for ubuntu:latest
```

Then let's calculate a sum of the whole output of `docker save`, you'll see the sums are different:
```bash
$ docker save docker.io/ubuntu | sha1sum 
fe2f2faaba96858b608df9304705bf904e86deb4  -
$ docker save docker.io/ubuntu | sha1sum 
18b3e77924041d2e6be6d19923af9579c4f2914c  -
$ docker save docker.io/ubuntu | sha1sum 
0f5d1621307a58fc733172c4215618b2950356b0  -
```

Alternatively, let's unwrap the tar (see the `tar xO`) to get only its contents, and you'll see consistent innards:
```bash
$ docker save docker.io/ubuntu | tar xO | sha1sum
c1d21660fcf50cb89309a27fd645ecc910e5b46c  -
$ docker save docker.io/ubuntu | tar xO | sha1sum
c1d21660fcf50cb89309a27fd645ecc910e5b46c  -
$ docker save docker.io/ubuntu | tar xO | sha1sum
c1d21660fcf50cb89309a27fd645ecc910e5b46c  -
```

To drive this home, let's remove and refetch the image (wash, rinse, repeat):
```bash
$ docker rmi docker.io/ubuntu
Untagged: docker.io/ubuntu:latest
Deleted: d2a0ecffe6fa4ef3de9646a75cc629bbd9da7eead7f767cb810f9808d6b3ecb6
Deleted: 29460ac934423a55802fcad24856827050697b4a9f33550bd93c82762fb6db8f
Deleted: b670fb0c7ecd3d2c401fbfd1fa4d7a872fbada0a4b8c2516d0be18911c6b25d6
Deleted: 83e4dde6b9cfddf46b75a07ec8d65ad87a748b98cf27de7d5b3298c1f3455ae4
$ docker pull docker.io/ubuntu                                                                                                                                                               
latest: Pulling from library/ubuntu

83e4dde6b9cf: Pull complete 
b670fb0c7ecd: Pull complete 
29460ac93442: Pull complete 
d2a0ecffe6fa: Already exists 
Digest: sha256:cb90b1a107073ab3e17271e45a6177b23f548b44157d88d955b7e8bcdbcfd14a
Status: Downloaded newer image for ubuntu:latest
$ docker save docker.io/ubuntu | tar xO | sha1sum                                                                                                                                            
c1d21660fcf50cb89309a27fd645ecc910e5b46c  -
```

**Comment by jrandall** [comment]
Should this issue be closed?

I suppose the output of `docker save` is now technically deterministic, but the output of `docker save` is still dependent on the time when it is run, and that limits some use cases. For example, one might want to upload the tar to a remote server with the ability to resume interrupted transfers. To accomplish this without identical `docker save` output on repeated invocations requires caching the tar locally until the transfer is complete. If `docker save` did produce bit-for-bit identical output each time, we wouldn't need to cache the tar and could resume a transfer simply by re-running `docker save` to regenerate it. 

It appears to me that mtime is the only aspect of the tar that now differs between subsequent `docker save` invocations. Is there any good reason that stable mtimes cannot be set when creating the tar?

**Comment by vbatts** [comment]
It is the contents of the `layer.tar` that matter here, not just the top-level output of `docker save`

**Comment by jrandall** [comment]
Right - and from what I understand as of v1.8.0, the underlying layer.tar issues have been fixed, and only the superficial mtime differences remain. My question is, why not fix that last bit as well by overriding mtime when the outer tar is created (either to 0 or to some stable timestamp value related to the image). 

I've just confirmed that recreating the tar with mtimes set to 0 does appear to work. 

I wrote a python helper script to stream tar from stdin to stdout and reset all of the mtimes:

```python
#!/usr/bin/env python
 
import tarfile
from sys import stdin, stdout, stderr

tar_in = tarfile.open(fileobj=stdin, mode="r|")
tar_out = tarfile.open(fileobj=stdout, mode="w|", format=tarfile.PAX_FORMAT)

for tarinfo in tar_in:
    tarinfo.mtime = 0
    tar_out.addfile(tarinfo, fileobj=tar_in.extractfile(tarinfo))
 
tar_in.close()
tar_out.close()
```

Using this script, one can achieve pure `docker save` output in a usable form (suitable for `docker load`):

```bash
$ docker save 91e54dfb1179 | ./tar-mtime-zero.py | sha1sum
c0a404f9cde27fe1462a7ffaca75f609a0272c2a  -
$ docker save 91e54dfb1179 | ./tar-mtime-zero.py | sha1sum
c0a404f9cde27fe1462a7ffaca75f609a0272c2a  -
$ docker save 91e54dfb1179 | ./tar-mtime-zero.py | sha1sum
c0a404f9cde27fe1462a7ffaca75f609a0272c2a  -
$ docker save 91e54dfb1179 | ./tar-mtime-zero.py | docker load
```

**Comment by vbatts** [comment]
@jrandall alrighty, see https://github.com/docker/docker/pull/16076

**Comment by jrandall** [comment]
@vbatts that is great, thanks!

**Comment by vbatts** [comment]
@jrandall #16076 just merged. It'll be in docker-1.9

**Comment by hellertime** [comment]
With 1.8.3 I still see non-deterministic output, even if I explode the output of `docker save`:

```
$ sudo docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64
$ sudo docker save appimage-sd-bind:1.0-1.2 | tar xO | sha256sum
3d4372214f5006d1b84d6d80d387f0073c1c05eb7b552d680fc640059932451b  -
$ sudo docker save appimage-sd-bind:1.0-1.2 | tar xO | sha256sum
bdb094a1420ad63236e1d9ffe83d8345de9343e9258df9b43f195fab9076b172  -
$ sudo docker save appimage-sd-bind:1.0-1.2 | tar xO | sha256sum
3d4372214f5006d1b84d6d80d387f0073c1c05eb7b552d680fc640059932451b  -
$ sudo docker save appimage-sd-bind:1.0-1.2 | tar xO | sha256sum
061e8ac4a2976b544d8ba360ad68a97c2181c958fbeafdfb759f6d79c7744dae  -
$ sudo docker save appimage-sd-bind:1.0-1.2 | tar xO | sha256sum
3d4372214f5006d1b84d6d80d387f0073c1c05eb7b552d680fc640059932451b  -
$ sudo docker save appimage-sd-bind:1.0-1.2 | tar xO | sha256sum
3d4372214f5006d1b84d6d80d387f0073c1c05eb7b552d680fc640059932451b  -
```

Is this a regression?

**Comment by cpuguy83** [comment]
@hellertime This isn't fixed until 1.9

**Comment by hellertime** [comment]
I had interpreted comment (https://github.com/docker/docker/issues/8819#issuecomment-124210503) as stating that stability WRT `docker save | tar x0 | shasum` was available with docker 1.8.0, and  stability WRT `docker save | shasum` would not be until 1.9.0.

**Comment by vbatts** [comment]
In docker 1.8, If you first `docker save $image | tar tv` to see the
listing _inside_ that initial tar stream. From that you can extract and see
the checksum of the individual .../layer.tar (I.e. `docker save $image |
tar xO $layerID/layer.tar | sha256sum `)

I had interpreted comment (#8819 (comment)
<https://github.com/docker/docker/issues/8819#issuecomment-124210503>) as
stating that stability WRT docker save | tar x0 | shasum was available with
docker 1.8.0, and stability WRT docker save | shasum would not be until
1.9.0.

—
Reply to this email directly or view it on GitHub
<https://github.com/docker/docker/issues/8819#issuecomment-151580552>.
