### ISSUE TITLE
some AUFS whiteouts don't survive a round trip into btrfs or devmapper

### ISSUE THREAD

**Issue by tianon** [docker/docker#9093]
Observe the following `Dockerfile`:
```Dockerfile
FROM busybox
RUN mkdir /test && echo hi > /test/test
RUN rm -rf /test && mkdir /test
CMD ["cat", "/test/test"]
```

On my AUFS machine, I `docker build` this image, then run it, and I get `cat: can't open '/test/test': No such file or directory`, as expected.  If I tag it appropriately and push it to the Hub, then pull it down on a BTRFS machine, it returns `hi`.  If I pull it down on another AUFS machine, it returns `cat: can't open '/test/test': No such file or directory` as expected.  I had @vbatts test it on device-mapper, and it returns the wrong thing for him there too (http://pastebin.com/w6YitdyG), so it's gotta be something in the way AUFS pushes up the whiteouts, I think.

This is actually the root cause of https://github.com/docker-library/wordpress/issues/4, and we've noticed it again more recently with other official images too.

If you want to test on your own machine, `docker run --rm tianon/aufs-whiteouts`.

**Comment by jfrazelle** [comment]
great comment from jlhawn on the issue https://github.com/docker/docker/issues/9690#issuecomment-76291959

**Comment by thaJeztah** [comment]
@tonistiigi Is this issue resolved by https://github.com/docker/docker/pull/16470? (Followed some links to related PRs)

**Comment by tonistiigi** [comment]
@thaJeztah Yes, should be.

**Comment by thaJeztah** [comment]
Thanks @tonistiigi, I'll go ahead and close this issue

@tianon feel free to comment or reopen if I closed this prematurely. Well, you know the drill :smile: thanks for reporting!

**Comment by cezarsa** [comment]
It seems like this issue wasn't completely solved. There are still problems with AUFS whiteouts. An easy reproduction of the bug is simply building the following Dockerfile using AUFS:
```
FROM busybox
RUN mkdir /x && echo "hey" > /x/a
RUN rm -rf /x && mkdir /x && echo "hey2" > /x/a
RUN rm -rf /x && mkdir /x
CMD ["cat", "/x/a"]
```

The result of building and running this Dockerfile is:
```
$ docker build -t bug .
Sending build context to Docker daemon 54.27 kB
Step 1 : FROM busybox
 ---> 47bcc53f74dc
Step 2 : RUN mkdir /x && echo "hey" > /x/a
 ---> Running in 6d19d1dea130
 ---> 072ccb7004e1
Removing intermediate container 6d19d1dea130
Step 3 : RUN rm -rf /x && mkdir /x && echo "hey2" > /x/a
 ---> Running in 5c3347beb627
 ---> 5eb7f2336945
Removing intermediate container 5c3347beb627
Step 4 : RUN rm -rf /x && mkdir /x
 ---> Running in 2ce7793ce71f
 ---> 6ab722c67194
Removing intermediate container 2ce7793ce71f
Step 5 : CMD cat /x/a
 ---> Running in 0c2b26b62217
 ---> f2a78bdaa084
Removing intermediate container 0c2b26b62217
Successfully built f2a78bdaa084

$ docker run --rm bug
hey2
```

The correct result would be for the error `cat: can't open '/x/a': No such file or directory` to show up. No contents for the `/x/a` file should exist in the image. This is was tested with docker `1.11.2`.

Should this issue be reopened or should I open a new one?
